import {SOURCES} from './definitions.js';
// V5 author-approved 1v1 adaptation: no fog/vision or invisible-target admission is claimed.
// Four slots, official identities, ranks and source coefficients remain immutable.
const freeze=x=>{if(x&&typeof x==='object'&&!Object.isFrozen(x)){Object.values(x).forEach(freeze);Object.freeze(x);}return x;};
export const ADAPTED_SOURCES=freeze(SOURCES.map(source=>{const p=structuredClone(source);if(p.definition.registryNumericId===21){const a=p.definition.abilities.find(a=>a.id==='bloodseeker_thirst');a.recipe.arenaNote='二维1v1改编：只按唯一敌人的实际失血比例加速；官方100%至25%生命阈值映射0至40%加速，破被动关闭。竞技场无战争迷雾；本版明确省略低血视野/反隐，不冒充公共隐身目标识别。';a.mvp.arenaNote=a.recipe.arenaNote;a.recipe.omissions=['fog-of-war vision','invisible-target reveal'];p.contract.arenaOmissions=[{abilityId:a.id,reason:'The fighter-only 1v1 adapter has no fog-of-war or shared visibility admission; Thirst retains actual health-driven movement.'}];}if(p.definition.registryNumericId===29){
 const ship=p.definition.abilities.find(a=>a.id==='kunkka_ghostship'),innate=p.contract.innateCandidates.find(a=>a.key==='kunkka_admirals_rum');
 const scalar=name=>{const v=innate.specialValues.find(s=>s.name===name)?.values_float;if(v?.length!==1||!Number.isFinite(v[0]))throw Error('Unreviewed Kunkka rum source');return v[0];};
 const duration=scalar('buff_duration'),fraction=scalar('ghostship_absorb')*ship.mvp.params.rum_factor/100,speed=scalar('movespeed_bonus')*ship.mvp.params.rum_factor/100;
 ship.recipe.rumSource={officialAbilityId:innate.id,source:innate.source,profile:'level18-base-no-item',formula:'18 * rum_factor2 / 100; 7.75 * rum_factor2 / 100; buff_duration5; arena repayment5',automaticInnateEnabled:false};
 ship.recipe.ops=[{op:'deferredHP',duration,damageFraction:fraction,repayDuration:duration,nonlethal:true},{op:'status',to:'self',duration,values:{moveBonus:speed},dispel:'none'},{op:'delay',delay:'tooltip_delay',ops:[{op:'damage',amount:'AbilityDamage',radius:'ghostship_width',center:'aim'},{op:'status',duration:'stun_duration',values:{stun:true},dispel:'strong',radius:'ghostship_width',center:'aim'}]}];
 const tide=p.definition.abilities.find(a=>a.id==='kunkka_tidebringer');tide.recipe.toggle=true;tide.recipe.attack.ops=[];tide.recipe.arenaNote+=' V8：加伤进入同一次实际普攻结算；破被动暂时关闭，未命中不消耗；再按S2可取消准备。';tide.mvp.arenaNote=tide.recipe.arenaNote;
 p.contract.arenaOmissions=[{abilityId:ship.id,reason:'Fixed aimed-point crash; self rum begins on activation for5s, followed by5s nonlethal repayment. Source innate scalar is used only as the declared Ghostship formula; no threshold-triggered innate is enabled.'},{abilityId:tide.id,reason:'Single target: no secondary cleave; next landed attack consumes one prepared bonus.'}];
 }return p;}));
