import {ADAPTED_SOURCES as SOURCES} from './adaptations.js';
import {createPackServices,packHasDebuffImmunity,PACK_ABI_VERSION} from '../../pack-services.js';
if(!['duel-pack-2.1-status','duel-pack-2.2-hp','duel-pack-2.3-control'].includes(PACK_ABI_VERSION))throw Error('r20_55 v5 requires frozen ABI 2.1');
const copy=x=>JSON.parse(JSON.stringify(x)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const abilities=new Map(SOURCES.flatMap(p=>[...p.definition.abilities,...p.definition.innates].map(a=>[a.id,a])));
const programs=new Map(),programIds=new WeakMap();
function collect(id,node,path='recipe'){if(Array.isArray(node)){if(node.length&&node.every(o=>o&&typeof o.op==='string')){programs.set(id+':'+path,node);programIds.set(node,id+':'+path);}node.forEach((o,i)=>collect(id,o,path+'.'+i));}else if(node&&typeof node==='object')for(const [k,v] of Object.entries(node))collect(id,v,path+'.'+k);}
for(const a of abilities.values())collect(a.id,a.recipe);
export const services=createPackServices('r20_55',{abilityIds:[...abilities.keys()],entityKinds:['area','spirit','orb'],eventKinds:['program'],maxEntities:64,maxJobs:128});
const state=(e,f)=>services.fighter(e,f),world=e=>services.world(e),own=(e,f)=>e.hero(f.i).packKey==='r20_55';
const active=(e,f,s)=>services.effective(e,f,s.key)&&(!s.hostile||f.invuln<=0);
const records=(e,f)=>state(e,f).statuses.filter(s=>active(e,f,s));
function context(e,owner,target,id,aim,reflected=false){return {e,f:e.fighters[owner],t:e.fighters[target],a:abilities.get(id),id,p:abilities.get(id).mvp.params,aim,reflected};}
function stat(c,name,who){const f=who==='target'?c.t:c.f,h=c.e.hero(f.i);if(name==='missingHp')return f.maxHp-f.hp;if(name==='attack'||name==='baseAttack')return h.attack;if(['str','agi','int'].includes(name))return h.arenaStats?.[name]??h.attributes18?.[name]??0;return f[name];}
function resolve(x,c){if(x==null)return 0;if(typeof x==='number')return x;if(typeof x==='string'){if(!Number.isFinite(c.p[x]))throw Error('Missing source coefficient '+c.id+'.'+x);return c.p[x];}if(x.stat)return stat(c,x.stat,x.who);if(x.mul)return x.mul.reduce((n,a)=>n*resolve(a,c),1);if(x.add)return x.add.reduce((n,a)=>n+resolve(a,c),0);if(x.div)return resolve(x.div[0],c)/resolve(x.div[1],c);if(x.min)return Math.min(...x.min.map(a=>resolve(a,c)));if(x.max)return Math.max(...x.max.map(a=>resolve(a,c)));throw Error('Unknown coefficient expression');}
const values=(v,c)=>Object.fromEntries(Object.entries(v||{}).map(([k,x])=>[k,typeof x==='boolean'?x:resolve(x,c)]));
function projection(e,f,key){let n=0;for(const s of records(e,f))n+=Number(s.values[key]||0);if(own(e,f)&&e.passivesEnabled(f))for(const a of [...e.hero(f.i).abilities,...e.hero(f.i).innates])if(a.mvp.passive&&a.recipe.stats?.[key])n+=resolve(a.recipe.stats[key],context(e,f.i,1-f.i,a.id,f.x));return n;}
export function effectiveCastRange(e,f,ability){let range=ability.mvp.range_wu;if(records(e,f).some(b=>b.abilityId==='dragon_knight_elder_dragon_form'))range+=abilities.get('dragon_knight_elder_dragon_form').mvp.params.bonus_ability_cast_range*.55;return Math.max(0,range*(1-clamp(projection(e,f,'castReduction'),0,1)));}
function thirst(e,f){if(!own(e,f)||!e.passivesEnabled(f))return 0;const a=e.hero(f.i).abilities.find(a=>a.id==='bloodseeker_thirst');if(!a)return 0;const p=a.mvp.params,t=e.fighters[1-f.i];return p.bonus_movement_speed/100*clamp((p.min_bonus_pct/100-t.hp/t.maxHp)/((p.min_bonus_pct-p.max_bonus_pct)/100),0,1);}
function hit(c,amount,type=c.a.mvp.damage_type){return services.damageResult(c.e,c.f.i,c.t,amount,{type:type==='none'?'magical':type,abilityId:c.id,reflected:c.reflected,noReflect:c.reflected}).actual;}
function program(ops){const id=programIds.get(ops);if(!id)throw Error('Noncanonical effect program');return id;}
function buff(c,op){const e=c.e,f=op.to==='self'?c.f:c.t,v=values(op.values,c),duration=resolve(op.duration,c),hostile=f!==c.f;
 if(duration<=0||f.hp<=0)return null;
 const options={key:op.key||c.id,owner:c.f.i,duration,values:v,dispel:op.dispel||'basic',pierces:!!op.pierces,interval:op.tick?resolve(op.tick.interval,c):0};let parts;
 const negativeKeys=new Set(['disarm','magicVulnerable','moveSlow']);
 if(v.physicalImmune&&Object.keys(v).some(k=>negativeKeys.has(k))){const positive=Object.fromEntries(Object.entries(v).filter(([k])=>!negativeKeys.has(k))),negative=Object.fromEntries(Object.entries(v).filter(([k])=>negativeKeys.has(k)));const pair=services.applyMixedStatus(e,f,{key:options.key,owner:options.owner,duration,positive:{values:positive,dispel:options.dispel},negative:{values:negative,dispel:options.dispel},pierces:options.pierces});parts=[pair.positive,pair.negative].filter(Boolean);}else{const part=hostile?services.applyStatus(e,f,options):services.applyPositiveStatus(e,f,options);parts=part?[part]:[];}
 for(const s of parts)Object.assign(s,{abilityId:c.id,reflected:!!c.reflected,programId:op.tick?program(op.tick.ops):null});
 if(parts.some(s=>s.hostile)||!hostile)for(const k of ['stun','root','hex','fear','taunt'])if(v[k])services.control(e,f,k,duration,!!op.pierces);
 return parts.find(s=>s.hostile)||parts[0]||null;
}
function addArea(c,op){const duration=resolve(op.duration,c),interval=resolve(op.interval,c);if(interval<=0)throw Error('Invalid interval');services.spawn(c.e,{kind:'area',owner:c.f.i,x:op.follow?c.f.x:c.aim,life:duration,data:{abilityId:c.id,target:c.t.i,programId:program(op.ops),interval,tick:0,radius:resolve(op.radius,c)*.55,growth:resolve(op.growth,c)*.55,pulses:0,hits:0,maxHits:resolve(op.maxHits,c),follow:!!op.follow,channel:!!op.channel,breakOnRange:!!op.breakOnRange,cancelOnLeave:!!op.cancelOnLeave,reflected:!!c.reflected}});if(op.channel)state(c.e,c.f).data.channel={abilityId:c.id,life:duration};}
function execute(c,ops){for(const op of ops){const e=c.e,f=op.to==='self'?c.f:c.t;if(!['area','delay'].includes(op.op)&&op.radius!==undefined&&Math.abs((op.center==='aim'?c.aim:c.f.x)-f.x)>resolve(op.radius,c)*.55)continue;
 switch(op.op){
 case 'damage':{const actual=hit({...c,t:f},resolve(op.amount,c),op.type||c.a.mvp.damage_type);if(op.healFraction)services.heal(e,c.f,actual*resolve(op.healFraction,c),{skill:c.id});break;}
 case 'heal':services.heal(e,f,resolve(op.amount,c),{skill:c.id});break;
 case 'status':buff(c,op);break;
 case 'delay':services.scheduleEffect(e,{abilityId:c.id,kind:'program',owner:c.f.i,target:c.t.i,delay:resolve(op.delay,c),data:{programId:program(op.ops),aim:c.aim,reflected:!!c.reflected,routeAtDelivery:c.id==='vengefulspirit_magic_missile'&&!c.reflected}});break;
 case 'area':addArea(c,op);break;
 case 'mana':{if(f.invuln>0||e.property(f,'debuffImmune'))break;const n=Math.min(f.mp,Math.max(0,resolve(op.amount,c)));f.mp-=n;if(op.steal)c.f.mp=Math.min(c.f.maxMp,c.f.mp+n);break;}
 case 'selfCost':e.nonlethalSelfDamage(c.f,c.f.maxHp*resolve(op.percent,c)/100);break;
 case 'swap':{if(c.t.invuln>0)break;const x=c.f.x;e.move(c.f,c.t.x-c.f.x);e.move(c.t,x-c.t.x);e.interrupt(c.t);break;}
 case 'move':{if(e.controlRemaining(f,'root')>0||f===c.t&&f.invuln>0)break;const x=op.mode==='behind'?c.t.x-Math.sign(c.t.x-c.f.x||1)*50:c.aim;e.move(f,x-f.x);break;}
 case 'pullStep':if(c.t.invuln<=0&&!e.property(c.t,'debuffImmune'))e.move(c.t,Math.sign(c.f.x-c.t.x)*Math.min(Math.abs(c.f.x-c.t.x),resolve(op.amount,c)));break;
 case 'dispel':e.dispel(f,op.tier);break;
 case 'toggle':{const old=state(e,c.f).statuses.find(s=>s.key===c.id);if(old){state(e,c.f).statuses=state(e,c.f).statuses.filter(s=>s!==old);c.f.buffs=c.f.buffs.filter(s=>s.key!==c.id);}else{buff(c,{...op,to:'self',duration:3600});e.addBuff(c.f,c.id,{r20Toggle:true},3600);}break;}
 case 'upkeepPulse':if(c.f.mp<resolve(op.cost,c)){state(e,c.f).statuses=state(e,c.f).statuses.filter(s=>s.key!==c.id);c.f.buffs=c.f.buffs.filter(s=>s.key!==c.id);}else{c.f.mp-=resolve(op.cost,c);if(Math.abs(c.f.x-c.t.x)<=resolve(op.radius,c)*.55)execute(c,op.ops);}break;
 case 'mark':{const s=buff(c,{duration:op.duration,values:{},dispel:'none'});if(s)s.returnX=c.t.x;break;}
 case 'rupture':{const s=buff(c,{duration:op.duration,values:{rupture:resolve(op.percent,c)/100,damageCap:resolve(op.cap,c)},dispel:'none',pierces:true});if(s)s.lastX=c.t.x;break;}
 case 'attackBuff':{buff(c,{to:'self',duration:3600,values:{attackBonus:resolve(op.damage,c),attackRange:resolve(op.range,c)*.55,charges:resolve(op.charges,c)},dispel:'none'});e.addBuff(c.f,c.id,{attack_range_override:resolve(op.range,c)*.55},3600);break;}
 case 'special':special(c,op.name);break;
 default:throw Error('Missing real Engine operation: '+c.id+'/'+op.op);
 }
}}
function special(c,name){const {e,f,t,p,id}=c;
 if(name==='orb'){services.spawn(e,{kind:'orb',owner:f.i,x:f.x,life:p.max_distance/p.orb_speed,data:{abilityId:id,target:t.i,direction:Math.sign(c.aim-f.x)||f.dir,remainingDistance:p.max_distance*.55,hit:false,tick:0,reflected:!!c.reflected}});e.addBuff(f,id,{r20Recast:true},p.max_distance/p.orb_speed);return;}
 if(name==='siphon'){services.spawn(e,{kind:'spirit',owner:f.i,x:f.x,life:p.haunt_duration,data:{kind:'siphon',abilityId:id,target:t.i,tick:0,hostile:true,polarity:'hostile',pierces:false,reflected:!!c.reflected}});return;}
 if(name==='exorcism'){state(e,f).data.swarm={abilityId:id,life:p.AbilityDuration,tick:0,spawned:0,actual:0,spirits:[]};return;}
 if(name==='dragon'){buff(c,{to:'self',duration:p.duration,values:{attackRange:p.bonus_attack_range*.55,moveFlat:p.bonus_movement_speed},dispel:'none'});e.addBuff(f,id,{attack_range_bonus:p.bonus_attack_range*.55},p.duration);return;}
 throw Error('Reserved capability: '+id+'/'+name);
}
// Canonical status programs are immutable. Mutable shields may only shrink from their source amount.
function statusSchema(e,g,f,b){
 const a=abilities.get(b.abilityId),c={e,f:g.fighters[b.owner],t:f,a,id:a.id,p:a.mvp.params,aim:f.x},variants=[];
 function visit(node){if(Array.isArray(node)){node.forEach(visit);return;}if(!node||typeof node!=='object')return;
  if(['status','toggle'].includes(node.op)){const key=node.key||a.id;if(b.key===key||b.group===key){const v=values(node.values,c),negativeKeys=new Set(['disarm','magicVulnerable','moveSlow']);const mixed=v.physicalImmune&&Object.keys(v).some(k=>negativeKeys.has(k));const selected=mixed?Object.fromEntries(Object.entries(v).filter(([k])=>negativeKeys.has(k)===b.hostile)):v;variants.push({values:selected,duration:node.op==='toggle'?3600:resolve(node.duration,c),interval:node.tick?resolve(node.tick.interval,c):0,programId:node.tick?program(node.tick.ops):null,hostile:mixed?b.hostile:node.to!=='self'&&node.op!=='toggle',pierces:mixed&&!b.hostile?false:!!node.pierces,dispel:node.dispel||'basic'});}}
  Object.values(node).forEach(visit);
 }
 visit(a.recipe);
 if(a.id==='tiny_tree_grab'&&b.key===a.id)variants.push({values:{attackBonus:a.mvp.params.bonus_damage,attackRange:a.mvp.params.attack_range*.55,charges:a.mvp.params.attack_count},duration:3600,interval:0,programId:null,hostile:false,pierces:false,dispel:'none'});
 if(a.id==='bloodseeker_rupture'&&b.key===a.id)variants.push({values:{rupture:a.mvp.params.movement_damage_pct/100,damageCap:a.mvp.params.damage_cap_amount},duration:a.mvp.params.duration,interval:0,programId:null,hostile:true,pierces:true,dispel:'none'});
 if(a.id==='dragon_knight_elder_dragon_form'){const p=a.mvp.params;if(b.key===a.id)variants.push({values:{attackRange:p.bonus_attack_range*.55,moveFlat:p.bonus_movement_speed},duration:p.duration,interval:0,programId:null,hostile:false,pierces:false,dispel:'none'});if(b.key===a.id+'_corrosion')variants.push({values:{},duration:p.corrosive_duration,interval:1,programId:null,hostile:true,pierces:false,dispel:'basic'});if(b.key===a.id+'_frost')variants.push({values:{moveSlow:p.frost_bonus_movement_speed/100,attackSlow:p.frost_bonus_attack_speed},duration:p.frost_duration,interval:0,programId:null,hostile:true,pierces:true,dispel:'basic'});}
 return variants.some(v=>v.duration===b.duration&&v.interval===b.interval&&v.programId===b.programId&&v.hostile===b.hostile&&v.pierces===b.pierces&&v.dispel===b.dispel&&Object.keys(v.values).length===Object.keys(b.values).length&&Object.entries(v.values).every(([k,n])=>['shield','charges'].includes(k)?(k!=='charges'||Number.isInteger(b.values[k]))&&Number.isFinite(b.values[k])&&b.values[k]>=0&&b.values[k]<=n:b.values[k]===n));
}
function tickStatus(e,f,s,enabled){if(enabled&&(!s.hostile||f.invuln<=0)&&s.programId){const c=context(e,s.owner,f.i,s.abilityId,f.x,s.reflected);execute(c,programs.get(s.programId));}}
function cleanup(e,f){services.cancelOwnerEffects(e,f.i,{includePersistent:true});world(e).entities=world(e).entities.filter(x=>x.owner!==f.i);const d=state(e,f).data;state(e,f).statuses=[];d.channel=null;d.swarm=null;f.buffs=f.buffs.filter(b=>!abilities.has(b.key));}
export const Combat={namespace:'r20_55',
 init(e){world(e);for(const f of e.fighters)state(e,f).data={channel:null,swarm:null,dead:false,aura:{},proc:{}};},
 cast(e,f,slot,options={}){const a=e.ability(f.i,slot),m=a?.mvp,t=e.fighters[1-f.i];if(!own(e,f)||!a||m.passive||a.engineStatus!=='implemented'||f.hp<=0||e.paused||e.phase!=='fight'||e.blocked(f)||e.isSilenced(f)||f.cast||f.recovery>0)return false;
  if(a.id==='puck_illusory_orb'){const orb=world(e).entities.find(x=>x.kind==='orb'&&x.owner===f.i&&x.life>0);if(orb){if(e.controlRemaining(f,'root')>0||records(e,f).some(s=>s.values.leash))return false;e.commitAction(f);e.move(f,orb.x-f.x);orb.life=0;f.buffs=f.buffs.filter(b=>b.key!==a.id);e.log('pack_recast',f.i,{skill:a.id,entityId:orb.id});return true;}}
  if(a.recipe.toggle&&state(e,f).statuses.some(s=>s.key===a.id)){e.commitAction(f);execute(context(e,f.i,t.i,a.id,f.x),a.recipe.ops);return true;}
  if(f.cd[slot]>1e-8||f.mp<m.mana||m.charges&&f.charges[slot]<=0)return false;
  const range=effectiveCastRange(e,f,a);
  if(a.recipe.target==='enemy'&&(t.hp<=0||t.invuln>0||!a.recipe.arenaGlobal&&Math.abs(t.x-f.x)>range+22))return false;
  const aim=options.aim??t.x;if(!Number.isFinite(aim)||a.recipe.target==='point'&&options.aim!==undefined&&(aim<45||aim>1155||Math.abs(aim-f.x)>range+22))return false;
  const x=a.recipe.target==='self'?f.x:clamp(aim,Math.max(45,f.x-(a.recipe.arenaGlobal?1200:range)),Math.min(1155,f.x+(a.recipe.arenaGlobal?1200:range)));
  e.commitAction(f);f.mp-=m.mana;f.cd[slot]=m.cooldown_s;if(m.charges){f.charges[slot]--;if(f.chargeTimers[slot]<=0)f.chargeTimers[slot]=m.charge_restore_s;}f.casts++;f.guard=false;
  const c={id:++e.seq,slot,abilityId:a.id,remaining:m.startup_frames/60,aim:x};if(a.recipe.target==='enemy')e.notifyTargeted(f,t,a.id);if(c.remaining>0)f.cast=c;else this.activate(e,f,c);e.animate(f,'cast',.35);e.log('cast',f.i,{skill:a.id,slot,cost:m.mana});return true;
 },
 activate(e,f,cast){const a=abilities.get(e.ability(f.i,cast.slot).id);if(e.ability(f.i,cast.slot).engineStatus!=='implemented')throw Error('Unimplemented owned activation');let t=e.fighters[1-f.i],source=f,reflected=false;const counter=e.buff(t,'counter');if(a.recipe.target==='enemy'&&a.id!=='vengefulspirit_magic_missile'&&counter&&!counter.m.counter_type){t.buffs=t.buffs.filter(b=>b!==counter);source=t;t=f;reflected=true;}f.recovery=a.mvp.recovery_frames/60;execute(context(e,source.i,t.i,a.id,cast.aim,reflected),a.recipe.ops);e.log('activate',f.i,{skill:a.id,slot:cast.slot});return true;},
 silenced(e,f){return !!state(e,f).data.channel||projection(e,f,'silence')>0;},
 disarmed(e,f){return !!state(e,f).data.channel||projection(e,f,'disarm')>0;},
 broken(f){return !!f.packModules?.r20_55?.statuses.some(s=>s.life>0&&s.values.break&&(!s.hostile||f.invuln<=0&&(s.pierces||!packHasDebuffImmunity(f)&&!f.buffs.some(b=>b.life>0&&b.m.debuffImmune))));},
 attack(e,f,t,amount,m){return (amount+projection(e,f,'attackBonus'))*(1+projection(e,f,'attackPct'))*(1-clamp(projection(e,f,'attackReduction'),0,1));},
 attackInterval(e,f,t,seconds){return seconds*100/Math.max(20,100+projection(e,f,'attackSpeed')-projection(e,f,'attackSlow'));},
 moveMultiplier(e,f){if(state(e,f).data.channel)return 0;return Math.max(0,(1+projection(e,f,'moveFlat')/e.hero(f.i).move_speed)*(1+projection(e,f,'moveBonus')+thirst(e,f))*(1-clamp(projection(e,f,'moveSlow'),0,.95)));},
 healing(e,f,amount){return amount*(1+projection(e,f,'healAmp')+projection(e,f,'graveHealAmpPerDecile')*Math.floor((1-f.hp/f.maxHp)*10));},
 modifyDamage(e,v){if(v.m.damage_type==='physical')v.sharedArmor=(v.sharedArmor||0)+projection(e,v.target,'armor');if(!v.info.basic&&!v.info.reflected)v.damage*=1+projection(e,v.attacker,'spellAmp');if(v.m.damage_type==='magical')v.damage*=(1-clamp(projection(e,v.target,'magicResist'),0,1))*(1+projection(e,v.target,'magicVulnerable'));if(v.info.basic)v.damage*=1-clamp(projection(e,v.target,'basicReduction'),0,1);},
 beforeDamage(e,v){if(v.m.damage_type==='physical'&&projection(e,v.target,'physicalImmune')>0)v.damage=0;if(projection(e,v.target,'grave'))v.damage=Math.min(v.damage,Math.max(0,v.target.hp-1));for(const s of records(e,v.target))if(s.values.shield>0){const n=Math.min(v.damage,s.values.shield);s.values.shield-=n;v.damage-=n;}},
 afterDamage(e,v){if(v.damage<=0||v.info.noLifesteal||v.info.reflected)return;for(const s of state(e,v.target).statuses)if(active(e,v.target,s)&&s.owner===v.attacker.i&&s.values.lifesteal)services.heal(e,v.attacker,v.damage*s.values.lifesteal,{skill:s.abilityId});},
 afterAttack(e,f,t,event,landed){if(!landed||event.m?.r20Secondary||!own(e,f))return;const tree=services.status(e,f,'tiny_tree_grab');if(tree){tree.values.charges--;if(tree.values.charges<=0){services.removeStatus(e,f,'tiny_tree_grab');f.buffs=f.buffs.filter(b=>b.key!=='tiny_tree_grab');}}if(!e.passivesEnabled(f))return;for(const a of e.hero(f.i).abilities){const r=a.recipe.attack;if(!r||a.engineStatus!=='implemented')continue;const c=context(e,f.i,t.i,a.id,t.x),d=state(e,f).data;if(r.requiresToggle&&!state(e,f).statuses.some(s=>s.key===a.id))continue;if((d.proc[a.id]||0)>e.t)continue;if(r.chance&&e.random()>=resolve(r.chance,c)/100)continue;if(r.mana&&f.mp<resolve(r.mana,c))continue;if(r.mana)f.mp-=resolve(r.mana,c);if(r.ops)execute(c,r.ops);if(r.cooldown)d.proc[a.id]=e.t+resolve(r.cooldown,c);if(r.consumeToggle){state(e,f).statuses=state(e,f).statuses.filter(s=>s.key!==a.id);f.buffs=f.buffs.filter(s=>s.key!==a.id);}}
  const dragon=state(e,f).statuses.find(s=>s.abilityId==='dragon_knight_elder_dragon_form');if(dragon){const c=context(e,f.i,t.i,dragon.abilityId,t.x),p=c.p;const s=buff(c,{key:c.id+'_corrosion',duration:p.corrosive_duration,values:{},dispel:'basic'});if(s){s.interval=1;s.specialTick='corrosion';}buff(c,{key:c.id+'_frost',duration:p.frost_duration,values:{moveSlow:p.frost_bonus_movement_speed/100,attackSlow:p.frost_bonus_attack_speed},pierces:true});}
 },
 interrupted(e,f){state(e,f).data.channel=null;world(e).entities=world(e).entities.filter(x=>x.owner!==f.i||!x.data.channel);const pending=world(e).jobs.filter(j=>j.owner===f.i&&!j.cancelOnInterrupt);services.cancelOwnerEffects(e,f.i);world(e).jobs=[...world(e).jobs.filter(j=>j.owner!==f.i),...pending];},
 dispel(e,f,tier){services.dispel(e,f,tier);},
 tick(e,dt){for(const f of e.fighters){const d=state(e,f).data;if(f.hp<=0){if(!d.dead){cleanup(e,f);d.dead=true;}continue;}d.dead=false;if(d.channel){d.channel.life-=dt;const inp=e.input[f.i];if(d.channel.life<=1e-8||inp.left||inp.right||inp.attack||[0,1,2,3].some(slot=>inp['s'+slot]&&!e.previous[f.i]['s'+slot])||e.blocked(f)||f.silence>0||projection(e,f,'silence')>0)this.interrupted(e,f);}
   for(const s of [...state(e,f).statuses]){if(s.values.rupture){const distance=Math.abs(f.x-s.lastX)/.55;s.lastX=f.x;if(active(e,f,s)&&distance<=s.values.damageCap)hit(context(e,s.owner,f.i,s.abilityId,f.x,s.reflected),distance*s.values.rupture,'pure');}if(s.returnX!==undefined&&s.life<=dt+1e-8&&active(e,f,s)&&f.invuln<=0)e.move(f,s.returnX-f.x);}
   services.advanceStatuses(e,f,dt,(s,enabled)=>{if(s.specialTick==='corrosion'){if(enabled&&(!s.hostile||f.invuln<=0))hit(context(e,s.owner,f.i,s.abilityId,f.x,s.reflected),abilities.get(s.abilityId).mvp.params.corrosive_damage_per_second,'magical');}else tickStatus(e,f,s,enabled);});

   if(own(e,f)&&e.passivesEnabled(f))for(const a of e.hero(f.i).abilities){const au=a.recipe.aura;if(!au)continue;d.aura[a.id]=(d.aura[a.id]||0)+dt;if(d.aura[a.id]>=au.interval-1e-8){d.aura[a.id]-=au.interval;const c=context(e,f.i,1-f.i,a.id,f.x);if(Math.abs(f.x-c.t.x)<=resolve(au.radius,c)*.55)execute(c,au.ops);}}
   if(d.swarm){const s=d.swarm,p=abilities.get(s.abilityId).mvp.params,t=e.fighters[1-f.i];s.life=Math.max(0,s.life-dt);s.tick+=dt;while(s.tick>=p.ghost_spawn_rate&&s.spawned<p.spirits){s.tick-=p.ghost_spawn_rate;s.spawned++;s.spirits.push({x:f.x,returning:false});}for(const sp of s.spirits){if(t.hp<=0||Math.abs(f.x-t.x)>p.give_up_distance*.55)sp.returning=true;const dest=sp.returning?f.x:t.x,dist=dest-sp.x,travel=p.spirit_speed*.55*dt;sp.x+=Math.sign(dist)*Math.min(Math.abs(dist),travel);if(Math.abs(dist)<=travel){if(sp.returning)sp.returning=false;else{s.actual+=hit(context(e,f.i,t.i,s.abilityId,t.x),p.average_damage,'physical');sp.returning=true;}}}if(s.life<=1e-8){services.heal(e,f,s.actual*p.heal_percent/100,{skill:s.abilityId});d.swarm=null;}}
  }
  services.runDue(e,j=>{let source=j.owner,target=j.target,reflected=j.data.reflected;const t=e.fighters[target],counter=e.buff(t,'counter');if(j.data.routeAtDelivery&&!reflected&&counter&&!counter.m.counter_type){t.buffs=t.buffs.filter(b=>b!==counter);source=target;target=j.owner;reflected=true;}execute(context(e,source,target,j.abilityId,j.data.aim,reflected),programs.get(j.data.programId));});
  const w=world(e);for(const ent of [...w.entities]){if(ent.life<=1e-8)continue;const d=ent.data,f=e.fighters[ent.owner],t=e.fighters[d.target],live=Math.min(dt,ent.life);if(f.hp<=0){ent.life=0;continue;}ent.life=Math.max(0,ent.life-live);const c=context(e,f.i,t.i,d.abilityId,ent.x,d.reflected);
   if(ent.kind==='orb'){const p=c.p,prev=ent.x,travel=Math.min(d.remainingDistance,p.orb_speed*.55*live);ent.x+=d.direction*travel;d.remainingDistance-=travel;if(!d.hit&&t.x>=Math.min(prev,ent.x)-p.radius*.55&&t.x<=Math.max(prev,ent.x)+p.radius*.55){hit(c,p.damage);d.hit=true;}d.tick+=live;while(d.tick>=p.damage_interval-1e-8){d.tick=Math.max(0,d.tick-p.damage_interval);if(Math.abs(ent.x-t.x)<=p.radius*.55)hit(c,p.damage*p.damage_over_time_pct/100);}if(d.remainingDistance<=0||ent.x<0||ent.x>1200)ent.life=0;if(ent.life<=1e-8)f.buffs=f.buffs.filter(b=>b.key!==c.id);continue;}
   if(ent.kind==='spirit'){const p=c.p;if(t.hp<=0||Math.abs(f.x-t.x)>(p.AbilityCastRange+p.siphon_buffer)*.55){ent.life=0;continue;}d.tick+=live;while(d.tick>=.25-1e-8){d.tick-=.25;if(t.invuln<=0&&!e.property(t,'debuffImmune'))services.heal(e,f,hit(c,p.damage*.25,'magical'),{skill:c.id});}continue;}
   if(d.follow)ent.x=f.x;if(d.channel&&!state(e,f).data.channel||d.breakOnRange&&Math.abs(f.x-t.x)>d.radius||d.cancelOnLeave&&Math.abs(f.x-ent.x)>d.radius){ent.life=0;continue;}d.tick+=live;while(d.tick>=d.interval-1e-8){d.tick-=d.interval;const radius=d.radius+d.growth*d.pulses++;if(Math.abs(ent.x-t.x)<=radius&&(!d.maxHits||d.hits<d.maxHits)){d.hits++;execute({...c,aim:ent.x},programs.get(d.programId));}}}
  w.entities=w.entities.filter(x=>x.life>1e-8);
 },
 endStep(e){for(const f of e.fighters)if(f.hp<=0&&!state(e,f).data.dead){cleanup(e,f);state(e,f).data.dead=true;}},
 validateSnapshot(e,g){if(!services.validateSnapshot(g)||!g.fighters.every((f,i)=>f.i===i))return false;try{const pairIds=new Set(e.runtimeHeroes.flatMap(h=>h.abilities.map(a=>a.id)));for(const f of g.fighters){const s=f.packModules.r20_55,d=s.data;if(e.hero(f.i).packKey==='r20_55'&&f.cast){const a=e.ability(f.i,f.cast.slot);if(!a||a.mvp.passive||f.cast.abilityId!==a.id||f.cast.m!==undefined||!Number.isFinite(f.cast.remaining)||f.cast.remaining<0||f.cast.remaining>a.mvp.startup_frames/60||!Number.isFinite(f.cast.aim)||f.cast.aim<45||f.cast.aim>1155)return false;}for(const b of f.buffs)if(abilities.has(b.key)){const expected=b.key==='dragon_knight_elder_dragon_form'?{attack_range_bonus:abilities.get(b.key).mvp.params.bonus_attack_range*.55}:b.key==='leshrac_pulse_nova'?{r20Toggle:true}:b.key==='tiny_tree_grab'?{attack_range_override:abilities.get(b.key).mvp.params.attack_range*.55}:b.key==='puck_illusory_orb'?{r20Recast:true}:null;if(!expected||JSON.stringify(b.m)!==JSON.stringify(expected))return false;}if(typeof d.dead!=='boolean'||!d.aura||!d.proc)return false;for(const b of s.statuses)if(!pairIds.has(b.abilityId)||!statusSchema(e,g,f,b)||b.values.rupture&&(!Number.isFinite(b.lastX)||b.lastX<0||b.lastX>1200)||typeof b.hostile!=='boolean'||!['positive','hostile','mixed'].includes(b.polarity)||typeof b.reflected!=='boolean'||b.life<0||b.life>3600||!Number.isFinite(b.interval)||b.interval<0||b.programId!==null&&(!programs.has(b.programId)||!b.programId.startsWith(b.abilityId+':'))||Object.values(b.values).some(v=>typeof v!=='boolean'&&!Number.isFinite(v)))return false;if(d.channel&&(!abilities.has(d.channel.abilityId)||!Number.isFinite(d.channel.life)||d.channel.life<0))return false;if(d.swarm&&(!abilities.has(d.swarm.abilityId)||!Number.isFinite(d.swarm.life)||d.swarm.life<0||!Array.isArray(d.swarm.spirits)||d.swarm.spirits.length>26||!Number.isFinite(d.swarm.actual)||d.swarm.actual<0||d.swarm.actual>1000000||d.swarm.abilityId!=='death_prophet_exorcism'||d.swarm.life>40||!Number.isInteger(d.swarm.spawned)||d.swarm.spawned!==d.swarm.spirits.length||d.swarm.spirits.some(sp=>!Number.isFinite(sp.x)||sp.x<0||sp.x>1200||typeof sp.returning!=='boolean')))return false;}
   for(const j of g.packModules.r20_55.jobs)if(!pairIds.has(j.abilityId)||!programs.has(j.data.programId)||!j.data.programId.startsWith(j.abilityId+':')||!Number.isFinite(j.data.aim)||typeof j.data.reflected!=='boolean'||typeof j.data.routeAtDelivery!=='boolean')return false;
   for(const x of g.packModules.r20_55.entities){if(x.life<0||x.life>100||!pairIds.has(x.data.abilityId))return false;if(x.kind==='area'&&(!programs.has(x.data.programId)||!x.data.programId.startsWith(x.data.abilityId+':')||!Number.isFinite(x.data.interval)||x.data.interval<=0||!Number.isFinite(x.data.radius)||x.data.radius<0))return false;if(x.kind==='orb'&&(x.data.abilityId!=='puck_illusory_orb'||![-1,1].includes(x.data.direction)||typeof x.data.hit!=='boolean'||!Number.isFinite(x.data.remainingDistance)||x.data.remainingDistance<0||x.data.remainingDistance>abilities.get(x.data.abilityId).mvp.params.max_distance*.55||!Number.isFinite(x.data.tick)||x.data.tick<0||x.data.tick>abilities.get(x.data.abilityId).mvp.params.damage_interval))return false;if(x.kind==='spirit'&&(x.data.kind!=='siphon'||x.data.abilityId!=='death_prophet_spirit_siphon'||x.data.hostile!==true||x.data.polarity!=='hostile'||x.data.pierces!==false))return false;}return true;}catch{return false;}}
};
