import {ADAPTED_SOURCES as SOURCES} from './adaptations.js';
import {Combat} from './combat.js';
export const GAPS={
 20:['cast-range-projection','positive-invulnerability'],22:['attribute-resource-transaction','combat-profile-transaction','positive-invulnerability'],23:['attackable-units','attack-intent-pursuit'],24:['positive-invulnerability'],26:['visibility-query','attack-intent','secondary-attack-receipt'],27:['control-duration-projection'],30:['attackable-units'],33:['visibility-query','positive-invulnerability'],34:['attackable-units'],35:['attackable-units'],37:['attackable-units'],38:['attackable-units'],39:['attackable-units'],40:['cooldown-rate-projection'],41:['attackable-units','pre-ko-revival'],43:['attackable-units','committed-mana-notification'],44:['visibility-query','secondary-attack-receipt'],46:['attackable-units'],48:['body-spirit-target-routing'],49:['attackable-units','terrain-collision'],51:['attackable-units','terrain-collision'],52:['attackable-units','positive-invulnerability'],53:['attackable-units','movement-immunity-projection'],54:['attackable-units','max-resource-transaction','visibility-query']
};
const deepFreeze=x=>{if(x&&typeof x==='object'&&!Object.isFrozen(x)){Object.values(x).forEach(deepFreeze);Object.freeze(x);}return x;};
const ready=new Set([21,28,29,32,36,42,47,50,55]);
// Deliberately narrow executable selection. Remaining heroes retain canonical source definitions and fail closed.
export const CANDIDATES=SOURCES.map(p=>{const d=structuredClone(p.definition),contract=structuredClone(p.contract);const available=ready.has(d.registryNumericId);for(const a of d.abilities){a.engineStatus=available?'implemented':'requires-capability';a.runtimeReady=false;a.activeUnlock=false;if(a.id==='puck_illusory_orb')a.mvp.toggle=true;if(a.recipe.toggle)a.mvp.toggle=true;if(a.id==='death_prophet_spirit_siphon'){a.mvp.charges=a.mvp.params.AbilityCharges;a.mvp.charge_restore_s=a.mvp.params.AbilityChargeRestoreTime;}}d.runtimeReady=false;d.activeUnlock=false;contract.requiresCapabilities=available?['typed-status','effective-status-values','fighter-state','fighter-damage','fighter-control','fighter-heal','negative-status','effect-entities','scheduled-effects','attack-hooks','damage-hooks','input-interruption','local-snapshot','cross-pack-status-query','targeted-spell-routing','action-cancellation',...(d.registryNumericId===29?['deferred-hp']:[])]:GAPS[d.registryNumericId];contract.baseCommit='c84ca0d9caf27ab27503384fafb26a8563c793c6';contract.version='r20-55-v8-abi2.4';contract.abiVersion='duel-pack-2.4-targeting';contract.state=available?'real_engine_adapter_candidate':'disabled_reserved_capabilities';contract.reflect='Owned targeted spells route counter at activation; Venge missile routes at delayed delivery. Reflected/noReflect/noLifesteal persist through the receipt pipeline.';contract.death='Owner status/job/effect cleanup at endStep; Kunkka rum delegates all capture, settlement and death attribution to the core HP lifecycle. No preKO revival is claimed.';contract.automaticInnateIds=available?d.innates.map(a=>a.valveAbilityId):[];contract.innateActivation=available?'reviewed_source_only':'disabled_with_hero';deepFreeze(d);deepFreeze(contract);return Object.freeze({definition:d,contract,systemId:'r20_55',sharedSystem:Combat});}).sort((a,b)=>a.definition.registryNumericId-b.definition.registryNumericId);
export const PACKS=Object.freeze(CANDIDATES.filter(p=>ready.has(p.definition.registryNumericId)));
export const DISABLED_PACKS=Object.freeze(CANDIDATES.filter(p=>!ready.has(p.definition.registryNumericId)));
