// Tests the shared real Engine transaction, not full Oracle/Legion/Kunkka adapters.
import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../src/engine.js';import {runtimeHeroes} from '../../src/runtime-heroes.js';import {HERO_PACKS} from '../../src/pack-runtime.js';import {ACTIVE_ROSTER} from '../../src/hero-registry.js';
const near=(a,b)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const source=HERO_PACKS.find(p=>p.definition.registryNumericId===94);
const system={namespace:'hp_fixture',init(e){e.enableHPLifecycle();e.packModules={hp_fixture:{duel:null,rewards:[0,0],settlements:[]}};},cast(){return false;},activate(){return true;},hpSettled(e,event){e.packModules.hp_fixture.settlements.push(event);},death(e,event){const w=e.packModules.hp_fixture,d=w.duel;if(d&&e.t<d.until&&!d.ended){w.rewards[1-event.actor]+=30;d.ended=true;d.deathId=event.id;}},validateSnapshot(e,g){return !!g.packModules?.hp_fixture;}};
function arena(side=0,opponent=0){const e=new Engine(runtimeHeroes,side?[opponent,94]:[94,opponent],{simulationRoster:{...ACTIVE_ROSTER,heroIds:[...ACTIVE_ROSTER.heroIds,94]},heroPacks:[{...source,systemId:'hp_fixture',sharedSystem:system}]}).start();return {e,f:e.fighters[side],t:e.fighters[1-side]};}
function run(e,seconds){let n=0;const until=e.t+seconds;while(e.t<until-1e-8&&e.phase==='fight'){e.step();assert(n++<20000);}}
const promise=(e,f,duration=10)=>e.beginDeferredHP(f,{owner:f.i,abilityId:'oracle_false_promise',duration,deferHealing:true,healingMultiplier:2});
const hit=(e,t,f,amount,type='pure')=>e.resolveDamage(t,f,amount,{damage_type:type,blockable:false},{skill:'damage_fixture',dot:true});
for(const side of [0,1])test(`P${side+1} deferred lethal HP emits exactly one death with cause and active Duel reward`,()=>{const {e,f,t}=arena(side);f.hp=100;const id=promise(e,f);const r=hit(e,t,f,200);near(f.hp,100);near(r.actual,0);near(r.deferred,200);run(e,9);e.packModules.hp_fixture.duel={until:e.t+5,ended:false};run(e,1.1);near(f.hp,0);assert.equal(e.packCore.deaths.length,1);const death=e.packCore.deaths[0];assert.equal(death.actor,side);assert.equal(death.cause.source,1-side);assert.equal(death.cause.kind,'deferred');assert.equal(death.cause.ledgerId,id);assert.equal(e.packModules.hp_fixture.rewards[1-side],30);assert.equal(e.phase,'roundEnd');near(e.settleDeferredHP(id,{force:true}).actualDamage,0);e.step();assert.equal(e.packCore.deaths.length,1);assert.equal(e.packModules.hp_fixture.rewards[1-side],30);});
test('mitigated debt is settled without a second resistance/amplification pass',()=>{const e=new Engine(runtimeHeroes,[0,5]).start();e.enableHPLifecycle();const [t,f]=e.fighters;f.hp=500;const id=promise(e,f,.2);near(hit(e,t,f,100,'magical').deferred,65);e.addBuff(f,'later_shield',{magic_reduction:.9},5);e.addBuff(t,'later_amp',{outgoingMultiplier:3},5);run(e,.25);near(f.hp,435);near(e.packCore.ledgers.find(l=>l.id===id).actualDamage,65);});
test('Promise captures already-modified healing once and never re-applies heal budget or multiplier at settlement',()=>{const {e,f,t}=arena();f.hp=100;const budget=f.healBudget;promise(e,f,.2);hit(e,t,f,200);near(e.heal(f,150,{skill:'heal_fixture'}),0);near(f.hp,100);near(f.healBudget,budget-150);run(e,.3);near(f.hp,200);near(f.healBudget,budget-150);assert.equal(e.packCore.deaths.length,0);});
test('overheal during deferral offsets debt even when current HP is full',()=>{const {e,f,t}=arena();const hp=f.hp;promise(e,f,.2);hit(e,t,f,200);near(e.heal(f,100),0);run(e,.3);near(f.hp,hp);});
test('invulnerability postpones settlement without discarding the ledger or charging twice',()=>{const {e,f,t}=arena();f.hp=100;const id=promise(e,f,.1);hit(e,t,f,200);f.invuln=.3;run(e,.2);near(f.hp,100);assert.equal(e.packCore.deaths.length,0);assert.equal(e.settleDeferredHP(id,{force:true}).status,'invulnerable');run(e,.2);near(f.hp,0);assert.equal(e.packCore.deaths.length,1);near(e.settleDeferredHP(id,{force:true}).actualDamage,0);});
test('partial rum-like debt applies immediate damage and nonlethal repayment at a fixed rate',()=>{const {e,f,t}=arena();f.hp=1000;const id=e.beginDeferredHP(f,{owner:f.i,abilityId:'kunkka_ghostship',duration:.1,damageFraction:.36,repayDuration:5,nonlethal:true});const r=hit(e,t,f,100);near(r.actual,64);near(r.deferred,36);near(f.hp,936);run(e,.2);f.hp=2;run(e,5);near(f.hp,1);assert.equal(e.packCore.deaths.length,0);assert.equal(e.packCore.ledgers.find(l=>l.id===id).phase,'settled');});
test('duplicate repayment in one simulation instant cannot advance two portions',()=>{const {e,f,t}=arena();const id=e.beginDeferredHP(f,{owner:0,abilityId:'rum',duration:1,repayDuration:5,damageFraction:1,nonlethal:true});hit(e,t,f,100);const first=e.settleDeferredHP(id,{force:true});const hp=f.hp;assert(first.actualDamage>0);assert.equal(e.settleDeferredHP(id,{force:true}).status,'already_processed');near(f.hp,hp);});
test('guarded/chip-only deferred damage cannot KO a living fighter',()=>{const {e,f,t}=arena();f.hp=10;promise(e,f,.1);e.hit(t,f,100,{damage_type:'pure',chip:true,blockable:false},{dot:true});run(e,.2);near(f.hp,1);assert.equal(e.packCore.deaths.length,0);});
test('deferred and direct deaths use the same once-per-life dispatcher',()=>{const {e,f,t}=arena();f.hp=10;hit(e,t,f,20);e.step();assert.equal(e.packCore.deaths.length,1);assert.equal(e.packCore.deaths[0].cause.kind,'damage');assert.equal(e.packCore.deaths[0].cause.source,1);for(let n=0;n<5;n++)e.step();assert.equal(e.packCore.deaths.length,1);});
test('settlement and Duel reward replay identically from a pending ledger snapshot',()=>{const {e,f,t}=arena();f.hp=100;promise(e,f,.5);hit(e,t,f,200);e.packModules.hp_fixture.duel={until:2,ended:false};run(e,.2);const restored=arena().e.restoreSimulation(e.snapshot());for(let n=0;n<70;n++){e.step();restored.step();assert.deepEqual(e.snapshot(),restored.snapshot());}});
test('ledger snapshot rejects forged actor/amount/cause and leaves simulation unchanged',()=>{const {e,f,t}=arena();promise(e,f);hit(e,t,f,200);const g=e.snapshot();for(const [key,value]of [['target',9],['damage',Infinity],['damageFraction',2],['phase','unknown'],['lastRepayAt',-1]]){const bad=structuredClone(g);bad.packCore.ledgers[0][key]=value;assert.throws(()=>e.restoreSimulation(bad));assert.deepEqual(e.snapshot(),g);}const bad=structuredClone(g);bad.packCore.ledgers[0].lastCause.source=9;assert.throws(()=>e.restoreSimulation(bad));});
test('round reset clears ledgers, death counters and rewards through normal pack initialization',()=>{const {e,f,t}=arena();promise(e,f);hit(e,t,f,200);e.resetRound();assert.equal(e.packCore.ledgers.length,0);assert.equal(e.packCore.deathSeq,0);assert.deepEqual(e.packModules.hp_fixture.rewards,[0,0]);});
