import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../src/engine.js';import {runtimeHeroes} from '../../src/runtime-heroes.js';
import {REGISTRY_VERSION} from '../../src/hero-registry.js';
import {createPackServices,PACK_STATUS_ABI_VERSION,PACK_CAPABILITIES} from '../../src/pack-services.js';
import {LEGACY_STATUS_POLICY} from '../../src/legacy-status-policy.js';
const a=createPackServices('status_one',{abilityIds:['oracle_fortunes_end','resistance_fixture']}),b=createPackServices('status_two');
const near=(x,y)=>assert(Math.abs(x-y)<1e-7,`${x} != ${y}`);
const frames=(e,n)=>{for(let i=0;i<n;i++){e.hitstop=0;e.step();}};
const ids=[0,1,3,5,9,15,25,31,45,100];
function arena(pair=[0,0]){return new Engine(runtimeHeroes,pair,{simulationRoster:{registryVersion:REGISTRY_VERSION,heroIds:ids},seed:73}).start();}
const provider=(e,f,extra={})=>e.registerStatusResistance(f,{source:f.i,abilityId:'resistance_fixture',resistance:.5,duration:10,...extra});
const purge=(e,f,hostile=true,extra={})=>e.dispelTarget(f,{source:1-f.i,abilityId:'oracle_fortunes_end',tier:'basic',hostile,...extra});
function add(api,e,f,key,{hostile=true,dispel='basic',...extra}={}){return api[hostile?'applyStatus':'applyPositiveStatus'](e,f,{key,owner:1-f.i,duration:2,values:{armor:hostile?-2:2},dispel,...extra});}

test('additive status ABI keeps authored ABI2.4 guards and advertises actual shared services',()=>{assert.equal(PACK_STATUS_ABI_VERSION,'duel-status-1');for(const key of ['positive-buff-purge','cross-system-positive-dispel','invulnerable-target-dispel','status-resistance','control-duration-projection'])assert(PACK_CAPABILITIES.includes(key));});
for(const side of [0,1])test(`P${side+1} polarity purge reaches every namespace and leaves the opposite component/none tiers`,()=>{
 const e=arena(),f=e.fighters[side],other=e.fighters[1-side];
 for(const api of [a,b]){add(api,e,f,'bad');add(api,e,f,'good',{hostile:false});add(api,e,f,'locked',{hostile:false,dispel:'none'});add(api,e,f,'strong',{dispel:'strong'});add(api,e,other,'other',{hostile:false});}
 const pair=a.applyMixedStatus(e,f,{key:'edict',owner:other.i,duration:2,positive:{values:{magicReduction:.75}},negative:{values:{disarm:true}}});
 const removed=purge(e,f,false);assert.equal(removed.length,3);assert(!a.status(e,f,'good'));assert(!b.status(e,f,'good'));assert(a.status(e,f,'bad'));assert(a.status(e,f,'strong'));assert(a.status(e,f,'locked'));assert.equal(a.status(e,f,'edict_hostile'),pair.negative);assert.equal(a.status(e,f,'edict_positive'),undefined);assert(a.status(e,other,'other'));
 purge(e,f,true,{tier:'strong'});assert(!a.status(e,f,'bad'));assert(!a.status(e,f,'strong'));assert(!a.status(e,f,'edict_hostile'));assert(a.status(e,f,'locked'));
});
test('positive purge of cross-system immunity resumes retained hostile effects',()=>{const e=arena(),f=e.fighters[0];add(a,e,f,'silence',{values:{silence:true}});add(b,e,f,'immune',{hostile:false,values:{debuffImmune:true}});assert(!e.isSilenced(f));purge(e,f,false);assert(e.isSilenced(f));assert(a.status(e,f,'silence'));});
test('global source control removal respects tier, target and none provenance',()=>{const e=arena(),f=e.fighters[0],g=e.fighters[1];const x=e.applyControlSource(f,{owner:1,key:'basic',type:'stun',duration:.3,dispel:'basic'}),y=e.applyControlSource(f,{owner:1,key:'strong',type:'root',duration:.3}),z=e.applyControlSource(f,{owner:1,key:'none',type:'fear',duration:.3,dispel:'none'}),q=e.applyControlSource(g,{owner:0,key:'other',type:'stun',duration:.3});purge(e,f);assert(!e.packCore.controls.some(c=>c.id===x));assert(e.packCore.controls.some(c=>c.id===y));purge(e,f,true,{tier:'strong'});assert(!e.packCore.controls.some(c=>c.id===y));assert(e.packCore.controls.some(c=>c.id===z));assert(e.packCore.controls.some(c=>c.id===q));});
test('explicit legacy adapters purge Warcry while retaining negative/none/unknown markers',()=>{const e=arena(),f=e.fighters[0];e.addBuff(f,'sven_warcry',{physical_reduction:.5},8);e.addBuff(f,'sven_strength',{attack_bonus:100},30);e.addBuff(f,'weak',{attack_damage_debuff:.3,dispelTier:'basic'},4);e.addBuff(f,'private_unknown',{move_bonus:100},4);purge(e,f,false,{tier:'strong'});assert(!e.buff(f,'sven_warcry'));for(const key of ['sven_strength','weak','private_unknown'])assert(e.buff(f,key),key);purge(e,f);assert(!e.buff(f,'weak'));assert(e.buff(f,'private_unknown'));});
test('legacy mixed Take Aim splits independently and repeated positive purge retains its downside',()=>{const e=arena(),f=e.fighters[0];e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,attack_range_bonus:165,self_slow:.65},3);purge(e,f,false);assert(!e.property(f,'headshotGuaranteed'));near(e.property(f,'self_slow'),.65);purge(e,f,false);near(e.property(f,'self_slow'),.65);purge(e,f);assert(!e.buff(f,'sniper_take_aim'));e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.65},3);purge(e,f);assert(e.property(f,'headshotGuaranteed'));assert(!e.property(f,'self_slow'));});
test('purging the temporary Feast grant settles its soul side effect once',()=>{const e=arena(),f=e.fighters[0];e.addBuff(f,'shadow_fiend_feast',{souls:3},8);e.buff(f,'shadow_fiend_feast').collectedSouls=3;f.souls=10;purge(e,f,false);assert.equal(f.souls,7);purge(e,f,false);assert.equal(f.souls,7);});
for(const side of [0,1])test(`P${side+1} Core4 shield purge invokes one burst after other removals commit`,()=>{const pair=side===0?[100,0]:[0,100],e=arena(pair),f=e.fighters[side],t=e.fighters[1-side];f.x=500;t.x=600;f.pack.shield={amount:210,life:12};f.pack.statuses.push({key:'withering',owner:t.i,life:2,values:{healReduction:.335},dispel:'none'});add(a,e,f,'extra_positive',{hostile:false});const hp=t.hp,removed=purge(e,f,false);assert(removed.some(v=>v.key==='aphotic_shield'));assert(!f.pack.shield);assert(!a.status(e,f,'extra_positive'));assert.equal(f.pack.statuses.length,1);near(hp-t.hp,210);assert.equal(e.logs.filter(v=>v.type==='shield_end'&&v.reason==='dispelled').length,1);purge(e,f,false);near(hp-t.hp,210);});
test('Core4 Sprint positive purge retains negative Haze and static-link shared state',()=>{const e=arena([31,0]),f=e.fighters[0];f.pack.sprint={life:10,age:0};f.pack.statuses.push({key:'haze',owner:1,life:18,values:{armor:-20},dispel:'basic'});e.packState.links.push({id:++e.seq,owner:0,target:1,amount:30,life:10,draining:false});purge(e,f,false);assert(!f.pack.sprint);assert.equal(f.pack.statuses.length,1);assert.equal(e.packState.links.length,1);purge(e,f);assert.equal(f.pack.statuses.length,0);assert.equal(e.packState.links.length,1);});
test('negative core purge removes poison but retains none Viper Strike',()=>{const e=arena([45,0]),f=e.fighters[1];f.pack.poison.push({id:++e.seq,owner:0,life:4,tick:0});f.pack.statuses.push({key:'viper_strike',owner:0,life:6,values:{},dispel:'none',pierces:true});purge(e,f);assert(!f.pack.poison.length);assert.equal(f.pack.statuses[0].key,'viper_strike');});
test('legacy DOT purge keeps Maledict and untyped unknown DOTs',()=>{const e=arena(),f=e.fighters[0];for(const [id,dispelTier]of [['axe_hunger','basic'],['witch_doctor_maledict','none'],['unknown',undefined]])e.addDebuffDot(f,{owner:1,id,life:3,tick:1,m:{damage:10,tick_interval_s:1,...(dispelTier?{dispelTier}:{})},hp0:f.hp});purge(e,f,true,{tier:'strong'});assert.deepEqual(f.dots.map(d=>d.id),['witch_doctor_maledict','unknown']);});
test('invulnerable target permission is explicit and cannot be substituted by immunity piercing',()=>{const e=arena(),f=e.fighters[0];add(a,e,f,'bad');f.invuln=2;const initial=f.invuln;assert.deepEqual(purge(e,f),[]);assert(!e.canTargetSpell({owner:1,target:0,abilityId:'oracle_fortunes_end',pierces:true}).ok);assert(e.canTargetSpell({owner:1,target:0,abilityId:'oracle_fortunes_end',allowInvulnerable:true}).ok);assert.throws(()=>purge(e,f,true,{abilityId:'other',allowInvulnerable:true}));assert.throws(()=>e.canTargetSpell({owner:1,target:0,abilityId:'other',allowInvulnerable:true}));assert.equal(purge(e,f,true,{allowInvulnerable:true}).length,1);assert.equal(f.invuln,initial);});
test('fresh hostile invulnerable status admission forwards permission to the effective-status gate',()=>{const e=arena(),f=e.fighters[0];f.invuln=1;assert.equal(add(a,e,f,'piercing',{pierces:true}),null);const s=add(a,e,f,'permitted',{allowInvulnerable:true,values:{silence:true}});assert(s);assert(a.effective(e,f,'permitted'));assert(e.isSilenced(f));});
test('invalid global request and foreign actor cannot partially remove statuses',()=>{const e=arena(),f=e.fighters[0];add(a,e,f,'bad');const g=e.snapshot();for(const options of [{source:9,abilityId:'oracle_fortunes_end'},{source:1,abilityId:'oracle_fortunes_end',tier:'none'},{source:1,abilityId:'oracle_fortunes_end',hostile:1},{source:1,abilityId:'other',allowInvulnerable:true}]){assert.throws(()=>e.dispelTarget(f,options));assert.deepEqual(e.snapshot(),g);}assert.throws(()=>purge(e,{...f}));});

for(const side of [0,1])test(`P${side+1} new legacy/source controls scale once before cap, existing timers and cooldowns remain`,()=>{const e=arena(),f=e.fighters[side];f.silence=2;f.cd[0]=5;provider(e,f);near(e.control(f,'stun',1),.5);const id=e.applyControlSource(f,{owner:1-side,key:'root',type:'root',duration:1});near(e.packCore.controls.find(v=>v.id===id).life,.5);near(f.silence,2);near(f.cd[0],5);near(f.ccChain,1);});
test('CC chain/grace and debuff immunity rules survive status resistance',()=>{const e=arena(),f=e.fighters[0];provider(e,f);near(e.control(f,'stun',4),1.5);assert.equal(e.control(f,'root',1),0);f.ccChain=0;f.ccGrace=1;assert.equal(e.control(f,'stun',1),0);f.ccGrace=0;e.addBuff(f,'immune',{debuffImmune:true},1);assert.equal(e.control(f,'stun',1),0);near(e.control(f,'stun',1,true),.5);});
test('typed positive and mixed-positive duration do not scale; hostile duration scales once',()=>{const e=arena(),f=e.fighters[0];provider(e,f);const good=add(a,e,f,'good',{hostile:false}),bad=add(a,e,f,'bad');near(good.duration,2);near(bad.duration,1);near(bad.durationScale,.5);const pair=a.applyMixedStatus(e,f,{key:'mixed',owner:1,duration:2,positive:{values:{armor:2}},negative:{values:{disarm:true}}});near(pair.positive.duration,2);near(pair.negative.duration,1);});
test('provider stacking is multiplicative and refresh/release is scoped to a handle',()=>{const e=arena(),f=e.fighters[0];const x=provider(e,f,{key:'one'}),y=provider(e,f,{key:'two'});near(e.statusResistance(f),.75);const z=provider(e,f,{key:'one',resistance:.2});assert(!e.releaseStatusResistance(x));near(e.statusResistance(f),.6);assert(e.releaseStatusResistance(y));near(e.statusResistance(f),.2);assert(e.releaseStatusResistance(z));near(e.statusResistance(f),0);});
test('100% resistance admits no new negative timers/statuses/DOT, but leaves existing effects',()=>{const e=arena(),f=e.fighters[0];f.silence=1;provider(e,f,{resistance:1});assert.equal(e.control(f,'stun',1),0);assert.equal(add(a,e,f,'bad'),null);assert.equal(e.addDebuffDot(f,{owner:1,id:'axe_hunger',life:3,tick:1,m:{damage:10,tick_interval_s:1}}),null);e.hit(e.fighters[1],f,1,{damage_type:'pure',silence_s:3,slow_pct:50},{dot:true});near(f.silence,1);near(f.slow,0);assert(add(a,e,f,'good',{hostile:false}));});
test('passive provider suppresses under Break while active provider and old effects persist',()=>{const e=arena([45,0]),f=e.fighters[1];provider(e,f,{requiresPassives:true});near(e.statusResistance(f),.5);f.pack.statuses.push({key:'viper_strike',owner:0,life:6,values:{},dispel:'none',pierces:true});near(e.statusResistance(f),0);provider(e,f,{key:'active',resistance:.2});near(e.statusResistance(f),.2);f.pack.statuses=[];near(e.statusResistance(f),.6);});
test('positive purge removes removable resistance only; negative cleanse preserves both providers',()=>{const e=arena(),f=e.fighters[0];provider(e,f,{key:'active',dispel:'basic'});provider(e,f,{key:'innate',dispel:'none'});purge(e,f);near(e.statusResistance(f),.75);purge(e,f,false);near(e.statusResistance(f),.5);assert.equal(e.packCore.statusResistance[0].key,'innate');});
test('provider expiry is fixed-step and never retroactively extends an admitted status',()=>{const e=arena(),f=e.fighters[0];provider(e,f,{duration:.1});const s=add(a,e,f,'bad');near(s.duration,1);frames(e,7);near(e.statusResistance(f),0);near(s.duration,1);assert.equal(e.admitStatusDuration(f,{duration:1}),1);});
test('periodic policy keeps pulse intervals/amounts and can reduce total DOT damage',()=>{const e=arena(),f=e.fighters[0];provider(e,f);const s=add(a,e,f,'dot',{duration:1,interval:.25,values:{dps:100}});near(s.duration,.5);near(s.interval,.25);let damage=0;for(let i=0;i<31;i++)a.advanceStatuses(e,f,1/60,(v,enabled)=>{if(enabled)damage+=v.values.dps*v.interval;});near(damage,50);});
test('legacy hit silence/slow, reflected root and harmful buffs enter global duration projection',()=>{const e=arena(),f=e.fighters[0];provider(e,f);e.hit(e.fighters[1],f,1,{damage_type:'pure',silence_s:2,slow_pct:50,slow_duration_s:4,vulnerability_physical:.2,vulnerability_s:6},{dot:true});near(f.silence,1);near(f.slow,2);near(e.buff(f,'vulnerable').life,3);e.addBuff(f,'sven_warcry',{physical_reduction:.5},8);near(e.buff(f,'sven_warcry').life,8);const d=e.addDebuffDot(f,{owner:1,id:'axe_hunger',life:12,tick:1,m:{damage:10,tick_interval_s:1}});near(d.life,6);});
test('Core4 Haze and Poison use the same admission factor, preserving immunity/tier flags',()=>{const e=arena([31,45]),f=e.fighters[1];provider(e,f);e.fighters[0].x=500;f.x=600;assert(e.cast(0,3));frames(e,25);const haze=f.pack.statuses.find(v=>v.key==='haze');assert(haze);near(haze.duration,9);assert(haze.pierces);e.packCombat.afterAttack(e,e.fighters[0],f,{m:{corePoison:true}},true);near(f.pack.poison[0].life,2);});
test('mixed legacy downside expires at its admitted time without shortening the positive buff',()=>{const e=arena(),f=e.fighters[0];provider(e,f);e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.65},1);near(e.buff(f,'sniper_take_aim').negativeLife,.5);frames(e,31);assert(e.property(f,'headshotGuaranteed'));assert.equal(e.property(f,'self_slow'),0);});
test('resistance and dispel state replay identically after snapshot restore',()=>{const e=arena(),f=e.fighters[0];provider(e,f,{dispel:'basic',duration:.7});e.applyControlSource(f,{owner:1,key:'root',type:'root',duration:1});e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.65},1);frames(e,5);const saved=e.snapshot(),r=arena().restoreSimulation(saved);for(let n=0;n<60;n++){if(n===10){purge(e,e.fighters[0],false);purge(r,r.fighters[0],false);}e.step();r.step();assert.deepEqual(r.snapshot(),e.snapshot());}});
test('forged resistance records reject atomically before restore',()=>{const e=arena();provider(e,e.fighters[0]);const good=e.snapshot();for(const patch of [{source:9},{target:9},{id:999999},{resistance:1.1},{resistance:-.1},{life:20},{duration:4000},{requiresPassives:1},{key:'__proto__'},{dispel:'all'}]){const bad=structuredClone(good);Object.assign(bad.packCore.statusResistance[0],patch);assert.throws(()=>e.restoreSimulation(bad));assert.deepEqual(e.snapshot(),good);}const duplicate=structuredClone(good);duplicate.packCore.statusResistance.push(structuredClone(duplicate.packCore.statusResistance[0]));assert.throws(()=>e.restoreSimulation(duplicate));});
test('provider admission/API unknown ability/foreign actor failures leave state unchanged',()=>{const e=arena(),f=e.fighters[0],g=e.snapshot();for(const extra of [{resistance:2},{duration:0},{source:4},{requiresPassives:1},{dispel:'all'}]){assert.throws(()=>provider(e,f,extra));assert.deepEqual(e.snapshot(),g);}assert.throws(()=>a.registerStatusResistance(e,f,{source:0,abilityId:'unknown',resistance:.5,duration:1}));assert.throws(()=>provider(e,{...f}));assert.deepEqual(e.snapshot(),g);f.invuln=1;assert.equal(provider(e,f),null);});
test('declared legacy map never marks toggle/internal source metadata as an enemy debuff',()=>{assert.equal(LEGACY_STATUS_POLICY.drow_ranger_frost.tier,'none');assert.equal(LEGACY_STATUS_POLICY.fiery.tier,'none');assert.equal(LEGACY_STATUS_POLICY.sven_warcry.polarity,'positive');});
test('a refreshed DOT slow is capped after admission, without applying resistance twice',()=>{const e=arena(),f=e.fighters[0];provider(e,f);const d=e.addDebuffDot(f,{owner:1,id:'axe_hunger',life:.6,tick:0,m:{damage:1,tick_interval_s:.25,damage_type:'pure',slow_pct:50,slow_duration_s:1,dispelTier:'basic'},hp0:f.hp});frames(e,1);near(d.life,.3-1/60);near(f.slow,d.life);});
test('Core4 Crush delay shortens with its stun while Viper decaying slow keeps initial magnitude',()=>{const e=arena([31,45]),f=e.fighters[1];provider(e,f);e.fighters[0].x=500;f.x=600;assert(e.cast(0,1));frames(e,30);const crush=f.pack.statuses.find(s=>s.key==='crush');assert(crush);near(crush.duration,3.4);near(crush.values.delay,.4);f.pack.statuses=[{key:'viper_strike',owner:0,life:3,duration:3,values:{},dispel:'none',pierces:true}];near(e.packCombat.moveMultiplier(e,f),.2);});
test('serialized split legacy modifier rejects forged polarity/negative clocks',()=>{const e=arena(),f=e.fighters[0];provider(e,f);e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.65},1);purge(e,f,false);const good=e.snapshot();for(const patch of [{statusPolarity:'positive'},{negativeLife:4},{negativeLife:Infinity},{m:{headshotGuaranteed:true,self_slow:.65}}]){const bad=structuredClone(good);Object.assign(bad.fighters[0].buffs[0],patch);assert.throws(()=>e.restoreSimulation(bad));assert.deepEqual(e.snapshot(),good);}});
test('duration schema matcher admits shortened canonical statuses and rejects extension/positive scaling',()=>{const e=arena(),f=e.fighters[0];provider(e,f);const s=add(a,e,f,'bad');assert(a.statusDurationMatches(s,2));assert(!a.statusDurationMatches({...s,duration:3},2));assert(!a.statusDurationMatches({...s,durationScale:2},2));assert(!a.statusDurationMatches({...s,hostile:false},2));assert(!a.statusDurationMatches(s,1));});

for(const side of [0,1]){
 test(`P${side+1} batch cleanse commits every removal and grace before callbacks; new callback controls survive`,()=>{
  const e=arena(),f=e.fighters[side],t=e.fighters[1-side],seen=[];
  e.applyControlSource(f,{owner:t.i,key:'first',type:'stun',duration:.3});
  e.applyControlSource(f,{owner:t.i,key:'second',type:'root',duration:.3});
  add(a,e,f,'negative');f.slow=1;f.slowPct=.5;
  const original=e.packCombat;e.packCombat={...original,controlEnded(engine,c){seen.push({key:c.key,controls:engine.packCore.controls.map(v=>v.key),blocked:engine.blocked(f),root:engine.controlRemaining(f,'root'),grace:f.ccGrace,slow:f.slow,status:a.status(engine,f,'negative')});if(c.key==='first'){f.ccGrace=0;engine.applyControlSource(f,{owner:t.i,key:'callback_new',type:'root',duration:.3,dispel:'basic'});}}};
  purge(e,f,true,{tier:'strong'});
  assert.equal(seen.length,2);assert.deepEqual(seen[0],{key:'first',controls:[],blocked:false,root:0,grace:1,slow:0,status:undefined});
  assert.deepEqual(seen[1].controls,['callback_new']);assert.deepEqual(e.packCore.controls.map(v=>v.key),['callback_new']);
 });
 test(`P${side+1} fully resisted hit, attack proc and drain keep the existing slow magnitude`,()=>{
  const e=arena(),f=e.fighters[side],t=e.fighters[1-side];f.x=500;t.x=600;f.slow=1;f.slowPct=.1;provider(e,f,{resistance:1});
  e.hit(t,f,1,{damage_type:'pure',slow_pct:90,slow_duration_s:3},{dot:true});near(f.slowPct,.1);
  e.addBuff(t,'proc_fixture',{on_attack_slow:.9,on_attack_slow_s:3},3);e.basicHit(t,f,{damage:1,m:{damage_type:'physical'},id:++e.seq});near(f.slowPct,.1);
  t.channel={slot:0,life:3,tick:0,m:{effect:'drain',tick_interval_s:.25,range_wu:1000,mana_drain_per_tick:1},id:'drain_fixture'};e.setInput(t.i,{s0:true});frames(e,1);near(f.slowPct,.1);assert(f.slow>0);
 });
 test(`P${side+1} rejected negative buff refresh preserves object, potency and clock`,()=>{const e=arena(),f=e.fighters[side],old=e.addBuff(f,'vulnerable',{vulnerability_physical:.1},2);provider(e,f,{resistance:1});assert.equal(e.addBuff(f,'vulnerable',{vulnerability_physical:.9},4),null);assert.equal(e.buff(f,'vulnerable'),old);near(old.life,2);near(old.m.vulnerability_physical,.1);});
 test(`P${side+1} rejected Poison at the stack cap retains identities, lifetimes and ordering`,()=>{const e=arena(side?[45,0]:[0,45]),f=e.fighters[side],t=e.fighters[1-side];for(let n=0;n<6;n++)e.packCombat.afterAttack(e,t,f,{m:{corePoison:true}},true);f.pack.poison.forEach((s,n)=>s.life=1+n*.4);const before=structuredClone(f.pack.poison);provider(e,f,{resistance:1});const seq=e.seq;e.packCombat.afterAttack(e,t,f,{m:{corePoison:true}},true);assert.deepEqual(f.pack.poison,before);assert.equal(e.seq,seq);});
 test(`P${side+1} natural resisted Frostbite refresh preserves old DOT and root clocks`,()=>{const e=arena(side?[1,0]:[0,1]),f=e.fighters[side],t=e.fighters[1-side];f.x=500;t.x=600;const spell=e.ability(t.i,1);f.root=2;const old=e.addDebuffDot(f,{owner:t.i,id:spell.id,life:2,tick:.5,m:spell.mvp,hp0:f.hp,elapsed:0});provider(e,f,{resistance:1});e.setInput(t.i,{s1:true});frames(e,1);e.setInput(t.i,{});frames(e,24);assert.equal(t.casts,1);near(f.root,2-25/60);assert.equal(f.dots[0],old);near(old.life,f.root);});
 test(`P${side+1} fully resisted mixed downside is absent immediately but the positive grant remains`,()=>{const e=arena(),f=e.fighters[side];provider(e,f,{resistance:1});e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.65},2);near(e.property(f,'self_slow'),0);assert(e.property(f,'headshotGuaranteed'));assert(!Object.hasOwn(e.buff(f,'sniper_take_aim').m,'self_slow'));});
 test(`P${side+1} denied mixed refresh retains the old downside through shorter positive expiry and restore`,()=>{
  const e=arena(),f=e.fighters[side];e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.3},2);provider(e,f,{resistance:1});e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.9},.2);near(e.property(f,'self_slow'),.3);
  const saved=e.snapshot(),twin=arena().restoreSimulation(saved);frames(e,15);frames(twin,15);assert.deepEqual(e.snapshot(),twin.snapshot());assert(!e.property(f,'headshotGuaranteed'));near(e.property(f,'self_slow'),.3);near(e.buff(f,'sniper_take_aim_negative').life,1.75);purge(e,f);assert(!e.property(f,'self_slow'));
 });
 test(`P${side+1} denied mixed refresh does not extend its saved negative clock; admitted refresh replaces it`,()=>{const e=arena(),f=e.fighters[side];e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.3},2);const id=provider(e,f,{resistance:1});e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.9},4);frames(e,15);e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.8},4);near(e.buff(f,'sniper_take_aim_negative').life,1.75);e.releaseStatusResistance(id);e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.6},3);assert(!e.buff(f,'sniper_take_aim_negative'));near(e.property(f,'self_slow'),.6);});
}

for(const side of [0,1])test(`P${side+1} saved negative Take Aim fragments reject positive payloads, duplicates and mixed clocks atomically`,()=>{
 const e=arena(),f=e.fighters[side];e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.3},2);provider(e,f,{resistance:1});e.addBuff(f,'sniper_take_aim',{headshotGuaranteed:true,self_slow:.9},3);const good=e.snapshot(),fragment=good.fighters[side].buffs.findIndex(b=>b.key==='sniper_take_aim_negative');assert(fragment>=0);assert.doesNotThrow(()=>arena().restoreSimulation(good));
 for(const patch of [{m:{self_slow:.3,headshotGuaranteed:true}},{m:{headshotGuaranteed:true}},{m:{self_slow:-.3}},{m:{self_slow:1.3}},{negativeLife:1},{statusPolarity:'negative'}]){const bad=structuredClone(good);Object.assign(bad.fighters[side].buffs[fragment],patch);assert.throws(()=>e.restoreSimulation(bad));assert.deepEqual(e.snapshot(),good);}
 for(const mutate of [g=>g.fighters[side].buffs.push({...g.fighters[side].buffs[fragment]}),g=>g.fighters[side].buffs.find(b=>b.key==='sniper_take_aim').m.self_slow=.6]){const bad=structuredClone(good);mutate(bad);assert.throws(()=>e.restoreSimulation(bad));assert.deepEqual(e.snapshot(),good);}
});
