// Real Engine integration with an explicit test roster. Default/UI/network roster stays unchanged.
import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../src/engine.js';import {runtimeHeroes} from '../../src/runtime-heroes.js';import {ACTIVE_ROSTER,REGISTRY_VERSION} from '../../src/hero-registry.js';
const roster={registryVersion:REGISTRY_VERSION,heroIds:[...ACTIVE_ROSTER.heroIds,94,97,99]};
function arena(id,side=0,opponent=0){const e=new Engine(runtimeHeroes,side?[opponent,id]:[id,opponent],{seed:197,simulationRoster:roster}).start(),f=e.fighters[side],t=e.fighters[1-side];f.x=side?600:400;t.x=side?500:500;return {e,f,t};}
function run(e,seconds){const end=e.t+seconds;let n=0;while(e.t<end-1e-8&&e.phase==='fight'){e.step();assert(n++<20000);}}
const near=(a,b)=>assert(Math.abs(a-b)<1e-5,`${a} != ${b}`);
test('integrated candidates cannot be selected by the default active roster',()=>{for(const id of [94,97,99])assert.throws(()=>new Engine(runtimeHeroes,[id,0]),/Inactive/);});
for(const id of [94,97,99])for(const side of [0,1])for(let slot=0;slot<4;slot++)test(`real Engine R91 ${id} P${side+1} slot${slot+1} accepted cast or passive refusal`,()=>{const {e,f}=arena(id,side);const a=e.ability(side,slot),mana=f.mp;e.setInput(side,{['s'+slot]:true});e.step();if(a.mvp.passive){assert.equal(f.casts,0);near(f.mp,mana);}else{assert.equal(f.casts,1);near(f.mp,mana-a.mvp.mana);run(e,.6);assert(e.logs.some(l=>l.type==='activate'&&l.skill===a.id));}assert.deepEqual(JSON.parse(JSON.stringify(e.snapshot())),e.snapshot());});
for(const side of [0,1])test(`Centaur P${side+1} windup moves, disarms and only hits after .5 seconds`,()=>{const {e,f,t}=arena(94,side);const hp=t.hp,x=f.x;e.setInput(side,{s0:true,attack:true,left:!!side,right:!side});run(e,.25);assert.notEqual(f.x,x);near(t.hp,hp);assert.equal(e.events.filter(v=>v.type==='attack').length,0);run(e,.3);near(hp-t.hp,280);assert(t.stun>0&&t.stun<=1.5);});
for(const side of [0,1])test(`Centaur P${side+1} Double Edge uses level18 strength and self damage stays nonlethal`,()=>{const {e,f,t}=arena(94,side);f.hp=10;const hp=t.hp;assert(e.cast(side,1));run(e,.4);near(hp-t.hp,451.65);near(f.hp,1);});
test('Centaur retaliate is an actual received basic proc with bounded reflection and break suppression',()=>{const {e,f,t}=arena(94,0,45);const hp=t.hp;e.hit(t,f,30,{damage_type:'physical'},{basic:true});near(hp-t.hp,80.385);const before=t.hp;e.hit(t,f,30,{damage_type:'pure'},{basic:true,reflected:true});near(before,t.hp);f.pack.statuses.push({key:'viper_strike',owner:1,life:6,values:{},dispel:'none',pierces:true});e.hit(t,f,30,{damage_type:'pure'},{basic:true});near(before,t.hp);});
test('Centaur Stampede applies contact damage once and expires without leaking into another round',()=>{const {e,f,t}=arena(94);t.x=f.x+65;const hp=t.hp;assert(e.cast(0,3));run(e,.5);near(hp-t.hp,303.3);run(e,1);near(hp-t.hp,303.3);run(e,3.1);assert.equal(f.packModules.r91.data.stampede,null);e.resetRound();assert.equal(e.packModules.r91.jobs.length,0);assert.equal(e.fighters[0].packModules.r91.statuses.length,0);});
for(const side of [0,1])test(`Skywrath P${side+1} bolt has real travel, follows a jump, and grants independent actual-damage barriers`,()=>{const {e,f,t}=arena(99,side);const hp=t.hp;assert(e.cast(side,0));run(e,.11);near(t.hp,hp);assert(e.packModules.r91.entities.some(x=>x.kind==='homing'));t.y=150;t.vy=100;run(e,1);near(hp-t.hp,150+e.hero(side).attributes18.int*1.5);near(f.packModules.r91.data.barriers[0].amount,13.5);const own=f.hp;e.hit(t,f,50,{damage_type:'magical'},{dot:true});near(own-f.hp,36.5);});
test('Skywrath Seal amplifier runs before existing Abaddon barrier absorption',()=>{const {e,f,t}=arena(99,0,100);assert(e.cast(1,1));run(e,.6);assert(e.cast(0,2));run(e,.3);const hp=t.hp;e.hit(f,t,200,{damage_type:'magical',blockable:false},{dot:true,skill:'test'});near(hp-t.hp,60);assert.equal(t.pack.shield,null);});
test('Skywrath Seal follows basic dispel and suppresses casting without bypassing immunity',()=>{const {e,f,t}=arena(99);e.cast(0,2);run(e,.3);assert(e.isSilenced(t));assert(!e.cast(1,0));e.dispel(t,'basic');assert(!e.isSilenced(t));assert(e.cast(1,0));f.cd[2]=0;f.recovery=0;e.cast(0,2);run(e,.3);assert(!e.isSilenced(t));});
test('Skywrath direct seal and homing projectile use existing Anti-Mage counter without recursive reflection',()=>{for(const slot of [0,2]){const {e,f,t}=arena(99,0,5);assert(e.cast(1,2));run(e,.1);assert(e.cast(0,slot));run(e,1);if(slot===2){assert(e.isSilenced(f));assert(!e.isSilenced(t));}else{assert(f.hp<f.maxHp);near(t.hp,t.maxHp);assert.equal(f.packModules.r91.data.barriers.length,0);}}});
test('Mystic Flare is a fixed area with20 ticks, misses after target exits and is not a second HP simulation',()=>{const {e,f,t}=arena(99);const hp=t.hp;e.cast(0,3);run(e,.2);assert(e.packModules.r91.entities.some(x=>x.kind==='flare'));run(e,1);t.x=1000;const escaped=t.hp;run(e,1);near(t.hp,escaped);const hits=e.logs.filter(l=>l.type==='hit'&&l.skill==='skywrath_mage_mystic_flare');assert(hits.length>0&&hits.length<20);near(hp-escaped,hits.length*80);});
test('Engine snapshot restores pending windup/projectiles and deterministic future state; invalid owner is rejected',()=>{for(const [id,slot]of [[94,0],[99,0]]){const {e}=arena(id);e.cast(0,slot);run(e,.12);const g=e.snapshot(),restored=new Engine(runtimeHeroes,[id,0],{seed:1,simulationRoster:roster}).restoreSimulation(g);for(let n=0;n<80;n++){e.step();restored.step();assert.deepEqual(restored.snapshot(),e.snapshot());}const bad=structuredClone(g);if(bad.packModules.r91.jobs.length)bad.packModules.r91.jobs[0].owner=9;else bad.packModules.r91.entities[0].data.target=9;assert.throws(()=>restored.restoreSimulation(bad));}});

for(const side of [0,1])test(`Bristle P${side+1} Goo has flight time, armor/slow stacks and basic dispel`,()=>{const {e,f,t}=arena(97,side);assert(e.cast(side,0));run(e,.3);assert.equal(t.packModules.r91.statuses.length,0);run(e,.3);const goo=t.packModules.r91.statuses.find(s=>s.key==='goo');assert(goo);near(goo.values.armor,6.5);near(goo.values.moveSlow,.24);const hp=t.hp;e.hit(f,t,100,{damage_type:'physical',blockable:false},{dot:true});near(hp-t.hp,100*(1+.39/1.39));e.dispel(t);assert.equal(t.packModules.r91.statuses.length,0);});
for(const side of [0,1])test(`Bristle P${side+1} independent Quill stacks and earned Warpath survive break`,()=>{const {e,f,t}=arena(97,side,45);let hp=t.hp;assert(e.cast(side,1));run(e,.25);near(hp-t.hp,85);assert.equal(t.packModules.r91.data.quills.length,1);assert.equal(f.packModules.r91.data.warpath.length,1);f.pack.statuses.push({key:'viper_strike',owner:1-side,life:6,values:{},dispel:'none',pierces:true});f.cd[1]=0;f.recovery=0;hp=t.hp;assert(e.cast(side,1));run(e,.25);near(hp-t.hp,115);assert.equal(f.packModules.r91.data.warpath.length,1);});
for(const side of [0,1])test(`Bristle P${side+1} retreat direction exposes back reduction and one delayed reflected Quill`,()=>{const {e,f,t}=arena(97,side);e.setInput(side,side?{right:true}:{left:true});const hp=f.hp,other=t.hp;e.hit(t,f,400,{damage_type:'pure',blockable:false},{dot:true});near(hp-f.hp,240);near(t.hp,other);assert.equal(e.packModules.r91.jobs.length,1);run(e,.12);near(other-t.hp,85*1.045);assert.equal(e.packModules.r91.jobs.length,0);near(f.packModules.r91.data.backDamage,40);});
test('Goo armor composes exactly once with core4 numeric armor and suppresses under immunity',()=>{const {e,f,t}=arena(97,0,31);assert(e.cast(0,0));run(e,.7);t.pack.statuses.push({key:'fixture_negative_armor',owner:0,life:5,values:{armor:-20},dispel:'basic',pierces:false});const hp=t.hp;e.hit(f,t,100,{damage_type:'physical',blockable:false},{dot:true});near(hp-t.hp,100*(1+1.59/2.59));e.addBuff(t,'test-immune',{debuffImmune:true},1);const immune=t.hp;e.hit(f,t,100,{damage_type:'physical',blockable:false},{dot:true});near(immune-t.hp,100);});
