import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../src/engine.js';import {runtimeHeroes} from '../../src/runtime-heroes.js';
import {CANDIDATE_ROSTER} from '../../src/candidate-roster.js';import {REGISTRY_VERSION} from '../../src/hero-registry.js';
import {createPackServices,PACK_SLOW_ABI_VERSION,PACK_CAPABILITIES} from '../../src/pack-services.js';
import {PackSlow} from '../../src/pack-slow.js';
const api=createPackServices('slow_a',{abilityIds:['tiny_insurmountable','ursa_enrage']}),foreign=createPackServices('slow_b');
const arena=pair=>new Engine(runtimeHeroes,pair??[0,0],{simulationRoster:{...CANDIDATE_ROSTER,registryVersion:REGISTRY_VERSION},seed:17}).start();
const near=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`),frames=(e,n)=>{for(let i=0;i<n;i++){e.hitstop=0;e.step();}};
const provider=(e,f,extra={})=>api.registerSlowResistance(e,f,{source:f.i,abilityId:'tiny_insurmountable',resistance:.5,duration:10,...extra});
const negative=(e,f,values)=>foreign.applyStatus(e,f,{key:'foreign',owner:1-f.i,duration:2,values});
test('additive slow ABI preserves old guards and declares only implemented shared strength capability',()=>{assert.equal(PACK_SLOW_ABI_VERSION,'duel-slow-1');assert(PACK_CAPABILITIES.includes('global-slow-resistance'));assert(PACK_CAPABILITIES.includes('slow-strength-projection'));});
for(const side of [0,1]){
 test(`P${side+1} slow and status duration providers are independent, without stored-value mutation`,()=>{const e=arena(),f=e.fighters[side];provider(e,f);const s=negative(e,f,{slow:.8,aspd:-100,dps:20,armor:-5});near(s.duration,2);near(foreign.value(e,f,'slow'),.4);near(foreign.value(e,f,'aspd',{mode:'sum'}),-50);near(s.values.slow,.8);near(s.values.aspd,-100);near(foreign.value(e,f,'dps'),20);near(foreign.value(e,f,'armor',{mode:'sum'}),-5);e.registerStatusResistance(f,{source:f.i,abilityId:'status',resistance:.25,duration:10});near(e.admitStatusDuration(f,{duration:4}),3);near(e.projectSlowMagnitude(f,{magnitude:.8}),.4);});
 test(`P${side+1} all explicit movement and attack speed representations project exactly once`,()=>{const e=arena(),f=e.fighters[side];provider(e,f);const s=negative(e,f,{moveSlow:.8,slow:.6,attackSlow:100,aspd:-80,attackSpeed:-60,moveFlat:-50,moveBonus:-.4});for(const [key,raw]of Object.entries(s.values))near(foreign.slowValue(e,f,s,key),raw*.5);const before=e.snapshot(),identity=s.values;PackSlow.withValues(e,f,()=>{for(const [key,raw]of Object.entries(identity)){near(s.values[key],raw*.5);near(foreign.value(e,f,key,{mode:'sum'}),raw*.5);}PackSlow.withValues(e,f,()=>near(s.values.slow,.3));});assert.equal(s.values,identity);assert.deepEqual(e.snapshot(),before);});
 test(`P${side+1} positive buffs, Grow-style self penalties and other negative attributes are excluded`,()=>{const e=arena(),f=e.fighters[side];provider(e,f,{resistance:1});foreign.applyPositiveStatus(e,f,{key:'grow',owner:f.i,duration:2,values:{attackSpeed:-60,aspd:-40,slow:.2,moveSlow:.3}});near(foreign.value(e,f,'attackSpeed',{mode:'sum'}),-60);near(foreign.value(e,f,'aspd',{mode:'sum'}),-40);near(foreign.value(e,f,'slow'),.2);near(e.projectSlowMagnitude(f,{magnitude:.8,hostile:false}),.8);near(e.projectSlowMagnitude(f,{magnitude:.8,ignoreSlowResistance:true}),.8);});
 test(`P${side+1} provider changes alter live strength while preserving original status clocks`,()=>{const e=arena(),f=e.fighters[side],s=negative(e,f,{slow:.8});near(foreign.value(e,f,'slow'),.8);const id=provider(e,f,{duration:.1});near(foreign.value(e,f,'slow'),.4);frames(e,7);near(foreign.value(e,f,'slow'),.8);near(s.duration,2);assert(!e.releaseSlowResistance(id));});
 test(`P${side+1} stacking, refresh handles and opposite-target ownership remain scoped`,()=>{const e=arena(),f=e.fighters[side],t=e.fighters[1-side],old=provider(e,f,{key:'a'});provider(e,f,{key:'b',resistance:.2});near(e.slowResistance(f),.6);near(e.slowResistance(t),0);const id=provider(e,f,{key:'a',resistance:.4});near(e.slowResistance(f),.52);assert(!e.releaseSlowResistance(old));assert(e.releaseSlowResistance(id));near(e.slowResistance(f),.2);});
 test(`P${side+1} legacy walking and jumping reduce slow strength but preserve self slow`,()=>{const e=arena(),f=e.fighters[side],t=e.fighters[1-side];f.x=side?900:300;t.x=side?300:900;f.slow=2;f.slowPct=.8;e.addBuff(f,'self_penalty',{self_slow:.25},2);provider(e,f);const x=f.x;e.setInput(side,{right:true});frames(e,1);near(f.x-x,e.hero(side).move_speed*.75*.6/60);e.setInput(side,{right:true,jump:true});frames(e,1);near(f.airVx,e.hero(side).move_speed*.75*.6);near(f.slowPct,.8);});
 test(`P${side+1} Core4 poison and decaying Viper movement/attack slows project once`,()=>{const e=arena(side?[0,45]:[45,0]),f=e.fighters[side];f.pack.statuses=[{key:'viper_strike',owner:1-side,life:3,duration:6,values:{},dispel:'none',pierces:true}];provider(e,f);near(e.packCombat.moveMultiplier(e,f),.8);near(e.packCombat.attackInterval(e,f,e.fighters[1-side],1),100/55);f.pack.statuses=[];f.pack.poison.push({id:++e.seq,owner:1-side,life:2,tick:1});near(e.packCombat.moveMultiplier(e,f),.94);});
 test(`P${side+1} legacy/core compound slowdown and preexisting legacy resistance do not double-project`,()=>{const e=arena(side?[0,45]:[45,0]),f=e.fighters[side];f.slow=2;f.slowPct=.3;e.addBuff(f,'resist_fixture',{slow_resistance:.2},2);f.pack.statuses=[{key:'viper_strike',owner:1-side,life:6,duration:6,values:{},dispel:'none',pierces:true}];provider(e,f);const legacy=1-e.projectSlowMagnitude(f,{magnitude:f.slowPct})*.8;near(legacy*e.packCombat.moveMultiplier(e,f),.68);});
 test(`P${side+1} actual Night Stalker input gives foreign slow/AS strength with canonical restore`,()=>{const e=arena(side?[58,0]:[0,58]),f=e.fighters[side],t=e.fighters[1-side];f.x=side?600:500;t.x=side?500:600;provider(e,f,{resistance:.2});e.setInput(t.i,{s0:true});frames(e,1);e.setInput(t.i,{});frames(e,35);assert.equal(t.casts,1);const s=f.packModules.c56_90.statuses.find(s=>s.key==='night_stalker_void');assert(s);near(s.values.slow,.5);near(s.values.aspd,-50);near(e.packCombat.moveMultiplier(e,f),.6);const base=100+(e.hero(side).attributes18?.agi??e.hero(side).level18?.agility??0);near(e.packCombat.attackInterval(e,f,t,1),base/(base-40));const twin=arena(side?[58,0]:[0,58]).restoreSimulation(e.snapshot());frames(e,10);frames(twin,10);assert.deepEqual(e.snapshot(),twin.snapshot());});
 test(`P${side+1} cross-A direct-reader hooks and cross-C api queries get the same projection`,()=>{const e=arena(side?[94,28]:[28,94]),f=e.fighters[side];provider(e,f,{resistance:.2});const a=createPackServices('r20_55'),c=createPackServices('r91');a.applyStatus(e,f,{key:'audit_slow_a',owner:1-side,duration:2,values:{moveSlow:.5,attackSlow:50}});c.applyStatus(e,f,{key:'audit_slow_c',owner:1-side,duration:2,values:{moveSlow:.25}});near(e.packCombat.moveMultiplier(e,f),.6*.8);near(e.packCombat.attackInterval(e,f,e.fighters[1-side],1),100/60);near(a.value(e,f,'moveSlow'),.4);near(c.value(e,f,'moveSlow'),.2);});
 test(`P${side+1} live provider Break and source death suppress, target death cleans up`,()=>{const e=arena(),f=e.fighters[side],t=e.fighters[1-side];provider(e,f,{source:t.i,requiresPassives:true});const original=e.packCombat;e.packCombat={...original,broken:(engine,actor)=>actor===t};near(e.slowResistance(f),0);e.packCombat=original;near(e.slowResistance(f),.5);t.hp=0;near(e.slowResistance(f),0);provider(e,f,{key:'active'});near(e.slowResistance(f),.5);f.hp=0;frames(e,1);assert.equal(e.packCore.slowResistance.length,0);e.resetRound();assert(!e.packCore?.slowResistance?.length);});
 test(`P${side+1} global positive purge removes eligible slow providers and negative cleanse retains them`,()=>{const e=arena(),f=e.fighters[side];provider(e,f,{key:'a',dispel:'basic'});provider(e,f,{key:'b',dispel:'strong'});provider(e,f,{key:'c',dispel:'none'});const options={source:1-side,abilityId:'oracle_fortunes_end'};e.dispelTarget(f,{...options,hostile:true,tier:'strong'});near(e.slowResistance(f),.875);e.dispelTarget(f,{...options,hostile:false,tier:'basic'});near(e.slowResistance(f),.75);e.dispelTarget(f,{...options,hostile:false,tier:'strong'});near(e.slowResistance(f),.5);});
 test(`P${side+1} runtime view restores identity and values after an adapter throws`,()=>{const e=arena(),f=e.fighters[side];provider(e,f);const s=negative(e,f,{slow:.8}),raw=s.values;assert.throws(()=>PackSlow.withValues(e,f,()=>{near(s.values.slow,.4);throw Error('adapter failed');}));assert.equal(s.values,raw);near(s.values.slow,.8);near(foreign.value(e,f,'slow'),.4);});
 test(`P${side+1} forged provider snapshots reject atomically`,()=>{const e=arena(),f=e.fighters[side];provider(e,f);const good=e.snapshot();for(const patch of [{target:4},{source:4},{resistance:1.1},{resistance:-.1},{life:11},{duration:0},{id:99999},{requiresPassives:1},{dispel:'all'}]){const bad=structuredClone(good);Object.assign(bad.packCore.slowResistance[0],patch);assert.throws(()=>e.restoreSimulation(bad));assert.deepEqual(e.snapshot(),good);}const bad=structuredClone(good);bad.packCore.slowResistance.push({...bad.packCore.slowResistance[0]});assert.throws(()=>e.restoreSimulation(bad));});
 test(`P${side+1} resistance request validation and unknown ability do not mutate state`,()=>{const e=arena(),f=e.fighters[side],good=e.snapshot();for(const patch of [{resistance:2},{duration:0},{source:4},{abilityId:'unknown'},{requiresPassives:1}]){assert.throws(()=>provider(e,f,patch));assert.deepEqual(e.snapshot(),good);}assert.throws(()=>e.projectSlowMagnitude(f,{magnitude:-1}));assert.throws(()=>provider(e,{...f}));f.invuln=1;assert.equal(provider(e,f),null);});
}
