import {REGISTRY_VERSION} from '../../src/hero-registry.js';
import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../src/engine.js';import {runtimeHeroes} from '../../src/runtime-heroes.js';import {createPackServices} from '../../src/pack-services.js';
const api=createPackServices('action_fixture',{abilityIds:['channel'],eventKinds:['pulse']});
const arena=()=>new Engine(runtimeHeroes,[0,0]).start();
function control(e,f,key,duration=.5,type='stun'){return api.applyControlSource(e,f,{owner:1-f.i,key,type,duration});}
function frames(e,n){for(let i=0;i<n;i++)e.step();}
for(const side of [0,1])test(`P${side+1} waking one scoped sleep does not erase another source stun or legacy timer`,()=>{const e=arena(),f=e.fighters[side];const sleep=control(e,f,'sleep',.4),stun=control(e,f,'other_stun',.6);e.control(f,'stun',.3);assert(e.blocked(f));assert(api.releaseControlSource(e,sleep,'woken'));assert(e.blocked(f));assert(e.packCore.controls.some(c=>c.id===stun));assert(f.stun>0);assert(api.releaseControlSource(e,stun,'woken'));assert(e.blocked(f));frames(e,20);assert(!e.blocked(f));assert.equal(api.releaseControlSource(e,sleep,'again'),false);});
test('scoped stun gates real movement, jump, attack and cast without writing a global timer',()=>{const e=arena(),f=e.fighters[0],x=f.x;control(e,f,'sleep');assert.equal(f.stun,0);e.setInput(0,{right:true,jump:true,attack:true,s0:true});frames(e,10);assert.equal(f.x,x);assert.equal(f.y,0);assert.equal(f.casts,0);assert.equal(e.events.length,0);});
test('scoped control uses existing immunity and continuous-control admission exactly once',()=>{const e=arena(),f=e.fighters[0];assert(control(e,f,'first',5));assert.equal(e.controlRemaining(f,'stun'),1.5);assert.equal(control(e,f,'second'),null);assert.equal(f.ccChain,1.5);frames(e,91);assert(!e.blocked(f));assert(f.ccGrace>0);assert.equal(control(e,f,'grace'),null);frames(e,61);assert(control(e,f,'after_grace',.1));});
test('scoped negative control suppresses during later immunity but its duration keeps advancing',()=>{const e=arena(),f=e.fighters[0];const id=control(e,f,'stun',1);assert(e.blocked(f));e.addBuff(f,'immune',{debuffImmune:true},.2);assert(!e.blocked(f));frames(e,20);assert(e.blocked(f));assert(e.packCore.controls.find(c=>c.id===id).life<.7);});
test('scoped root expiry releases its chain budget and root blocks movement/jump',()=>{const e=arena(),f=e.fighters[0],x=f.x;control(e,f,'root',.1,'root');e.setInput(0,{right:true,jump:true});frames(e,3);assert.equal(f.x,x);assert.equal(f.y,0);frames(e,5);assert.equal(e.controlRemaining(f,'root'),0);assert.equal(f.ccChain,0);assert(f.ccGrace>0);});
test('strong dispel removes scoped strong control while none-tier and other actors remain',()=>{const e=arena(),a=e.fighters[0],b=e.fighters[1];const strong=control(e,a,'strong',.5);const locked=api.applyControlSource(e,a,{owner:1,key:'locked',type:'stun',duration:.5,dispel:'none'});const other=control(e,b,'other',.5);e.dispel(a,'strong');assert(!e.packCore.controls.some(c=>c.id===strong));assert(e.packCore.controls.some(c=>c.id===locked));assert(e.packCore.controls.some(c=>c.id===other));assert(e.blocked(a));});
for(const reason of ['control','input_cancel','movement','action'])test(`scheduled ${reason} cancellation persists after short input/control has ended`,()=>{const e=arena(),f=e.fighters[0];api.scheduleEffect(e,{owner:0,target:1,abilityId:'channel',kind:'pulse',delay:.3,cancelOnAction:[reason]});if(reason==='control')e.control(f,'stun',.05);if(reason==='input_cancel')e.cancelInput(0);if(reason==='movement'){e.setInput(0,{right:true});e.setInput(0,{});}if(reason==='action'){e.setInput(0,{attack:true});e.setInput(0,{});}frames(e,25);let n=0;api.runDue(e,()=>n++);assert.equal(n,0);});
test('selective action tokens allow movement where an ability explicitly allows it',()=>{const e=arena(),f=e.fighters[0],token=api.actionToken(e,f,['control','input_cancel']);e.setInput(0,{right:true});assert(api.actionTokenValid(e,token));e.control(f,'stun',.05);assert(!api.actionTokenValid(e,token));frames(e,20);assert(!api.actionTokenValid(e,token));});
test('control source timers and cancellation revisions restore with identical future behavior',()=>{const e=arena(),f=e.fighters[0];control(e,f,'sleep',.5);const token=api.actionToken(e,f,['movement','action']);frames(e,5);const g=e.snapshot(),b=arena().restoreSimulation(g);for(let n=0;n<50;n++){if(n===15){e.setInput(0,{right:true});b.setInput(0,{right:true});}e.step();b.step();assert.deepEqual(e.snapshot(),b.snapshot());}assert(!api.actionTokenValid(e,token));assert(!api.actionTokenValid(b,token));});
test('forged control owner/duration/revisions reject atomically',()=>{const e=arena();control(e,e.fighters[0],'sleep');const g=e.snapshot();for(const [key,value]of [['id',999999],['owner',8],['duration',10],['life',5],['type','hp']]){const bad=structuredClone(g);bad.packCore.controls[0][key]=value;assert.throws(()=>e.restoreSimulation(bad));assert.deepEqual(e.snapshot(),g);}const bad=structuredClone(g);bad.packCore.actionRevisions[0].movement=-1;assert.throws(()=>e.restoreSimulation(bad));});

test('accepted direct casts from each registered system invalidate prior action tokens; refusals preserve them',()=>{for(const id of [0,25,28,57,94]){const ids=[...new Set([0,25,28,57,94])],e=new Engine(runtimeHeroes,[id,0],{simulationRoster:{registryVersion:REGISTRY_VERSION,heroIds:ids}}).start();e.fighters[0].x=450;e.fighters[1].x=550;const f=e.fighters[0],token=e.actionToken(f,['action']);assert(e.cast(0,0),String(id));assert(!e.actionTokenValid(token),String(id));const next=e.actionToken(f,['action']);assert(!e.cast(0,0));assert(e.actionTokenValid(next));}});
