import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../src/engine.js';import {runtimeHeroes} from '../../src/runtime-heroes.js';import {createPackServices} from '../../src/pack-services.js';
const a=createPackServices('origin',{abilityIds:['targeted']}),b=createPackServices('external',{abilityIds:['silence']});
function arena(){const e=new Engine(runtimeHeroes,[0,5]).start();e.fighters[0].x=400;e.fighters[1].x=500;return e;}
for(const side of [0,1])test(`P${side+1} cross-pack effective silence observes immunity/dispel and excludes own action locks`,()=>{const e=arena(),f=e.fighters[side];b.applyStatus(e,f,{key:'silence',owner:1-side,duration:2,values:{silence:1}});assert(a.effectiveStatus(e,f,'silence'));e.addBuff(f,'immune',{debuffImmune:true},1);assert(!a.effectiveStatus(e,f,'silence'));f.buffs=[];assert(a.effectiveStatus(e,f,'silence'));b.dispel(e,f);assert(!a.effectiveStatus(e,f,'silence'));f.silence=.1;assert(a.effectiveStatus(e,f,'silence'));f.silence=0;f.channel={};assert(!a.effectiveStatus(e,f,'silence'));});
test('read-only admission never consumes counter, rejects range/death/invulnerability and does not debit mana',()=>{const e=arena(),[f,t]=e.fighters;e.addBuff(t,'counter',{},1);const before=JSON.stringify(e.snapshot()),o={owner:0,target:1,abilityId:'targeted',range:20};assert.equal(a.canTargetSpell(e,o).reason,'out_of_range');assert.equal(JSON.stringify(e.snapshot()),before);assert(a.canTargetSpell(e,{...o,range:200}).ok);assert(e.buff(t,'counter'));t.invuln=1;assert.equal(a.canTargetSpell(e,{...o,range:200}).reason,'target_invulnerable');t.invuln=0;t.hp=0;assert.equal(a.canTargetSpell(e,{...o,range:200}).reason,'target_dead');assert.equal(f.mp,f.maxMp);});
for(const side of [0,1])test(`P${side+1} one route reflects all components once, retains original identity and disables re-reflection/lifesteal`,()=>{const e=arena(),f=e.fighters[side],t=e.fighters[1-side];e.addBuff(t,'counter',{},1);e.addBuff(f,'counter',{},1);const route=a.routeTargetedSpell(e,{owner:side,target:1-side,abilityId:'targeted'});assert.equal(route.owner,1-side);assert.equal(route.target,side);assert.equal(route.originalOwner,side);assert(route.accepted&&route.reflected&&route.noReflect&&route.noLifesteal);assert(!e.buff(t,'counter'));assert(e.buff(f,'counter'));const again=a.routeTargetedSpell(e,route);assert(again.accepted);assert.equal(again.originalOwner,side);assert.equal(again.owner,1-side);assert(e.buff(f,'counter'));assert.equal(e.logs.filter(l=>l.type==='spell_reflected').length,1);});
test('area/nonreflectable and physical counter are not consumed; reflected destination is rechecked',()=>{const e=arena(),[f,t]=e.fighters;e.addBuff(t,'counter',{},1);assert(!a.routeTargetedSpell(e,{owner:0,target:1,abilityId:'targeted',reflectable:false}).reflected);assert(e.buff(t,'counter'));f.invuln=1;const r=a.routeTargetedSpell(e,{owner:0,target:1,abilityId:'targeted'});assert(r.reflected&&!r.accepted);assert.equal(r.reason,'target_invulnerable');assert(!e.buff(t,'counter'));f.invuln=0;e.addBuff(t,'counter',{counter_type:'basic_physical'},1);assert(!a.routeTargetedSpell(e,{owner:0,target:1,abilityId:'targeted'}).reflected);assert(e.buff(t,'counter'));});
test('debuff immunity rejection is explicit; ordinary damaging spells retain their separate damage/status policies',()=>{const e=arena(),t=e.fighters[1];e.addBuff(t,'immune',{debuffImmune:true},2);const o={owner:0,target:1,abilityId:'targeted'};assert(a.canTargetSpell(e,o).ok);assert(!a.canTargetSpell(e,{...o,rejectDebuffImmune:true}).ok);assert(a.canTargetSpell(e,{...o,rejectDebuffImmune:true,pierces:true}).ok);assert.throws(()=>a.routeTargetedSpell(e,{...o,owner:5}));assert.throws(()=>a.routeTargetedSpell(e,{...o,abilityId:'unknown'}));});
for(const side of [0,1])test(`P${side+1} existing hostile silence pauses effectiveness under invulnerability without deleting or extending it`,()=>{const e=arena(),f=e.fighters[side];const s=b.applyStatus(e,f,{key:'silence',owner:1-side,duration:2,values:{silence:1},pierces:true});f.invuln=1;assert(!a.effectiveStatus(e,f,'silence'));for(let n=0;n<10;n++)b.advanceStatuses(e,f,.05);assert(Math.abs(s.life-1.5)<1e-8);assert(b.status(e,f,'silence'));f.invuln=0;assert(a.effectiveStatus(e,f,'silence'));});
