import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../src/engine.js';import {runtimeHeroes} from '../../src/runtime-heroes.js';import {HERO_PACKS} from '../../src/pack-runtime.js';import {ACTIVE_ROSTER} from '../../src/hero-registry.js';import {createPackServices} from '../../src/pack-services.js';
const api=createPackServices('tick_fixture');
function arena(onTick,opponent=0){const base=HERO_PACKS.find(p=>p.definition.registryNumericId===94),system={namespace:'tick_fixture',init(e){api.world(e);e.fighters.forEach(f=>api.fighter(e,f));},cast(){return false;},activate(){return true;},dispel(e,f,tier){api.dispel(e,f,tier);},tick(e,dt){for(const f of e.fighters)api.advanceStatuses(e,f,dt,(s,enabled)=>onTick(e,f,s,enabled));}};return new Engine(runtimeHeroes,[94,opponent],{heroPacks:[{...base,systemId:'tick_fixture',sharedSystem:system}],simulationRoster:{...ACTIVE_ROSTER,heroIds:[...ACTIVE_ROSTER.heroIds,94]}}).start();}
function dot(e,key,damage=1,options={}){return api.applyStatus(e,e.fighters[1],{key,owner:0,duration:1,interval:.05,values:{damage},...options});}
test('real Tidehunter Kraken dispel removes second due DOT before its stale callback',()=>{const trace=[],e=arena((e,f,s,enabled)=>{trace.push({key:s.key,enabled,present:api.fighter(e,f).statuses.includes(s)});if(enabled)api.damageResult(e,s.owner,f,s.values.damage,{type:'pure',abilityId:'fixture_dot'});},19);dot(e,'first',500);dot(e,'second',25);const hp=e.fighters[1].hp;for(let n=0;n<3;n++)e.step();assert.equal(hp-e.fighters[1].hp,500);assert.deepEqual(trace,[{key:'first',enabled:true,present:true}]);assert.equal(api.fighter(e,e.fighters[1]).statuses.length,0);});
test('dispel during a multi-pulse step cancels the remaining callbacks on that same status',()=>{let n=0;const e=arena((e,f)=>{n++;api.dispel(e,f);});dot(e,'rapid',1,{interval:.01});e.step(.05);assert.equal(n,1);});
test('same-key refresh replaces record identity so an older tick cannot run the new schedule',()=>{let n=0;const e=arena((e,f,s)=>{n++;if(n===1)dot(e,s.key,1,{interval:.01});});const old=dot(e,'refresh',1,{interval:.01});e.step(.05);assert.equal(n,1);const next=api.status(e,e.fighters[1],'refresh');assert.notEqual(next,old);assert.equal(next.elapsed,0);e.step(.01);assert.equal(n,2);});
test('a lethal first periodic callback cancels every other target callback',()=>{const seen=[],e=arena((e,f,s)=>{seen.push(s.key);api.damageResult(e,0,f,100,{type:'pure',abilityId:'fixture_dot'});});e.fighters[1].hp=10;dot(e,'first');dot(e,'second');e.step(.05);assert.deepEqual(seen,['first']);});
test('a valid exact-expiry final tick executes once, including snapshot-list membership',()=>{const seen=[],e=arena((e,f,s,enabled)=>seen.push({enabled,life:s.life,present:api.fighter(e,f).statuses.includes(s)}));dot(e,'last',1,{duration:.05});e.step(.05);assert.deepEqual(seen,[{enabled:true,life:0,present:true}]);e.step(.05);assert.equal(seen.length,1);});
test('round replacement inside a callback cancels work on the detached fighter/state',()=>{let n=0;const e=arena(e=>{n++;e.resetRound();});dot(e,'first');dot(e,'second');e.step(.05);assert.equal(n,1);});
