import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../src/engine.js';import {runtimeHeroes} from '../../src/runtime-heroes.js';import {CANDIDATE_ROSTER} from '../../src/candidate-roster.js';import {REGISTRY_VERSION} from '../../src/hero-registry.js';
import {createPackServices,PACK_UNIT_ABI_VERSION,PACK_CAPABILITIES} from '../../src/pack-services.js';
const templates=[{id:'beetle',namespace:'unit_fixture',abilityId:'unit_fixture',hitsToKill:9},{id:'missile',namespace:'unit_fixture',abilityId:'unit_fixture',hitsToKill:3,warmup:2},{id:'spider',namespace:'unit_fixture',abilityId:'unit_fixture',hp:100,damage:20,attackInterval:.2,attackRange:120,moveSpeed:100,windup:.05},{id:'illusion',namespace:'unit_fixture',abilityId:'unit_fixture',hp:100,damage:20,attackInterval:.2,attackRange:120,moveSpeed:100,windup:.05,persistOnOwnerDeath:true},{id:'reflector',namespace:'unit_fixture',abilityId:'unit_fixture',hp:100,reflectTargeted:true},{id:'meepo',namespace:'unit_fixture',abilityId:'unit_fixture',hp:50,groupDeath:true},{id:'armor',namespace:'unit_fixture',abilityId:'unit_fixture',hp:100,armor:-5},{id:'invulnerable',namespace:'unit_fixture',abilityId:'unit_fixture',hp:100,invulnerable:true}];
const api=createPackServices('unit_fixture',{abilityIds:['unit_fixture']});
const arena=(pair=[0,0])=>new Engine(runtimeHeroes,pair,{simulationRoster:{...CANDIDATE_ROSTER,registryVersion:REGISTRY_VERSION},unitTemplates:templates,seed:27}).start();
const near=(a,b)=>assert(Math.abs(a-b)<1e-7,`${a} != ${b}`),frames=(e,n)=>{for(let i=0;i<n;i++){e.hitstop=0;e.step();}};
const spawn=(e,owner,id='beetle',extra={})=>api.spawnUnit(e,{owner,templateId:id,abilityId:'unit_fixture',x:owner?700:500,duration:10,...extra});
const damage=(e,source,target,amount=20,flags={},extra={})=>api.resolveActorDamage(e,{source,target,amount,damageType:'pure',abilityId:'unit_fixture',flags,...extra});
test('unit protocol is a review ABI and does not unlock reserved full-unit hero gates',()=>{assert.equal(PACK_UNIT_ABI_VERSION,'duel-unit-protocol-0.1');for(const pending of ['attackable-units','unit-death-groups','secondary-attack-flags'])assert(!PACK_CAPABILITIES.includes(pending));});
for(const side of [0,1]){
 test(`P${side+1} refs resolve actual units without a fighter index and are epoch-scoped`,()=>{const e=arena(),ref=spawn(e,side),u=e.resolveActor(ref),owner=e.fighters[side];assert.equal(u.owner,side);assert.equal(u.i,undefined);assert.notEqual(u,owner);assert.equal(e.resolveActor(api.actorRef(e,owner)),owner);assert(e.removeUnit(ref));assert.equal(e.resolveActor(ref),null);assert(!e.removeUnit(ref));e.resetRound();const next=spawn(e,side);assert(next.epoch>ref.epoch);assert.equal(e.resolveActor(ref),null);assert(e.resolveActor(next));});
 test(`P${side+1} beetle needs nine unique landed attacks and missile three during warmup`,()=>{for(const [id,count]of [['beetle',9],['missile',3]]){const e=arena(),ref=spawn(e,side,id),f=e.actorRef(e.fighters[1-side]);for(let n=0;n<count;n++){const attackId=++e.seq;assert(damage(e,f,ref,999,{basic:true},{attackId}).landed);if(n<count-1){assert(e.resolveActor(ref));assert(!damage(e,f,ref,999,{basic:true},{attackId}).accepted);}}assert.equal(e.resolveActor(ref),null);assert.equal(e.packCore.units.deaths.length,1);}});
 test(`P${side+1} misses, spells and invulnerability do not count as hit-health attacks`,()=>{const e=arena(),ref=spawn(e,side),source=e.actorRef(e.fighters[1-side]);assert(!damage(e,source,ref,999).accepted);assert(!damage(e,source,ref,999,{basic:true,landed:false},{attackId:++e.seq}).accepted);near(e.resolveActor(ref).hp,9);const invuln=spawn(e,side,'invulnerable');assert(!damage(e,source,invuln,999,{basic:true},{attackId:++e.seq}).accepted);near(e.resolveActor(invuln).hp,100);});
 test(`P${side+1} removed queued target never retargets its owner or a new unit`,()=>{const e=arena(),target=spawn(e,side,'spider'),source=e.actorRef(e.fighters[1-side]);e.fighters[1-side].x=side?600:400;const id=e.queueActorAttack({source,target,delay:.2});assert(id);const hp=e.fighters[side].hp;e.removeUnit(target);const replacement=spawn(e,side,'spider');frames(e,15);near(e.fighters[side].hp,hp);near(e.resolveActor(replacement).hp,100);});
 test(`P${side+1} automatic spider attacks nearest legal actual unit rather than its owner`,()=>{const e=arena();e.fighters[1-side].x=side?100:1100;const source=spawn(e,side,'spider',{x:600}),target=spawn(e,1-side,'reflector',{x:650}),ownerHp=e.fighters[1-side].hp;frames(e,6);near(e.resolveActor(target).hp,80);near(e.fighters[1-side].hp,ownerHp);const job=e.packCore.units.jobs.find(j=>j.source.id===source.id);if(job)assert.equal(job.target.id,target.id);});
 test(`P${side+1} unit damage uses native fighter HP ledger with actual source provenance`,()=>{const e=arena(),source=spawn(e,side,'reflector'),target=e.actorRef(e.fighters[1-side]),f=e.fighters[1-side];const ledger=e.beginDeferredHP(f,{owner:1-side,abilityId:'unit_fixture',duration:.1,damageFraction:.5}),hp=f.hp;const r=damage(e,source,target,40);near(r.actual,20);near(r.deferred,20);near(f.hp,hp-20);assert.deepEqual(e.packCore.ledgers[0].lastCause.sourceActor,source);frames(e,8);near(f.hp,hp-40);assert.equal(e.packCore.ledgers.find(l=>l.id===ledger).phase,'settled');});
 test(`P${side+1} actual Core4 Aphotic Shield absorbs unit source damage once`,()=>{const e=arena(side?[100,0]:[0,100]),source=spawn(e,side,'reflector'),f=e.fighters[1-side];f.pack.shield={amount:30,life:12};const hp=f.hp,r=damage(e,source,e.actorRef(f),40);near(r.actual,10);near(f.hp,hp-10);assert(!f.pack.shield);assert.equal(e.logs.filter(l=>l.type==='shield_end').length,1);});
 test(`P${side+1} reflected actor spell damages and controls the actual source unit`,()=>{const e=arena(),source=spawn(e,side,'spider'),f=e.fighters[1-side],target=e.actorRef(f),hp=e.fighters[side].hp;e.addBuff(f,'counter',{},3);const route=api.routeActorSpell(e,{source,target,abilityId:'unit_fixture'});assert(route.accepted&&route.reflected);assert.deepEqual(route.target,source);damage(e,route.source,route.target,20,{reflected:true,noReflect:true});near(e.resolveActor(source).hp,80);const c=e.controlActor({source:route.source,target:route.target,type:'stun',duration:.5});assert(c);assert.equal(e.resolveActor(source).controls.length,1);near(e.fighters[side].stun,0);near(e.fighters[side].hp,hp);});
 test(`P${side+1} source-unit fighter controls retain source ref in public end events`,()=>{const e=arena(),source=spawn(e,side,'reflector'),f=e.fighters[1-side],target=e.actorRef(f),seen=[];const original=e.packCombat;e.packCombat={...original,controlEnded:(engine,c)=>seen.push(c)};const c=e.controlActor({source,target,type:'root',duration:.2});assert(c.id);assert.deepEqual(e.packCore.controls[0].sourceActor,source);frames(e,13);assert.deepEqual(seen[0].sourceActor,source);});
 test(`P${side+1} group member damage death kills owner and peers exactly once; expiry does not`,()=>{const e=arena(),a=spawn(e,side,'meepo',{group:'group_a'}),b=spawn(e,side,'meepo',{group:'group_a'}),source=e.actorRef(e.fighters[1-side]);const r=damage(e,source,a,100);assert(r.accepted);assert.equal(e.resolveActor(a),null);assert.equal(e.resolveActor(b),null);near(e.fighters[side].hp,0);assert.equal(e.packCore.deaths.length,1);assert.equal(e.packCore.deaths[0].cause.kind,'group');assert(!e.removeUnit(a));assert.equal(e.packCore.deaths.length,1);const other=arena();spawn(other,side,'meepo',{group:'group_a',duration:.05});const hp=other.fighters[side].hp;frames(other,4);near(other.fighters[side].hp,hp);});
 test(`P${side+1} KO cancels nonpersistent owner jobs and freezes retained jobs without altering the round result`,()=>{const e=arena(),a=spawn(e,side,'spider',{x:600}),b=spawn(e,side,'illusion',{x:600}),target=spawn(e,1-side,'reflector',{x:650});e.resolveActor(b).attackCd=.2;const doomed=e.queueActorAttack({source:a,target,delay:.2}),retained=e.queueActorAttack({source:b,target,delay:.2,persist:true});const fighterJob=e.queueActorAttack({source:e.actorRef(e.fighters[side]),target,delay:.2});e.fighters[side].hp=0;frames(e,1);assert.equal(e.phase,'roundEnd');const history=structuredClone(e.history),score=[...e.score];frames(e,12);assert.equal(e.resolveActor(a),null);assert(e.resolveActor(b));near(e.resolveActor(target).hp,100);assert(!e.packCore.units.jobs.some(j=>j.id===doomed||j.id===fighterJob));assert(e.packCore.units.jobs.some(j=>j.id===retained));assert.deepEqual(e.history,history);assert.deepEqual(e.score,score);const twin=arena().restoreSimulation(e.snapshot());frames(e,5);frames(twin,5);assert.deepEqual(e.snapshot(),twin.snapshot());});
 test(`P${side+1} persistent unit jobs deliver through owner death when training continues without KO`,()=>{const e=arena();e.mode='training';const a=spawn(e,side,'spider',{x:600}),b=spawn(e,side,'illusion',{x:600}),target=spawn(e,1-side,'reflector',{x:650});e.resolveActor(b).attackCd=.2;e.queueActorAttack({source:a,target,delay:.2});e.queueActorAttack({source:b,target,delay:.2,persist:true});e.fighters[side].hp=0;frames(e,13);assert.equal(e.phase,'fight');assert.equal(e.resolveActor(a),null);assert(e.resolveActor(b));near(e.resolveActor(target).hp,80);assert.equal(e.history.length,0);});
 test(`P${side+1} noProc/noCleave propagate through nested actual actor damage`,()=>{const e=arena(),source=spawn(e,side,'reflector'),target=spawn(e,1-side,'reflector'),original=e.packCombat,seen=[];let attacks=0;e.packCombat={...original,afterActorDamage(engine,event){seen.push(event.flags);if(seen.length===1){const r=damage(engine,source,target,10,{noProc:false,noCleave:false},{kind:'cleave'});assert(!r.accepted);}},afterActorAttack(){attacks++;}};const r=damage(e,source,target,20,{basic:true,noProc:true,noCleave:true},{attackId:++e.seq});assert(r.accepted);near(e.resolveActor(target).hp,80);assert.equal(attacks,0);assert(seen[0].noProc&&seen[0].noCleave);});
 test(`P${side+1} canonical negative armor increases actual unit damage`,()=>{const e=arena(),source=e.actorRef(e.fighters[1-side]),target=spawn(e,side,'armor');const r=api.resolveActorDamage(e,{source,target,amount:20,damageType:'physical',abilityId:'unit_fixture'});near(r.actual,20*(1+.3/1.3));});
 test(`P${side+1} unit timers, jobs, deaths and controls restore deterministically`,()=>{const e=arena(),source=spawn(e,side,'spider'),target=spawn(e,1-side,'reflector',{x:650});e.controlActor({source:target,target:source,type:'root',duration:.15});e.queueActorAttack({source,target,delay:.3});frames(e,3);const saved=e.snapshot(),twin=arena().restoreSimulation(saved);for(let i=0;i<30;i++){frames(e,1);frames(twin,1);assert.deepEqual(e.snapshot(),twin.snapshot());}});
 test(`P${side+1} malformed refs/templates and forged unit health reject before live mutation`,()=>{const e=arena(),ref=spawn(e,side,'reflector'),good=e.snapshot();for(const patch of [{hp:200},{maxHp:200},{owner:3},{templateId:'unknown'},{groupKillsOwner:true},{ref:{...ref,epoch:99}},{ref:{...ref,id:999999}}]){const bad=structuredClone(good);Object.assign(bad.packCore.units.records[0],patch);assert.throws(()=>e.restoreSimulation(bad));assert.deepEqual(e.snapshot(),good);}assert.throws(()=>e.resolveActor({kind:'fighter',id:side}));assert.throws(()=>api.spawnUnit(e,{owner:side,templateId:'unknown',abilityId:'unit_fixture',x:600,duration:1}));assert.deepEqual(e.snapshot(),good);});
}
