import {c43Enabled} from '../../hero-c43-host.js';
import {validateExtraStatus,validateExtraJob,validateExtraEntity,EXTRA_IDS} from './extra.js';
import {DEFINITIONS} from './definitions.js';
const eq=(a,b)=>JSON.stringify(a)===JSON.stringify(b),n=(x,min=0,max=1e6)=>Number.isFinite(x)&&x>=min&&x<=max,actor=x=>x===0||x===1;
const keys=(v,allowed)=>v&&typeof v==='object'&&!Array.isArray(v)&&Object.keys(v).every(k=>allowed.includes(k))&&allowed.every(k=>Object.hasOwn(v,k));
const find=(e,owner,id)=>{const slot=e.hero(owner).abilities.findIndex(a=>a.id===id);return slot<0?undefined:e.ability(owner,slot);},param=(a,k)=>a?.official.params[k];
const buff=(b,owner,extra)=>keys(b,['owner','hostile','polarity','pierces',...extra])&&b.owner===owner&&b.hostile===false&&b.polarity==='positive'&&b.pierces===false;
const statusRules={seal:{duration:6,values:{magicAmp:.35,silence:true},dispel:'basic'},concussive_slow:{duration:4,values:{moveSlow:.4},dispel:'basic'},stampede_slow:{duration:3,values:{moveSlow:1},dispel:'basic'}};
export function validateSnapshot(e,g){try{
 const controlRules={centaur_hoof_stomp:['stun','strong',1.5],ember_spirit_searing_chains:['root','basic',1.5],abyssal_underlord_pit_of_malice:['root','basic',1.5],void_spirit_aether_remnant:['stun','strong',1.5],dawnbreaker_fire_wreath:['stun','strong',1.2],dawnbreaker_solar_guardian:['stun','strong',1.5]};
 for(const c of g.packCore?.controls||[])if(c.key.startsWith('r91:')){const id=c.key.slice(4),r=controlRules[id];if(!r||!find(e,c.owner,id)||c.target!==1-c.owner||c.type!==r[0]||c.dispel!==r[1]||c.pierces!==false||!n(c.duration,0,r[2]))return false;}
 const w=g.packModules.r91;if(!keys(w,['entities','jobs','revisions','data'])||!keys(w.data,[]))return false;
 const ids=new Set(),idOK=id=>Number.isSafeInteger(id)&&id>0&&id<=g.packClock.seq&&!ids.has(id)&&!!ids.add(id);
 for(const j of w.jobs){if(!idOK(j.id)||!keys(j,['id','abilityId','kind','owner','target','at','data','persist','cancelOnInterrupt','revision',...(j.kind==='stomp'?['actionToken']:[])])||!find(e,j.owner,j.abilityId)||(j.target!==null&&!actor(j.target))||!n(j.at,g.t-1e-7,g.t+15)||!n(j.revision,0,w.revisions[j.owner]))return false;
  if(j.kind==='extra'){if(!validateExtraJob(e,j))return false;const d=j.data,fields=['op','token',...(['star'].includes(d.op)?['part']:['hammer_out','hammer_return'].includes(d.op)?['from','x']:['deadshot','veil'].includes(d.op)?[]:['x'])];if(!keys(d,fields)||d.token!==null&&(!Number.isSafeInteger(d.token)||!n(d.token,0,g.fighters[j.owner].packModules.r91.data.extra.revision))||d.x!==undefined&&!n(d.x,45,1155)||d.from!==undefined&&!n(d.from,45,1155)||d.part!==undefined&&![0,1,2].includes(d.part))return false;continue;}
  if(j.persist!==false||!actor(j.target))return false;
  if(j.kind==='stomp'){if(j.abilityId!=='centaur_hoof_stomp'||!keys(j.data,[])||j.cancelOnInterrupt!==true||!keys(j.actionToken,['actor','revisions'])||j.actionToken.actor!==j.owner||!keys(j.actionToken.revisions,['control','input_cancel','action']))return false;}
  else if(j.kind==='quill'){if(j.abilityId!=='bristleback_quill_spray'||!eq(j.data,{reflected:true})||j.cancelOnInterrupt!==false)return false;}else return false;
 }
 for(const z of w.entities){if(!idOK(z.id)||!keys(z,['id','kind','owner','x','y','life','data'])||!n(z.x,-500,1700)||!n(z.y,-500,2000))return false;const d=z.data;
  if(z.kind==='extra'){const limits={remnant:1,storm:6.000001,pit:12,gate:20,aether:17,hammer_burn:4,calling:8};if(!validateExtraEntity(e,z)||!keys(d,['abilityId','mode','from','age','tick','nextHit','face','waves'])||!n(z.life,0,limits[d.mode])||!n(d.age,0,limits[d.mode]+1e-7)||!n(d.tick,-1e-7,limits[d.mode]+1e-7)||!n(d.nextHit,0,g.t+4)||!n(d.from,45,1155)||![-1,1].includes(d.face)||!Number.isInteger(d.waves)||!n(d.waves,0,6))return false;continue;}
  if(z.kind==='homing'){const goo=d.goo===true;if(!keys(d,['target','abilityId','damage','speed','slow','reflected',...(goo?['goo']:[])])||typeof d.reflected!=='boolean'||!n(z.life,0,8)||!actor(d.target)||d.target===z.owner)return false;const original=d.reflected?d.target:z.owner,a=find(e,original,d.abilityId);if(!a)return false;
   let damage,speed,slow=null;if(a.id==='bristleback_viscous_nasal_goo'&&goo){damage=0;speed=param(a,'goo_speed');}else if(a.id==='skywrath_mage_arcane_bolt'&&!goo){damage=param(a,'bolt_damage')+e.hero(original).attributes18.int*param(a,'int_multiplier');speed=param(a,'bolt_speed');}else if(a.id==='skywrath_mage_concussive_shot'&&!goo){damage=param(a,'damage');speed=param(a,'speed');slow={duration:param(a,'slow_duration'),amount:param(a,'movement_speed_pct')/100};}else return false;if(d.damage!==damage||d.speed!==speed*.55||!eq(d.slow,slow))return false;
  }else if(z.kind==='flare'){const a=find(e,z.owner,d.abilityId);if(a?.id!=='skywrath_mage_mystic_flare'||!keys(d,['abilityId','radius','interval','tick','damage'])||!n(z.life,0,2)||d.radius!==param(a,'radius')*.55||d.interval!==param(a,'damage_interval')||!n(d.tick,-1e-7,d.interval)||d.damage!==param(a,'damage')/(param(a,'duration')/d.interval))return false;}else return false;
 }
 for(let i=0;i<2;i++){const f=g.fighters[i],v=f.packModules.r91,d=v.data,key=e.hero(i).key;if(!keys(v,['statuses','data'])||!keys(d,['barriers','stampede','windup','dead','quills','warpath','backDamage','extra'])||typeof d.dead!=='boolean'||(d.windup!==null&&(!keys(d.windup,['owner','hostile','polarity','pierces','life'])||d.windup.owner!==i||d.windup.hostile!==false||d.windup.polarity!=='self_restriction'||d.windup.pierces!==false||!n(d.windup.life,0,.5)))||!n(d.backDamage,0,200)||![d.barriers,d.quills,d.warpath].every(Array.isArray)||d.barriers.length>64||d.quills.length>64||d.warpath.length>12)return false;
  if(d.barriers.some(b=>!buff(b,i,['amount','life'])||!n(b.amount,0,13.5)||!n(b.life,0,12))||key!=='skywrath_mage'&&d.barriers.length||d.warpath.some(s=>!buff(s,i,['life'])||!n(s.life,0,20))||key!=='bristleback'&&d.warpath.length)return false;
  if(d.quills.some(s=>!keys(s,['owner','life','hostile','polarity','pierces'])||!actor(s.owner)||e.hero(s.owner).key!=='bristleback'||!n(s.life,0,14*1.045)||s.hostile!==true||s.polarity!=='hostile'||s.pierces!==true))return false;
  if(d.stampede!==null&&(key!=='centaur'||!buff(d.stampede,i,['life','hit'])||!n(d.stampede.life,0,4.5)||!Array.isArray(d.stampede.hit)||d.stampede.hit.length>1||d.stampede.hit.some(x=>x!==1-i)))return false;
  const x=d.extra;if(!keys(x,['revision','channel','charges','luminosity','gunslinger','deathSeen'])||!Number.isSafeInteger(x.revision)||x.revision<0||!Number.isInteger(x.luminosity)||!n(x.luminosity,0,3)||typeof x.gunslinger!=='boolean'||typeof x.deathSeen!=='boolean'||!Array.isArray(x.charges))return false;
  const expected=e.hero(i).abilities.filter(a=>EXTRA_IDS.includes(e.hero(i).registryNumericId)&&a.official?.params?.AbilityCharges>0);if(x.charges.length!==expected.length)return false;for(const c of x.charges){const a=expected.find(a=>a.id===c.abilityId);if(!a||!keys(c,['abilityId','count','max','restore','pending'])||c.max!==a.official.params.AbilityCharges||c.restore!==a.official.params.AbilityChargeRestoreTime||!Number.isInteger(c.count)||!n(c.count,0,c.max)||!Array.isArray(c.pending)||c.count+c.pending.length!==c.max||c.pending.some((at,i)=>!n(at,g.t-1e-7,g.t+c.max*c.restore+1e-7)||i>0&&at<c.pending[i-1]))return false;}
  if(x.channel!==null&&(!keys(x.channel,['kind','startX','until','flight'])||!({sleight:104,gate:106,phase:117,star:121,solar:121}[x.channel.kind]===e.hero(i).registryNumericId)||!n(x.channel.startX,45,1155)||!n(x.channel.until,g.t-1e-7,g.t+3.5)||typeof x.channel.flight!=='boolean'||x.channel.flight&&x.channel.kind!=='solar'))return false;

  for(const s of v.statuses){if(s.key.startsWith('x_')){if(!keys(s,['key','owner','life','duration','elapsed','tick','interval','values','dispel','pierces','hostile','polarity','origin','group','allowInvulnerable','abilityId'])||!validateExtraStatus(e,s)||Math.abs(s.elapsed+s.life-s.duration)>1e-6)return false;continue;}if(!keys(s,['key','owner','life','duration','elapsed','tick','interval','values','dispel','pierces','hostile','polarity','origin','group','allowInvulnerable'])||!actor(s.origin)||s.owner!==s.origin&&i!==s.origin||s.hostile!==true||s.polarity!=='hostile'||s.group!==null||s.allowInvulnerable!==false||s.pierces!==false||s.interval!==0||!n(s.life,0,s.duration)||!n(s.elapsed,0,s.duration+1e-7)||!n(s.tick,0,s.duration+1e-7)||Math.abs(s.elapsed+s.life-s.duration)>1e-6)return false;
   if(s.key==='goo'){const c=s.values.stacks;if(e.hero(s.origin).key!=='bristleback'||!Number.isInteger(c)||!n(c,1,6)||!eq(s.values,{stacks:c,armor:3+3.5*c,moveSlow:(12+12*c)/100})||!n(s.duration,5,5*1.045)||s.dispel!=='basic')return false;}
   else {const a=s.key==='seal'&&c43Enabled(e,s.origin,2)?e.ability(s.origin,2):null,r=a?{duration:a.official.params.seal_duration,values:{magicAmp:-a.official.params.resist_debuff/100,silence:true},dispel:'basic'}:statusRules[s.key],caster={seal:'skywrath_mage',concussive_slow:'skywrath_mage',stampede_slow:'centaur'}[s.key];if(!r||e.hero(s.origin).key!==caster||s.duration!==r.duration||!eq(s.values,r.values)||s.dispel!==r.dispel)return false;}
  }
  // Core holds a copied casting profile; pin it to the immutable selected slot.
  if(f.cast&&e.hero(i).packKey==='r91'){const c=f.cast,a=e.ability(i,c.slot);if(!a||a.mvp.passive||!eq(c.m,a.mvp)||!Number.isInteger(c.slot)||!n(c.remaining,0,a.mvp.startup_frames/60)||!n(c.aim,45,1155))return false;}
 }
 return true;
}catch{return false;}}
