import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../../src/engine.js';import {runtimeHeroes} from '../../../src/runtime-heroes.js';import {ACTIVE_ROSTER} from '../../../src/hero-registry.js';import {CORE4_PACKS} from '../../../src/hero-packs/index.js';
import {PACKS,CANDIDATES,DISABLED_PACKS} from '../../../src/hero-packs/r20_55/index.js';import {Combat,services} from '../../../src/hero-packs/r20_55/combat.js';
const ids=PACKS.map(p=>p.definition.registryNumericId),defs=PACKS.map(p=>p.definition),heroes=[...runtimeHeroes.filter(h=>!ids.includes(h.registryNumericId)),...defs];
function fixture(id=28,side=0,other=0,extras=[]){const all=[...PACKS,...extras],added=extras.map(p=>p.definition),hs=[...heroes.filter(h=>!added.some(a=>a.registryNumericId===h.registryNumericId)),...added];return new Engine(hs,side?[other,id]:[id,other],{seed:197,heroPacks:[...CORE4_PACKS,...all],simulationRoster:{...ACTIVE_ROSTER,heroIds:[...new Set([...ACTIVE_ROSTER.heroIds,...all.map(p=>p.definition.registryNumericId)])]}}).start();}
function run(e,seconds){const end=e.t+seconds;for(let guard=0;e.t<end-1e-8&&guard<10000;guard++){if(e.phase!=='fight')break;e.step();}}
function nearFixture(e){e.fighters[0].x=500;e.fighters[1].x=560;} // HARNESS geometry injection, not natural match evidence.
function press(e,side,slot){e.setInput(side,{});e.step();e.setInput(side,{['s'+slot]:true});e.step();e.setInput(side,{});}
const approx=(a,b)=>assert.ok(Math.abs(a-b)<1e-7,`${a} != ${b}`);
function restore(e){// Restore only mutable Engine state against the same canonical pair.
 const all=[...CORE4_PACKS,...PACKS];const next=new Engine(heroes,e.indices,{seed:197,heroPacks:all,simulationRoster:{...ACTIVE_ROSTER,heroIds:[...new Set([...ACTIVE_ROSTER.heroIds,...ids])]}}).start();next.restoreSimulation(e.snapshot());return next;}
for(const p of PACKS)for(const side of [0,1])for(let slot=0;slot<4;slot++)test(`REAL ENGINE HARNESS ${p.definition.registryNumericId} side${side} slot${slot+1} input and replay`,()=>{const e=fixture(p.definition.registryNumericId,side),f=e.fighters[side];nearFixture(e);const a=p.definition.abilities[slot],mp=f.mp;press(e,side,slot);run(e,.8);if(a.mvp.passive){assert.equal(f.casts,0);assert.equal(f.cd[slot],0);}else{assert.equal(f.casts,1);assert.ok(e.logs.some(l=>l.type==='activate'&&l.skill===a.id));assert.ok(e.logs.some(l=>l.type==='cast'&&l.skill===a.id&&l.cost===a.mvp.mana));}const twin=restore(e);for(let n=0;n<70;n++){e.step();twin.step();}assert.deepEqual(twin.snapshot(),e.snapshot());assert.equal(p.definition.runtimeReady,false);assert.equal(p.definition.activeUnlock,false);});
test('REAL ENGINE Venge all four inputs reached by walking from default spawn, no state injection',()=>{for(let slot=0;slot<4;slot++){const e=fixture(),f=e.fighters[0],t=e.fighters[1];e.setInput(0,{right:true});for(let n=0;Math.abs(t.x-f.x)>70&&n<300;n++)e.step();e.setInput(0,{});run(e,.25);press(e,0,slot);run(e,1);assert.equal(f.casts,slot===2?0:1);if(slot!==2)assert.ok(e.logs.some(l=>l.type==='activate'&&l.slot===slot));}});
test('REAL ENGINE Venge missile damages and control is capped by Engine',()=>{const e=fixture();nearFixture(e);const t=e.fighters[1],hp=t.hp;press(e,0,0);run(e,.6);assert.equal(hp-t.hp,340);assert.ok(t.stun>0&&t.stun<=1.5);});
test('REAL ENGINE Venge aura scales base damage and passive button never spends',()=>{const e=fixture(),f=e.fighters[0],t=e.fighters[1],h=e.hero(0);approx(e.packCombat.attack(e,f,t,h.attack,{}),h.attack*1.3125);const mp=f.mp;assert.equal(e.cast(0,2),false);assert.equal(f.mp,mp);});
test('REAL ENGINE Venge Wave attack and armor are suppressed by later immunity, resume before expiry',()=>{const e=fixture();nearFixture(e);const f=e.fighters[0],t=e.fighters[1];press(e,0,1);run(e,.5);const s=services.status(e,t,'vengefulspirit_wave_of_terror');assert.equal(s.hostile,true);assert.equal(s.polarity,'hostile');const base=e.hero(1).attack;assert.ok(e.packCombat.attack(e,t,f,base,{})<base);e.addBuff(t,'harness_immune',{debuffImmune:true},1);approx(e.packCombat.attack(e,t,f,base,{}),base);const hp=t.hp;e.resolveDamage(f,t,100,{damage_type:'physical',blockable:false},{dot:true});approx(hp-t.hp,100);run(e,1.1);assert.ok(e.packCombat.attack(e,t,f,base,{})<base);e.dispel(t);approx(e.packCombat.attack(e,t,f,base,{}),base);});
test('REAL ENGINE negative new status rejects immune and invulnerable without blocking self shield',()=>{const e=fixture();nearFixture(e);const [f,t]=e.fighters;e.addBuff(t,'harness_immune',{debuffImmune:true},5);press(e,0,1);run(e,.5);assert.equal(services.status(e,t,'vengefulspirit_wave_of_terror'),undefined);run(e,.3);e.addBuff(f,'harness_immune',{debuffImmune:true},5);press(e,0,3);run(e,.7);assert.ok(services.fighter(e,f).statuses.some(s=>s.values.shield===450&&s.polarity==='positive'&&!s.hostile));t.invuln=1;assert.equal(services.applyStatus(e,t,{key:'probe',owner:0,duration:1,pierces:true}),null);});
test('REAL ENGINE Swap cancels original core startup permanently and shield consumes actual incoming amount',()=>{const e=fixture(28,0,4);nearFixture(e);const [f,t]=e.fighters;e.setInput(1,{s3:true});e.step();assert.ok(t.cast);press(e,0,3);run(e,.6);assert.equal(t.cast,null);run(e,1);assert.equal(e.logs.some(l=>l.type==='activate'&&l.player===1),false);const hp=f.hp;const receipt=e.resolveDamage(t,f,500,{damage_type:'pure',blockable:false},{dot:true});approx(receipt.actual,50);approx(hp-f.hp,50);});
test('REAL ENGINE Venge discrete reflection debits original resources and targets original caster once',()=>{const e=fixture();nearFixture(e);const [f,t]=e.fighters;e.addBuff(t,'counter',{},5);const hp=f.hp,enemy=t.hp;press(e,0,0);run(e,.7);approx(hp-f.hp,340);approx(t.hp,enemy);assert.equal(f.casts,1);assert.equal(e.buff(t,'counter'),undefined);});
test('REAL ENGINE paused timer is frozen and canceled channels never resume after short stun',()=>{const e=fixture(32);nearFixture(e);press(e,0,2);run(e,.4);assert.ok(services.fighter(e,e.fighters[0]).data.channel);const snap=e.snapshot();e.paused=true;for(let i=0;i<50;i++)e.step();approx(e.t,snap.t);e.paused=false;e.control(e.fighters[0],'stun',.05);run(e,.1);const mp=e.fighters[1].mp;run(e,1);assert.equal(services.world(e).entities.some(x=>x.data.channel),false);assert.ok(e.fighters[1].mp>=mp);});
test('REAL ENGINE channel movement and input cancel invalidate persistent effect',()=>{for(const reason of ['move','input_cancel']){const e=fixture(32);nearFixture(e);press(e,0,2);run(e,.4);if(reason==='move')e.setInput(0,{left:true});else e.cancelInput(0);run(e,.2);assert.equal(services.world(e).entities.some(x=>x.data.channel),false);assert.equal(services.fighter(e,e.fighters[0]).data.channel,null);}});
test('REAL ENGINE Omni physical immunity, positive immunity heal ticks and magic remain independent',()=>{const e=fixture(55);nearFixture(e);const [f,t]=e.fighters;f.hp-=400; // HARNESS missing HP for heal receipt.
 e.addBuff(f,'harness_immune',{debuffImmune:true},4);press(e,0,1);run(e,1.5);assert.ok(f.hp>f.maxHp-400);run(e,.3);press(e,0,3);run(e,.5);assert.equal(e.resolveDamage(t,f,100,{damage_type:'physical',blockable:false},{dot:true}).actual,0);approx(e.resolveDamage(t,f,100,{damage_type:'magical',blockable:false},{dot:true}).actual,40);});
test('REAL ENGINE Siphon charges exhaust through real input and recover one at a time',()=>{const e=fixture(42);nearFixture(e);for(let i=0;i<4;i++){press(e,0,2);run(e,.4);}assert.equal(e.fighters[0].charges[2],0);press(e,0,2);run(e,.3);assert.equal(e.fighters[0].casts,4);e.fighters[1].x=1155;run(e,40);assert.equal(e.fighters[0].charges[2],1);});
test('REAL ENGINE Siphon lifesteal uses receipt actual, zero against immunity, overkill capped',()=>{const e=fixture(42);nearFixture(e);const [f,t]=e.fighters;f.hp-=500;t.hp=7; // HARNESS actual debit/overkill boundary.
 press(e,0,2);run(e,.4);approx(f.hp,f.maxHp-493);assert.equal(t.hp,0);});
test('REAL ENGINE Dragon form range and speed change, corrosion suppressed during immunity, frost pierces',()=>{const e=fixture(47);nearFixture(e);press(e,0,3);run(e,.3);const [f,t]=e.fighters;assert.ok(e.property(f,'attack_range_bonus')>0);assert.ok(e.packCombat.moveMultiplier(e,f)>1);e.packCombat.afterAttack(e,f,t,{id:11,m:{}},true);const poison=services.status(e,t,'dragon_knight_elder_dragon_form_corrosion'),frost=services.status(e,t,'dragon_knight_elder_dragon_form_frost');assert.equal(poison.pierces,false);assert.equal(frost.pierces,true);e.addBuff(t,'harness_immune',{debuffImmune:true},2);const hp=t.hp;run(e,1.1);approx(t.hp,hp);assert.ok(e.packCombat.moveMultiplier(e,t)<1);});
test('REAL ENGINE Leshrac same button toggle off is reachable during cooldown without paying mana',()=>{const e=fixture(50);nearFixture(e);press(e,0,3);run(e,.3);assert.ok(services.fighter(e,e.fighters[0]).statuses.some(s=>s.key==='leshrac_pulse_nova'));const casts=e.fighters[0].casts;press(e,0,3);run(e,.3);assert.equal(services.fighter(e,e.fighters[0]).statuses.some(s=>s.key==='leshrac_pulse_nova'),false);assert.equal(e.fighters[0].casts,casts);});
test('REAL ENGINE own-data restore rejects noncanonical programs, polarity, owner and nonfinite values',()=>{const e=fixture();nearFixture(e);press(e,0,1);run(e,.5);for(const mutate of [g=>g.fighters[1].packModules.r20_55.statuses[0].owner=2,g=>g.fighters[1].packModules.r20_55.statuses[0].polarity='positive',g=>g.fighters[1].packModules.r20_55.statuses[0].programId='injected',g=>g.fighters[1].packModules.r20_55.statuses[0].values.attackReduction=Infinity]){const g=e.snapshot();mutate(g);assert.throws(()=>e.restoreSimulation(g));}});
test('REAL ENGINE all reserved-capability heroes reject construction rather than fallback',()=>{assert.equal(CANDIDATES.length,33);assert.equal(DISABLED_PACKS.length,25);for(const p of DISABLED_PACKS)assert.throws(()=>new Engine([...heroes,p.definition],[p.definition.registryNumericId,0],{heroPacks:[...CORE4_PACKS,...PACKS,p],simulationRoster:{...ACTIVE_ROSTER,heroIds:[...ACTIVE_ROSTER.heroIds,p.definition.registryNumericId]}}),/Missing public pack capability/);});
// Diagnostic partial Bane fixture: only Enfeeble/Sap are enabled. It deliberately excludes
// unresolved cast-range projection and sleep; never exported in PACKS or called a complete Bane.
function baneProbe(){const original=CANDIDATES.find(p=>p.definition.registryNumericId===20),p={...original,definition:structuredClone(original.definition),contract:{...original.contract,requiresCapabilities:['negative-status','damage-hooks'],state:'HARNESS_PARTIAL_MECHANISM_PROBE'}};p.definition.abilities[0].engineStatus='implemented';p.definition.abilities[1].engineStatus='implemented';const e=fixture(20,0,0,[p]);nearFixture(e);return e;}
test('REAL ENGINE PARTIAL Bane regression A: attack reduction and DOT suppressed, clocks continue, then resume',()=>{const e=baneProbe();const [f,t]=e.fighters;press(e,0,0);run(e,.3);const base=e.hero(1).attack;approx(e.packCombat.attack(e,t,f,base,{}),base*.3);e.addBuff(t,'harness_immune',{debuffImmune:true},1);approx(e.packCombat.attack(e,t,f,base,{}),base);const hp=t.hp,s=services.status(e,t,'bane_enfeeble'),life=s.life;run(e,.9);approx(t.hp,hp);assert.ok(s.life<life);run(e,.3);approx(e.packCombat.attack(e,t,f,base,{}),base*.3);run(e,1);assert.ok(t.hp<hp);});
for(const p of PACKS)for(const side of [0,1])test(`REAL ENGINE default-spawn walking reaches every slot: ${p.definition.registryNumericId}/side${side}`,()=>{for(let slot=0;slot<4;slot++){const e=fixture(p.definition.registryNumericId,side),f=e.fighters[side],t=e.fighters[1-side];e.setInput(side,{[side?'left':'right']:true});for(let n=0;Math.abs(t.x-f.x)>60&&n<360;n++)e.step();e.setInput(side,{});run(e,.25);press(e,side,slot);run(e,1.1);assert.equal(f.casts,p.definition.abilities[slot].mvp.passive?0:1);}});
test('REAL ENGINE mixed Ghost Shroud keeps positive immunity and healing while its negative half is suppressed',()=>{const e=fixture(36);nearFixture(e);press(e,0,1);run(e,.5);const [f,t]=e.fighters;const group='necrolyte_ghost_shroud',pos=services.status(e,f,group+'_positive'),neg=services.status(e,f,group+'_hostile');assert.equal(pos.polarity,'mixed');assert.equal(neg.polarity,'mixed');assert.equal(pos.hostile,false);assert.equal(neg.hostile,true);assert.equal(e.packCombat.disarmed(e,f),true);e.addBuff(f,'harness_immune',{debuffImmune:true},1);assert.equal(e.packCombat.disarmed(e,f),false);approx(e.resolveDamage(t,f,100,{damage_type:'physical',blockable:false},{dot:true}).actual,0);approx(e.resolveDamage(t,f,100,{damage_type:'magical',blockable:false},{dot:true}).actual,100);services.dispel(e,f,'basic',{hostile:false});assert.equal(services.status(e,f,group+'_positive'),undefined);assert.ok(services.status(e,f,group+'_hostile'));run(e,1.2);assert.equal(e.packCombat.disarmed(e,f),true);services.dispel(e,f,'basic',{hostile:true});assert.equal(e.packCombat.disarmed(e,f),false);});
test('REAL ENGINE positive namespace immunity suppresses existing other-side slow and negative DOT without suppressing own healing',()=>{const e=fixture(55,0,47);nearFixture(e);const [f,t]=e.fighters;press(e,1,0);run(e,.5);assert.ok(services.status(e,f,'dragon_knight_breathe_fire'));const base=e.hero(0).attack;assert.ok(e.packCombat.attack(e,f,t,base,{})<base);press(e,0,1);run(e,.5);assert.ok(e.property(f,'debuffImmune'));approx(e.packCombat.attack(e,f,t,base,{}),base);});
test('REAL ENGINE mixed snapshot replays and cannot flip hostile component positive',()=>{const e=fixture(36);nearFixture(e);press(e,0,1);run(e,.5);const copy=restore(e);run(e,1);run(copy,1);assert.deepEqual(copy.snapshot(),e.snapshot());const bad=e.snapshot();bad.fighters[0].packModules.r20_55.statuses.find(s=>s.hostile).hostile=false;assert.throws(()=>e.restoreSimulation(bad));});
test('REAL ENGINE self/point/enemy validation completes before resource debit',()=>{const e=fixture(50),f=e.fighters[0],mp=f.mp;for(const aim of [NaN,Infinity,-1,1201,1150]){assert.equal(e.cast(0,0,{aim}),false);assert.equal(f.mp,mp);assert.equal(f.cd[0],0);}assert.equal(e.cast(0,2),false);e.fighters[1].invuln=5;assert.equal(e.cast(0,1),true);});
test('REAL ENGINE new skill action cancels channel before accepting that skill',()=>{const e=fixture(32);nearFixture(e);press(e,0,2);run(e,.4);press(e,0,0);run(e,.5);assert.equal(services.fighter(e,e.fighters[0]).data.channel,null);assert.ok(e.logs.some(l=>l.type==='activate'&&l.skill==='lich_frost_nova'));});
test('REAL ENGINE Lich gaze and Siphon do not drain through later invulnerability or debuff immunity',()=>{for(const id of [32,42])for(const immunity of ['debuff','invuln']){const e=fixture(id);nearFixture(e);press(e,0,2);run(e,.4);const t=e.fighters[1],hp=t.hp,mp=t.mp;if(immunity==='debuff')e.addBuff(t,'harness_immune',{debuffImmune:true},2);else t.invuln=2;run(e,1);approx(t.hp,hp);assert.ok(t.mp>=mp);}});
test('REAL ENGINE damage shield and Abaddon conversion yield zero Siphon heal without HP differencing',()=>{const e=fixture(42,0,100);nearFixture(e);const [f,t]=e.fighters;f.hp-=500;t.hp=600;t.pack.borrowed=2;press(e,0,2);run(e,.5);approx(f.hp,f.maxHp-500);assert.ok(t.hp>600);});
test('REAL ENGINE cross-system armor is aggregated once with core4 mitigation',()=>{const e=fixture(28,0,25);nearFixture(e);const [f,t]=e.fighters;press(e,0,1);run(e,.5);const s=services.status(e,t,'vengefulspirit_wave_of_terror'),armor=s.values.armor;const r=e.resolveDamage(f,t,100,{damage_type:'physical',blockable:false},{dot:true});approx(r.actual,100*(1-.06*armor/(1+.06*Math.abs(armor))));});
test('REAL ENGINE launched missile survives later caster stun and reflects at delivery',()=>{for(const reflected of [false,true]){const e=fixture();nearFixture(e);press(e,0,0);run(e,.4);assert.ok(services.world(e).jobs.length);e.control(e.fighters[0],'stun',.05);const [f,t]=e.fighters,fh=f.hp,th=t.hp;if(reflected)e.addBuff(t,'counter',{},2);run(e,.4);approx(fh-f.hp,reflected?340:0);approx(th-t.hp,reflected?0:340);}});
test('REAL ENGINE owner death clears channel, returning spirits and namespace jobs',()=>{for(const id of [32,42,50]){const e=fixture(id);nearFixture(e);press(e,0,id===32?2:3);run(e,.6);const f=e.fighters[0];e.resolveDamage(e.fighters[1],f,100000,{damage_type:'pure',blockable:false},{dot:true});e.step();assert.equal(f.hp,0);assert.equal(services.world(e).entities.some(x=>x.owner===0),false);assert.equal(services.world(e).jobs.some(x=>x.owner===0),false);assert.equal(services.fighter(e,f).data.channel,null);assert.equal(services.fighter(e,f).data.swarm,null);assert.equal(services.fighter(e,f).statuses.length,0);}});
test('REAL ENGINE ground area is created before occupancy and can hit an arriving target',()=>{const e=fixture(50);press(e,0,1);run(e,.7);assert.ok(services.world(e).entities.length);const t=e.fighters[1],hp=t.hp;e.move(t,e.fighters[0].x+40-t.x);run(e,.5);assert.ok(t.hp<hp);});
test('REAL ENGINE startup snapshot uses canonical ability ID without copied skill profile',()=>{const e=fixture();nearFixture(e);press(e,0,0);assert.ok(e.fighters[0].cast);assert.equal(e.fighters[0].cast.m,undefined);const twin=restore(e);run(e,1);run(twin,1);assert.deepEqual(e.snapshot(),twin.snapshot());});
test('REAL ENGINE own snapshot rejects source coefficient, piercing and native profile injection',()=>{const e=fixture(47);nearFixture(e);press(e,0,3);run(e,.4);e.packCombat.afterAttack(e,e.fighters[0],e.fighters[1],{id:12,m:{}},true);for(const mutate of [g=>g.fighters[0].buffs.find(b=>b.key==='dragon_knight_elder_dragon_form').m.attack_range_bonus=999999,g=>g.fighters[1].packModules.r20_55.statuses.find(s=>s.key.endsWith('_corrosion')).pierces=true,g=>g.fighters[1].packModules.r20_55.statuses.find(s=>s.key.endsWith('_frost')).values.moveSlow=.999]){const bad=e.snapshot();mutate(bad);assert.throws(()=>e.restoreSimulation(bad));}});
test('REAL ENGINE Exorcism heals actual accumulated damage only at expiry and replays across the expiry',()=>{const e=fixture(42),[f,t]=e.fighters;f.hp-=600; // HARNESS missing HP only; spell still enters through normal input.
 press(e,0,3);run(e,3.2);const s=services.fighter(e,f).data.swarm;assert.ok(s.actual>0);const actual=s.actual;approx(f.hp,f.maxHp-600);t.invuln=45; // HARNESS boundary: later spirit hits have zero actual debit.
 run(e,35);const twin=restore(e);run(e,3);run(twin,3);assert.deepEqual(e.snapshot(),twin.snapshot());assert.equal(services.fighter(e,f).data.swarm,null);approx(f.hp,f.maxHp-600+actual*.25);});
test('REAL ENGINE Dragon temporary attack and movement profiles expire without mutating canonical stats',()=>{const e=fixture(47),f=e.fighters[0],base=e.hero(0).attack_range;press(e,0,3);run(e,.3);assert.ok(e.property(f,'attack_range_bonus')>0);run(e,60.1);assert.equal(e.property(f,'attack_range_bonus'),0);approx(e.packCombat.moveMultiplier(e,f),1);assert.equal(e.hero(0).attack_range,base);});
test('REAL ENGINE V5 Bloodrage grants attack speed/spell amplification and exact nonlethal periodic self cost',()=>{const e=fixture(21);nearFixture(e);const [f,t]=e.fighters;press(e,0,0);run(e,.2);const interval=e.packCombat.attackInterval(e,f,t,1);approx(interval,100/230);const hp=f.hp;run(e,1);approx(hp-f.hp,f.maxHp*.012);const receipt=e.resolveDamage(f,t,100,{damage_type:'pure',blockable:false},{dot:true,skill:'bloodseeker_blood_bath'});approx(receipt.actual,130);f.hp=1; // HARNESS nonlethal self-cost boundary.
 run(e,1);assert.equal(f.hp,1);});
test('REAL ENGINE V5 Blood Rite resolves at delayed fixed point and leaving avoids it',()=>{for(const leave of [false,true]){const e=fixture(21);nearFixture(e);const t=e.fighters[1],hp=t.hp;press(e,0,1);run(e,.5);assert.equal(t.hp,hp);if(leave)e.move(t,1155-t.x);run(e,2.6);approx(hp-t.hp,leave?0:265);assert.equal(e.isSilenced(t),!leave);}});
test('REAL ENGINE V5 Thirst is health-driven speed and break disables it; no visibility claim',()=>{const e=fixture(21);const [f,t]=e.fighters;approx(e.packCombat.moveMultiplier(e,f),1);t.hp=t.maxHp*.625; // HARNESS thresholds, not natural match evidence.
 approx(e.packCombat.moveMultiplier(e,f),1.2);t.hp=t.maxHp*.25;approx(e.packCombat.moveMultiplier(e,f),1.4);services.applyStatus(e,f,{key:'harness_break',owner:1,duration:1,values:{break:true}});approx(e.packCombat.moveMultiplier(e,f),1);assert.match(e.hero(0).abilities[2].mvp.arenaNote,/省略低血视野\/反隐/);assert.equal(e.hero(0).abilities[2].mvp.passive,true);});
test('REAL ENGINE V5 Rupture normal movement damages, immunity does not suppress piercing, large teleport is capped out',()=>{const e=fixture(21);nearFixture(e);press(e,0,3);run(e,.6);const t=e.fighters[1],mark=services.status(e,t,'bloodseeker_rupture');assert.ok(mark.pierces);const hp=t.hp;e.addBuff(t,'harness_immune',{debuffImmune:true},3);e.setInput(1,{right:true});run(e,.3);assert.ok(t.hp<hp);e.setInput(1,{});run(e,.05);const before=t.hp;e.move(t,1155-t.x);e.step();approx(t.hp,before);});
test('REAL ENGINE V5 reflected Rupture retains owner, piercing and flags through restore',()=>{const e=fixture(21);nearFixture(e);const [f,t]=e.fighters;e.addBuff(t,'counter',{},3);press(e,0,3);run(e,.6);const s=services.status(e,f,'bloodseeker_rupture');assert.equal(s.owner,1);assert.equal(s.reflected,true);assert.equal(s.pierces,true);const twin=restore(e);e.setInput(0,{left:true});twin.setInput(0,{left:true});run(e,.4);run(twin,.4);assert.deepEqual(e.snapshot(),twin.snapshot());});
test('REAL ENGINE V5 Enfeeble rejects owned enemy/point casts outside reduced range before mana/CD, then immunity restores range',()=>{for(const slot of [0,1]){const original=CANDIDATES.find(p=>p.definition.registryNumericId===20),probe={...original,definition:structuredClone(original.definition),contract:{...original.contract,requiresCapabilities:['typed-status'],state:'PARTIAL_MECHANISM_PROBE'}};probe.definition.abilities[0].engineStatus='implemented';const e=fixture(20,0,slot===0?28:50,[probe]);nearFixture(e);press(e,0,0);run(e,.5);const f=e.fighters[1],a=e.ability(1,0),target=e.fighters[0],range=a.mvp.range_wu;e.move(target,Math.max(45,f.x-range*.85-22)-target.x);const mp=f.mp,cd=f.cd[0],options=slot===1?{aim:target.x}:{};assert.equal(e.cast(1,0,options),false);assert.equal(f.mp,mp);assert.equal(f.cd[0],cd);e.addBuff(f,'harness_immune',{debuffImmune:true},2);assert.equal(e.cast(1,0,options),true);}});
// These diagnostic fixtures intentionally narrow a disabled hero to selected implemented
// mechanisms, with unresolved innates off. They are NOT exported full-hero candidates.
function partialFixture(id,slots,side=0){const original=CANDIDATES.find(p=>p.definition.registryNumericId===id),probe={...original,definition:structuredClone(original.definition),contract:{...original.contract,requiresCapabilities:['typed-status','effect-entities'],automaticInnateIds:[],state:'PARTIAL_MECHANISM_PROBE'}};probe.definition.innates=[];for(const slot of slots)probe.definition.abilities[slot].engineStatus='implemented';return fixture(id,side,0,[probe]);}
for(const side of [0,1])test(`REAL ENGINE PARTIAL Tiny four slots via walking/input; innate gated, side${side}`,()=>{for(let slot=0;slot<4;slot++){const e=partialFixture(27,[0,1,2,3],side),f=e.fighters[side],t=e.fighters[1-side];e.setInput(side,{[side?'left':'right']:true});for(let n=0;Math.abs(f.x-t.x)>60&&n<360;n++)e.step();e.setInput(side,{});run(e,.2);press(e,side,slot);run(e,.6);assert.equal(f.casts,slot===3?0:1);const twin=partialFixture(27,[0,1,2,3],side).restoreSimulation(e.snapshot());run(e,.8);run(twin,.8);assert.deepEqual(e.snapshot(),twin.snapshot());}});
test('REAL ENGINE PARTIAL Tiny tree uses eight unguarded landed attacks, real range projection and snapshot charges',()=>{const e=partialFixture(27,[0,1,2,3]);nearFixture(e);const [f,t]=e.fighters;t.hp=t.maxHp=20000; // HARNESS durability to inspect all eight hits.
 press(e,0,2);run(e,.5);assert.equal(e.property(f,'attack_range_override'),165);assert.equal(services.status(e,f,'tiny_tree_grab').values.charges,8);e.setInput(0,{attack:true});e.setInput(1,{right:true});for(let n=0;n<80;n++)e.step();assert.equal(services.status(e,f,'tiny_tree_grab').values.charges,8);e.setInput(1,{});for(let n=0;n<2000&&services.status(e,f,'tiny_tree_grab');n++){e.setInput(0,{attack:true,...(Math.abs(t.x-f.x)>80?{[t.x>f.x?'right':'left']:true}:{})});e.step();}assert.equal(services.status(e,f,'tiny_tree_grab'),undefined);assert.equal(e.property(f,'attack_range_override'),0);assert.ok(t.hp<20000);});
test('REAL ENGINE PARTIAL Tiny Grow projects attack, armor, movement and attack penalty, break leaves active tree buff',()=>{const e=partialFixture(27,[0,1,2,3]);nearFixture(e);const [f,t]=e.fighters,base=e.hero(0).attack;approx(e.packCombat.attack(e,f,t,base,{}),base+180);approx(e.packCombat.attackInterval(e,f,t,1),100/65);assert.ok(e.packCombat.moveMultiplier(e,f)>1);approx(e.resolveDamage(t,f,100,{damage_type:'physical',blockable:false},{dot:true}).actual,100/1.9);press(e,0,2);run(e,.5);services.applyStatus(e,f,{key:'harness_break',owner:1,duration:1,values:{break:true}});approx(e.packCombat.attack(e,f,t,base,{}),base+40);approx(e.packCombat.attackInterval(e,f,t,1),1);});
for(const side of [0,1])test(`REAL ENGINE PARTIAL Puck Orb launch then release/repress jaunt via ordinary input, side${side}`,()=>{const e=partialFixture(24,[0],side),f=e.fighters[side],start=f.x;press(e,side,0);run(e,.5);assert.ok(services.world(e).entities.some(x=>x.kind==='orb'));assert.ok(f.cd[0]>0);press(e,side,0);run(e,.1);assert.equal(f.casts,1);assert.notEqual(f.x,start);assert.equal(services.world(e).entities.some(x=>x.kind==='orb'),false);assert.ok(e.logs.some(l=>l.type==='pack_recast'));});
test('REAL ENGINE PARTIAL Puck held key never auto-jaunts; recast root gate preserves state and needs no extra mana',()=>{const e=partialFixture(24,[0]),f=e.fighters[0];e.setInput(0,{s0:true});run(e,.7);assert.equal(f.x,320);assert.equal(f.casts,1);f.root=.5;f.mp=0; // HARNESS recast admission/resource boundary.
 press(e,0,0);run(e,.1);assert.equal(e.logs.some(l=>l.type==='pack_recast'),false);assert.ok(services.world(e).entities.some(x=>x.kind==='orb'));run(e,.5);press(e,0,0);run(e,.1);assert.ok(e.logs.some(l=>l.type==='pack_recast'));assert.equal(f.casts,1);});
test('REAL ENGINE PARTIAL Puck Orb snapshot is canonical and owner death cleans effect/token',()=>{const e=partialFixture(24,[0]);press(e,0,0);run(e,.3);const twin=partialFixture(24,[0]).restoreSimulation(e.snapshot());run(e,.4);run(twin,.4);assert.deepEqual(e.snapshot(),twin.snapshot());e.resolveDamage(e.fighters[1],e.fighters[0],100000,{damage_type:'pure',blockable:false},{dot:true});e.step();assert.equal(services.world(e).entities.length,0);assert.equal(e.buff(e.fighters[0],'puck_illusory_orb'),undefined);});
test('REAL ENGINE PARTIAL Bane Brain Sap damage and fixed spell heal route once, including counter reflection',()=>{for(const reflect of [false,true]){const e=partialFixture(20,[0,1]);nearFixture(e);const [f,t]=e.fighters;f.hp-=400;t.hp-=300; // HARNESS heal capacity.
 if(reflect)e.addBuff(t,'counter',{},3);const fh=f.hp,th=t.hp;press(e,0,1);run(e,.5);approx(f.hp,reflect?fh-300:fh+300);approx(t.hp,reflect?th+300:th-300);assert.equal(f.casts,1);}});
