import fs from 'node:fs';import assert from 'node:assert/strict';import crypto from 'node:crypto';
import {PACKS,CANDIDATES,DISABLED_PACKS} from '../../../src/hero-packs/r20_55/index.js';
import {Engine} from '../../../src/engine.js';import {runtimeHeroes} from '../../../src/runtime-heroes.js';import {ACTIVE_ROSTER} from '../../../src/hero-registry.js';import {CORE4_PACKS} from '../../../src/hero-packs/index.js';
const root=new URL('../../../',import.meta.url),out=new URL('docs/r20_55/',root),source=JSON.parse(fs.readFileSync(new URL('src/hero-packs/r20_55/source.json',root)));
const write=(name,data)=>fs.writeFileSync(new URL(name,out),JSON.stringify(data,null,2));let checks=0;
const matrix=CANDIDATES.map(p=>{const row=source.find(r=>r.registry.registryNumericId===p.definition.registryNumericId);assert.ok(row);assert.equal(p.definition.id,row.registry.internalHeroId);assert.equal(p.definition.valveHeroId,row.registry.valveHeroId);assert.equal(p.definition.activeUnlock,false);assert.equal(p.definition.runtimeReady,false);assert.deepEqual(p.contract.selectedAbilityIds,p.definition.abilities.map(a=>a.valveAbilityId));checks+=5;const slots=p.definition.abilities.map((a,i)=>{assert.equal(a.id,row.selection.slots[i].officialAbilityKey);assert.equal(a.valveAbilityId,row.selection.slots[i].officialAbilityId);assert.equal(a.mvp.passive,row.selection.slots[i].passiveGrayDisabled);assert.equal(a.official.rank,row.selection.slots[i].arenaRank);assert.deepEqual(a.mvp.params,row.abilities[i].rankParams);checks+=5;return {slot:i+1,key:a.id,valveAbilityId:a.valveAbilityId,passiveGray:a.mvp.passive,rank:a.official.rank,status:a.engineStatus,source:a.official.source,sourcePointer:a.official.jsonPointer,arenaNote:a.mvp.arenaNote};});return {registryNumericId:p.definition.registryNumericId,hero:p.definition.key,state:p.contract.state,slots,automaticInnates:p.contract.automaticInnateIds,disabledInnateCandidates:p.contract.innateCandidates.filter(x=>!p.contract.automaticInnateIds.includes(x.id)).map(x=>x.id),requiresCapabilities:p.contract.requiresCapabilities,partialMechanismEvidence:({20:{slots:[1,2],scope:'Diagnostic Enfeeble/Sap only; legacy cast range and Nightmare control remain gated.'},24:{slots:[1],scope:'Diagnostic real-input Orb/recast only; full Puck still gated.'},27:{slots:[1,2,3,4],scope:'Diagnostic four selected slots with innate explicitly disabled; Tiny remains gated on full-source control resistance.'}})[p.definition.registryNumericId]||null,activeUnlock:false,runtimeReady:false};});
write('four-slot-matrix.json',matrix);write('source-audit.json',{checks,heroes:33,slots:132,readyCandidates:PACKS.map(p=>p.definition.registryNumericId).sort((a,b)=>a-b),readySlots:PACKS.length*4,disabledHeroes:DISABLED_PACKS.length,disabledSlots:DISABLED_PACKS.length*4,activeUnlocked:0,registryConflicts:[],sourceSha256:crypto.createHash('sha256').update(fs.readFileSync(new URL('src/hero-packs/r20_55/source.json',root))).digest('hex')});
const ids=PACKS.map(p=>p.definition.registryNumericId),heroes=[...runtimeHeroes.filter(h=>ids.includes(h.registryNumericId)===false),...PACKS.map(p=>p.definition)];
const opts={seed:197,heroPacks:[...CORE4_PACKS,...PACKS],simulationRoster:{...ACTIVE_ROSTER,heroIds:[...new Set([...ACTIVE_ROSTER.heroIds,...ids])]}};
const report={kind:'REAL_ENGINE_DETERMINISTIC_INPUT_STRESS',claim:'Default spawn, real setInput/step, no HP/MP injection; synthetic controls, not browser or natural match acceptance.',pairs:0,frames:0,snapshotReplays:0,maxSnapshotBytes:0,failures:[]};
for(const p of PACKS)for(const q of PACKS){try{const e=new Engine(heroes,[p.definition.registryNumericId,q.definition.registryNumericId],opts).start();for(let frame=0;frame<600;frame++){for(let i=0;i<2;i++){const f=e.fighters[i],t=e.fighters[1-i],cmd={};if(Math.abs(t.x-f.x)>80)cmd[t.x>f.x?'right':'left']=true;if(frame%60===0)cmd['s'+Math.floor(frame/60)%4]=true;if(frame%60>30)cmd.attack=true;e.setInput(i,cmd);}e.step();report.frames++;if(frame===240){const snap=e.snapshot();const twin=new Engine(heroes,e.indices,opts).start().restoreSimulation(snap);twin.setInput(0,{});twin.setInput(1,{});e.setInput(0,{});e.setInput(1,{});for(let n=0;n<30;n++){twin.step();e.step();report.frames++;}assert.deepEqual(twin.snapshot(),e.snapshot());report.snapshotReplays++;}for(const f of e.fighters)assert.ok(Number.isFinite(f.hp)&&Number.isFinite(f.mp)&&f.hp>=0&&f.mp>=0);}const snap=e.snapshot();report.maxSnapshotBytes=Math.max(report.maxSnapshotBytes,Buffer.byteLength(JSON.stringify(snap)));new Engine(heroes,e.indices,opts).start().restoreSimulation(snap);report.pairs++;}catch(error){report.failures.push({left:p.definition.registryNumericId,right:q.definition.registryNumericId,error:error.stack});}}
write('engine-matrix.json',report);console.log({checks,...report});if(report.failures.length)process.exitCode=1;
