import {execFileSync} from 'node:child_process';
import {CANDIDATE_ROSTER} from '../src/candidate-roster.js';
import {STABLE_ROSTER,REGISTRY_VERSION} from '../src/hero-registry.js';
import {bundleApp} from './bundle-app.mjs';
import fs from 'node:fs';import {createHash} from 'node:crypto';import path from 'node:path';import {fileURLToPath} from 'node:url';
const candidate=process.argv.includes('--candidate');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const dist=path.join(root,candidate?'dist-candidate':'dist'),pub=path.join(dist,'client');fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(pub,{recursive:true});fs.mkdirSync(path.join(pub,'src'),{recursive:true});fs.mkdirSync(path.join(pub,'assets'),{recursive:true});
await import('./generate-catalog.mjs');
const heroRuleFiles=['hero-rules-host.js','heros-rules.js','hero-area-pulse-receipts.js','hero-legacy-linear-host.js'];
const packFiles=fs.readdirSync(path.join(root,'src/hero-packs'),{recursive:true}).filter(f=>f.endsWith('.js')).sort().map(f=>'hero-packs/'+f).concat(heroRuleFiles);
const fingerprint=createHash('sha256');for(const f of ['../scripts/build.mjs','../package-lock.json','../scripts/bundle-app.mjs','../scripts/generate-catalog.mjs',...packFiles,'cohort-data.js','cohort-combat.js','cohort-render.js','pack-render.js','remote-snapshot.js','pack-dispatcher.js','pack-services.js','pack-hp.js','pack-control.js','pack-targeting.js','pack-runtime.js','registry-data.js','catalog-data.js','rules-version.js','hero-registry.js','hero-catalog.js','compatibility.js','../assets/atlas.json','../assets/cohort/core4-sprites.png','../index.html','../manifest.webmanifest','style.css','release-profile.js','candidate-roster.js','hero-presentation.js','runtime-heroes.js','data.js','engine.js','app.js','audio-score.js','audio-map.js','pack-audio.js','audio-synth.js','audio.js','official-music.js','mobile.js','music.js','net-quality.js','match-api.js','local-rooms.js','p2p.js'])fingerprint.update(fs.readFileSync(path.join(root,'src',f)));for(const asset of fs.readdirSync(path.join(root,'assets'),{recursive:true}).filter(f=>/\.(png|webp|mp3|json)$/.test(f)&&!f.startsWith('audio/')).sort()){fingerprint.update(asset);fingerprint.update(fs.readFileSync(path.join(root,'assets',asset)));}if(candidate)fingerprint.update('candidate:'+CANDIDATE_ROSTER.rosterId);const netVersion='duel-'+fingerprint.digest('hex').slice(0,20),netSource=`export const NET_VERSION='${netVersion}';\n`;if(!candidate)fs.writeFileSync(path.join(root,'src/net-version.js'),netSource);
fs.cpSync(path.join(root,'src/hero-packs'),path.join(pub,'src/hero-packs'),{recursive:true});
for(const f of heroRuleFiles)fs.copyFileSync(path.join(root,'src',f),path.join(pub,'src',f));
for(const f of ['index.html','manifest.webmanifest'])fs.copyFileSync(path.join(root,f),path.join(pub,f));for(const f of ['net-version.js','cohort-data.js','cohort-combat.js','cohort-render.js','pack-render.js','remote-snapshot.js','pack-dispatcher.js','pack-services.js','pack-hp.js','pack-control.js','pack-targeting.js','pack-runtime.js','registry-data.js','catalog-data.js','rules-version.js','hero-registry.js','hero-catalog.js','compatibility.js','release-profile.js','candidate-roster.js','hero-presentation.js','runtime-heroes.js','data.js','engine.js','app.js','style.css','audio-score.js','audio-map.js','pack-audio.js','audio-synth.js','audio.js','official-music.js','mobile.js','music.js','net-quality.js','match-api.js','local-rooms.js','p2p.js'])fs.copyFileSync(path.join(root,'src',f),path.join(pub,'src',f));
for(const f of fs.readdirSync(path.join(root,'assets'))){if(f.endsWith('-render.png')||f==='audio')continue;const p=path.join(root,'assets',f);if(fs.statSync(p).isDirectory())fs.cpSync(p,path.join(pub,'assets',f),{recursive:true});else fs.copyFileSync(p,path.join(pub,'assets',f));}
let data=fs.readFileSync(path.join(root,'src/data.js'),'utf8');data=data.replaceAll(/assets\/[a-z_]+-render\.png/g,m=>m.replace('assets/','assets/portraits/').replace('-render.png','.webp'));fs.writeFileSync(path.join(pub,'src/data.js'),data);
const dataUri=(f)=>{const mime=f.endsWith('.mp3')?'audio/mpeg':f.endsWith('.webp')?'image/webp':'image/png';return `data:${mime};base64,${fs.readFileSync(path.join(root,f)).toString('base64')}`;};
fs.writeFileSync(path.join(pub,'src/net-version.js'),netSource);if(candidate)fs.writeFileSync(path.join(pub,'src/release-profile.js'),'export const CANDIDATE_BUILD=true;\n');
const {code:js}=await bundleApp({offline:true,candidate,overrides:{'net-version.js':netSource}});
let css=fs.readFileSync(path.join(root,'src/style.css'),'utf8').replace(/^@import[^\r\n]*(?:\r?\n|$)/,'');let html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace('<link rel="stylesheet" href="src/style.css">','<style>'+css+'</style>').replace('<script type="module" src="src/app.js"></script>','<script type="module">'+js.replaceAll('</script','<\\/script')+'</script>');
html=html.replace('<link rel="manifest" href="manifest.webmanifest">','').replace('href="assets/app-icon-180.png"','href="'+dataUri('assets/app-icon-180.png')+'"');
fs.mkdirSync(path.join(root,'release'),{recursive:true});fs.writeFileSync(path.join(root,candidate?'release/DOTA_DUEL_46_QA候选版.html':'release/DOTA_DUEL_1V1_候选版.html'),html);console.log(JSON.stringify({build:'passed',candidate,netVersion,standaloneBytes:Buffer.byteLength(html),dist}));


fs.copyFileSync(path.join(root,'_headers'),path.join(pub,'_headers'));

fs.writeFileSync(path.join(pub,'build-manifest.json'),JSON.stringify({candidate,commit:execFileSync('git',['rev-parse','HEAD'],{cwd:root,encoding:'utf8'}).trim(),gameVersion:netVersion,roster:candidate?{...CANDIDATE_ROSTER,registryVersion:REGISTRY_VERSION}:STABLE_ROSTER,browserAcceptance:false},null,2)+'\n');
