import {bundleApp} from './bundle-app.mjs';
import fs from 'node:fs';import {createHash} from 'node:crypto';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');const dist=path.join(root,'dist'),pub=path.join(dist,'client');fs.rmSync(dist,{recursive:true,force:true});fs.mkdirSync(pub,{recursive:true});fs.mkdirSync(path.join(pub,'src'),{recursive:true});fs.mkdirSync(path.join(pub,'assets'),{recursive:true});
await import('./generate-catalog.mjs');
const packFiles=fs.readdirSync(path.join(root,'src/hero-packs'),{recursive:true}).filter(f=>f.endsWith('.js')).sort().map(f=>'hero-packs/'+f);
const fingerprint=createHash('sha256');for(const f of ['../scripts/build.mjs','../scripts/bundle-app.mjs','../scripts/generate-catalog.mjs',...packFiles,'cohort-data.js','cohort-combat.js','cohort-render.js','pack-dispatcher.js','pack-services.js','pack-hp.js','pack-control.js','pack-targeting.js','pack-runtime.js','registry-data.js','catalog-data.js','rules-version.js','hero-registry.js','hero-catalog.js','compatibility.js','../assets/atlas.json','../assets/cohort/core4-sprites.png','../index.html','../manifest.webmanifest','style.css','runtime-heroes.js','data.js','engine.js','app.js','audio-score.js','audio-map.js','audio-synth.js','audio.js','official-music.js','mobile.js','music.js','net-quality.js','match-api.js','local-rooms.js','p2p.js'])fingerprint.update(fs.readFileSync(path.join(root,'src',f)));fs.writeFileSync(path.join(root,'src/net-version.js'),`export const NET_VERSION='duel-${fingerprint.digest('hex').slice(0,20)}';\n`);
fs.cpSync(path.join(root,'src/hero-packs'),path.join(pub,'src/hero-packs'),{recursive:true});
for(const f of ['index.html','manifest.webmanifest'])fs.copyFileSync(path.join(root,f),path.join(pub,f));for(const f of ['net-version.js','cohort-data.js','cohort-combat.js','cohort-render.js','pack-dispatcher.js','pack-services.js','pack-hp.js','pack-control.js','pack-targeting.js','pack-runtime.js','registry-data.js','catalog-data.js','rules-version.js','hero-registry.js','hero-catalog.js','compatibility.js','runtime-heroes.js','data.js','engine.js','app.js','style.css','audio-score.js','audio-map.js','audio-synth.js','audio.js','official-music.js','mobile.js','music.js','net-quality.js','match-api.js','local-rooms.js','p2p.js'])fs.copyFileSync(path.join(root,'src',f),path.join(pub,'src',f));
for(const f of fs.readdirSync(path.join(root,'assets'))){if(f.endsWith('-render.png')||f==='audio')continue;const p=path.join(root,'assets',f);if(fs.statSync(p).isDirectory())fs.cpSync(p,path.join(pub,'assets',f),{recursive:true});else fs.copyFileSync(p,path.join(pub,'assets',f));}
let data=fs.readFileSync(path.join(root,'src/data.js'),'utf8');data=data.replaceAll(/assets\/[a-z_]+-render\.png/g,m=>m.replace('assets/','assets/portraits/').replace('-render.png','.webp'));fs.writeFileSync(path.join(pub,'src/data.js'),data);
const dataUri=(f)=>{const mime=f.endsWith('.mp3')?'audio/mpeg':f.endsWith('.webp')?'image/webp':'image/png';return `data:${mime};base64,${fs.readFileSync(path.join(root,f)).toString('base64')}`;};
const {code:js}=await bundleApp({offline:true});
let css=fs.readFileSync(path.join(root,'src/style.css'),'utf8').replace(/^@import[^\r\n]*(?:\r?\n|$)/,'');let html=fs.readFileSync(path.join(root,'index.html'),'utf8').replace('<link rel="stylesheet" href="src/style.css">','<style>'+css+'</style>').replace('<script type="module" src="src/app.js"></script>','<script type="module">'+js.replaceAll('</script','<\\/script')+'</script>');
html=html.replace('<link rel="manifest" href="manifest.webmanifest">','').replace('href="assets/app-icon-180.png"','href="'+dataUri('assets/app-icon-180.png')+'"');
fs.mkdirSync(path.join(root,'release'),{recursive:true});fs.writeFileSync(path.join(root,'release/DOTA_DUEL_1V1_候选版.html'),html);console.log(JSON.stringify({build:'passed',standaloneBytes:Buffer.byteLength(html),dist}));


fs.copyFileSync(path.join(root,'_headers'),path.join(pub,'_headers'));
