import {createReleasedHeroRegistry} from './released-hero-rules.js';
import {HEROS22_BUILD} from './release-profile.js';
import {DEFAULT_PICKS,storedHeroPicks,directoryHeroId,directoryRuntimeHero} from './release-selection.js';
import {drawPackWorld,drawPackFighter,packSkillUI} from './pack-render.js';
import {createRemoteSnapshotValidator} from './remote-snapshot.js';
import {drawCohortWorld,drawCohortFighter,validCohortSnapshot} from './cohort-render.js';
import {ACTIVE_ROSTER,isActiveHero,validHeroPair,runtimeHeroId,lookupRuntimeHero} from './hero-registry.js';
import {heroCatalog,historicalHeroName} from './hero-catalog.js';
import {GAME_COMPATIBILITY,compatibleGame} from './compatibility.js';
import {VirtualStick,mobileViewport,portraitViewport,controlSlots,arenaViewport,toggleGameFullscreen,visualBounds,displayMode,protectBattleGestures,combatLabelLayout} from './mobile.js';
import {LocalRoomRegistry} from './local-rooms.js';
import {MatchAPI,MatchRecord,recordStatusText,matchRequestId} from './match-api.js';
import {ArcadeAudio} from './audio.js';
import {OfficialAlbumPlayer,OFFICIAL_ALBUM} from './official-music.js';
import {soundForLog} from './audio-map.js';
import {PeerSession} from './p2p.js';
import {DEFAULT_NET_POLICY,validPolicy} from './net-quality.js';
import {DATA} from './data.js';
import {runtimeHeroes} from './runtime-heroes.js';
import {Engine,FIXED_DT,formatCombatNumber} from './engine.js';
const $=s=>document.querySelector(s),app=$('#app'),esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const playableHero=id=>lookupRuntimeHero(runtimeHeroes,id);
const activeHeroes=Object.freeze(ACTIVE_ROSTER.heroIds.map(playableHero));
const selectionHeroes=HEROS22_BUILD?runtimeHeroes:activeHeroes;
const releasedHeroRules=HEROS22_BUILD?createReleasedHeroRegistry():undefined;
const state={screen:'select',mode:mobileViewport(window)?'p2p':'local',myHero:DEFAULT_PICKS[0],picks:[...DEFAULT_PICKS],picking:0,skillHero:DEFAULT_PICKS[0],skill:0,sound:true,room:null,assetsReady:false};const deviceService=new MatchAPI(),localRooms=new LocalRoomRegistry();let activeRecord=null;let engine=null,modal=null,canvas=null,ctx=null,remoteSnapshot=null,lastPhase='',lastLogFrame=0,toastTimer;const input=[{},{}],pendingInput=[{},{}],images=new Map();
// Keep devices and pointers independent; queue short presses until simulation consumes them.
const inputSources=[new Map(),new Map()],touchResetters=new Set(),padLatch=[{armed:true,up:false},{armed:true,up:false}];
function sourceInput(i,id,values,queue=true){values={...values};for(const key of ['heavy','dash','guard'])delete values[key];for(let slot=0;slot<4;slot++)if(playableHero(state.picks[i])?.abilities[slot]?.mvp.passive)delete values['s'+slot];const before=input[i];if(Object.values(values).some(Boolean))inputSources[i].set(id,values);else inputSources[i].delete(id);const next={};for(const v of inputSources[i].values())for(const [k,on]of Object.entries(v))if(on)next[k]=true;input[i]=Object.fromEntries(Object.keys({...before,...next}).map(k=>[k,!!next[k]]));if(queue)for(const [k,on]of Object.entries(next))if(on&&!before[k])pendingInput[i][k]=true;}
function sampledInput(i){return {...input[i],...pendingInput[i]};}let atlas=null;
try{state.sound=JSON.parse(localStorage.getItem('dota-duel-sound')||'true');const p=JSON.parse(localStorage.getItem('dota-duel-picks')||'null');state.picks=storedHeroPicks(p);}catch{}
state.myHero=state.picks[0];
const music=new ArcadeAudio({storage:localStorage,internalMusic:false,contextFactory:()=>new (window.AudioContext||window.webkitAudioContext)(),onchange:()=>refreshMusicStatus()});state.sound=music.settings.sfxEnabled;
const officialMusic=new OfficialAlbumPlayer({document,onchange:()=>refreshOfficialStatus()});officialMusic.configure(music.settings.musicEnabled,music.settings.musicVolume);
window.addEventListener('pointerdown',()=>{if(!music.unlocked||music.ctx?.state!=='running')music.unlock();officialMusic.unlock();});window.addEventListener('keydown',()=>{if(!music.unlocked||music.ctx?.state!=='running')music.unlock();officialMusic.unlock();});document.addEventListener('visibilitychange',()=>{music.lifecycle({hidden:document.hidden});officialMusic.lifecycle({hidden:document.hidden});});window.addEventListener('pagehide',()=>{music.lifecycle({pageAway:true});officialMusic.lifecycle({pageAway:true});});window.addEventListener('pageshow',()=>{music.lifecycle({pageAway:false});officialMusic.lifecycle({pageAway:false});});
function img(src){if(!src)return null;if(!images.has(src)){const im=new Image();im.src=src;images.set(src,im);}return images.get(src);}
activeHeroes.forEach(h=>{img(h.portrait);img(h.render);h.abilities.forEach(a=>img(a.icon));});img('assets/arena.png');
fetch('assets/atlas.json').then(r=>r.ok?r.json():null).then(a=>{atlas=a;if(a?.sheets)Object.values(a.sheets).forEach(s=>img(s));}).catch(()=>{});
function toast(t){const el=$('#toast');clearTimeout(toastTimer);el.hidden=false;el.textContent=t;el.classList.add('visible');toastTimer=setTimeout(()=>{el.classList.remove('visible');el.hidden=true;el.textContent='';},2800);}
function sound(kind){if(state.sound)music.playEffect(kind);}
function head(){return `<header class="mast"><div><div class="brand">DOTA <span>DUEL</span></div><div class="version">1V1 ARCADE · FAN EDITION 1.0 RC</div></div><nav class="nav"><button class="quiet" data-action="manual">操作说明</button><button class="quiet" data-action="codex">英雄档案</button><button class="quiet" data-action="records">战绩</button><button class="quiet" data-action="music">音乐 / 音量</button><button class="quiet" data-action="sound">${state.sound?'音效 开':'音效 关'}</button><button class="quiet" data-action="fullscreen" aria-label="全屏或添加到主屏幕">⛶ 全屏 / 主屏幕</button></nav></header>`;}
function heroCard(player){if(player===1&&['room','p2p'].includes(state.mode)&&!state.room)return `<article class="fighter-card opponent-card"><div class="label">OPPONENT</div><div class="opponent-placeholder">VS</div><div class="info"><h2>等待对手</h2><p>进入房间后确认英雄</p></div></article>`;const h=playableHero(state.picks[player]);return `<article class="fighter-card p${player+1} ${state.picking===player?'current':''}"><img src="${h.portrait}" alt="${esc(h.name)}"><div class="label">${['room','p2p'].includes(state.mode)?'我的英雄':state.mode==='cpu'?(player?'电脑对手':'我的英雄'):(player?'PLAYER 02 · DIRE':'PLAYER 01 · RADIANT')}</div><div class="info"><div class="en">${h.en}</div><h2>${h.name}</h2><p>${h.role}</p><div class="smallskills">${h.abilities.map((a,s)=>`<button data-detail="${state.picks[player]},${s}" title="${a.name}">${a.icon?`<img src="${a.icon}" alt="${a.name}">`:s+1}<small>${a.mvp.passive?'被':(player&&!['room','p2p'].includes(state.mode)?['U','I','O','P']:['Q','E','R','T'])[s]}</small></button>`).join('')}</div></div><button class="pick-player" data-player="${player}" aria-label="为玩家${player+1}选英雄"></button></article>`;}
function selection(){state.picks=storedHeroPicks(state.picks);if(!isActiveHero(state.myHero))state.myHero=state.picks[0];const draftSingle=['room','p2p'].includes(state.mode)&&!state.room;if(['room','p2p'].includes(state.mode)&&!state.room){state.picks[0]=state.myHero;state.picking=0;}finishRecord('cancelled');music.setScene('menu');officialMusic.setScene('menu');state.screen='select';engine=null;remoteSnapshot=null;modal=null;release();app.innerHTML=`<div class="shell">${head()}<div class="selection-title"><div><div class="eyebrow">CHOOSE YOUR FIGHTER</div><h1>一人一英雄，一战定胜负</h1></div><p>${activeHeroes.length} 位已开放${HEROS22_BUILD?` · ${selectionHeroes.length-activeHeroes.length} 位未发布`:""} · 三局两胜 · 99 秒回合</p></div><div class="mode-tabs" aria-label="玩法"><button class="mode ${state.mode!=='cpu'?'active':''}" data-playmode="pvp"><strong>对战</strong><small>与真人较量</small></button><button class="mode ${state.mode==='cpu'?'active':''}" data-playmode="pve"><strong>人机</strong><small>与电脑练习</small></button></div>${state.mode==='cpu'?'':`<div class="connection-options" aria-label="对战方式"><span>对战方式</span>${(mobileViewport(window)?[['p2p','联网对战']]:[['local','同屏双人'],['room','同浏览器双窗口'],['p2p','联网对战']]).map(([m,n])=>`<button class="quiet ${state.mode===m?'active':''}" data-mode="${m}">${n}</button>`).join('')}</div>`}<div class="selection">${heroCard(0)}<div class="roster-box"><div class="choose-label"><strong>${['room','p2p'].includes(state.mode)?'选择我的英雄':state.mode==='cpu'?(state.picking?'选择电脑英雄':'选择我的英雄'):'正在为 P'+(state.picking+1)+' 选择英雄'}</strong><span>${draftSingle?'创建或加入都使用此英雄':'点击左右人物卡切换玩家'}</span></div><div class="roster">${selectionHeroes.map(h=>{const i=directoryHeroId(h),enabled=isActiveHero(i);return `<button class="hero ${enabled?"":"unreleased"} ${state.picks[0]===i?'picked1':''} ${!draftSingle&&state.picks[1]===i?'picked2':''}" data-hero="${i}" ${enabled?"":'disabled aria-disabled="true" title="未发布 · 四技能尚未全部验收 · 暂停适配"'} aria-label="${enabled?"选择":"未发布"}${h.name}"><img src="${h.portrait}" alt=""><span>${h.name}</span>${enabled?"":'<small class="release-status">未发布 · 暂停适配</small>'}${(draftSingle?state.picks[0]===i:state.picks.includes(i))?`<b class="tag">${draftSingle?'已选':(state.picks[0]===i?'P1':'')+(state.picks[1]===i?' P2':'')}</b>`:''}</button>`;}).join('')}</div><div class="draft-help">${['room','p2p'].includes(state.mode)?'创建或加入房间，都会使用你选中的英雄':'双方可以选择相同英雄 · 被动自动生效，无需按键'}</div></div>${heroCard(1)}</div><div class="bottom-bar"><div class="rules"><strong>P1</strong>　A / D 移动 · W 跳跃 · F 攻击 · Q E R T 技能<br>${state.mode==='local'?'<strong>P2</strong>　← / → 移动 · ↑ 跳跃 · J 攻击 · U I O P 技能':'后方向防御 · 后下蹲防 · F 攻击'}</div><button class="button primary launch" data-action="start">${['room','p2p'].includes(state.mode)?'创建 / 加入房间':'进入竞技场'}</button></div><footer class="fineprint"><span>非官方 Dota 同人游戏 · 四槽竞技场适配 · 无装备、无登录、无付费数值</span><button data-action="about">官网数据与格斗改编说明</button></footer></div>`;bind();syncViewport();refreshDisplayButtons();}
function bind(){app.querySelectorAll('[data-playmode]').forEach(b=>b.onclick=()=>{if(state.room)leaveRoom();state.mode=b.dataset.playmode==='pve'?'cpu':mobileViewport(window)?'p2p':'local';selection();sound('select');});app.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));app.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{if(state.room)leaveRoom();state.mode=b.dataset.mode;selection();sound('select');});app.querySelectorAll('[data-player]').forEach(b=>b.onclick=()=>{if(['room','p2p'].includes(state.mode)&&+b.dataset.player===1)return;state.picking=+b.dataset.player;selection();});app.querySelectorAll('[data-hero]').forEach(b=>b.onclick=()=>{if(!isActiveHero(+b.dataset.hero))return;state.picks[state.picking]=+b.dataset.hero;if(state.picking===0)state.myHero=+b.dataset.hero;try{localStorage.setItem('dota-duel-picks',JSON.stringify(state.picks));}catch{}selection();sound('select');});app.querySelectorAll('[data-detail]').forEach(b=>b.onclick=e=>{e.stopPropagation();const [h,s]=b.dataset.detail.split(',').map(Number);skillDialog(h,s);});}
function overlay(html,cls=''){modal=document.createElement('div');modal.className='overlay';modal.innerHTML=`<section class="panel ${cls}" role="dialog" aria-modal="true"><button class="quiet close" data-action="close" aria-label="关闭">✕</button>${html}</section>`;app.appendChild(modal);modal.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>action(b.dataset.action));modal.querySelector('.close')?.focus();}
function close(){if(state.screen==='battle'&&portraitViewport(window))return;if(state.screen==='battle'&&state.room?.peerPortrait){pause('等待对方恢复横屏');return;}const ended=engine||remoteSnapshot;if(state.screen==='battle'&&ended?.phase==='matchEnd'){closeOnly();result(ended,true);return;}if(state.screen==='select')++roomOperation;if(p2pSession&&state.screen==='battle'&&!p2pSession.connected){toast('连接已中断，请重新建房');return;}if(modal){modal.remove();modal=null;}if(state.room&&state.screen==='select')leaveRoom();if(state.screen==='battle'&&(!state.room||state.room.connected)){if(engine)engine.paused=false;if(state.room)sendRoom({type:'pause',value:false});}release();}
function manual(){if(engine)engine.paused=true;overlay(`<div class="eyebrow">HOW TO PLAY</div><h2>方向、攻击、四个技能</h2><div class="manual-grid"><div><h3 style="color:var(--p1)">P1 · 天辉</h3><div class="keys"><kbd>A</kbd> <kbd>D</kbd> 移动　<kbd>W</kbd> 跳跃　<kbd>S</kbd> 下蹲<br><kbd>F</kbd> 攻击 / 按住连击<br><kbd>Q</kbd> <kbd>E</kbd> <kbd>R</kbd> <kbd>T</kbd> 四个技能</div></div><div><h3 style="color:var(--p2)">P2 · 夜魇</h3><div class="keys"><kbd>←</kbd> <kbd>→</kbd> 移动　<kbd>↑</kbd> 跳跃　<kbd>↓</kbd> 下蹲<br><kbd>J</kbd> 攻击 / 按住连击<br><kbd>U</kbd> <kbd>I</kbd> <kbd>O</kbd> <kbd>P</kbd> 四个技能</div></div></div><p>后方向始终是远离对手的一侧：地面按后方向会后退兼防御，后下方向为原地蹲防；换边后立即跟随双方位置判断。正下和前下只下蹲，不防御。上或斜上起跳，跳跃保留起跳时的水平惯性。</p><p>不区分高、低段格挡；只在地面、防守方向正确且未攻击、施法、蓄力或处于硬直时防御。可格挡命中减少80%伤害，守势耗尽会破防；持续伤害和标注不可格挡的技能不受此减伤。没有独立重击、冲刺或格挡按钮。</p><p>手机横屏：左手拖动摇杆，右手一个攻击键和四个技能。被动自动生效；引导技能按住，蓄力技能按住后松开。指向地面技能默认瞄准对手施法时的位置。标准手柄：左摇杆 / 十字键移动、后方向防御，向上或 A 跳跃，X 攻击；肩键和扳机对应四个技能。摇杆回到中立后才能再次上推跳跃。</p><div class="notice">联网房间双方使用自己的 P1 键位或触控。桌面同屏可用两套键位或两个手柄。同浏览器双窗口仅支持当前设备、当前浏览器；跨设备使用 P2P，双方连接检查通过并准备后开战。</div><button class="button primary" data-action="close">准备好了</button>`);}
function skillDialog(hi=state.picks[state.picking],slot=0){if(engine)engine.paused=true;closeOnly();state.skillHero=hi;state.skill=slot;let h=directoryRuntimeHero(runtimeHeroes,hi),a=h.abilities[slot],m=a.mvp,o=a.official;overlay(`<div class="eyebrow">HERO ARCHIVE · ${h.en}</div><h2>${h.name} · ${a.name}</h2><div class="skillnav">${h.abilities.map((s,i)=>`<button class="${i===slot?'active':''}" data-slot="${i}">${s.icon?`<img src="${s.icon}" alt="">`:''}${s.name}${s.mvp.passive?' · 被动':''}</button>`).join('')}</div><div class="metrics"><div class="metric"><b>${m.passive?'被动':m.cooldown_s+'s'}</b><span>官网满级冷却</span></div><div class="metric"><b>${m.mana}</b><span>法力消耗</span></div><div class="metric"><b>${h.renderAspect&&!o?.damage&&!m.damage?'见说明':o?.damage??m.damage}</b><span>${esc(({per_second:'每秒伤害',instant:'单次基础伤害',none:'无直接伤害',crit:'暴击',on_attack_bonus:'普攻附加伤害',per_trigger:'触发伤害',per_ward_attack:'每次守卫伤害',total_over_knockback:'总持续伤害',per_explosion:'每次爆炸伤害',initial_plus_periodic:'初始伤害',full_charge_instant:'满蓄力伤害',attack_plus_bonus:'普攻额外伤害',instant_global:'全场伤害'}[o?.damage_semantics])||'官网伤害基值')}</span></div><div class="metric"><b>${o?.duration_s||'—'}</b><span>官网持续秒数</span></div></div><p>${esc(a.descriptionZh||m.mechanics)}</p><div class="notice">${esc(m.arenaNote||'伤害、冷却和耗蓝采用官网满级基础技能。二维射程、格挡、生命与连招规则为本作改编。')}</div><details><summary>查看官方数值与来源</summary><div class="ref">${o?Object.entries(o.semantic||{}).map(([k,v])=>`<div><b>${esc(k)}</b> ${esc(v)}</div>`).join(''):Object.entries(a.original).map(([k,v])=>`<div><b>${k}</b> ${esc(v)}</div>`).join('')}</div><p><a href="${h.officialUrl||h.sources?.[0]||'https://www.dota2.com/heroes'}" target="_blank" rel="noopener">Dota 2 官网 · ${h.name}</a> · <a href="${o?.source||h.sources?.[0]||'https://www.dota2.com/heroes'}" target="_blank" rel="noopener">官方技能数据快照来源</a></p></details>`);modal.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>skillDialog(hi,+b.dataset.slot));}
function closeOnly(){if(modal){modal.remove();modal=null;}}
function about(){if(engine)engine.paused=true;overlay(`<div class="eyebrow">FAN GAME · RULESET 1.0</div><h2>同样的英雄，二维格斗规则</h2><p>20位英雄和80个基础技能来自原交互原型。技能名称、主动 / 被动分类、伤害类型、伤害基值、冷却、耗蓝和持续时间以2026年9月30日读取的 Dota 2 官方数据为准。官网动态数据没有补丁标签，不能视作完整7.41f客户端复刻。</p><p>本作是独立同人2D格斗改编：角色生命与法力、移动速度和普攻使用竞技场配置；1个Dota距离单位映射0.55竞技场单位；加上跳跃、普攻、后方向防御、99秒回合与三局两胜。连续硬控最长1.5秒，脱控后有1秒控制保护。</p><p>保留主要技能机制与引导打断、弹体、充能、开关、被动和公式伤害；地图没有小兵、树林或多人目标，不使用装备、天赋、神杖和命石系统。灵魂、墙体绑定和二维随机范围有明确格斗适配。各技能详情可查看本作实际参数与说明。</p><p>背景音乐为《Dota 2 Reborn D+B Remix》，收录于《The Dota 2 Remixes EP》，作者 Valve Studio Orchestra。这是混音版。人物图像与技能图标原始素材属于 Valve；额外2D角色与场景为AI生成同人美术。此作品与 Valve、Dota 2 或拳皇官方没有关联，无商用授权声明。</p><div class="notice">游戏本身不要求账号。私有托管页面可能需要拥有者的站点访问身份；下载的离线HTML可以直接双击使用同屏模式。</div><button class="button primary" data-action="close">知道了</button>`);}
function battleHTML(){const [h,e]=state.picks.map(i=>playableHero(i)),slots=controlSlots(state.mode,state.room,mobileViewport(window));return `<section class="battle-screen"><div class="arena-wrap"><canvas id="arena" width="1280" height="720" aria-label="DOTA双人格斗竞技场"></canvas><div class="hud">${hud(h,0)}<div class="timer"><small id="roundtext">ROUND 1</small><strong id="clock">99</strong><small>FIRST TO TWO</small></div>${hud(e,1)}</div><div class="battle-meta">${state.mode==='training'?'TRAINING · 无限练习':state.mode==='cpu'?'ARCADE · 人机对决':state.mode==='p2p'?'P2P · WebRTC直连':state.mode==='room'?'LOCAL ROOM · 双窗口真实同步':'LOCAL VERSUS · 同屏真人对战'}</div><div class="battle-tools"><button data-action="music" aria-label="音乐与音量">♫</button><button data-action="sound" aria-label="音效">${state.sound?'♪':'♩'}</button><button data-action="fullscreen" aria-label="全屏">⛶</button><button data-action="pause" aria-label="暂停">Ⅱ</button></div><div class="battle-center" id="announce"></div><div class="controls ${slots.length===1?'single':'dual'}">${slots.map(i=>controls(playableHero(state.picks[i]),i)).join('')}</div></div></section>`;}
function hud(h,i){return `<div class="hud-fighter ${i?'right':''}"><img class="hud-portrait" src="${h.portrait}" alt="${h.name}"><div class="hud-bars"><div class="hud-name"><b>${h.name}</b><small>${state.mode==='cpu'&&i===1?'CPU':state.room?(state.room.player===i?'YOU':'RIVAL'):'P'+(i+1)}</small></div><div class="bar"><i id="hp${i}"></i><span id="hpt${i}"></span></div><div class="mana"><i id="mp${i}"></i></div><div class="guardbar"><i id="gd${i}"></i></div><div class="rounds" id="wins${i}">◇◇</div></div></div>`;}
function controls(h,i){const keys=i&&!state.room?['U','I','O','P']:['Q','E','R','T'];return `<div class="controlside ${i?'right':''}" data-side="${i}"><div class="joystick" data-stick="${i}" role="group" aria-label="P${i+1}拖动摇杆：左右移动，上推跳跃，后推防御、后下蹲防"><span class="stick-base"></span><span class="stick-cap"></span><span class="stick-caption">移动 / 跳跃 / 后防</span></div><div class="action-cluster"><button class="attack-main" data-playerinput="${i}" data-input="attack" aria-label="P${i+1}普通攻击"><span>攻击</span><small>按住连击</small></button>${h.abilities.map((a,j)=>`<button class="skill-button skill-orbit orbit-${j} ${a.mvp.passive?'passive':''}" data-playerinput="${i}" data-input="s${j}" data-skill="${i},${j}" ${a.mvp.passive?'disabled':''} aria-label="P${i+1}${a.name}${a.mvp.passive?'（被动，自动生效）':''}">${a.icon?`<img src="${a.icon}" alt="">`:''}<span class="key">${a.mvp.passive?'被动':keys[j]}</span><span class="name">${a.name}</span><span class="cooldown" style="display:none"></span></button>`).join('')}</div></div>`;}

function start(opts={}){if(!validHeroPair([opts.p1??state.picks[0],opts.p2??state.picks[1]]))throw Error('英雄尚未开放');if(portraitViewport(window)&&!state.room){syncViewport();return null;}finishRecord('cancelled');closeOnly();state.mode=opts.mode||state.mode;if(state.room&&!['room','p2p'].includes(state.mode))leaveRoom();state.picks=[opts.p1??state.picks[0],opts.p2??state.picks[1]];state.screen='battle';music.resetMatch();music.setScene('battle');officialMusic.setScene('battle');engine=new Engine(runtimeHeroes,state.picks,{heroRuleRegistry:releasedHeroRules,simulationRoster:ACTIVE_ROSTER,mode:['room','p2p'].includes(state.mode)?'local':state.mode});remoteSnapshot=null;lastLogFrame=0;lastPhase='';release();roomSounds=[];qaFrames.length=0;qaLast=0;app.innerHTML=battleHTML();canvas=$('#arena');ctx=canvas.getContext('2d');bind();bindTouch();if(state.room)app.querySelectorAll('[data-playerinput]').forEach(b=>{if(+b.dataset.playerinput!==state.room.player)b.disabled=true;});beginRecord(opts);syncViewport({matchStart:true});if(opts.pauseForOrientation||state.room?.peerPortrait){if(engine)engine.paused=true;sendRoom({type:'pause',value:true,orientation:portraitViewport(window)});if(!portraitViewport(window))pause('屏幕方向已变化，准备好后继续');}sound('start');return engine;}
function bindTouch(){touchResetters.clear();protectBattleGestures(app.querySelector('.battle-screen'),()=>state.screen==='battle'&&!modal&&!portraitViewport(window));
 app.querySelectorAll('[data-input]').forEach(b=>{const player=+b.dataset.playerinput,k=b.dataset.input;let pointer=null,source='',current={};
 const clear=(cancel=false)=>{const captured=pointer;pointer=null;try{if(captured!==null&&b.hasPointerCapture?.(captured))b.releasePointerCapture(captured);}catch{}const keys=Object.keys(current);if(source)sourceInput(player,source,{},false);if(cancel)for(const key of keys)if(!input[player][key])delete pendingInput[player][key];pointer=null;source='';current={};b.classList.remove('pressed');};
 b.addEventListener('pointerdown',e=>{if(pointer!==null||b.disabled||modal||portraitViewport(window)||state.room&&player!==state.room.player)return;e.preventDefault();pointer=e.pointerId;source='touch:'+pointer;try{b.setPointerCapture(pointer);}catch{clear(true);return;}current={[k]:true};sourceInput(player,source,current);b.classList.add('pressed');});
 const up=e=>{if(e.pointerId===pointer)clear(e.type!=='pointerup');};for(const event of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(event,up);touchResetters.add(()=>clear(true));
 });
 app.querySelectorAll('[data-stick]').forEach(pad=>{const player=+pad.dataset.stick,stick=new VirtualStick(),cap=pad.querySelector('.stick-cap');let pointer=null,source='',rect=null,current={};
 const paint=v=>{cap.style.transform=`translate(${v.x}px,${v.y}px)`;};
 const move=e=>{if(e.pointerId!==pointer)return;e.preventDefault();const unit=(pad.offsetWidth||rect.width)/rect.width,v=stick.update((e.clientX-rect.left-rect.width/2)*unit,(e.clientY-rect.top-rect.height/2)*unit,rect.width*.31*unit);current=v.input;sourceInput(player,source,current);paint(v);};
 const clear=()=>{const captured=pointer;pointer=null;try{if(captured!==null&&pad.hasPointerCapture?.(captured))pad.releasePointerCapture(captured);}catch{}if(source)sourceInput(player,source,{},false);for(const key of Object.keys(current))if(!input[player][key])delete pendingInput[player][key];pointer=null;source='';current={};paint(stick.reset());pad.classList.remove('active');};
 pad.addEventListener('pointerdown',e=>{if(pointer!==null||modal||portraitViewport(window)||state.room&&player!==state.room.player)return;e.preventDefault();pointer=e.pointerId;source='stick:'+pointer;rect=pad.getBoundingClientRect();try{pad.setPointerCapture(pointer);}catch{clear();return;}stick.reset();pad.classList.add('active');move(e);});pad.addEventListener('pointermove',move);
 for(const event of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(event,e=>{if(e.pointerId===pointer)clear();});touchResetters.add(clear);
 });
}
const keymaps=[{KeyA:'left',KeyD:'right',KeyW:'jump',KeyS:'down',KeyF:'attack',KeyQ:'s0',KeyE:'s1',KeyR:'s2',KeyT:'s3'},{ArrowLeft:'left',ArrowRight:'right',ArrowUp:'jump',ArrowDown:'down',KeyJ:'attack',KeyU:'s0',KeyI:'s1',KeyO:'s2',KeyP:'s3'}];
window.addEventListener('keydown',e=>{if(state.screen!=='battle'||e.target?.tagName==='INPUT')return;if(e.code==='Escape'){e.preventDefault();if(!e.repeat)modal?close():pause();return;}if(modal||portraitViewport(window)||e.repeat)return;for(let i=0;i<2;i++){const k=keymaps[i][e.code];if(k){e.preventDefault();if((state.room||state.mode==='cpu')&&i===1)continue;sourceInput(state.room?state.room.player:i,'key:'+e.code,{[k]:true});}}});
window.addEventListener('keyup',e=>{for(let i=0;i<2;i++){if(keymaps[i][e.code]){if((state.room||state.mode==='cpu')&&i===1)continue;sourceInput(state.room?state.room.player:i,'key:'+e.code,{},false);}}});
function release(requireNeutral=null){for(const clear of touchResetters)clear();for(const sources of inputSources)sources.clear();for(const p of padLatch){if(requireNeutral!==null)p.blocked=requireNeutral;p.armed=!p.blocked;p.up=false;}input[0]={};input[1]={};pendingInput[0]={};pendingInput[1]={};roomGuestPending={};if(engine){engine.cancelInput(0);engine.cancelInput(1);}if(state.room?.role==='guest')sendRoom({type:'input',input:{},release:true});}
window.addEventListener('blur',()=>{release(true);if(engine&&!state.room&&state.screen==='battle'&&!modal)pause('窗口失去焦点，已自动暂停');});document.addEventListener('visibilitychange',()=>{if(document.hidden){release(true);if(engine&&!state.room&&state.screen==='battle'&&!modal)pause('切回此窗口后继续战斗');}});
function gamepads(){const pads=navigator.getGamepads?.()||[];for(let i=0;i<2;i++){if((state.room||state.mode==='cpu')&&i>0)continue;const pi=state.room?state.room.player:i,p=pads[i],latch=padLatch[pi];if(!p||document.hidden||modal||portraitViewport(window)){if(inputSources[pi].has('pad')){sourceInput(pi,'pad',{},false);latch.blocked=true;latch.up=false;}continue;}const b=n=>!!p.buttons[n]?.pressed,x=p.axes[0]||0,y=p.axes[1]||0,neutral=Math.abs(x)<.2&&Math.abs(y)<.2&&![0,2,4,5,6,7,12,13,14,15].some(b);if(neutral){latch.armed=true;latch.blocked=false;}if(latch.blocked)continue;const up=y<-.5||b(12);if(up&&!latch.up){latch.up=latch.armed;latch.armed=false;}else if(!up)latch.up=false;const g={left:x<-.3||b(14),right:x>.3||b(15),up,jump:b(0)||latch.up,down:y>.5||b(13),attack:b(2),s0:b(4),s1:b(5),s2:b(6),s3:b(7)};if(Object.values(g).some(Boolean)||inputSources[pi].has('pad'))sourceInput(pi,'pad',g,false);}}
function pause(reason='暂停'){release(true);if(state.room){sendRoom({type:'pause',value:true});if(engine)engine.paused=true;}else if(engine)engine.paused=true;closeOnly();overlay(`<div class="eyebrow">TIME OUT</div><h2>${reason}</h2><p>当前回合已冻结，双方状态保留</p><div class="room-actions"><button class="button primary" data-action="resume">继续对战</button><button class="button" data-action="manual">操作说明</button>${state.mode==='training'?'<button class="button" data-action="reset">重置训练</button>':''}<button class="button" data-action="quit">退出并重新选人</button></div>`,'pausepanel');}
function result(g,force=false){if(lastPhase==='shownResult'&&!force)return;const first=lastPhase!=='shownResult';finishRecord('',g);lastPhase='shownResult';const winner=g.score[0]>=2?0:1;closeOnly();overlay(`<header class="result-summary"><div class="result-heroes">${state.picks.map(i=>`<img src="${playableHero(i).portrait}" alt="${playableHero(i).name}">`).join('')}</div><div class="result-heading"><div class="eyebrow">对局结束 · 三局两胜</div><h2>P${winner+1} · ${playableHero(state.picks[winner]).name} 获胜</h2></div><strong class="result-score">${g.score[0]} : ${g.score[1]}</strong></header><div class="result-details" tabindex="0" aria-label="回合与保存详情，可滚动"><div class="result-stats"><span>${g.history.length} 个回合</span><span>P1最高 ${g.fighters[0].maxCombo} 连击</span><span>P2最高 ${g.fighters[1].maxCombo} 连击</span></div><p id="record-status" role="status"></p></div><footer class="result-footer"><div class="result-save-row"><span id="record-summary" role="status"></span><button class="button" data-action="retryRecord" hidden>重试保存</button></div><div class="result-actions"><button class="button primary" data-action="rematch">再战一场</button><button class="button" data-action="quit">返回选人</button></div></footer>`,'result-panel');modal.querySelector('.close')?.remove();modal.querySelector('[data-action="rematch"]')?.focus();refreshRecordStatus();if(first)sound('victory');}
function action(a){if(portraitViewport(window)&&['start','resume','rematch','p2pReady','p2pStart','roomStart'].includes(a)){syncViewport();return;}if(a==='records'){recordsDialog();return;}if(a==='retryRecord'){activeRecord?.submit();return;}if(a==='music'){audioDialog();return;}if(a==='p2pCreate'){createP2P();return;}if(a==='p2pJoin'){joinP2P();return;}if(a==='p2pReady'){p2pSession?.setReady(!p2pSession.ready);return;}if(a==='p2pStart'){p2pSession?.start();return;}if(a==='p2pRetry'){leaveRoom();selection();p2pDialog();return;}if(a==='manual'){closeOnly();manual();}else if(a==='codex')skillDialog();else if(a==='about')about();else if(a==='close')close();else if(a==='start'){if(state.mode==='p2p')p2pDialog();else if(state.mode==='room')roomDialog();else start();}else if(a==='pause')pause();else if(a==='resume'){if(state.room?.peerPortrait)return toast('等待对方恢复横屏');if(state.room&&!state.room.connected)return toast('等待另一位玩家恢复连接');close();if(state.room)sendRoom({type:'pause',value:false});if(engine)engine.paused=false;}else if(a==='quit'){leaveRoom();selection();}else if(a==='reset'){engine?.resetRound();engine?.start();close();}else if(a==='rematch'){if(state.room){sendRoom({type:'rematch'});if(state.room.role==='host')startRoomMatch();else toast('已向房主请求再战');}else start();}else if(a==='sound'){state.sound=!state.sound;music.configure({sfxEnabled:state.sound});try{localStorage.setItem('dota-duel-sound',JSON.stringify(state.sound));}catch{}toast(state.sound?'音效已开启':'音效已关闭');if(state.screen==='select')selection();else app.querySelectorAll('[data-action="sound"]').forEach(b=>b.textContent=state.sound?'♪':'♩');sound('select');}else if(a==='fullscreen'){requestGameDisplay();}else if(a==='install'){installDialog();}else if(a==='installPrompt'){promptInstall();}else if(a==='roomCreate')createRoom();else if(a==='roomJoin')joinRoom();else if(a==='roomStart')startRoomMatch();}
function roomDialog(){if(!('BroadcastChannel'in window)||location.protocol==='file:'){toast('双窗口模式需要同源网站与可用的本机存储；离线文件支持同屏双人');return;}overlay(`<div class="eyebrow">TWO WINDOWS · ONE BROWSER</div><h2>双窗口真实对战</h2><p>在同一个浏览器中打开两份本网站，拖成两个独立窗口。没有游戏账号、没有模拟对手。两个窗口要使用相同的网站地址。键盘只控制当前聚焦的窗口；两人同时用键盘请选同屏双人。房号10分钟有效，每分钟最多10次加入尝试；异常关闭窗口后席位最多约20秒释放；它仅用于本机协调，不是强身份认证。</p><div class="room-actions"><button class="button primary" data-action="roomCreate">创建房间</button></div><p>或者输入朋友窗口显示的六位房号</p><input id="roomInput" class="room-input" maxlength="6" placeholder="房间号" aria-label="六位房间号"><div class="room-actions"><button class="button" data-action="roomJoin">加入房间</button></div><div class="notice">仅同一浏览器的两个窗口，不支持不同电脑。双方在自己的窗口使用 P1 键位；触控使用各自一侧。</div>`);}
let channel=null,roomTimer=null,lastHeartbeat=0,lastInputAt=0,roomGuestInput={},roomGuestPending={},roomSounds=[],tabId=crypto.randomUUID(),roomOperation=0;function sendRoom(v){if(v.type==='hello'&&state.room?.role==='guest')state.room.requestedHero=v.hero;if(p2pSession){p2pSession.sendGame(v);return;}channel?.postMessage({...v,compatibility:GAME_COMPATIBILITY,sender:tabId});}
function connect(code,role,reservation=null){leaveRoom();channel=new BroadcastChannel(reservation?'dota-duel-v2-'+reservation.id:'dota-duel-v1-'+code);state.room={code,role,reservation,player:role==='host'?0:1,connected:false,peer:null};lastHeartbeat=performance.now();channel.onmessage=ev=>handleRoomMessage(ev.data);roomTimer=setInterval(()=>{if(!state.room)return;sendRoom({type:'ping'});if(state.room.reservation&&state.room.role==='guest')localRooms.renew(state.room.code,state.room.reservation.id,tabId).catch(()=>{});if(performance.now()-lastHeartbeat>6000&&state.room.connected){state.room.connected=false;state.room.peer=null;roomGuestInput={};roomGuestPending={};if(engine){engine.paused=true;engine.setInput(1,{});}finishRecord('disconnect');toast('对方窗口失去连接，已返回房间');if(state.screen==='battle')selection();roomWaiting();}if(!state.room.connected&&role==='guest')sendRoom({type:'hello',hero:state.picks[1],reservationId:state.room?.reservation?.id||null});},1000);}
async function handleRoomMessage(m){if(!m||typeof m!=='object'||m.sender===tabId)return;const r=state.room;if(!r)return;if(r.transport!=='p2p'&&!compatibleGame(m.compatibility)){if(m.type==='hello')sendRoom({type:'incompatible',target:m.sender});if(m.type==='welcome'||m.type==='incompatible'&&m.target===tabId){leaveRoom();toast('双方游戏版本或可玩英雄名单不一致，请刷新');}return;}if(m.sender===r.peer)lastHeartbeat=performance.now();
 if(m.type==='hello'&&r.role==='host'){if(!isActiveHero(m.hero))return;if(r.reservation){if(m.reservationId!==r.reservation.id)return;try{if(!await localRooms.verifyGuest(r.code,r.reservation.id,m.sender)||state.room!==r)return;}catch{return;}}if(r.peer&&r.peer!==m.sender){sendRoom({type:'full',target:m.sender});return;}r.peer=m.sender;r.connected=true;lastHeartbeat=performance.now();state.picks[1]=m.hero;sendRoom({type:'welcome',target:m.sender,picks:state.picks});roomWaiting();}
 if(m.type==='welcome'&&r.role==='guest'&&m.target===tabId){if(!validHeroPair(m.picks)||m.picks[1]!==r.requestedHero)return;r.connected=true;r.peer=m.sender;lastHeartbeat=performance.now();state.picks=m.picks;roomWaiting();}
 if(m.type==='full'&&m.target===tabId){leaveRoom();closeOnly();toast('房间已有两位玩家');roomDialog();}
 if(m.type==='input'&&r.role==='host'&&m.sender===r.peer){roomGuestInput=Object.fromEntries(['left','right','up','jump','down','attack','s0','s1','s2','s3'].filter(k=>m.input?.[k]===true).map(k=>[k,true]));if(m.release){roomGuestPending={};engine?.cancelInput(1);}else for(const [k,v] of Object.entries(roomGuestInput))if(v)roomGuestPending[k]=true;lastInputAt=performance.now();}
 if(m.type==='start'&&m.sender===r.peer){if(!validHeroPair(m.picks)||JSON.stringify(m.picks)!==JSON.stringify(state.picks))return;if(r.role==='guest'){r.recordEpoch=m.recordEpoch;start({mode:'room',p1:m.picks[0],p2:m.picks[1],recordEpoch:m.recordEpoch});engine=null;}}
 if(m.type==='recordStatus'&&r.transport!=='p2p'&&r.role==='guest'&&m.sender===r.peer&&m.record?.localId===r.recordEpoch)activeRecord?.observeHost(m.record);
 if(m.type==='snapshot'&&r.role==='guest'&&m.sender===r.peer){if(!validRemoteSnapshot(m.snapshot)||JSON.stringify(m.snapshot.indices)!==JSON.stringify(state.picks))return;remoteSnapshot=m.snapshot;if(state.screen!=='battle'){start({mode:'room',p1:m.snapshot.indices[0],p2:m.snapshot.indices[1],recordEpoch:r.recordEpoch});engine=null;}for(const packet of Array.isArray(m.sounds)?m.sounds.slice(0,64):[])sound(packet);updateHUD(remoteSnapshot);}
 if(m.type==='ping'&&m.sender===r.peer)sendRoom({type:'pong'});
 if(m.type==='pause'&&m.sender===r.peer){if(typeof m.orientation==='boolean')r.peerPortrait=m.orientation;if(!m.value&&r.peerPortrait)return;if(engine)engine.paused=m.value||portraitViewport(window);if(!m.value)closeOnly();else if(!modal&&state.screen==='battle')pausePeer();}
 if(m.type==='p2pLobby'&&p2pSession){p2pLobby();return;}if(m.type==='rematch'&&r.role==='host'&&m.sender===r.peer)startRoomMatch();
 if(m.type==='leave'&&m.sender===r.peer){finishRecord('disconnect');if(engine){engine.paused=true;engine.setInput(1,{});}roomGuestInput={};roomGuestPending={};r.connected=false;r.peer=null;toast('另一位玩家离开了房间');if(state.screen==='battle'){selection();}roomWaiting();}
 }
async function createRoom(){if(!validHeroPair(state.picks)||!isActiveHero(state.myHero))return toast('英雄尚未开放');state.mode='room';const operation=++roomOperation;try{const reservation=await localRooms.reserve(tabId);if(operation!==roomOperation||state.mode!=='room'){await localRooms.release(reservation.code,reservation.id,tabId);return;}connect(reservation.code,'host',reservation);roomWaiting();}catch(e){toast(e.message);}}
async function joinRoom(){if(!validHeroPair(state.picks)||!isActiveHero(state.myHero))return toast('英雄尚未开放');state.mode='room';const code=$('#roomInput')?.value.trim(),operation=++roomOperation;try{const reservation=await localRooms.claim(code,tabId);if(operation!==roomOperation||state.mode!=='room'){await localRooms.release(reservation.code,reservation.id,tabId);return;}state.picks[1]=state.myHero;connect(code,'guest',reservation);sendRoom({type:'hello',hero:state.picks[1],reservationId:reservation.id});roomWaiting();}catch(e){toast(e.message);}}
function roomWaiting(){if(p2pSession){renderP2PLobby();return;}if(state.screen==='battle')return;closeOnly();const r=state.room;if(!r)return;overlay(`<div class="eyebrow">${r.role==='host'?'HOST · P1':'GUEST · P2'}</div><h2>${r.connected?'两位玩家已连接':'等待另一位玩家'}</h2><div class="room-code">${r.code}</div><p style="text-align:center">${r.connected?playableHero(state.picks[0]).name+'　VS　'+playableHero(state.picks[1]).name:'在本浏览器另一窗口输入上面的房号'}</p><div class="notice">双方都使用自己窗口的 P1 键位。请把两个窗口并排显示，避免后台标签页限速。</div><div class="room-actions">${r.role==='host'?`<button class="button primary" data-action="roomStart" ${r.connected?'':'disabled'}>双方开战</button>`:'<span>等待房主开始</span>'}<button class="button" data-action="quit">离开房间</button></div>`,'pausepanel');}
function startRoomMatch(){if(!validHeroPair(state.picks))return toast('英雄尚未开放');if(p2pSession){p2pRematch();return;}if(!state.room?.connected)return toast('等待另一位玩家连接');const recordEpoch=matchRequestId();state.room.recordEpoch=recordEpoch;sendRoom({type:'start',picks:state.picks,recordEpoch});start({mode:'room',recordEpoch});}
function pausePeer(){overlay('<h2>对方暂停了比赛</h2><p>双方状态已保留</p><button class="button primary" data-action="resume">继续</button>','pausepanel');}
function leaveRoom(){++roomOperation;finishRecord('left');const r=state.room;if(r?.reservation)localRooms.release(r.code,r.reservation.id,tabId).catch(()=>{});const oldPeer=p2pSession;p2pSession=null;oldPeer?.close();if(channel){sendRoom({type:'leave'});channel.close();channel=null;}clearInterval(roomTimer);roomTimer=null;state.room=null;roomGuestInput={};roomGuestPending={};roomSounds=[];}
window.addEventListener('beforeunload',()=>sendRoom({type:'leave'}));
function updateHUD(g){if(!g||!$('#clock'))return;g.fighters.forEach((f,i)=>{$('#hp'+i).style.width=f.hp/f.maxHp*100+'%';$('#hpt'+i).textContent=Math.ceil(f.hp)+' / '+Math.ceil(f.maxHp);$('#mp'+i).style.width=f.mp/f.maxMp*100+'%';$('#gd'+i).style.width=f.guardMeter+'%';$('#wins'+i).textContent='◆'.repeat(g.score[i])+'◇'.repeat(Math.max(0,2-g.score[i]));app.querySelectorAll(`[data-skill^="${i},"]`).forEach(b=>{let slot=+b.dataset.skill.split(',')[1],a=playableHero(state.picks[i]).abilities[slot],m=a.mvp,c=f.cd[slot],ui=packSkillUI(f,a,g);const empty=m.charges&&f.charges?.[slot]<=0;const text=ui.chargeWait>0?Math.ceil(ui.chargeWait):empty?Math.ceil(f.chargeTimers[slot]):c>.05?Math.ceil(c):f.mp<m.mana?'MP':null;if(m.charges)b.querySelector('.key').textContent='×'+f.charges[slot];if(ui.charges!==null)b.querySelector('.key').textContent='×'+ui.charges;if(ui.toggle!==null)b.querySelector('.key').textContent=ui.toggle?'开启':'开关';if(ui.armed)b.querySelector('.key').textContent='已装填';if(m.toggle)b.querySelector('.key').textContent=f.buffs.some(x=>x.key===playableHero(state.picks[i]).abilities[slot].id||(m.effect==='aura'&&x.key==='aura'))?'开启':'开关';b.querySelector('.cooldown').style.display=text?'flex':'none';b.querySelector('.cooldown').textContent=text||'';b.style.opacity=f.mp<m.mana&&!m.passive?'.55':'1';});});$('#clock').textContent=state.mode==='training'?'∞':Math.ceil(g.time);$('#roundtext').textContent='ROUND '+g.round;
 let big='',sub='';if(g.phase==='intro'){big=g.phaseTime>1.1?'ROUND '+g.round:'READY';sub=playableHero(state.picks[0]).name+'  VS  '+playableHero(state.picks[1]).name;}if(g.phase==='roundEnd'){big=g.winner===-1?'DRAW':'K.O.';sub=g.winner===-1?'平局，再战一回合':`P${g.winner+1} 拿下本回合　${g.score[0]} : ${g.score[1]}`;}$('#announce').innerHTML=big?`<div class="big">${big}</div><div class="sub">${sub}</div>`:'';
 if(g.phase==='matchEnd')result(g);
}
function draw(g,now){if(!ctx||!g)return;const c=ctx;c.setTransform(1,0,0,1,0,0);const box=canvas.getBoundingClientRect?.(),vw=canvas.clientWidth||box?.width||1280,vh=canvas.clientHeight||box?.height||720,dpr=Math.min(2,window.devicePixelRatio||1),view=arenaViewport(vw,vh,viewportSafe,mobileViewport(window)?154:170);if(canvas.width!==Math.round(vw*dpr)||canvas.height!==Math.round(vh*dpr)){canvas.width=Math.round(vw*dpr);canvas.height=Math.round(vh*dpr);}c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,vw,vh);c.save();if(g.shake)c.translate(Math.sin(now*.083)*g.shake,Math.cos(now*.13)*g.shake*.5);const bg=img('assets/arena.png');if(bg?.complete&&bg.naturalWidth){const cover=Math.max(vw/1280,view.ground/505,(vh-view.ground)/215);c.drawImage(bg,(vw-1280*cover)/2,view.ground-505*cover,1280*cover,720*cover);}else{const grad=c.createLinearGradient(0,0,0,720);grad.addColorStop(0,'#111e2e');grad.addColorStop(.7,'#344b53');grad.addColorStop(1,'#0c1720');c.fillStyle=grad;c.fillRect(0,0,vw,vh);}
 const shade=c.createLinearGradient(0,0,0,720);shade.addColorStop(0,'#0007');shade.addColorStop(.4,'#0000');shade.addColorStop(.75,'#07152115');shade.addColorStop(1,'#000a');c.fillStyle=shade;c.fillRect(0,0,vw,vh);c.translate(view.x,view.y);c.scale(view.scale,view.scale);c.strokeStyle='#cebd9730';c.beginPath();c.moveTo(25,505);c.lineTo(1255,505);c.stroke();
 drawCohortWorld(c,g,now);drawPackWorld(c,g,now,playableHero);for(const z of g.zones)if(!['ward','deathWard'].includes(z.type))drawZone(c,z,g);
 [...g.fighters].sort((a,b)=>a.y-b.y).forEach(f=>drawFighter(c,f,g,now));for(const z of g.zones)if(['ward','deathWard'].includes(z.type))drawZone(c,z,g);
 for(const p of g.projectiles){const color=playableHero(g.indices[p.owner]).color;c.save();c.translate(p.x+40,505-p.y);c.scale(p.dir,1);c.shadowColor=color;c.shadowBlur=20;c.fillStyle=color;c.beginPath();c.ellipse(0,0,Math.min(p.r+12,60),Math.min(p.r*.55+5,32),0,0,Math.PI*2);c.fill();c.strokeStyle='#fff2c7';c.lineWidth=3;c.beginPath();c.moveTo(-45,0);c.lineTo(15,0);c.stroke();if(p.id==='pudge_hook'){c.strokeStyle='#b7a17a';c.lineWidth=3;c.setLineDash([8,5]);c.beginPath();c.moveTo(0,0);const f=g.fighters[p.owner];c.lineTo((f.x-p.x)*p.dir,0);c.stroke();}c.restore();}
 for(const e of g.effects)if(e.type!=='text')drawEffect(c,e);
 c.restore();const labels=g.effects.filter(e=>e.type==='text').map(e=>({...e,text:/^[+-]?\d+(?:\.\d+)?$/.test(String(e.text))?(String(e.text).startsWith('+')?'+':'')+formatCombatNumber(Number(e.text)):e.text}));for(const f of g.fighters)if(f.comboTime>0&&f.combo>=2)labels.push({x:f.x,y:f.y+220,text:f.combo+' HITS',color:f.i?'#ffb29f':'#b6eeff',life:1,maxLife:1});
 for(const label of combatLabelLayout(labels,view,vw,vh,viewportSafe)){c.save();c.globalAlpha=label.alpha;c.font=`700 ${label.font}px Rajdhani,sans-serif`;c.textAlign='center';c.lineWidth=3;c.strokeStyle='#071018';c.strokeText(label.text,label.x,label.y);c.fillStyle=label.color;c.fillText(label.text,label.x,label.y);c.restore();}}
function drawFighter(c,f,g,now){const h=playableHero(g.indices[f.i]),x=f.x+40,y=505-f.y;const pulse=Math.sin(now*.004+f.i)*2;const active=f.animation,walking=active==='walk';const pose=f.y>15?3:['attack','heavy','cast'].includes(active)?1:['hurt'].includes(active)||f.guard?2:0;let im=null,frame=null;
 if(atlas?.heroes?.[h.id]){const data=atlas.heroes[h.id];frame=data.frames[pose]||data.frames[0];im=img(data.sheet||atlas.sheets[data.sheetId]);}if(!im?.complete||!im.naturalWidth){im=img(h.render||h.portrait);frame=null;}
 c.save();c.fillStyle='#03080ba0';c.beginPath();c.ellipse(x,508,58*(1-f.y/600),11,0,0,Math.PI*2);c.fill();c.translate(x,y);c.scale(f.dir,f.crouching?.72:1);const moon=!f.pack?.revealed&&f.buffs.some(b=>b.key==='mirana_moonlight'&&!(b.reveal>0));if(moon)c.globalAlpha=.48;if(f.invuln>0){c.shadowColor=h.color;c.shadowBlur=30;}if(f.hitFlash>0){c.filter='brightness(2.2) saturate(.3)';}const lean=['attack','heavy','cast'].includes(active)?.07:walking?.03*Math.sin(now*.02):0;c.rotate(lean);const squash=walking?1+Math.sin(now*.017)*.018:1;const wide=['pudge','tidehunter','earthshaker','mirana','storm_spirit'].includes(h.id);let w=wide?260:210,hh=wide?220:232;if(active==='heavy'){w*=1.08;hh*=1.025;}c.scale(1,squash);if(im?.complete&&im.naturalWidth){if(frame){const [sx,sy,sw,sh,px,py]=frame;const ref=atlas.heroes[h.id].referenceHeight;const scale=hh/ref;w=sw*scale;c.drawImage(im,sx,sy,sw,sh,-px*scale,-py*scale+pulse,sw*scale,sh*scale);}else{if(h.renderAspect){w=hh*h.renderAspect;if(w>350){w=350;hh=w/h.renderAspect;}if(['attack','cast'].includes(active))c.translate(15,0);if(active==='hurt')c.rotate(-.08);if(f.y>15)c.rotate(-.06);}c.drawImage(im,-w/2,-hh+pulse,w,hh);}}c.filter='none';c.globalAlpha=1;
 if(f.guard){c.strokeStyle='#9addf5';c.shadowColor='#79d4ff';c.shadowBlur=16;c.lineWidth=4;c.beginPath();c.ellipse(35,-90,45,82,0,-1.3,1.3);c.stroke();}
 if(f.buffs.length){c.strokeStyle=h.color;c.globalAlpha=.6;c.lineWidth=3;c.beginPath();c.ellipse(0,-5,65,12,0,0,Math.PI*2);c.stroke();c.globalAlpha=1;}
 c.restore();drawCohortFighter(c,f);let labels=drawPackFighter(c,f,g,h.color).labels;if(f.pack?.poison.length)labels.push('毒×'+f.pack.poison.length);if(f.pack?.statuses.some(s=>s.key==='viper_strike'))labels.push('破被动');if(f.stun>0)labels.push('眩晕');if(f.hex>0)labels.push('妖术');if(f.root>0)labels.push('禁锢');if(f.silence>0)labels.push('沉默');if(f.fear>0)labels.push('恐惧');if(f.taunt>0)labels.push('嘲讽');if(f.ccGrace>0)labels.push('控制保护');if(f.channel)labels.push('引导中');if(labels.length){c.textAlign='center';c.font='bold 15px sans-serif';c.fillStyle='#fff1bd';c.fillText([...new Set(labels)].join(' · '),x,y-248);}if(f.chargeSlot>=0){c.fillStyle='#0d1823';c.fillRect(x-45,y-255,90,7);c.fillStyle='#ecd89b';c.fillRect(x-45,y-255,90*f.charge,7);}}
function drawZone(c,z,g){const color=playableHero(g.indices[z.owner]).color,x=z.x+40;c.save();c.strokeStyle=color;c.fillStyle=color;c.shadowColor=color;c.shadowBlur=15;c.globalAlpha=.28;if(z.type==='wall'){c.fillRect(x-15,505-z.height,30,z.height);c.globalAlpha=.8;c.strokeRect(x-15,505-z.height,30,z.height);}else if(['ward','deathWard'].includes(z.type)){const icon=img(playableHero(g.indices[z.owner]).abilities[z.type==='ward'?1:3]?.icon);if(icon?.complete&&icon.naturalWidth){c.globalAlpha=1;c.drawImage(icon,x-23,443,46,46);}c.globalAlpha=1;c.fillStyle=z.type==='ward'?'#91f4b1':'#d5b0ff';c.fillRect(x-23,435,46*Math.max(0,z.life/z.m.duration_s),4);c.strokeStyle=c.fillStyle;c.lineWidth=2;c.beginPath();c.ellipse(x,498,29,9,0,0,Math.PI*2);c.stroke();c.globalAlpha=.18;c.beginPath();c.ellipse(x,503,z.m.radius_wu,28,0,0,Math.PI*2);c.fill();}else{const r=z.type==='expanding'?Math.min(z.m.radius_wu,z.age*z.m.wave_speed_wu_s):z.m.radius_wu||65;c.beginPath();c.ellipse(x,500,r,Math.min(50,r*.16),0,0,Math.PI*2);c.fill();c.globalAlpha=.7;c.lineWidth=3;c.stroke();if(z.type==='trap'){c.globalAlpha=.5;c.beginPath();c.arc(x,450,28+Math.sin(z.age*6)*4,0,Math.PI*2);c.stroke();}}c.restore();}
function drawEffect(c,e){c.save();const x=e.x+40,y=505-e.y,progress=1-e.life/(e.maxLife||.5);c.globalAlpha=Math.min(1,e.life/(e.maxLife||.5));c.fillStyle=e.color;c.strokeStyle=e.color;c.shadowColor=e.color;c.shadowBlur=18;c.lineWidth=3;if(e.type==='text'){c.font='bold 25px Rajdhani,sans-serif';c.textAlign='center';c.fillText(e.text,x,y-progress*45);}else if(e.type==='announce'){c.font='bold 80px Rajdhani,sans-serif';c.textAlign='center';c.fillText(e.text,640,310);}else if(e.type==='beam'){c.lineWidth=10;c.beginPath();c.moveTo(x,y);c.lineTo(e.tx+40,505-e.ty);c.stroke();c.strokeStyle='#fff';c.lineWidth=2;c.stroke();}else if(e.type==='pillar'){c.fillStyle=e.color;c.globalAlpha*=.6;const gr=c.createLinearGradient(0,505,0,210);gr.addColorStop(0,e.color);gr.addColorStop(1,'transparent');c.fillStyle=gr;c.fillRect(x-e.size,210,e.size*2,295);}else if(e.type==='slash'){c.translate(x,y);c.scale(e.dir||1,1);c.rotate(-.4+progress*1.4);c.lineWidth=10*(1-progress)+1;c.beginPath();c.arc(0,0,e.size||80,-1.3,.65);c.stroke();}else if(e.type==='hit'){const size=(e.size||38)*(1+progress);for(let k=0;k<8;k++){const a=k*Math.PI/4+progress;c.beginPath();c.moveTo(x+Math.cos(a)*12,y+Math.sin(a)*12);c.lineTo(x+Math.cos(a)*size,y+Math.sin(a)*size);c.stroke();}}else{const size=(e.size||50)*(e.type==='warning'?1:progress+.3);c.beginPath();c.ellipse(x,e.type==='warning'?503:y,size,e.type==='warning'?17:size*.6,0,0,Math.PI*2);c.stroke();}c.restore();}
let lastTime=performance.now(),accum=0,lastSync=0,lastHUD=0;
const qaEnabled=location.search?.includes('qa=1'),qaFrames=[];let qaLast=0,qaMeter=null;
function measureFrame(now){if(!qaEnabled||document.hidden||state.screen!=='battle'){qaLast=0;return;}if(qaLast)qaFrames.push(now-qaLast);qaLast=now;if(qaFrames.length>600)qaFrames.shift();if(qaFrames.length&&qaFrames.length%60===0){if(!qaMeter){qaMeter=document.createElement('output');qaMeter.id='qa-metrics';qaMeter.style.cssText='position:fixed;top:0;left:0;z-index:99;background:#071019e8;color:#fff;padding:4px;font:11px monospace;pointer-events:none';document.body.appendChild(qaMeter);}const sorted=[...qaFrames].sort((a,b)=>a-b),mean=sorted.reduce((a,b)=>a+b,0)/sorted.length;qaMeter.textContent=JSON.stringify({samples:sorted.length,fps:+(1000/mean).toFixed(1),meanMs:+mean.toFixed(2),p95Ms:+sorted[Math.floor(sorted.length*.95)].toFixed(2),audio:music.status().context});}}
function loop(now){measureFrame(now);let dt=Math.min(.12,(now-lastTime)/1000);lastTime=now;if(state.screen==='battle'){if(portraitViewport(window)&&engine)engine.paused=true;gamepads();if(engine){if(state.room?.role==='host'){if(now-lastInputAt>350){roomGuestInput={};roomGuestPending={};}engine.setInput(0,sampledInput(0));engine.setInput(1,{...roomGuestInput,...roomGuestPending});}else{engine.setInput(0,sampledInput(0));if(state.mode!=='cpu')engine.setInput(1,sampledInput(1));}accum+=dt;let safety=0,consumedInput=false;while(accum>=FIXED_DT&&safety++<8){if(!engine.paused&&engine.phase==='fight'&&engine.hitstop<=0)consumedInput=true;engine.step();accum-=FIXED_DT;}if(consumedInput){pendingInput[0]={};pendingInput[1]={};roomGuestPending={};}for(const log of engine.logs.filter(l=>l.logId>lastLogFrame)){const key=soundForLog(log,engine.hero(log.player===1?1:0));if(key){const packet={id:String(log.logId),key,player:log.player};sound(packet);if(state.room?.role==='host')roomSounds.push(packet);}}lastLogFrame=engine.logSeq;
 if(state.room?.role==='host'&&now-lastSync>33){sendRoom({type:'snapshot',snapshot:engine.snapshot(),sounds:roomSounds.splice(0)});lastSync=now;}
 }else if(state.room?.role==='guest'&&now-lastSync>25){sendRoom({type:'input',input:sampledInput(1)});pendingInput[1]={};lastSync=now;}
 const g=engine||remoteSnapshot;if(g){draw(g,now);if(now-lastHUD>50){updateHUD(g);lastHUD=now;}}}requestAnimationFrame(loop);}requestAnimationFrame(loop);
let p2pSession=null;
function officialStatusText(){const s=officialMusic.status();return s.error||({disabled:'音乐已关闭',missing:'官方音乐文件尚未接入',ready:'点击播放音乐',starting:'正在播放…',playing:'官方原声 · 循环播放',buffering:'音乐缓冲中…',paused:'音乐已暂停，点击播放继续',stopped:'音乐已停止',blocked:'点击播放以开启音乐'}[s.state]||'音乐暂不可用');}
function refreshOfficialStatus(){refreshMusicStatus();}
function refreshMusicStatus(){const n=$('#music-status');if(n)n.textContent=officialStatusText();}
let pendingInstall=null;
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();pendingInstall=e;});window.addEventListener('appinstalled',()=>{pendingInstall=null;toast('已添加，可从主屏幕打开 DOTA DUEL');refreshDisplayButtons();});
function refreshDisplayButtons(){const mode=displayMode(document,window);app.querySelectorAll('[data-action="fullscreen"]').forEach(b=>{b.setAttribute?.('aria-pressed',String(mode!=='browser'));b.setAttribute?.('aria-label',mode==='fullscreen'?'退出全屏':mode==='standalone'?'已在主屏幕模式':'全屏或添加到主屏幕');});}
async function requestGameDisplay(){const result=await toggleGameFullscreen(document,window.screen,toast,window);syncViewport();refreshDisplayButtons();if(result.reason){if(portraitViewport(window)){const help=$('#orientation-install-help');if(help)help.open=true;}else installDialog();}}
function installDialog(){if(engine)engine.paused=true;release(true);if(state.room)sendRoom({type:'pause',value:true});closeOnly();const mode=displayMode(document,window);overlay(`<h2>${mode==='standalone'?'已在主屏幕模式':'全屏与主屏幕游玩'}</h2><p>Safari 普通标签页不能由游戏强制隐藏地址栏和标签栏。添加到主屏幕后，请从新图标打开独立画面。</p><ol class="install-steps"><li>在 Safari 点“分享”按钮。</li><li>选择“添加到主屏幕”；若有“作为网页 App 打开”，保持开启。</li><li>点“添加”，再从主屏幕的 DOTA DUEL 图标进入并横屏。</li></ol><p>联网对战仍需要网络。主屏幕模式由浏览器支持决定，不是修改 Safari 设置。</p>${pendingInstall?'<button class="button primary" data-action="installPrompt">添加 DOTA DUEL</button>':''}<button class="button" data-action="close">返回游戏</button>`,'install-panel');}
async function promptInstall(){if(!pendingInstall)return;const prompt=pendingInstall;pendingInstall=null;try{await prompt.prompt();await prompt.userChoice;}catch{toast('未能添加，请通过浏览器菜单添加到主屏幕');}}
let viewportSafe={},wasPortrait=false,viewportLayout=null;
function syncViewport({matchStart=false}={}){
 const root=document.documentElement,computed=window.getComputedStyle?.(root);for(const k of ['left','right','top','bottom'])viewportSafe[k]=parseFloat(computed?.getPropertyValue('--safe-'+k))||0;
 const portrait=portraitViewport(window),gate=$('#orientation-gate');p2pSession?.setAvailable(!portrait);if(gate)gate.hidden=!portrait;app.inert=portrait;root.setAttribute?.('data-portrait',portrait?'true':'false');root.setAttribute?.('data-mobile',mobileViewport(window)?'true':'false');
 const v=visualBounds(window),moved=viewportLayout&&(Math.abs(v.scale-viewportLayout.scale)>.01||Math.abs(v.left-viewportLayout.left)>1||Math.abs(v.top-viewportLayout.top)>1);viewportLayout=v;for(const [key,value] of Object.entries({'view-height':v.height,'view-width':v.width,'view-left':v.left,'view-top':v.top,'game-width':v.gameWidth,'game-height':v.gameHeight}))root.style?.setProperty?.('--'+key,value+'px');root.style?.setProperty?.('--game-scale',String(1/v.scale));root.setAttribute?.('data-screen',state.screen);root.setAttribute?.('data-short-view',v.height<300?'true':'false');root.setAttribute?.('data-display-mode',displayMode(document,window));if(moved&&state.screen==='battle'){release(true);if(engine)engine.paused=true;if(state.room)sendRoom({type:'pause',value:true});if(!portrait&&!modal)pause('画面已适配当前缩放，确认后继续');}
 if(portrait&&state.screen==='battle'){release(true);if(engine)engine.paused=true;if((!wasPortrait||matchStart)&&state.room)sendRoom({type:'pause',value:true,orientation:true});}
 if(!portrait&&wasPortrait&&state.screen==='battle'){if(state.room)sendRoom({type:'pause',value:true,orientation:false});if(!modal)pause('已恢复横屏，准备好后继续');}wasPortrait=portrait;const area=app.querySelector('.controls');if(area&&state.screen==='battle'){const slots=controlSlots(state.mode,state.room,mobileViewport(window)),shown=[...app.querySelectorAll('[data-side]')].map(e=>+e.dataset.side);if(shown.length&&slots.join()!==shown.join()){release(true);area.className='controls '+(slots.length===1?'single':'dual');area.innerHTML=slots.map(i=>controls(playableHero(state.picks[i]),i)).join('');bindTouch();}}
}
window.addEventListener('resize',()=>{release(true);syncViewport();});window.visualViewport?.addEventListener('resize',()=>{release(true);syncViewport();});window.visualViewport?.addEventListener('scroll',()=>{release(true);syncViewport();});window.addEventListener('orientationchange',()=>{release(true);syncViewport();});
$('#orientation-fullscreen')?.addEventListener('click',requestGameDisplay);for(const name of ['fullscreenchange','webkitfullscreenchange'])document.addEventListener(name,()=>{release(true);syncViewport();refreshDisplayButtons();});
syncViewport();
function requestOfficialPlay(){music.configure({musicEnabled:true});officialMusic.configure(true,music.settings.musicVolume);if(officialMusic.state==='error')officialMusic.retry();else if(!officialMusic.intent)officialMusic.play();}
function setOfficialVolume(value){music.configure({musicVolume:value});officialMusic.setVolume(music.settings.musicVolume);}
function audioDialog(){if(engine)engine.paused=true;if(state.room)sendRoom({type:'pause',value:true});release();closeOnly();const a=music.settings;overlay(`<div class="eyebrow">AUDIO</div><h2>音乐与音量</h2><p id="music-status" role="status"></p><div class="audio-grid"><label><input id="music-enabled" type="checkbox" ${a.musicEnabled?'checked':''}> 背景音乐</label><label>音乐音量 <input id="music-volume" aria-label="音乐音量" type="range" min="0" max="100" value="${Math.round(a.musicVolume*100)}"></label><label><input id="sfx-enabled" type="checkbox" ${a.sfxEnabled?'checked':''}> 游戏音效</label><label>音效音量 <input id="sfx-volume" aria-label="音效音量" type="range" min="0" max="100" value="${Math.round(a.sfxVolume*100)}"></label></div><div class="room-actions"><button id="music-play" class="button" ${OFFICIAL_ALBUM.src?'':'disabled'}>播放音乐</button><button id="music-stop" class="button">暂停音乐</button></div><p>${esc(OFFICIAL_ALBUM.title)} · ${esc(OFFICIAL_ALBUM.artist)}。菜单与对局连续播放同一首混音。</p><p>音乐开启后循环播放。切到后台会暂停，返回后可在这里继续。</p>`);refreshMusicStatus();$('#music-enabled').onchange=e=>{music.configure({musicEnabled:e.target.checked});officialMusic.configure(e.target.checked,music.settings.musicVolume);};$('#music-volume').oninput=e=>setOfficialVolume(+e.target.value/100);$('#sfx-enabled').onchange=e=>{state.sound=e.target.checked;music.configure({sfxEnabled:state.sound});};$('#sfx-volume').oninput=e=>music.configure({sfxVolume:+e.target.value/100});$('#music-play').onclick=()=>{requestOfficialPlay();$('#music-enabled').checked=true;};$('#music-stop').onclick=()=>officialMusic.stop();}


function beginRecord(opts){activeRecord=null;if(state.mode==='training')return;const observer=state.mode==='room'&&state.room?.role==='guest',transport=state.mode==='room'?'broadcastchannel':state.mode==='p2p'?'webrtc':'local';const record=new MatchRecord({mode:state.mode==='cpu'?'pve':'pvp',transport,heroes:state.picks,localId:opts.recordEpoch||null,observer,match:opts.match||null,service:observer?null:opts.service||deviceService,storage:localStorage,onchange:()=>{if(activeRecord===record)refreshRecordStatus();const r=state.room;if(r?.role==='host'&&r.transport!=='p2p'&&r.recordEpoch===record.localId)sendRoom({type:'recordStatus',record:record.view()});}});activeRecord=record;if(observer){record.status='awaiting_report';return;}if(state.mode==='cpu')record.beginPVE();else if(['local','room'].includes(state.mode))record.beginLocal();}
function finishRecord(reason='',game=engine?.snapshot?.()||remoteSnapshot){if(activeRecord&&game&&!activeRecord.payload)activeRecord.finish(game,reason);}
function refreshRecordStatus(){const r=activeRecord?.view(),out=$('#record-status');if(out&&r)out.textContent=recordStatusText(r.status)+(r.error?' · '+r.error:'');const summary=$('#record-summary');if(summary)summary.textContent=r?recordStatusText(r.status):'本地对局';const retry=app.querySelector('[data-action="retryRecord"]');if(retry){const canRetry=!!activeRecord&&!activeRecord.observer&&!!activeRecord.payload&&!!activeRecord.service&&['error','local'].includes(activeRecord.status);retry.hidden=!canRetry;retry.disabled=!canRetry;}}
function recordsDialog(){if(engine)engine.paused=true;release(true);closeOnly();let rows=[];try{rows=JSON.parse(localStorage.getItem('dota-duel-history')||'[]');}catch{}overlay(`<h2>对战记录</h2><p>对战与人机分开记录。此列表保留本浏览器最近200局；只有“战绩已保存”表示服务器已接收。中止或有争议的比赛不计胜负。</p><div class="record-list">${rows.length?rows.map(r=>`<article><strong>${r.mode==='pve'?'人机':'对战'} · ${esc(historicalHeroName(r,0))} vs ${esc(historicalHeroName(r,1))}</strong><p>${esc(r.result?.score?.join(' : ')||'—')} · ${Math.round((r.durationMs||0)/1000)}秒 · ${esc(recordStatusText(r.status))}</p><small>${esc(r.version)} · ${esc(new Date(r.startedAt).toLocaleString())}</small></article>`).join(''):'<p>尚无已结束的比赛。</p>'}</div>`);}
window.addEventListener('pagehide',()=>{finishRecord('left');const r=state.room;if(r?.reservation)localRooms.release(r.code,r.reservation.id,tabId).catch(()=>{});});
window.addEventListener('storage',e=>{if(e.key!=='dota-duel-history'||!activeRecord?.observer)return;try{const row=JSON.parse(e.newValue||'[]').find(v=>v.localId===activeRecord.localId);if(row)activeRecord.observeHost(row);}catch{}});

function p2pDialog(){if(location.protocol==='file:'){toast('P2P信令需要托管网址；离线文件可同屏对战');return;}closeOnly();overlay(`<div class="eyebrow">PEER TO PEER</div><h2>跨设备 P2P 对战</h2><p>两台设备打开同一网址，房主把六位数字口令告知对手。无需游戏账号；双方通过连接检查和战绩服务确认后开战。</p><div class="net-rule"><label>RTT 禁战方向<select id="net-direction" aria-label="RTT禁战方向"><option value="">请选择规则</option><option value="above">高于阈值禁止开战</option><option value="below">低于阈值禁止开战</option></select></label><label>阈值（毫秒）<input id="net-rtt" aria-label="RTT阈值毫秒" type="number" min="1" max="2000" placeholder="等待确认"></label></div><p>使用最近30次探测的P95 RTT；至少24次完成。双方还需满足抖动≤30ms、探测丢包≤5%，并各自点击准备。</p><button class="button primary" data-action="p2pCreate">创建 P2P 房间</button><hr><label>加入房间<input id="p2p-code" aria-label="六位数字对局口令" maxlength="6" inputmode="numeric" pattern="[0-9]{6}" placeholder="六位数字口令"></label><button class="button" data-action="p2pJoin">加入 P2P 房间</button><div class="notice">先尝试 WebRTC 直连，使用 Cloudflare STUN 查找公网地址。未配置 TURN；某些网络会连接失败，可重试或换网络。战斗数据不经过信令服务器。</div>`);}
function newP2P(role,policy){if(!isActiveHero(state.myHero))throw Error('英雄尚未开放');leaveRoom();state.room={transport:'p2p',role,player:role==='host'?0:1,code:'',connected:false,peer:'p2p-peer'};const hero=state.myHero;state.picks[role==='host'?0:1]=hero;const session=new PeerSession({role,hero,policy,available:!portraitViewport(window),onstate:x=>{if(p2pSession!==session)return;state.room.code=x.code;state.room.connected=x.connected&&!!x.version;state.room.peerPortrait=x.peerAvailable===false;if(state.room.peerPortrait&&state.screen==='battle'){release(true);if(engine)engine.paused=true;if(!modal)pausePeer();}if(isActiveHero(x.hero))state.picks[role==='host'?1:0]=x.hero;if(state.screen==='select')renderP2PLobby();},onmessage:m=>{if(!['input','snapshot','pause','rematch','p2pLobby'].includes(m.type))return;if(m.type==='input'){if(role!=='host'||!m.input||typeof m.input!=='object')return;const allowed=['left','right','up','jump','down','attack','s0','s1','s2','s3'];m.input=Object.fromEntries(allowed.filter(k=>m.input[k]===true).map(k=>[k,true]));}if(m.type==='snapshot'&&(role!=='guest'||!validRemoteSnapshot(m.snapshot)))return;handleRoomMessage(m);},onstart:({picks,match,service,pauseForOrientation})=>{start({mode:'p2p',p1:picks[0],p2:picks[1],match,service,pauseForOrientation});if(role==='guest')engine=null;},onfault:reason=>{finishRecord('disconnect');release();roomGuestInput={};roomGuestPending={};if(engine)engine.paused=true;if(state.room)state.room.connected=false;if(state.screen==='battle'){closeOnly();overlay(`<h2>连接已暂停</h2><p>${esc(reason)}</p><button class="button primary" data-action="p2pRetry">重新连接</button><button class="button" data-action="quit">返回选人</button>`);}else renderP2PLobby();}});p2pSession=session;renderP2PLobby();return session;}
const validatePeerSnapshot=createRemoteSnapshotValidator(runtimeHeroes,{roster:ACTIVE_ROSTER,heroRuleRegistry:releasedHeroRules});
function validRemoteSnapshot(g){return validatePeerSnapshot(g);}
function createP2P(){const policy={...DEFAULT_NET_POLICY,direction:$('#net-direction')?.value,rttMs:Number($('#net-rtt')?.value)};if(!validPolicy(policy))return toast('请先明确选择RTT方向及1–2000毫秒阈值');newP2P('host',policy).create();}
function joinP2P(){const code=$('#p2p-code')?.value.trim();if(!/^\d{6}$/.test(code||''))return toast('请输入六位数字口令');newP2P('guest',null).join(code);}
function renderP2PLobby(){if(!p2pSession||state.screen==='battle')return;const x=p2pSession.info();if(!$('#p2p-status')){closeOnly();overlay(`<div class="eyebrow">WEBRTC · ${x.role==='host'?'P1':'P2'}</div><h2>P2P 房间</h2><div class="room-code" id="p2p-room-code"></div><p id="p2p-status" role="status"></p><p id="p2p-rule"></p><pre id="p2p-quality" class="net-quality"></pre><p id="p2p-ready-state"></p><div class="room-actions"><button class="button" data-action="p2pReady">准备</button>${x.role==='host'?'<button class="button primary" data-action="p2pStart">双方开战</button>':''}<button class="button" data-action="p2pRetry">重新连接</button><button class="button" data-action="quit">离开房间</button></div><small>房间最多等待2分钟。断线后重新建房；不会恢复未完成的旧回合。探测丢包为DataChannel应用层超时比例。</small>`);}
 $('#p2p-room-code').textContent=x.code||'正在建立…';$('#p2p-status').textContent=x.error||x.gate.reason;$('#p2p-rule').textContent=validPolicy(x.policy)?`P95 RTT ${x.policy.direction==='above'?'>':'<'} ${x.policy.rttMs}ms 禁战 · 抖动≤30ms · 探测丢包≤5%`:'等待房主规则';const fmt=q=>q?`样本 ${q.samples}/24　RTT P95 ${q.p95?.toFixed(1)??'—'}ms　抖动 ${q.jitter?.toFixed(1)??'—'}ms　丢包 ${q.loss?.toFixed(1)??'—'}%`:'尚未收到';$('#p2p-quality').textContent='本端 '+fmt(x.quality)+'\n对端 '+fmt(x.peerQuality);$('#p2p-ready-state').textContent=`自己 ${x.ready?'已准备':'未准备'} · 对方 ${x.peerReady?'已准备':'未准备'}`;const ready=app.querySelector('[data-action="p2pReady"]');ready.disabled=!x.gate.ok;ready.textContent=x.ready?'取消准备':'准备';const begin=app.querySelector('[data-action="p2pStart"]');if(begin)begin.disabled=!x.gate.ok||!x.ready||!x.peerReady;}
function p2pLobby(){p2pSession?.returnToLobby();selection();renderP2PLobby();}
function p2pRematch(){if(activeRecord&&!['confirmed','aborted','disputed'].includes(activeRecord.status))return toast('等待战绩确认；保存失败时请先重试');sendRoom({type:'p2pLobby'});p2pLobby();}

window.DUEL={heroes:activeHeroes,catalog:heroCatalog,roster:ACTIVE_ROSTER,compatibility:GAME_COMPATIBILITY,DATA,state,get musicStatus(){return {...music.status(),...officialMusic.status(),sfx:music.status()};},get record(){return activeRecord?.view()||null;},get viewport(){return {portrait:portraitViewport(window),mobile:mobileViewport(window),safe:{...viewportSafe}};},get backend(){return {base:deviceService.base,registry:deviceService.registryStatus};},get network(){return p2pSession?.info();},start,selection,get engine(){return engine;},setInput:(i,v)=>{input[i]=v;engine?.setInput(i,v);},get snapshot(){return(engine||remoteSnapshot)?.snapshot?.()||remoteSnapshot;},get room(){return state.room;},createRoom,joinRoom,roomDialog,release,render:()=>engine&&draw(engine,performance.now())};
selection();

if(location.hostname==='127.0.0.1'&&location.port==='4174'){deviceService.loadRegistry().then(r=>toast(r.status==='verified'?'候选后端注册表已核对':'候选后端注册表不可用，新名单未获批准')).catch(e=>toast('候选后端：'+e.message));}
