import {snapshotBAreas,validBAreas,restoreBAreas} from './hero-b-area-host.js';
import {bridgeBStatusPacks,bModuleAbility,bStatusPulse,snapshotBStatuses,validBStatuses,restoreBStatuses} from './hero-b-status-host.js';
import {withRuleManagedFrame} from './hero-rules-host.js';
import {observeChargePhase,observeChargeAdvance,cancelCharge,withChargeRelease} from './hero-legacy-charge-host.js';
import {nativeCaptureFacts,recordNativeDamageDebit,beginLinearDotIteration,endLinearDotIteration,observeLinearDotTargetPhase,withLinearDotPulse,observeLinearHitTargetPhase,observeLinearAdvance,withLinearContact} from './hero-legacy-linear-host.js';
import {PackTargeting} from './pack-targeting.js';
import {rulePeriodicInputPlan,rulePeriodicToggle,observeRulePeriodicBuff,beginRulePeriodicDots,endRulePeriodicDots,dispatchRulePeriodicDot,beginRulePeriodicAreas,endRulePeriodicAreas,dispatchRulePeriodicArea,rulePeriodicSnapshot,restoreRulePeriodicSnapshot,ruleChannelInputPlan,dispatchRuleChannelInterrupt,beginRuleChannels,endRuleChannels,dispatchRuleChannelAdvance,beginRuleChannelProjectiles,endRuleChannelProjectiles,observeRuleChannelProjectile,dispatchRuleChannelContact,beginRuleChannelUnits,endRuleChannelUnits,dispatchRuleChannelUnitAdvance,ruleChannelSnapshot,restoreRuleChannelSnapshot,ruleStatusDotInputPlan,beginRuleStatusDots,endRuleStatusDots,dispatchRuleStatusDotAdvance,ruleStatusDotSnapshot,restoreRuleStatusDotSnapshot,ruleUnitInputPlan,dispatchRuleUnitEnd,beginRuleUnits,endRuleUnits,dispatchRuleUnitAdvance,ruleUnitSnapshot,restoreRuleUnitSnapshot,ruleFieldInputPlan,ruleFieldToggle,observeRuleFieldBuff,dispatchRuleFieldBuffExpiry,ruleFieldAttackBlocked,beginRuleFields,endRuleFields,dispatchRuleFieldAdvance,ruleFieldSnapshot,restoreRuleFieldSnapshot,ruleProgramInputPlan,ruleDotInputPlan,ruleLinearDotSnapshot,restoreRuleLinearDotSnapshot,dispatchRuleLinearDotPulse,ruleChargeInputPlan,beginRuleCharge,commitRuleChargeCast,ruleChargeSnapshot,restoreRuleChargeSnapshot,ruleLinearSnapshot,restoreRuleLinearSnapshot,dispatchRuleLinearContact,planLegacyRuleCast,withLegacyPhaseReceipt,validateRuleLegacyPhases,dispatchLegacyActivation,projectLegacyVulnerability,dispatchLegacyWardCleave,withRuleAttackReceipt,dispatchRuleAfterAttack,projectRuleArmedAttack,initRulePassiveAuras,observeRulePassiveAura,readyRulePassiveAura,dispatchRulePassiveAura,validateRuleStaticPassives,projectRuleStaticPassive,dispatchRuleEntityPulse,reconcileRuleAreas,dispatchRuleJobDue,reconcileRuleJobs,dispatchRuleStatusPulse,projectLegacyPassive,activateHeroRule,castHeroRule,usesPrivateRuleCast,reconcileRuleStatuses,ruleHostSnapshot,ruleHostEpochSnapshot,validRuleHostSnapshot,validRulePackSnapshot,restoreRuleHostSnapshot,moduleAbility,rulesSnapshot,validRulesSnapshot,restoreRulesSnapshot,validHeroRuleResources,validateHeroRuleFacts} from './hero-rules-host.js';
import {PackControl} from './pack-control.js';
import {PackHP} from './pack-hp.js';
import {createPackDispatcher} from './pack-dispatcher.js';
import {assertPackSerializable,packHasDebuffImmunity,packStatusFlag} from './pack-services.js';
import {HERO_PACKS} from './pack-runtime.js';
import {lookupRuntimeHero,validHeroPair,validSimulationPair} from './hero-registry.js';
export const formatCombatNumber=value=>{if(!Number.isFinite(value))return '0';const n=Math.max(0,value);return n>0&&n<.1?'<0.1':n.toFixed(1).replace(/\.0$/,'');};
// DOTA DUEL fixed-step deterministic two-sided combat engine.
// Gameplay units use a 1200-wide arena; skill geometry is adapted to 2D.
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const clone=x=>JSON.parse(JSON.stringify(x));
export const FIXED_DT=1/60;
export class Engine {
 constructor(heroes,indices=[0,3],opts={}){this.heroRuleRegistry=opts.heroRuleRegistry;if(opts.heroPacks&&!opts.simulationRoster)throw Error('Custom packs require an explicit simulation roster');this.packCombat=createPackDispatcher(bridgeBStatusPacks(opts.heroPacks??HERO_PACKS));if(!(opts.simulationRoster?validSimulationPair(indices,opts.simulationRoster):validHeroPair(indices)))throw Error('Inactive hero selection');this.heroes=heroes;this.simulationRoster=opts.simulationRoster;this.indices=[...indices];this.runtimeHeroes=this.indices.map(id=>lookupRuntimeHero(heroes,id,opts.simulationRoster));this.mode=opts.mode||'local';this.seed=opts.seed??8192;this.score=[0,0];this.round=1;this.history=[];this.logSeq=0;this.resetRound();}
 random(){this.seed=(this.seed*1664525+1013904223)>>>0;return this.seed/4294967296;}
 hero(i){return this.runtimeHeroes[i];}
 ability(i,s){return bModuleAbility(this,i,s,moduleAbility(this,i,s,this.hero(i).abilities[s]));}
 heroRuleAfterAttack(f,t,a,event,landed){return dispatchRuleAfterAttack(this,f,t,a,event,landed);}
 heroRuleArmedAttack(f,t,amount){return projectRuleArmedAttack(this,f,t,amount);}
 resetRound(){this.packCore=null;this.packModules=null;this.time=99;this.t=0;this.frame=0;this.phase='intro';this.phaseTime=2.3;this.winner=null;this.paused=false;this.hitstop=0;this.shake=0;this.events=[];this.projectiles=[];this.zones=[];this.effects=[];this.logs=[];this.seq=0;this.input=[{},{}];this.previous=[{},{}];this.fighters=[0,1].map(i=>{let h=this.hero(i);return {i,x:i===0?320:880,y:0,vy:0,airVx:0,crouching:false,direction:5,jumpKind:'neutral',dir:i===0?1:-1,hp:h.combatHp||h.hp*2.8,maxHp:h.combatHp||h.hp*2.8,mp:h.combatMana||1200,maxMp:h.combatMana||1200,hits:0,received:0,combo:0,comboTime:0,maxCombo:0,damage:0,casts:0,cd:[0,0,0,0],attackCd:0,recovery:0,stun:0,root:0,silence:0,hex:0,fear:0,taunt:0,slow:0,slowPct:0,invuln:0,ccGrace:0,ccChain:0,guard:0,guardMeter:100,buffs:[],dots:[],animation:'idle',animTime:0,cast:null,channel:null,receivedDamage:0,healBudget:h.hp*20,souls:0,charges:h.abilities.map(a=>a.mvp.charges||0),chargeTimers:[0,0,0,0],lastDamageTime:0,cleanseDamage:0,hitFlash:0,charge:0,chargeSlot:-1,skillBuffer:null,aiDelay:.3};});this.packCombat.init(this);initRulePassiveAuras(this);}
 heroRulePassiveProjection(f,abilityId,key){return projectRuleStaticPassive(this,f,abilityId,key);}
 heroRulePassiveAuraObserve(f,dt,alive){return observeRulePassiveAura(this,f,dt,alive);}
 heroRulePassiveAuraReady(f,abilityId){return readyRulePassiveAura(this,f,abilityId);}
 heroRulePassiveAuraPulse(f,abilityId){return dispatchRulePassiveAura(this,f,abilityId);}
 heroRuleEntityPulse(entity,event){return dispatchRuleEntityPulse(this,entity,event);}
 heroRuleJobDue(job,accepted,namespace){return dispatchRuleJobDue(this,job,accepted,namespace);}
 heroRuleStatusPulse(f,record,enabled){return bStatusPulse(this,f,record,enabled)||dispatchRuleStatusPulse(this,f,record,enabled);}
 canTargetSpell(options){return PackTargeting.canTarget(this,options);}
 routeTargetedSpell(options){return PackTargeting.route(this,options);}
 hasEffectiveStatus(f,key){if(!f||this.fighters[f.i]!==f||typeof key!=='string')throw Error('Invalid status query');return (['silence','stun','root','hex','fear','taunt'].includes(key)&&(key==='silence'?f.silence>0:this.controlRemaining(f,key)>0))||packStatusFlag(this,f,key);}
 applyControlSource(f,options){return PackControl.apply(this,f,options);}
 releaseControlSource(id,reason){return PackControl.release(this,id,reason);}
 controlRemaining(f,type){return PackControl.remaining(this,f,type);}
 actionToken(f,reasons){return PackControl.token(this,f,reasons);}
 actionTokenValid(token){return PackControl.valid(this,token);}
 notifyAction(f,reason){PackControl.invalidate(this,f,reason);this.packCombat.actionChanged(this,f,reason);}
 commitAction(f){this.notifyAction(f,'action');}
 enableHPLifecycle(){return PackHP.enable(this);}
 beginDeferredHP(f,options){return PackHP.begin(this,f,options);}
 settleDeferredHP(id,options){return PackHP.settle(this,id,options);}
 start(){this.phase='fight';this.phaseTime=0;return this;}
 setInput(i,input){const allowed=['left','right','up','jump','down','attack','s0','s1','s2','s3'];const old=this.input[i],next=Object.fromEntries(allowed.filter(k=>input?.[k]===true).map(k=>[k,true]));if(['left','right','up','jump'].some(k=>next[k]&&!old[k]))this.notifyAction(this.fighters[i],'movement');if(['attack','s0','s1','s2','s3'].some(k=>next[k]&&!old[k]))this.notifyAction(this.fighters[i],'action');this.input[i]=next;}
 cancelInput(i){cancelCharge(this,this.fighters[i]);this.notifyAction(this.fighters[i],'input_cancel');this.packCombat.interrupted(this,this.fighters[i],'input_cancel');this.input[i]={};const f=this.fighters[i];f.skillBuffer=null;f.chargeSlot=-1;f.charge=0;if(f.channel){if(!dispatchRuleChannelInterrupt(this,f,'cancel-input')){if(f.channel.m.effect==='grab'){const t=this.fighters[1-i];t.stun=0;t.grabbedBy=null;}f.channel=null;f.recovery=Math.max(f.recovery,.2);}this.log('channel_end',i,{reason:'input_cancel'});}}
 queueSkill(i,slot){const f=this.fighters[i],a=this.ability(i,slot),m=a?.mvp;if(!m||m.passive||f.hp<=0)return false;const chargePlan=ruleChargeInputPlan(this,i,slot)??ruleDotInputPlan(this,i,slot)??ruleProgramInputPlan(this,i,slot)??ruleFieldInputPlan(this,i,slot)??ruleUnitInputPlan(this,i,slot)??ruleStatusDotInputPlan(this,i,slot)??ruleChannelInputPlan(this,i,slot)??rulePeriodicInputPlan(this,i,slot);if(chargePlan===false)return false;const toggleOff=m.toggle&&this.buff(f,m.effect==='aura'?'aura':a.id);if(!toggleOff&&(f.cd[slot]>0||f.mp<(chargePlan?.manaCost??m.mana)||m.charges&&f.charges[slot]<=0))return false;f.skillBuffer={slot,expires:this.t+.35};this.log('skill_input',i,{skill:a.id,slot,buffered:!!(f.recovery>0||f.cast||f.channel)});return true;}
 consumeSkill(i){const f=this.fighters[i],pending=f.skillBuffer;if(!pending)return false;if(this.t>pending.expires+1e-7){f.skillBuffer=null;this.log('skill_input_expired',i,{slot:pending.slot});this.fx('text',f.x,f.y+185,'#d3c6b0',{text:'暂无法施法',target:i});return false;}const m=this.ability(i,pending.slot).mvp,key='s'+pending.slot;if(m.input==='charge'&&this.input[i][key]){const chargePlan=ruleChargeInputPlan(this,i,pending.slot);if(chargePlan===false||this.blocked(f)||this.isSilenced(f)||f.recovery>0||f.cast||f.channel||f.mp<(chargePlan?.manaCost??m.mana)||f.cd[pending.slot]>0)return false;if(!beginRuleCharge(this,f,pending.slot))return false;f.chargeSlot=pending.slot;f.charge=0;f.guard=false;f.skillBuffer=null;return true;}if(this.cast(i,pending.slot)){f.skillBuffer=null;return true;}return false;}
 fx(type,x,y,color='#fff',extra={}){
  const effect={type,x,y,color,life:.5,maxLife:.5,...extra};
  if(type==='text'){
   effect.target??=this.fighters.reduce((a,b)=>Math.abs(a.x-x)<Math.abs(b.x-x)?a:b).i;
   if(Number.isFinite(effect.amount)){
    const recent=this.effects.find(e=>e.type==='text'&&e.target===effect.target&&e.kind===effect.kind&&e.color===color&&Number.isFinite(e.amount)&&e.maxLife-e.life<.14);
    if(recent){recent.amount+=effect.amount;recent.text=(effect.kind==='heal'?'+':'')+formatCombatNumber(recent.amount);recent.x=x;recent.y=y;return;}
    effect.text=(effect.kind==='heal'?'+':'')+formatCombatNumber(effect.amount);
   }
   const same=this.effects.filter(e=>e.type==='text'&&e.target===effect.target);if(same.length>=3)this.effects=this.effects.filter(e=>e!==same[0]);
   const all=this.effects.filter(e=>e.type==='text');if(all.length>=6)this.effects=this.effects.filter(e=>e!==all[0]);
  }
  this.effects.push(effect);
 }
 log(type,i,detail){this.logs.push({frame:this.frame,logId:++this.logSeq,type,player:i,...detail});if(this.logs.length>200)this.logs.shift();}
 buff(f,key){return f.buffs.find(b=>b.key===key);}
 addBuff(f,key,m,duration){f.buffs=f.buffs.filter(b=>b.key!==key);f.buffs.push({key,m:clone(m),life:duration||m.duration_s||2});}
 property(f,key,fallback=0){if(key==='debuffImmune'&&packHasDebuffImmunity(f))fallback=Math.max(fallback,1);return f.buffs.reduce((v,b)=>Math.max(v,b.m[key]||0),fallback);}
 passivesEnabled(f){return !this.packCombat.broken(this,f);}
 notifyTargeted(f,t,skill){this.packCombat.targeted(this,f,t,skill);}
 isSilenced(f){return f.silence>0||packStatusFlag(this,f,'silence')||this.packCombat.silenced(this,f);}
 blocked(f,{ignoreTaunt=false}={}){return ['stun','hex','fear',...(!ignoreTaunt?['taunt']:[])].some(type=>this.controlRemaining(f,type)>0);}
 animate(f,name,duration=.35){f.animation=name;f.animTime=duration;}
 interrupt(f){cancelCharge(this,f,{casts:true});this.notifyAction(f,'control');this.packCombat.interrupted(this,f,'control');if(f.pack)f.pack.attackRecoveryUntil=0;if(f.cast){this.log('interrupted',f.i,{skill:f.cast.slot});f.cast=null;}if(f.channel){this.log('channel_end',f.i,{reason:'interrupted'});if(!dispatchRuleChannelInterrupt(this,f,'interrupt'))f.channel=null;}f.buffs=f.buffs.filter(b=>!b.m.interruptOnCC);f.chargeSlot=-1;}
 control(target,type,duration,pierces=false,{sourceOnly=false}={}){if(duration<=0||target.invuln>0||target.ccGrace>0||!pierces&&this.property(target,'debuffImmune'))return 0;const d=Math.min(duration,1.5-target.ccChain);if(d<=0)return 0;if(!sourceOnly)target[type]=Math.max(target[type]||0,d);target.ccChain+=d;target.lastControl=type;if(['stun','hex','fear','taunt'].includes(type))this.interrupt(target);this.log('control',target.i,{control:type,duration:d});return d;}
 updateGuard(f){const t=this.fighters[1-f.i],inp=this.input[f.i],horizontal=(inp.right?1:0)-(inp.left?1:0);f.dir=t.x>=f.x?1:-1;f.relativeDirection=horizontal*f.dir;const skillHeld=[0,1,2,3].some(s=>inp['s'+s]&&!this.ability(f.i,s).mvp.passive);f.guard=horizontal*f.dir<0&&f.y<=0&&f.vy<=0&&!this.blocked(f)&&!inp.attack&&!skillHeld&&!f.cast&&!f.channel&&f.chargeSlot<0&&f.recovery<=0&&this.controlRemaining(f,'root')<=0;return f.guard;}
 move(f,dx){const old=f.x;let x=clamp(old+dx,45,1155);for(const z of this.zones){if(z.type==='wall'&&f.y<z.height){if(old<z.x&&x>=z.x-35)x=z.x-35;if(old>z.x&&x<=z.x+35)x=z.x+35;}}f.x=x;}
 dispel(f,tier='basic'){const removable=m=>m?.dispelTier==='basic'||tier==='strong'&&m?.dispelTier==='strong';const fields=['root','silence','slow',...(tier==='strong'?['stun','hex','fear']:[])];for(const k of fields)f[k]=0;f.slowPct=0;f.dots=f.dots.filter(d=>!removable(d.m));f.buffs=f.buffs.filter(b=>!removable(b.m));PackControl.dispel(this,f,tier);this.packCombat.dispel(this,f,tier);reconcileRuleStatuses(this);reconcileRuleJobs(this);reconcileRuleAreas(this);this.log('dispel',f.i,{tier});}
 bladeDance(f,damage){return projectLegacyPassive(this,this.indices[f.i],2,'projectAttack',{owner:f.i,damage},()=>{const a=this.hero(f.i).abilities.find(a=>a.id==='juggernaut_blade_dance');return {damage:this.passivesEnabled(f)&&a&&this.random()<a.mvp.critChance?damage*a.mvp.critMultiplier:damage};}).damage;}
 nonlethalSelfDamage(f,amount){if(f.hp<=0||!Number.isFinite(amount)||amount<=0)return 0;const before=f.hp;f.hp=Math.max(Math.min(1,before),before-amount);return before-f.hp;}
 heal(f,amount,details={},receipt=null){if(receipt)Object.assign(receipt,{actual:0,deferred:0});if(f.hp<=0||!Number.isFinite(amount))return 0;amount=this.packCombat.healing(this,f,amount);const deferred=PackHP.captureHeal(this,f,Math.min(amount,f.healBudget));if(deferred>0){if(receipt)receipt.deferred=deferred;f.healBudget-=deferred;this.log('heal_deferred',f.i,{amount:deferred,...details});return 0;}const n=Math.min(f.maxHp-f.hp,amount,f.healBudget);if(n<=0)return 0;f.hp+=n;f.healBudget-=n;if(receipt)receipt.actual=n;this.fx('text',f.x,f.y+190,'#91f4b1',{amount:n,kind:'heal',target:f.i,life:.8,maxLife:.8});this.log('heal',f.i,{amount:n,...details});return n;}
 resolveDamage(attacker,target,damage,m={},info={}){const receipt={accepted:false,landed:false,guard:false,actual:0,killedAtDebit:false,rawDamage:damage};this.hit(attacker,target,damage,m,info,receipt);return receipt;}
 hit(attacker,target,damage,m={},info={},receipt=null){
  if(target.hp<=0||target.invuln>0){this.log('evade',target.i,{reason:'invulnerable'});return false;}
  const basic=!!info.basic,physical=m.damage_type==='physical';const targetHero=this.hero(target.i);if(projectLegacyPassive(this,this.indices[target.i],2,'projectDamage',{owner:target.i,basic},()=>({evaded:basic&&this.passivesEnabled(target)&&targetHero.id==='phantom_assassin'&&this.random()<targetHero.abilities[2].mvp.evasion})).evaded){this.fx('text',target.x,target.y+180,'#cfe7ff',{text:'闪避'});return false;}
  if(basic&&this.property(target,'basic_attack_evasion')){this.fx('text',target.x,target.y+170,'#b7ffbd',{text:'闪避'});return false;}
  const evasion=this.buff(target,'counter');if(basic&&physical&&evasion?.m.counter_type==='basic_physical'){target.buffs=target.buffs.filter(b=>b!==evasion);this.addBuff(target,'counterReward',{next_attack_bonus:evasion.m.next_attack_bonus||30},3);this.fx('text',target.x,target.y+170,'#aaf6ff',{text:'闪避反击'});return false;}
  this.updateGuard(target);let guard=target.guard>0&&m.blockable!==false&&!info.dot;
  let d=damage*(this.property(attacker,'outgoingMultiplier')||1);if(basic&&physical&&this.passivesEnabled(target)&&targetHero.id==='tidehunter')d=Math.max(0,d-(this.buff(target,'tidehunter_shell')?150:75));
  if(physical){const armor=Math.max(this.property(target,'physical_reduction'),0);d*=1-armor;const vuln=Math.max(this.property(target,'vulnerability_physical'),projectLegacyVulnerability(this,attacker,target,m.damage_type)??(this.passivesEnabled(attacker)&&this.hero(attacker.i).id==='shadow_fiend'&&Math.abs(target.x-attacker.x)<=this.ability(attacker.i,2).mvp.radius_wu?(7*.06/(1+7*.06)):0));d*=1+vuln;}
  if(m.damage_type==='magical')d*=1-Math.max(this.property(target,'magic_reduction'),targetHero.id==='anti_mage'&&this.passivesEnabled(target)?.35:0);
  for(const b of target.buffs){if((m.damage_type!=='pure'||b.key==='pudge_meat_shield')&&b.m.block_flat&&b.key!=='tidehunter_shell'&&(!b.m.physical_only||physical))d-=Math.min(b.m.block_flat,d*(b.m.block_fraction_cap||.4));}
  if(guard){target.guardMeter=Math.max(0,target.guardMeter-(info.heavy?35:Math.min(24,8+d*.025)));d*=.2;if(target.guardMeter<=0){target.guard=0;this.control(target,'stun',.8);this.fx('text',target.x,target.y+200,'#ffb462',{text:'破防!'});}this.fx('guard',target.x,target.y+95,'#75d8ff');}
  const hpBeforeHooks=target.hp,damageEvent={attacker,target,damage:Math.max(0,d),rawDamage:damage,attackId:info.attackId??null,m,info,guard,hpBefore:hpBeforeHooks};this.packCombat.beforeDamage(this,damageEvent);d=damageEvent.damage;
  // Enforce guarded/chip survival after every damage modifier and shield/conversion hook.
  d=Math.max(0,d);if(guard||m.chip)d=Math.min(d,Math.max(0,target.hp-1));damageEvent.damage=d;const resolvedBeforeCapture=d,captureBefore=receipt?nativeCaptureFacts(this,target):[];const deferredDamage=PackHP.captureDamage(this,damageEvent);d=damageEvent.damage;const hpAtDebit=target.hp;target.hp=Math.max(0,target.hp-d);const actualDebit=hpAtDebit-target.hp;PackHP.noteDamage(this,target,attacker.i,info,actualDebit);if(receipt)Object.assign(receipt,{accepted:true,landed:!guard,guard:!!guard,actual:actualDebit,deferred:deferredDamage,killedAtDebit:hpAtDebit>0&&target.hp<=0});recordNativeDamageDebit(this,receipt,{source:attacker.i,target:target.i,raw:damage,hpBeforeHooks,hpAtDebit,hpAfterDebit:target.hp,resolvedBeforeCapture,immediate:d,deferred:deferredDamage,chip:!!(guard||m.chip),beforeCapture:captureBefore});target.hitFlash=.12;target.receivedDamage+=d;attacker.damage+=d;target.cleanseDamage+=d;target.lastDamageTime=this.t;if(this.passivesEnabled(target)&&targetHero.id==='tidehunter'&&target.cleanseDamage>=450){this.dispel(target,'strong');target.cleanseDamage=0;this.fx('text',target.x,target.y+190,'#9ff4d9',{text:'强驱散'});}if(m.selfReflection&&d)this.nonlethalSelfDamage(attacker,d*m.selfReflection);
  if(d){this.fx('hit',target.x,target.y+90,guard?'#80d3ee':this.hero(attacker.i).color,{size:info.heavy?65:38});this.fx('text',target.x,target.y+165,guard?'#b5dbe8':'#fff1ce',{amount:d,kind:'damage',target:target.i,life:.7,maxLife:.7});this.shake=Math.max(this.shake,info.heavy?9:4);if(!info.dot)this.hitstop=Math.max(this.hitstop,info.heavy?.055:.028);}
  if(!guard){
   if(!info.dot){attacker.combo=attacker.comboTime>0?attacker.combo+1:1;attacker.comboTime=.95;attacker.maxCombo=Math.max(attacker.maxCombo,attacker.combo);this.animate(target,'hurt',.22);}
   if(m.stun_s)this.control(target,m.control||'stun',m.stun_s);
   if(m.root_s)this.control(target,'root',m.root_s);
   if(m.silence_s&&!this.property(target,'debuffImmune'))target.silence=Math.max(target.silence,m.silence_s);
   if(m.slow_pct&&(m.slow_duration_s??1)>0&&!this.property(target,'debuffImmune')){target.slow=Math.max(target.slow,m.slow_duration_s??1);target.slowPct=Math.max(target.slowPct,m.slow_pct/100);}
   if(m.knockback_wu)this.move(target,attacker.dir*m.knockback_wu);
   if(m.pull_to_distance){this.move(target,attacker.x+attacker.dir*m.pull_to_distance-target.x);this.control(target,'stun',m.pull_cap_s||.25);}
   if(m.vulnerability_physical)this.addBuff(target,'vulnerable',{...m,dispelTier:'basic'},m.vulnerability_s);
   if(m.attack_damage_debuff)this.addBuff(target,'weak',{...m,dispelTier:'basic'},m.debuff_duration_s);
   if(basic){attacker.hits++;}
   if(!info.dot&&m.hitstun_s&&!m.stun_s){target.recovery=Math.max(target.recovery,Math.min(.16,m.hitstun_s));}
   if(!basic&&!info.passive&&this.passivesEnabled(attacker)&&this.hero(attacker.i).id==='lina'&&!info.linaDone){const b=this.buff(attacker,'fiery');this.addBuff(attacker,'fiery',{stacks:Math.min(7,(b?.m.stacks||0)+1)},16);if((b?.m.stacks||0)<7)this.log('passive',attacker.i,{skill:'lina_fiery'});}
  }
  if(basic){target.received++;const pa=this.hero(target.i).abilities.find(a=>a.mvp.trigger_every_received_attacks);if(this.passivesEnabled(target)&&pa&&target.received%(pa.mvp.trigger_every_received_attacks||3)===0&&!this.buff(target,'helix_cd')&&Math.abs(target.x-attacker.x)<=pa.mvp.radius_wu+25){this.addBuff(target,'helix_cd',{},pa.mvp.internal_cooldown_s||1);this.log('passive',target.i,{skill:pa.id});this.hit(target,attacker,pa.mvp.damage,{...pa.mvp,blockable:true},{passive:true});this.fx('ring',target.x,target.y+60,this.hero(target.i).color,{size:pa.mvp.radius_wu});}}
  damageEvent.damage=actualDebit;this.packCombat.afterDamage(this,damageEvent);
  this.log(guard?'block':'hit',attacker.i,{damage:d,target:target.i,basic,heavy:!!info.heavy,skill:info.skill||null});return !guard;
 }
 attack(i,{forced=false}={}){const heavy=false;const f=this.fighters[i],t=this.fighters[1-i],h=this.hero(i);if(this.phase!=='fight'||this.paused||f.hp<=0||this.blocked(f,{ignoreTaunt:forced})||this.packCombat.disarmed(this,f)||packStatusFlag(this,f,'disarm')||this.controlRemaining(f,'root')>0||f.attackCd>1e-7||f.recovery>1e-7||f.cast||f.channel||(ruleFieldAttackBlocked(this,f)??(this.buff(f,'aura')&&h.id==='juggernaut')))return false;
  if(!validateRuleLegacyPhases(this,i)||!validateRuleStaticPassives(this,i))return false;
  if(!forced)this.commitAction(f);const fiery=this.passivesEnabled(f)?this.buff(f,'fiery')?.m.stacks||0:0;const interval=this.packCombat.attackInterval(this,f,t,this.property(f,'attack_interval_override_s')||h.attack_interval_s*(this.property(f,'attack_interval_multiplier')||1)*(1/(1+fiery*.28)));const moon=this.buff(f,'mirana_moonlight');if(moon)moon.reveal=1.5;f.attackCd=interval*(heavy?1.65:1);f.recovery=Math.min(.22,interval);this.animate(f,heavy?'heavy':'attack',heavy?.45:.32);f.guard=0;
  let range=(this.property(f,'attack_range_override')||h.attack_range)+this.property(f,'attack_range_bonus')+this.property(f,'next_attack_range_bonus');let d=this.property(f,'attack_damage_override')||h.attack;d+=this.property(f,'attack_bonus');if(h.id==='shadow_fiend')d+=f.souls;d*=1-this.property(f,'attack_damage_debuff');if(heavy){d*=1.55;range+=24;}
  const buff=f.buffs.find(b=>b.m.next_attack_override);if(buff)d=buff.m.next_attack_override;
  d+=this.property(f,'next_attack_bonus');
  d=projectLegacyPassive(this,this.indices[f.i],3,'projectAttack',{owner:f.i,target:t.i,damage:d},()=>({damage:d+(this.passivesEnabled(f)&&h.id==='drow_ranger'&&Math.abs(t.x-f.x)>=(h.abilities[3].mvp.distance_threshold_wu||165)&&this.random()<.4?(h.abilities[3].mvp.attack_bonus||90):0)})).damage;
  let extra={damage_type:'physical',blockable:true,hitstun_s:heavy?.18:.1,knockback_wu:heavy?45:6};const passive=h.abilities.find(a=>a.mvp.trigger_every_hits);if(h.id==='juggernaut'){const raw=d;d=this.bladeDance(f,d);extra.critical=d>raw;}const headshot=projectLegacyPassive(this,this.indices[f.i],1,'projectAttack',{owner:f.i,guaranteed:!!this.property(f,'headshotGuaranteed')},()=>{const proc=this.passivesEnabled(f)&&h.id==='sniper'&&(!!this.property(f,'headshotGuaranteed')||this.random()<.4);return {proc,damageBonus:proc?110:0,knockbackBonus:proc?27.5:0,slowPercentage:proc?100:0,slowSeconds:proc?.5:0};});if(headshot.proc){d+=headshot.damageBonus;extra.knockback_wu+=headshot.knockbackBonus;extra.slow_pct=headshot.slowPercentage;extra.slow_duration_s=headshot.slowSeconds;}if(this.passivesEnabled(f)&&h.id==='phantom_assassin'){if(this.buff(f,'deadlyFocus')){d*=4.5;f.buffs=f.buffs.filter(b=>b.key!=='deadlyFocus');extra.critical=true;}else if(this.random()<.17)this.addBuff(f,'deadlyFocus',{},10);}
  if(this.passivesEnabled(f)&&passive&&(f.hits+1)%(passive.mvp.trigger_every_hits||4)===0){d*=passive.mvp.attack_multiplier||1;d+=passive.mvp.damage||0;extra.knockback_wu+=passive.mvp.knockback_wu||0;}
  d=this.packCombat.attack(this,f,t,d,extra);const id=++this.seq;this.events.push({at:this.t+(heavy?.24:.1),type:'attack',owner:i,damage:d,m:extra,range,heavy,id,dir:f.dir,y:f.y});return true;
 }
 endWard(z,reason,attacker=null){if(z.ended)return;if(dispatchRuleUnitEnd(this,z,reason,attacker))return;z.ended=true;z.life=0;this.log('ward_end',z.owner,{skill:z.id,reason,attacker,healed:z.healed||0,ticks:z.healTicks||0});if(reason==='attack'){this.fx('text',z.x,190,'#ffd297',{text:'守卫被摧毁',target:z.owner,life:.9,maxLife:.9});this.fx('hit',z.x,50,'#ffe4a2');}}
 resolveAttack(e){const f=this.fighters[e.owner],t=this.fighters[1-e.owner];if(['stun','hex','fear'].some(type=>this.controlRemaining(f,type)>0)||f.hp<=0)return;this.log('attack',f.i,{heavy:!!e.heavy});const ranged=this.hero(f.i).attack_range>200&&!this.property(f,'melee');if(!ranged)for(const z of this.zones)if(z.type==='ward'&&z.life>0&&z.owner!==f.i&&Math.abs(z.x-f.x)<e.range+20&&(z.x-f.x)*e.dir>=-20&&Math.abs(f.y)<105)this.endWard(z,'attack',f.i);
  if(ranged){this.projectiles.push({owner:f.i,x:f.x+f.dir*38,y:f.y+100,dir:e.dir,v:980,travel:0,range:e.range,r:10,damage:e.damage,m:e.m,basic:true,heavy:e.heavy,id:e.id});}
  else if(Math.abs(f.x-t.x)<e.range+22&&Math.abs(f.y-t.y)<105&&(t.x-f.x)*e.dir>=-35){this.basicHit(f,t,e);}
  this.fx('slash',f.x+f.dir*45,f.y+100,this.hero(f.i).color,{dir:f.dir,size:e.heavy?125:85});
 }
 basicHit(f,t,e){this.updateGuard(t);const h=this.hero(f.i);let d=e.damage,manaBurn=0;const mana=h.abilities.find(a=>a.mvp.mana_burn);if(this.passivesEnabled(f)&&mana&&!t.guard){const burn=Math.min(t.mp,mana.mvp.mana_burn+(mana.mvp.mana_burn_pct||0)*t.maxMp);manaBurn=burn;d+=burn*mana.mvp.mana_damage_ratio;}
  const frost=this.buff(f,'drow_ranger_frost');if(frost){if(f.mp>=12)f.mp-=12;else{d-=30;f.buffs=f.buffs.filter(b=>b!==frost);}}const ok=this.hit(f,t,d,e.m,{basic:true,heavy:e.heavy,skill:typeof e.id==='string'?e.id:null,attackId:Number.isSafeInteger(e.id)?e.id:null});if(ok&&manaBurn){t.mp=Math.max(0,t.mp-manaBurn);this.log('passive',f.i,{skill:mana.id});}if(!withLegacyPhaseReceipt(this,f,t,e,'legacy-basic-hit-completed',()=>dispatchLegacyWardCleave(this,f,t,e,ok))&&this.passivesEnabled(f)&&h.id==='sven'){for(const z of this.zones)if(z.type==='ward'&&z.owner!==f.i&&(z.x-t.x)*f.dir>=0&&Math.abs(z.x-t.x)<330){this.endWard(z,'attack',f.i);this.fx('slash',z.x,60,h.color,{size:120,dir:f.dir});this.log('cleave',f.i,{target:'ward'});this.log('passive',f.i,{skill:'sven_cleave'});}}const next=f.buffs.filter(b=>b.m.next_attack_override||b.m.next_attack_bonus);for(const b of next){if(ok||b.key==='earthshaker_totem')f.buffs=f.buffs.filter(x=>x!==b);}
  if(ok){const slow=this.property(f,'on_attack_slow');if(slow){t.slow=Math.max(t.slow,this.property(f,'on_attack_slow_s'));t.slowPct=slow;}
   if(this.passivesEnabled(f)&&this.buff(f,'overload')){this.log('passive',f.i,{skill:'storm_spirit_overload'});const m=h.abilities[2].mvp;this.hit(f,t,m.damage||30,{damage_type:'magical',blockable:true,slow_pct:80,slow_duration_s:.8},{passive:true});f.buffs=f.buffs.filter(b=>b.key!=='overload');}}withRuleAttackReceipt(this,f,t,e,ok,()=>this.packCombat.afterAttack(this,f,t,e,ok));
 }
 cast(i,slot,options={}){if(!validateRuleLegacyPhases(this,i))return false;if(!validateHeroRuleFacts(this,i,slot,options))return false;const migrated=castHeroRule(this,i,slot,options);if(migrated!==undefined)return migrated;const handled=this.packCombat.cast(this,this.fighters[i],slot,options);if(handled!==undefined)return handled;const f=this.fighters[i],a=this.ability(i,slot),rulePlan=planLegacyRuleCast(this,i,slot,options);if(rulePlan===false)return false;const periodicToggle=rulePeriodicToggle(this,i,slot);if(periodicToggle!==undefined)return periodicToggle;const fieldToggle=ruleFieldToggle(this,i,slot);if(fieldToggle!==undefined)return fieldToggle;const m=rulePlan?{...a.mvp,mana:rulePlan.manaCost,cooldown_s:rulePlan.cooldownSeconds,startup_frames:rulePlan.windupSeconds*60,recovery_frames:rulePlan.recoverySeconds*60}:a?.mvp;if(m?.toggle&&this.buff(f,m.effect==='aura'?'aura':a.id)){this.commitAction(f);f.buffs=f.buffs.filter(b=>b.key!==(m.effect==='aura'?'aura':a.id));this.zones=this.zones.filter(z=>!(z.owner===i&&z.id===a.id));return true;}if(!m||m.passive||f.chargeSlot>=0||this.phase!=='fight'||this.paused||this.blocked(f)||this.isSilenced(f)||f.cd[slot]>0||(m.charges&&f.charges[slot]<=0)||f.mp<m.mana||f.recovery>0||f.cast||f.channel)return false;
  if(m.effect==='drain'&&(Math.abs(this.fighters[1-i].x-f.x)>m.range_wu+22||this.fighters[1-i].hp<=0||this.fighters[1-i].invuln>0||this.property(this.fighters[1-i],'debuffImmune')))return false;
  const motion=['blink','blink_strike','leap','leap_hit','dash_hit'].includes(m.effect);if(motion&&(this.controlRemaining(f,'root')>0||f.y>5))return false;
  this.commitAction(f);const moon=this.buff(f,'mirana_moonlight');if(moon)moon.reveal=1.5;f.mp-=m.mana;f.cd[slot]=m.cooldown_s;if(m.charges){f.charges[slot]--;if(f.chargeTimers[slot]<=0)f.chargeTimers[slot]=m.charge_restore_s;}f.casts++;f.guard=0;const target=this.fighters[1-i];let aim=options.aim??target.x;aim=clamp(aim,f.x-m.range_wu,f.x+m.range_wu);if(m.input==='raze'){const ranges=m.raze_distances||[150,300,450];const range=options.raze??(Math.abs(target.x-f.x)<200?ranges[0]:Math.abs(target.x-f.x)>350?ranges[2]:ranges[1]);aim=f.x+f.dir*range;}
  f.cast={slot,remaining:m.startup_frames/60,m:clone(m),dir:options.dir||((this.input[i].right?1:0)-(this.input[i].left?1:0))||f.dir,aim:clamp(aim,45,1155),charge:clamp(options.charge||0,0,m.charge_max_s||.8),id:++this.seq};commitRuleChargeCast(this,f,f.cast);this.animate(f,'cast',m.startup_frames/60+.25);
  this.fx('cast',f.x,f.y+100,this.hero(i).color,{life:m.startup_frames/60,maxLife:m.startup_frames/60,size:slot===3?100:60});
  if(['ground','ground_dot','wall','curse'].includes(m.effect))this.fx('warning',f.cast.aim,0,this.hero(i).color,{size:m.radius_wu,life:m.startup_frames/60,maxLife:m.startup_frames/60});
  if(this.hero(i).id==='storm_spirit')this.addBuff(f,'overload',{},4);
  if(['hit','root','hex','dot','pull','grab','drain','blink_strike'].includes(m.effect))this.packCombat.targeted(this,f,target,a.id);this.log('cast',i,{skill:a.id,slot,cost:m.mana});return true;
 }
 release(i,slot){const f=this.fighters[i];if(f.channel?.slot===slot){if(!dispatchRuleChannelInterrupt(this,f,'release')){f.channel=null;f.recovery=.2;}this.log('channel_end',i,{reason:'release'});}if(f.chargeSlot===slot){const amount=f.charge;withChargeRelease(this,f,slot,amount,()=>{f.chargeSlot=-1;f.charge=0;this.cast(i,slot,{charge:amount});});}}
 activate(f,c){if(usesPrivateRuleCast(this,f.i,c.slot)){f.recovery=this.ability(f.i,c.slot).mvp.recovery_frames/60;const result=activateHeroRule(this,f,c);if(!result.handled)throw Error('Missing migrated activation');this.log('activate',f.i,{skill:this.ability(f.i,c.slot).id,slot:c.slot});return;}if(this.packCombat.activate(this,f,c))return;const m=c.m,t=this.fighters[1-f.i],a=this.ability(f.i,c.slot),id=a.id;f.recovery=m.recovery_frames/60;this.animate(f,'cast',.35);const near=(r)=>Math.abs(t.x-f.x)<=r+22&&((m.height!=='ground')||t.y<45);const hit=(d=m.damage,mm=m)=>this.hit(f,t,d,mm,{skill:id});
  const moduleResult=activateHeroRule(this,f,c);if(moduleResult.handled){if(!moduleResult.reflected)this.log('activate',f.i,{skill:id,slot:c.slot});return;}
  const reflect=this.buff(t,'counter');if(reflect&&!reflect.m.counter_type&&['hit','root','hex','dot','pull','blink_strike'].includes(m.effect)&&near(m.range_wu||m.radius_wu)&&!c.reflected){
   if(['root','dot'].includes(m.effect)){f.dots.push({owner:t.i,id,life:m.duration_s,tick:m.tick_interval_s,m,hp0:f.hp,elapsed:0});if(m.effect==='root')f.root=m.duration_s;}
   else if(m.effect==='hex')this.control(f,'hex',m.duration_s);else{let damage=m.missing_mana_multiplier?(f.maxMp-f.mp)*m.missing_mana_multiplier:m.damage;this.hit(t,f,damage,m,{skill:id,reflected:true});}
   this.fx('beam',t.x,t.y+100,'#95dcff',{tx:f.x,ty:f.y+100});this.fx('text',t.x,t.y+180,'#bbf0ff',{text:'法术反制'});this.log('reflect',t.i,{skill:id});return;
  }
  if(id==='lion_finger')this.addBuff(f,'lionForm',{attack_range_override:137.5,attack_bonus:40,move_bonus:16.5,melee:true},20);
  if(!withLegacyPhaseReceipt(this,f,t,c,'legacy-skill-activating',()=>dispatchLegacyActivation(this,f,c))&&this.passivesEnabled(f)&&this.hero(f.i).id==='earthshaker'&&near(this.ability(f.i,2).mvp.radius_wu)){this.log('passive',f.i,{skill:'earthshaker_aftershock'});this.hit(f,t,this.ability(f.i,2).mvp.damage,{damage_type:'magical',blockable:true,stun_s:1.3},{passive:true});}
  switch(m.effect){
   case 'buff':case 'counter':{this.addBuff(f,m.effect==='counter'?'counter':id,m,m.duration_s);if(m.souls){const b=this.buff(f,id);b.collectedSouls=0;b.collectTick=m.officialSemantic?.collection_interval_s||.5;}if(m.cleanse){for(const k of m.cleanse)f[k]=0;}this.fx('ring',f.x,f.y+70,this.hero(f.i).color,{size:100,life:.7,maxLife:.7});break;}
   case 'blink':this.fx('dash',f.x,f.y+80,this.hero(f.i).color);this.move(f,c.dir*m.range_wu);f.invuln=4/60;break;
   case 'blink_strike':if(near(m.range_wu)){this.move(f,t.x-c.dir*70-f.x);hit();this.addBuff(f,id,m,m.buff_duration_s||2);}break;
   case 'leap':case 'leap_hit':{if(m.effect==='leap_hit'&&near(m.radius_wu))hit();f.vy=650;f.motion={dir:c.dir,speed:m.range_wu/(m.travelDuration||.55),life:m.travelDuration||.55};this.addBuff(f,'leapSpeed',{move_multiplier:m.move_multiplier||1.1,attack_interval_multiplier:m.attack_interval_multiplier||1},m.duration_s||2);break;}
   case 'dash_hit':f.motion={dir:c.dir,speed:m.range_wu/m.duration_s,life:m.duration_s,damage:m.damage,m,id,distance:0,maxDistance:m.range_wu,hit:false};f.invuln=m.duration_s;break;
   case 'ward':this.zones=this.zones.filter(z=>!(z.owner===f.i&&z.type==='ward'));this.zones.push({type:'ward',owner:f.i,x:f.x,life:m.duration_s,tick:m.tick_interval_s,m,id,healed:0,healTicks:0});this.log('ward_spawn',f.i,{skill:id,x:f.x,duration:m.duration_s,radius:m.radius_wu});this.fx('text',f.x,190,'#91f4b1',{text:'治疗守卫',target:f.i,life:.9,maxLife:.9});break;
   case 'heal':this.addBuff(f,id,{...m,interruptOnCC:true},m.duration_s);this.zones.push({type:'heal',owner:f.i,x:f.x,life:m.duration_s,tick:m.tick_interval_s,m,id});break;
   case 'aura':if(m.debuffImmune)this.dispel(f,'basic');this.addBuff(f,'aura',m,m.duration_s);this.zones.push({type:'aura',owner:f.i,x:f.x,life:m.duration_s,tick:m.tick_interval_s,m,id});break;
   case 'channel':case 'channel_projectile':case 'drain':case 'grab':{
    if(['grab','drain'].includes(m.effect)&&(!near(m.range_wu)||t.hp<=0||t.invuln>0||m.effect==='drain'&&this.property(t,'debuffImmune')))break;
    f.channel={slot:c.slot,life:m.duration_s+(m.summonWard?FIXED_DT:0),tick:m.tick_interval_s,m,dir:c.dir,id,wardToken:c.id};if(m.summonWard){this.zones.push({type:'deathWard',owner:f.i,x:c.aim,life:m.duration_s,tick:m.tick_interval_s,m,id,wardToken:c.id,invulnerable:true});this.log('ward_spawn',f.i,{skill:id,x:c.aim,duration:m.duration_s,radius:m.radius_wu,invulnerable:true});}f.recovery=0;if(m.effect==='grab'){this.control(t,'stun',m.duration_s);t.grabbedBy=f.i;}break;}
   case 'projectile':case 'projectile_dot':case 'wave':this.spawnProjectile(f,c,m.damage+(m.charge_damage_per_s||0)*c.charge,id);break;
   case 'ground_dot':case 'trap':case 'wall':this.zones.push({type:m.effect,owner:f.i,x:m.effect==='trap'&&m.walkSpeed?f.x:c.aim,life:m.duration_s,tick:m.tick_interval_s||.2,m,id,height:m.wall_height_wu||55,arm:m.arming_s||0,age:0,targetX:c.aim});if(m.effect==='wall'&&Math.abs(t.x-c.aim)<=m.radius_wu+22&&t.y<45)hit();break;
   case 'dot':case 'root':case 'curse':{if((m.effect==='curse'?Math.abs(t.x-c.aim)<=m.radius_wu+22:near(m.range_wu))&&!t.guard&&t.invuln<=0){t.dots=t.dots.filter(d=>d.id!==id);t.dots.push({owner:f.i,id,life:m.duration_s,tick:m.tick_interval_s,m,hp0:t.hp,elapsed:0,nextBurst:m.burstInterval||0});if(m.effect==='root'&&!this.property(t,'debuffImmune')){t.root=m.duration_s;this.fx('root',t.x,t.y+50,this.hero(f.i).color,{life:m.duration_s,maxLife:m.duration_s});}}break;}
   case 'hex':if(near(m.range_wu)&&!t.guard)this.control(t,'hex',m.duration_s);break;
   case 'taunt':if(near(m.radius_wu)&&!t.guard){this.control(t,'taunt',m.duration_s);this.addBuff(f,id,m,m.duration_s);}break;
   case 'pull':if(near(m.range_wu))hit();break;
   case 'multi':{if(m.invulnerable_active&&!near(m.range_wu))break;if(m.invulnerable_active){this.dispel(f,'basic');f.invuln=m.duration_s;}for(let n=0;n<m.ticks;n++)this.events.push({type:'skill_hit',at:this.t+(m.tick_offsets_s?.[n]??n*m.tick_interval_s),owner:f.i,m,id,damage:m.hit_damages?.[n]??m.damage,range:m.tracking_break_wu||m.range_wu||m.radius_wu,track:m.invulnerable_active});break;}
   case 'aura_hit':if(m.wave_speed_wu_s){this.zones.push({type:'expanding',owner:f.i,x:f.x,life:m.radius_wu/m.wave_speed_wu_s+.1,m,id,age:0,hit:false});}else if(near(m.radius_wu))hit(m.soulLines?m.damage*Math.max(1,Math.min(3,f.souls)):m.damage);this.fx('ring',f.x,60,this.hero(f.i).color,{size:m.radius_wu,life:.65,maxLife:.65});break;
   case 'ground':if(Math.abs(t.x-c.aim)<=m.radius_wu+22&&(m.height!=='ground'||t.y<45)){let d=m.damage+(id==='shadow_fiend_raze'?f.souls*2:0);if(m.stack_damage){const b=this.buff(t,'raze');d+=(b?.m.stacks||0)*m.stack_damage;this.addBuff(t,'raze',{stacks:Math.min(m.max_stacks,(b?.m.stacks||0)+1)},m.stack_duration_s);}hit(d);}this.fx('pillar',c.aim,0,this.hero(f.i).color,{size:m.radius_wu,life:.6,maxLife:.6});break;
   case 'hit':if(near(m.range_wu||m.radius_wu)){let d=m.damage;if(m.missing_mana_multiplier)d=Math.min(m.damage_cap,d+(t.maxMp-t.mp)*m.missing_mana_multiplier);if(m.execute_threshold_pct&&t.hp/t.maxHp<=m.execute_threshold_pct)d=m.execute_damage;if(id==='sven_cleave')d+=this.property(f,'cleave_bonus');hit(d);this.fx('beam',f.x,f.y+100,this.hero(f.i).color,{tx:t.x,ty:t.y+100});}break;
   default:throw Error('Unsupported ability effect: '+m.effect);
  }
  this.log('activate',f.i,{skill:id,slot:c.slot});
 }
 spawnProjectile(f,c,damage,id){const m=c.m;this.projectiles.push({owner:f.i,x:f.x+f.dir*35,y:f.y+(m.height==='ground'?35:100),dir:c.dir,v:m.projectile_speed_wu_s||800,travel:0,range:m.range_wu,r:Math.max(12,m.radius_wu||18),damage,m,id,reflected:false});}

 // Sweep the actual travelled segment against the existing horizontal hitboxes.
 // Earliest contact wins. At equal entry distances (including starting overlaps),
 // a hero body wins over its ward; ward ties use geometry/identity, not array order.
 projectileCollision(p,from,to){
  const distanceTo=(center,radius)=>{const lo=center-radius,hi=center+radius;if(from>=lo&&from<=hi)return 0;if(to>from&&from<lo&&to>=lo)return lo-from;if(to<from&&from>hi&&to<=hi)return from-hi;return Infinity;};
  const t=this.fighters[1-p.owner],candidates=[];
  if(t.hp>0&&Math.abs(p.y-(t.y+80))<p.r+65&&(p.m.height!=='ground'||t.y<45)){const distance=distanceTo(t.x,p.r+28);if(Number.isFinite(distance))candidates.push({type:'fighter',target:t,distance,priority:0});}
  if(p.basic&&p.y>=-25&&p.y<=125)for(const z of this.zones)if(z.type==='ward'&&z.life>0&&z.owner!==p.owner&&this.fighters[z.owner].hp>0){const distance=distanceTo(z.x,25);if(Number.isFinite(distance))candidates.push({type:'ward',target:z,distance,priority:1});}
  candidates.sort((a,b)=>Math.abs(a.distance-b.distance)>1e-7?a.distance-b.distance:a.priority-b.priority||Math.abs(a.target.x-from)-Math.abs(b.target.x-from)||(a.target.owner??a.target.i)-(b.target.owner??b.target.i)||(String(a.target.id??'')<String(b.target.id??'')?-1:String(a.target.id??'')>String(b.target.id??'')?1:0));
  return candidates[0]||null;
 }

 step(dt=FIXED_DT){return withRuleManagedFrame(this,()=>{if(this.paused||this.phase==='matchEnd')return;dt=Math.min(dt,.05);this.frame++;this.effects=this.effects.filter(e=>(e.life-=dt)>0);this.shake=Math.max(0,this.shake-dt*30);if(this.hitstop>0){this.hitstop-=dt;return;}
  if(this.phase!=='fight'){this.phaseTime-=dt;if(this.phaseTime<=0){if(this.phase==='intro'){this.phase='fight';this.fx('announce',600,310,'#ffe3ab',{text:'FIGHT',life:.8,maxLife:.8});}else if(this.phase==='roundEnd'){if(this.score.some(s=>s>=2))this.phase='matchEnd';else{this.round++;this.resetRound();}}}return;}
  PackHP.syncLife(this);this.t+=dt;if(this.mode!=='training')this.time=Math.max(0,this.time-dt);
  this.packCombat.tick(this,dt);reconcileRuleStatuses(this);reconcileRuleJobs(this);reconcileRuleAreas(this);if(this.mode==='cpu')this.ai(1,dt);
  for(const f of this.fighters){const i=f.i,t=this.fighters[1-i],h=this.hero(i),inp=this.input[i],prev=this.previous[i];
   observeLinearDotTargetPhase(this,f,dt);observeChargePhase(this,f,dt);observeLinearHitTargetPhase(this,f,dt);if(f.hp<=0){if(f.channel)dispatchRuleChannelInterrupt(this,f,'owner-dead');f.cast=null;f.channel=null;f.motion=null;f.skillBuffer=null;continue;}
   const hard=this.blocked(f);
   for(const k of ['attackCd','recovery','stun','root','silence','hex','fear','taunt','slow','invuln','ccGrace','animTime','hitFlash','comboTime'])f[k]=Math.max(0,(f[k]||0)-dt);
   PackControl.advance(this,f,dt);if(hard&&!this.blocked(f)){f.ccGrace=1;f.ccChain=0;}if(f.slow<=0)f.slowPct=0;
   f.cd=f.cd.map(v=>Math.max(0,v-dt));for(const b of [...f.buffs]){const liveDt=Math.min(dt,b.life);observeRuleFieldBuff(this,f,b,dt);observeRulePeriodicBuff(this,f,b,dt);b.life-=dt;b.reveal=Math.max(0,(b.reveal||0)-dt);if(b.m.souls){b.collectTick-=liveDt;if(b.collectTick<=1e-7&&b.life>1e-7){b.collectTick+=b.m.officialSemantic?.collection_interval_s||.5;if(!b.collectedSouls&&t.hp>0&&Math.abs(f.x-t.x)<=b.m.radius_wu+22){b.collectedSouls=Math.min(b.m.souls,20-f.souls);f.souls+=b.collectedSouls;this.log('souls',i,{amount:b.collectedSouls,target:t.i});}}if(b.life<=1e-7)f.souls=Math.max(0,f.souls-(b.collectedSouls||0));}if(b.life<=1e-7&&!dispatchRuleFieldBuffExpiry(this,f,b)&&b.m.endDispel)this.dispel(f,b.m.endDispel);}f.buffs=f.buffs.filter(b=>b.life>1e-8);if(f.animTime<=0)f.animation='idle';
   for(let s=0;s<4;s++){const m=this.ability(i,s).mvp;if(m.charges&&f.charges[s]<m.charges){f.chargeTimers[s]-=dt;if(f.chargeTimers[s]<=1e-8){f.charges[s]++;f.chargeTimers[s]=f.charges[s]<m.charges?m.charge_restore_s:0;}}}if(this.t-f.lastDamageTime>7)f.cleanseDamage=0;const regen=projectLegacyPassive(this,this.indices[f.i],2,'projectInterval',{owner:f.i,kind:'mana-regeneration'},()=>({manaPerSecond:h.id==='crystal_maiden'&&this.passivesEnabled(f)?((h.mana_regen||8)+4)*1.8:(h.mana_regen||8)})).manaPerSecond;f.mp=Math.min(f.maxMp,f.mp+regen*dt);f.dir=t.x>=f.x?1:-1;
   const horizontal=(inp.right?1:0)-(inp.left?1:0),vertical=(inp.up||inp.jump?1:0)-(inp.down?1:0);f.direction=(vertical>0?7:vertical<0?1:4)+horizontal+1;f.relativeDirection=horizontal*f.dir;f.crouching=vertical<0&&f.y<=0&&!this.blocked(f)&&!f.cast&&!f.channel&&f.recovery<=0;let move=horizontal;if(this.controlRemaining(f,'fear')>0)move=-f.dir;if(this.controlRemaining(f,'taunt')>0)move=f.dir;
   this.updateGuard(f);
   if(!f.guard)f.guardMeter=Math.min(100,f.guardMeter+dt*18);
   if(f.cast){f.cast.remaining-=dt;if(f.cast.remaining<=0){const c=f.cast;f.cast=null;this.activate(f,c);}}
   beginRuleChannels(this,f);if(f.channel&&!dispatchRuleChannelAdvance(this,f,dt,{moving:!!move,held:!!inp['s'+f.channel.slot],blocked:this.blocked(f),silenced:this.isSilenced(f)})){const ch=f.channel,m=ch.m;if(move||!inp['s'+ch.slot]||this.blocked(f)||this.isSilenced(f)||m.effect==='drain'&&(t.hp<=0||t.invuln>0||this.property(t,'debuffImmune'))){f.channel=null;f.recovery=.2;if(m.effect==='grab'){t.stun=0;t.grabbedBy=null;}}else{ch.life-=dt;ch.tick-=dt;this.animate(f,'cast',.1);if(ch.tick<=1e-7){ch.tick+=m.tick_interval_s;const range=m.break_range_wu||m.range_wu||m.radius_wu;if(!m.summonWard&&Math.abs(f.x-t.x)<=range+22){if(m.effect==='drain'){const amt=Math.min(t.mp,m.mana_drain_per_tick||12,f.maxMp-f.mp);t.mp-=amt;f.mp+=amt;t.slow=.4;t.slowPct=t.mp<=0?.45:.3;this.fx('beam',f.x,f.y+100,'#8db7ff',{tx:t.x,ty:t.y+100});}else if(m.effect==='channel_projectile'){this.spawnProjectile(f,{m,dir:ch.dir},m.damage,ch.id);}else{let lands=true;if(m.randomExplosion){const a=this.random()*Math.PI*2,r=m.explosionMin+this.random()*(m.explosionMax-m.explosionMin),ex=f.x+Math.cos(a)*r,ez=Math.sin(a)*r;this.fx('pillar',ex,0,this.hero(f.i).color,{size:35,life:.2,maxLife:.2});lands=Math.hypot(t.x-ex,ez)<m.explosionRadius;}if(lands)this.hit(f,t,m.damage,m,{skill:ch.id,linaDone:true});if(m.heal_total)this.heal(f,m.heal_total/m.ticks);this.fx('ring',f.x,60,h.color,{size:m.radius_wu||90});}}else if(m.effect==='drain'||m.effect==='grab')ch.life=0;}if(ch.life<=1e-7){f.channel=null;f.recovery=.25;t.grabbedBy=null;}}}
   endRuleChannels(this);if(f.motion){const mot=f.motion;const before=f.x;this.move(f,mot.dir*mot.speed*Math.min(dt,mot.life));mot.distance=(mot.distance||0)+Math.abs(f.x-before);mot.life-=dt;if(mot.damage&&!mot.hit&&Math.abs(f.x-t.x)<65&&Math.abs(f.y-t.y)<110){this.hit(f,t,mot.damage*Math.min(1,mot.distance/(mot.maxDistance||mot.distance)),mot.m,{skill:mot.id});mot.hit=true;}if(mot.life<=0)f.motion=null;}
   else if(this.controlRemaining(f,'stun')<=0&&this.controlRemaining(f,'root')<=0&&!f.cast&&!f.channel&&(f.recovery<=0||this.packCombat.movingAttack(this,f))){const fiery=this.passivesEnabled(f)?this.buff(f,'fiery')?.m.stacks||0:0;const multiplier=(this.property(f,'move_multiplier')||1)*(1-this.property(f,'self_slow'))*(1-f.slowPct*(1-this.property(f,'slow_resistance')))*(1+fiery*.025)*this.packCombat.moveMultiplier(this,f);const groundSpeed=this.controlRemaining(f,'hex')>0?100:(h.move_speed+this.property(f,'move_bonus'))*multiplier;this.move(f,(f.y>0||f.vy>0?f.airVx:f.crouching?0:move*groundSpeed)*dt);if(f.crouching)this.animate(f,'crouch',.1);else if(move&&f.y<=0)this.animate(f,'walk',.1);}
   if(f.y>0||f.vy>0){f.y+=f.vy*dt;f.vy-=1750*dt;if(f.y<=0){f.y=0;f.vy=0;f.airVx=0;this.fx('dust',f.x,0,'#bfb8a3');}}
   let skillUsed=false,acceptedSkill=false;
   for(let s=0;s<4;s++){const key='s'+s;if(!inp[key]&&prev[key]){const wasCharge=f.chargeSlot===s;this.release(i,s);skillUsed=skillUsed||wasCharge;}if(inp[key]&&!prev[key]&&!acceptedSkill)acceptedSkill=this.queueSkill(i,s);}
   skillUsed=this.consumeSkill(i)||skillUsed;
   if(!this.blocked(f)){
    if(inp.jump&&!prev.jump&&!inp.down&&f.y<=0&&this.controlRemaining(f,'root')<=0&&!f.cast&&!f.channel&&f.recovery<=0){f.vy=680;f.airVx=horizontal*(h.move_speed+this.property(f,'move_bonus'))*(this.property(f,'move_multiplier')||1)*(1-this.property(f,'self_slow'))*(1-f.slowPct*(1-this.property(f,'slow_resistance')))*(1+(this.passivesEnabled(f)?this.buff(f,'fiery')?.m.stacks||0:0)*.025)*this.packCombat.moveMultiplier(this,f);f.jumpKind=horizontal===0?'neutral':horizontal*f.dir>0?'forward':'back';f.guard=false;f.crouching=false;this.animate(f,'jump',.8);}
    if(inp.attack&&!skillUsed&&!f.skillBuffer&&f.chargeSlot<0)this.attack(i);
    if(f.chargeSlot>=0){f.charge=Math.min(this.ability(i,f.chargeSlot).mvp.charge_max_s||1,f.charge+dt);observeChargeAdvance(this,f,dt);}
   }
   if(this.controlRemaining(f,'taunt')>0&&f.attackCd<=0)this.attack(i,{forced:true});
   const nativeDots=beginLinearDotIteration(this,f);beginRuleStatusDots(this,f,nativeDots);beginRulePeriodicDots(this,f,nativeDots);for(const dot of nativeDots){if(dispatchRulePeriodicDot(this,f,dot,dt)||dispatchRuleStatusDotAdvance(this,f,dot,dt))continue;dot.life-=dt;dot.elapsed=(dot.elapsed||0)+dt;dot.tick-=dt;if(dot.tick<=1e-7){dot.tick+=dot.m.tick_interval_s;if(!withLinearDotPulse(this,f,dot,()=>dispatchRuleLinearDotPulse(this,f,dot)))this.hit(this.fighters[dot.owner],f,dot.m.damage,{...dot.m,stun_s:0,hitstun_s:0,slow_duration_s:Math.min(dot.m.slow_duration_s??1,Math.max(0,dot.life))},{dot:true,skill:dot.id,linaDone:true});}if(dot.m.burstInterval&&dot.elapsed+1e-7>=dot.nextBurst){this.hit(this.fighters[dot.owner],f,Math.max(0,dot.hp0-f.hp)*dot.m.lost_hp_multiplier,dot.m,{dot:true,skill:dot.id});dot.nextBurst+=dot.m.burstInterval;}if(dot.life<=1e-7&&dot.m.lost_hp_multiplier&&!dot.m.burstInterval)this.hit(this.fighters[dot.owner],f,Math.min(dot.m.burst_cap,Math.max(0,dot.hp0-f.hp)*dot.m.lost_hp_multiplier),dot.m,{dot:true,skill:dot.id});}
   f.dots=f.dots.filter(d=>d.life>1e-7);endLinearDotIteration(this,f);endRuleStatusDots(this);endRulePeriodicDots(this);this.previous[i]={...inp};
  }
  const [a,b]=this.fighters;if(Math.abs(a.x-b.x)<60&&Math.abs(a.y-b.y)<90&&!a.motion&&!b.motion){const dir=a.x<=b.x?-1:1,mid=(a.x+b.x)/2;a.x=clamp(mid+dir*30,45,1155);b.x=clamp(mid-dir*30,45,1155);}
  for(const f of this.fighters)this.updateGuard(f);
  const due=this.events.filter(e=>e.at<=this.t+1e-7);this.events=this.events.filter(e=>e.at>this.t+1e-7);for(const e of due){if(e.type==='attack')this.resolveAttack(e);else if(e.type==='skill_hit'){const f=this.fighters[e.owner],t=this.fighters[1-e.owner];if(f.hp>0&&Math.abs(t.x-f.x)<=e.range+22&&!this.blocked(f)){if(e.track){this.move(f,t.x-f.dir*75-f.x);this.fx('slash',t.x,t.y+100,this.hero(f.i).color,{size:160,dir:f.dir});}if(e.track)this.basicHit(f,t,{...e,damage:this.bladeDance(f,e.damage)});else this.hit(f,t,e.damage,e.m,{skill:e.id,linaDone:true});}}}
  beginRuleChannelProjectiles(this);for(const p of this.projectiles){const old=p.x,remaining=Math.max(0,p.range-p.travel),distance=Math.min(Math.max(0,p.v*dt),remaining),next=clamp(old+p.dir*distance,0,1200);observeLinearAdvance(this,p,dt,{from:old,to:next,travelBefore:p.travel});observeRuleChannelProjectile(this,p,dt,{from:old,to:next,travelBefore:p.travel});const f=this.fighters[p.owner],t=this.fighters[1-p.owner];if(old<0||old>1200||remaining<=0){p.dead=true;continue;}const collision=this.projectileCollision(p,old,next);p.x=collision?old+p.dir*collision.distance:next;p.travel+=Math.abs(p.x-old);
   if(!collision){if(p.travel>=p.range-1e-7||p.x<=0||p.x>=1200)p.dead=true;continue;}
   if(collision.type==='ward'){this.endWard(collision.target,'attack',p.owner);p.dead=true;continue;}
   if(collision.type==='fighter'){if(dispatchRuleChannelContact(this,p,collision))continue;if(withLinearContact(this,p,collision,()=>dispatchRuleLinearContact(this,p,collision)))continue;const counter=this.buff(t,'counter');if(!p.basic&&p.m.reflectable&&!p.reflected&&counter&&!counter.m.counter_type){p.owner=t.i;p.dir=-p.dir;p.reflected=true;p.travel=0;p.x=t.x+p.dir*35;t.buffs=t.buffs.filter(x=>x!==counter);this.fx('text',t.x,t.y+190,'#b5dcff',{text:'反制!'});continue;}
    if(p.basic)this.basicHit(f,t,p);else{let m={...p.m},damage=p.damage;if(m.distance_damage_per_100){damage=Math.min(m.damage_cap,damage+p.travel/100*m.distance_damage_per_100);m.stun_s=Math.min(m.stun_cap_s,m.stun_s+(m.arrowStunRate||.0006)*p.travel);}if(m.wall_bind_distance_wu&&((p.dir===1?1155-t.x:t.x-45)<m.wall_bind_distance_wu||this.zones.some(z=>z.type==='wall'&&Math.abs(z.x-t.x)<m.wall_bind_distance_wu)))m.stun_s=m.wall_bind_stun_s;
     this.updateGuard(t);const waveTotal=m.damageOverTime?damage:0,waveGuard=!!t.guard,waveEligible=t.invuln<=0;if(m.damageOverTime)damage=0;const ok=this.hit(f,t,damage,m,{skill:p.id});if(m.damageOverTime&&waveEligible){t.dots.push({owner:p.owner,id:p.id,life:m.damageOverTime,tick:.1,m:{...m,damage:waveTotal/(m.damageOverTime/.1)*(waveGuard?.2:1),damageOverTime:0,tick_interval_s:.1,knockback_wu:0,stun_s:0,chip:waveGuard},hp0:t.hp});}if(ok&&p.id==='phantom_assassin_dagger'&&this.random()<.34)this.addBuff(f,'deadlyFocus',{},10);if(ok&&m.effect==='projectile_dot')t.dots.push({owner:p.owner,id:p.id,life:m.duration_s,tick:m.tick_interval_s,m:{...m,damage:m.dot_damage,stun_s:0},hp0:t.hp});}
    p.dead=true;}}
  this.projectiles=this.projectiles.filter(p=>!p.dead);endRuleChannelProjectiles(this);
  beginRuleFields(this);beginRuleUnits(this);beginRuleChannelUnits(this);beginRulePeriodicAreas(this);for(const z of this.zones){if(dispatchRulePeriodicArea(this,z,dt)||dispatchRuleChannelUnitAdvance(this,z,dt)||dispatchRuleUnitAdvance(this,z,dt)||dispatchRuleFieldAdvance(this,z,dt))continue;const f=this.fighters[z.owner],t=this.fighters[1-z.owner],m=z.m;if(z.life<=1e-7)continue;if(['aura','ward','heal','deathWard'].includes(z.type)&&f.hp<=0){if(z.type==='ward')this.endWard(z,'owner_defeated');else z.life=0;continue;}const liveDt=Math.min(dt,z.life);z.life-=dt;z.age=(z.age||0)+liveDt;if(z.type==='trap'&&m.walkSpeed)z.x+=clamp(z.targetX-z.x,-m.walkSpeed*dt,m.walkSpeed*dt);if(z.type==='ward'&&m.follow){const speed=(m.officialSemantic?.ward_move_speed||325)*.55;z.x+=clamp(f.x-z.x,-speed*liveDt,speed*liveDt);}if(z.type==='heal'&&m.mana_per_second){f.mp=Math.max(0,f.mp-m.mana_per_second*dt);if(f.mp<=0){z.life=0;f.buffs=f.buffs.filter(b=>b.key!==z.id);}}z.tick=(z.tick||0)-liveDt;
   if(z.type==='deathWard'&&(!f.channel||f.channel.wardToken!==z.wardToken)){z.life=0;continue;}
   if(z.type==='heal'&&!this.buff(f,z.id)){z.life=0;continue;}
   if(z.type==='aura'){if(!this.buff(f,'aura')){z.life=0;continue;}z.x=f.x;}
   if(z.type==='expanding'){if(!z.hit&&Math.abs(t.x-z.x)<=z.age*m.wave_speed_wu_s&&Math.abs(t.x-z.x)<=m.radius_wu){this.hit(f,t,m.damage,m,{skill:z.id});z.hit=true;}continue;}
   if(z.type==='trap'&&z.age>=z.arm&&t.y<45&&Math.abs(t.x-z.x)<=(m.triggerRadius??m.radius_wu)+22){if(Math.abs(t.x-z.x)<=m.radius_wu+22)this.hit(f,t,m.damage,m,{skill:z.id});this.fx('ring',z.x,50,this.hero(z.owner).color,{size:m.radius_wu});z.life=0;continue;}
   if(z.tick<=1e-7){z.tick+=m.tick_interval_s||.2;if(z.type==='deathWard'){if(Math.abs(t.x-z.x)<=m.radius_wu+22){this.hit(f,t,m.damage,m,{skill:z.id,linaDone:true});this.fx('beam',z.x,80,this.hero(f.i).color,{tx:t.x,ty:t.y+80,life:.16,maxLife:.16});}}else if(['ward','heal'].includes(z.type)){if(z.type==='ward')z.healTicks++;if(z.type==='heal'||Math.abs(f.x-z.x)<=m.radius_wu){const amount=z.type==='ward'?f.maxHp*(m.officialSemantic?.heal_max_hp_pct_per_s||0)/100*m.tick_interval_s:m.heal_total/m.ticks;const healed=this.heal(f,amount,{skill:z.id,source:z.type});if(z.type==='ward'){z.healed+=healed;z.lastHealAt=this.t;}}}else if(['aura','ground_dot'].includes(z.type)){if(Math.abs(t.x-z.x)<=m.radius_wu+22&&(z.type!=='ground_dot'||t.y<45))this.hit(f,t,z.id==='juggernaut_blade_fury'?this.bladeDance(f,m.damage):m.damage,{...m,slow_duration_s:m.slow_linger_s??Math.min(m.slow_duration_s??1,m.tick_interval_s||.2)},{dot:true,skill:z.id,linaDone:true});if(m.self_damage_per_tick)this.nonlethalSelfDamage(f,m.self_damage_per_tick);}}
  }for(const z of this.zones){if(this.fighters[z.owner].hp<=0&&['aura','ward','heal','deathWard'].includes(z.type)){if(z.type==='ward')this.endWard(z,'owner_defeated');else z.life=0;}else if(z.type==='ward'&&z.life<=1e-7&&!z.ended)this.endWard(z,'expired');}this.zones=this.zones.filter(z=>z.life>1e-7);endRuleFields(this);endRuleUnits(this);endRuleChannelUnits(this);endRulePeriodicAreas(this);
  PackHP.tick(this,dt);PackHP.deaths(this);this.packCombat.endStep(this);reconcileRuleStatuses(this);reconcileRuleJobs(this);reconcileRuleAreas(this);PackHP.deaths(this);PackControl.cleanup(this);if(this.mode==='training'){for(const f of this.fighters)if(f.hp<=0){f.hp=f.maxHp;f.mp=f.maxMp;this.fx('text',f.x,220,'#fff',{text:'训练重置'});}}
  else if(a.hp<=0||b.hp<=0||this.time<=0){const diff=a.hp/a.maxHp-b.hp/b.maxHp;this.winner=Math.abs(diff)<.0001?-1:diff>0?0:1;if(this.winner>=0)this.score[this.winner]++;this.phase='roundEnd';this.phaseTime=3;this.input=[{},{}];this.history.push({round:this.round,winner:this.winner,remaining:this.time,damage:[a.damage,b.damage]});this.log('round_end',this.winner,{score:[...this.score]});}
 });}
 ai(i,dt){const f=this.fighters[i],t=this.fighters[1-i],d=Math.abs(f.x-t.x),inp={};f.aiDelay-=dt;if(f.aiDelay<=0){f.aiDelay=.12+this.random()*.16;f.aiIntent={defend:!!t.cast&&this.random()<.65,attack:d<this.hero(i).attack_range+15,jump:this.projectiles.some(p=>p.owner!==i&&Math.abs(p.x-f.x)<220)&&this.random()<.4};if(this.random()<.35){const slots=this.hero(i).abilities.map((a,s)=>s).filter(s=>!this.ability(i,s).mvp.passive&&f.cd[s]<=0&&f.mp>=this.ability(i,s).mvp.mana&&!(this.ability(i,s).valveAbilityId===5218&&f.pack?.poisonOn));if(slots.length)f.aiIntent['s'+slots[Math.floor(this.random()*slots.length)]]=true;}}
  Object.assign(inp,f.aiIntent);if(inp.defend){inp[t.x>f.x?'left':'right']=true;delete inp.attack;for(let s=0;s<4;s++)delete inp['s'+s];}else if(d>this.hero(i).attack_range*.8){inp[t.x>f.x?'right':'left']=true;}if(f.channel){for(let s=0;s<4;s++)inp['s'+s]=s===f.channel.slot;delete inp.left;delete inp.right;}this.setInput(i,inp);}
 restoreSimulation(g){
  if(!validBAreas(this,g)||!validBStatuses(this,g)||!validRulesSnapshot(this,g.heroRules,g.fighters)||!validHeroRuleResources(this,g.fighters)||!validRuleHostSnapshot(this,g))throw Error('Invalid rules namespace snapshot');
  assertPackSerializable(g);if(JSON.stringify(g.indices)!==JSON.stringify(this.indices)||!g.packClock||!Array.isArray(g.fighters)||g.fighters.length!==2||!validRulePackSnapshot(this,g)||!PackHP.validate(g)||!PackControl.validate(g))throw Error('Invalid simulation snapshot');const clock=g.packClock;if(!['seed','seq','logSeq'].every(k=>Number.isSafeInteger(clock[k])&&clock[k]>=0)||!Array.isArray(clock.events)||clock.events.length>256||!Array.isArray(clock.input)||clock.input.length!==2||!Array.isArray(clock.previous)||clock.previous.length!==2||!Number.isFinite(clock.hitstop))throw Error('Invalid simulation clock');
  const saved=clone(g);for(const key of ['fighters','score','round','time','t','frame','phase','phaseTime','winner','paused','projectiles','zones','effects','shake','history'])this[key]=saved[key];this.packCore=saved.packCore||null;this.packModules=saved.packModules;this.packState=saved.packState||null;for(const key of ['seed','seq','events','input','previous','hitstop','logSeq'])this[key]=saved.packClock[key];restoreRulesSnapshot(this,saved.heroRules);restoreRuleHostSnapshot(this,saved.heroHost,saved.packClock.heroEpoch);restoreRuleLinearSnapshot(this,saved.packClock.legacyLinear);restoreRuleChargeSnapshot(this,saved.packClock.legacyCharge);restoreRuleLinearDotSnapshot(this,saved.packClock.legacyDot);restoreRuleFieldSnapshot(this,saved.packClock.legacyFields);restoreRuleUnitSnapshot(this,saved.packClock.legacyUnits);restoreRuleStatusDotSnapshot(this,saved.packClock.legacyStatusDots);restoreRuleChannelSnapshot(this,saved.packClock.legacyChannels);restoreRulePeriodicSnapshot(this,saved.packClock.legacyPeriodic);restoreBStatuses(this,saved.packClock.bStatuses);restoreBAreas(this,saved.packClock.bAreas);this.logs=[];return this;
 }
 snapshot(){const bAreas=snapshotBAreas(this),bStatuses=snapshotBStatuses(this),heroHost=ruleHostSnapshot(this),linear=ruleLinearSnapshot(this),charge=ruleChargeSnapshot(this),dot=ruleLinearDotSnapshot(this),fields=ruleFieldSnapshot(this),units=ruleUnitSnapshot(this),statusDots=ruleStatusDotSnapshot(this),channels=ruleChannelSnapshot(this),periodic=rulePeriodicSnapshot(this);return clone({heroRules:rulesSnapshot(this),...(heroHost?{heroHost}:{}),...(this.packCore?{packCore:this.packCore}:{}),...(this.packModules||this.packCore?{packModules:this.packModules}:{}),packClock:{...(bAreas?{bAreas}:{}),...(bStatuses?{bStatuses}:{}),...(periodic?{legacyPeriodic:periodic}:{}),...(channels?{legacyChannels:channels}:{}),...(statusDots?{legacyStatusDots:statusDots}:{}),...(units?{legacyUnits:units}:{}),...(fields?{legacyFields:fields}:{}),...(dot?{legacyDot:dot}:{}),...(charge?{legacyCharge:charge}:{}),...(linear?{legacyLinear:linear}:{}),...(heroHost?{heroEpoch:ruleHostEpochSnapshot(this)}:{}),seed:this.seed,seq:this.seq,events:this.events,input:this.input,previous:this.previous,hitstop:this.hitstop,logSeq:this.logSeq},...(this.packState?{packState:this.packState}:{}),indices:this.indices,mode:this.mode,score:this.score,round:this.round,time:this.time,t:this.t,frame:this.frame,phase:this.phase,phaseTime:this.phaseTime,winner:this.winner,paused:this.paused,fighters:this.fighters,projectiles:this.projectiles,zones:this.zones,effects:this.effects,shake:this.shake,history:this.history});}
}
