// Coordination only: same origin/device/browser. This is not strong authentication.
export function secureRoomCode(random=globalThis.crypto){const words=new Uint32Array(1),limit=Math.floor(0x100000000/1000000)*1000000;for(let i=0;i<128;i++){random.getRandomValues(words);if(words[0]<limit)return String(words[0]%1000000).padStart(6,'0');}throw Error('无法生成房号，请重试');}
export class LocalRoomRegistry{
 constructor({indexedDB=globalThis.indexedDB,random=globalThis.crypto,now=()=>Date.now(),name='dota-duel-local-rooms-v2'}={}){Object.assign(this,{indexedDB,random,now,name});this.opening=null;}
 open(){if(this.opening)return this.opening;if(!this.indexedDB)return Promise.reject(Error('本浏览器无法安全预约本机房间，请使用同屏对战'));this.opening=new Promise((resolve,reject)=>{const r=this.indexedDB.open(this.name,1);r.onupgradeneeded=()=>r.result.createObjectStore('registry');r.onsuccess=()=>{r.result.onversionchange=()=>{r.result.close();this.opening=null;};resolve(r.result);};r.onerror=()=>{this.opening=null;reject(Error('无法读取本机房号注册表'));};r.onblocked=()=>{this.opening=null;reject(Error('本机房号注册表被占用，请关闭旧版本窗口'));};});return this.opening;}
 async atomic(change){const db=await this.open();const outcome=await new Promise((resolve,reject)=>{let result;const t=db.transaction('registry','readwrite'),store=t.objectStore('registry'),read=store.get('state');t.oncomplete=()=>resolve(result);t.onabort=t.onerror=()=>reject(Error('本机房号预约失败，请重试'));read.onsuccess=()=>{const state=read.result||{rooms:{},attempts:[]};const now=this.now();for(const [code,r]of Object.entries(state.rooms))if(r.expires<=now)delete state.rooms[code];state.attempts=state.attempts.filter(at=>at>now-60000);try{result=change(state,now);store.put(state,'state');}catch(e){result={error:e.message};store.put(state,'state');}};});if(outcome?.error)throw Error(outcome.error);return outcome;}
 reserve(owner){return this.atomic((s,now)=>{if(Object.keys(s.rooms).length>=64)return {error:'本机房间过多，请关闭旧房间或稍后重试'};for(let i=0;i<32;i++){const code=secureRoomCode(this.random);if(s.rooms[code])continue;const r={code,id:this.random.randomUUID(),owner,expires:now+600000,guest:null};s.rooms[code]=r;return {...r};}return {error:'房号碰撞，请重试'};});}
 claim(code,owner){return this.atomic((s,now)=>{if(s.attempts.length>=10)return {error:'加入尝试过多，请一分钟后重试'};s.attempts.push(now);if(!/^\d{6}$/.test(code))return {error:'请输入六位数字房号'};const r=s.rooms[code];if(!r)return {error:'本机房间不存在或口令已过期'};if(r.owner===owner)return {error:'不能加入自己创建的窗口'};if(r.guest&&r.guest.owner!==owner&&r.guest.expires>now)return {error:'房间已有两位玩家'};r.guest={owner,expires:now+20000};return {...r};});}
 verifyGuest(code,id,owner){return this.atomic((s,now)=>{const r=s.rooms[code];return !!r&&r.id===id&&r.guest?.owner===owner&&r.guest.expires>now;});}
 renew(code,id,owner){return this.atomic((s,now)=>{const r=s.rooms[code];if(!r||r.id!==id||r.guest?.owner!==owner)return false;r.guest.expires=now+20000;return true;});}
 release(code,id,owner){return this.atomic(s=>{const r=s.rooms[code];if(!r||r.id!==id)return false;if(r.owner===owner){delete s.rooms[code];return true;}if(r.guest?.owner===owner){r.guest=null;return true;}return false;});}
}
