import {NET_VERSION} from './net-version.js';
export const matchRequestId=()=>globalThis.crypto.randomUUID();
export const resultPayload=(game,reason='')=>{const rounds=(game.history||[]).map((r,i)=>({number:i+1,winner:r.winner,remainingMs:Math.max(0,Math.min(99000,Math.round(r.remaining*1000)))})),score=[0,0];for(const r of rounds)if(r.winner>=0)score[r.winner]++;const winner=score.findIndex(n=>n>=2),complete=winner>=0;return {version:NET_VERSION,outcome:complete?'completed':'aborted',rounds,score,winner:complete?winner:-1,reason:complete?'':reason||'cancelled'};};
export const recordStatusText=status=>({confirmed:'战绩已保存 · 双方一致',recorded:'战绩已保存 · 客户端上报',pending:'已提交，等待对方确认',disputed:'双方战果不一致，未计胜负',aborted:'比赛已中止，未计胜负',in_progress:'比赛进行中',awaiting_ready:'等待双方确认开战',awaiting_report:'等待房主保存战绩',saving:'正在保存战绩…',local:'已保存本机，尚未同步服务器',error:'尚未保存到服务器，可重试'}[status]||'尚未保存到服务器');
export class MatchAPI{
 constructor({fetcher=(...a)=>globalThis.fetch(...a),base,storage=globalThis.sessionStorage}={}){this.fetcher=fetcher;this.base=base??(['127.0.0.1','localhost'].includes(globalThis.location?.hostname)?'http://127.0.0.1:18082/api/v1':'https://api.dotapk.lol/api/v1');this.storage=storage;this.credentials=null;this.sessionTask=null;}
 async request(path,body,method='POST',{unauthenticated=false,keepalive=false}={}){
  if(!unauthenticated)await this.session();const response=await this.fetcher(this.base+'/'+path,{method,headers:{'Content-Type':'application/json',...(!unauthenticated?{Authorization:'Bearer '+this.credentials.token}:{})},...(body!==undefined&&body!==null?{body:JSON.stringify(body)}:{}),cache:'no-store',keepalive,...(globalThis.AbortSignal?.timeout?{signal:globalThis.AbortSignal.timeout(10000)}:{})});
  const data=await response.json().catch(()=>({error:'战绩服务没有返回有效数据'}));if(!response.ok){const e=Error(data.error||'战绩服务暂不可用');e.status=response.status;throw e;}return data;
 }
 session(){if(this.credentials)return Promise.resolve(this.credentials);if(this.sessionTask)return this.sessionTask;this.sessionTask=this.request('sessions',{},'POST',{unauthenticated:true}).then(v=>{if(!/^[a-f0-9]{64}$/.test(v.playerId)||typeof v.token!=='string'||v.token.length<32)throw Error('战绩会话无效');this.credentials=v;return v;}).finally(()=>this.sessionTask=null);return this.sessionTask;}
 createPVE(hero,opponentHero,requestId){return this.request('matches/pve',{requestId,version:NET_VERSION,hero,opponentHero,aiDifficulty:'normal'});}
 createLocal(hero,opponentHero,transport,requestId){return this.request('matches/local',{requestId,version:NET_VERSION,hero,opponentHero,transport});}
 createMatch(roomId,requestId){return this.request('rooms/'+roomId+'/matches',{requestId,version:NET_VERSION});}
 ready(id){return this.request('matches/'+id+'/ready',{version:NET_VERSION});}
 getMatch(id){return this.request('matches/'+id,null,'GET');}
 submit(id,payload,keepalive=false){return this.request('matches/'+id+'/results',payload,'POST',{keepalive});}
}

export class MatchRecord{
 constructor({mode,transport,heroes,service=null,match=null,observer=false,localId=null,storage=globalThis.localStorage,onchange=()=>{},schedule=(fn,ms)=>globalThis.setTimeout(fn,ms)}){Object.assign(this,{mode,transport,heroes,service,match,observer,storage,onchange,schedule});this.heroes=[...heroes];this.localId=localId||matchRequestId();this.startedAt=Date.now();this.status=match?.status||'local';this.error='';this.payload=null;this.sending=null;this.polling=false;this.creation=null;}
 view(){return {localId:this.localId,matchId:this.match?.id||null,mode:this.mode,transport:this.match?.transport||this.transport,observer:this.observer,participantKinds:this.match?.participantKinds||null,reporterPlayerId:this.match?.reporterPlayerId||null,heroes:[...this.heroes],version:NET_VERSION,startedAt:this.startedAt,endedAt:this.endedAt||null,durationMs:this.endedAt?this.endedAt-this.startedAt:0,status:this.status,error:this.error,result:this.payload,trust:this.match?.trust||'local_only',reported:this.match?.reported||null};}
 emit(){if(this.payload&&!this.observer){try{const previous=JSON.parse(this.storage?.getItem('dota-duel-history')||'[]'),id=this.match?.id,same=e=>e.localId===this.localId||id&&e.matchId===id,existing=previous.find(same),entries=previous.filter(e=>!same(e)),terminal=['confirmed','recorded','disputed','aborted'];entries.unshift(existing&&terminal.includes(existing.status)&&!terminal.includes(this.status)?existing:this.view());this.storage?.setItem('dota-duel-history',JSON.stringify(entries.slice(0,200)));}catch{}}this.onchange(this.view());}
 beginPVE(){return this.begin(()=>this.service.createPVE(this.heroes[0],this.heroes[1],this.localId));}
 beginLocal(){return this.begin(()=>this.service.createLocal(this.heroes[0],this.heroes[1],this.transport,this.localId));}
 begin(create){if(this.observer)return Promise.resolve(this.view());this.createFactory=create;this.status='saving';this.error='';this.emit();this.creation=Promise.resolve().then(create).then(match=>{this.match=match;this.status=match.status;this.error='';this.emit();}).catch(e=>{this.status='local';this.error='战绩服务不可用，本局仅保留本机记录：'+e.message;this.emit();});return this.creation;}
 observeHost(view){if(!this.observer||view?.localId!==this.localId||view.version!==NET_VERSION||view.mode!=='pvp'||view.transport!=='broadcastchannel'||JSON.stringify(view.heroes)!==JSON.stringify(this.heroes)||view.matchId!==null&&!/^[a-f0-9]{64}$/.test(view.matchId||'')||!['saving','local','error','in_progress','recorded','aborted'].includes(view.status))return false;if(['recorded','aborted'].includes(this.status)&&view.status!==this.status)return false;this.match=view.matchId?{id:view.matchId,status:view.status,trust:view.trust,transport:view.transport,participantKinds:view.participantKinds,reporterPlayerId:view.reporterPlayerId}:null;this.status=view.status;this.error=String(view.error||'').slice(0,240);this.emit();return true;}
 finish(game,reason=''){if(this.observer){if(!['recorded','aborted','error','local'].includes(this.status))this.status='awaiting_report';this.emit();return Promise.resolve(this.view());}if(this.payload)return this.sending||Promise.resolve(this.view());this.payload=resultPayload(game,reason);this.endedAt=Date.now();this.emit();return this.submit(false);}
 async submit(retryCreation=true){if(this.observer)return this.view();if(this.sending)return this.sending;const work=async()=>{if(this.creation)await this.creation;if(retryCreation&&!this.match&&this.createFactory)await this.begin(this.createFactory);if(!this.service||!this.match){this.status='local';this.emit();return this.view();}this.status='saving';this.error='';this.emit();try{this.match=await this.service.submit(this.match.id,this.payload,true);this.status=this.match.status;this.error='';this.emit();this.watch();}catch(e){this.status='error';this.error=e.message;this.emit();}return this.view();};this.sending=work().finally(()=>this.sending=null);return this.sending;}
 watch(){if(this.polling||this.status!=='pending')return;this.polling=true;this.schedule(async()=>{this.polling=false;try{this.match=await this.service.getMatch(this.match.id);this.status=this.match.status;this.error='';this.emit();this.watch();}catch(e){this.status='error';this.error=e.message;this.emit();}},2000);}
}
