import {isActiveHero,validHeroPair} from './hero-registry.js';
import {GAME_COMPATIBILITY,compatibleGame,compatibleMatch,compatibleRoom} from './compatibility.js';
import {MatchAPI,matchRequestId} from './match-api.js';
import {ProbeWindow,qualityDecision,validPolicy,validQuality} from './net-quality.js';
import {RoomSelection} from './room-selection.js';
import {isCasualPolicy,qualityHint} from './net-quality.js';
import {NET_VERSION} from './net-version.js';
const randomToken=()=>crypto.randomUUID()+crypto.randomUUID();
// Native browser fetch requires Window as its receiver, not PeerSession.
const browserFetch=(...args)=>globalThis.fetch(...args);
export class PeerSession{
 constructor({role,hero,policy,roomFirst=false,available=true,onstate=()=>{},onmessage=()=>{},onstart=()=>{},onfault=()=>{},fetcher=browserFetch,Peer=globalThis.RTCPeerConnection,service=null,iceServers=[{urls:'stun:stun.cloudflare.com:3478'}]}={}){Object.assign(this,{role,hero,policy,roomFirst,available,onstate,onmessage,onstart,onfault,fetcher,Peer,iceServers});if(!isActiveHero(hero))throw Error('英雄尚未开放');this.peerCompatibility=null;this.id=randomToken();this.token=randomToken();this.service=service||new MatchAPI({fetcher});this.roomId='';this.match=null;this.matchRequest=null;this.code='';this.status='idle';this.error='';this.stopped=false;this.connected=false;this.ready=false;this.peerReady=false;this.peerAvailable=true;this.orientationHold=false;this.peerVersion=null;this.peerHero=null;this.peerQuality=null;this.peerQualityAt=0;this.lastSeen=0;this.probes=new ProbeWindow(roomFirst?{window:12,timeoutMs:3000}:{});this.foreground=true;this.peerForeground=true;this.lastControlSeen=0;this.congestedAt=null;this.draft=roomFirst?new RoomSelection(this):null;this.fighting=false;this.sequence=0;this.lastGameSeq=-1;this.seenEpoch='';this.abort=new AbortController();this.timers=new Set();}
 emit(){this.onstate(this.info());}
 later(fn,ms){const t=setTimeout(()=>{this.timers.delete(t);if(!this.stopped)fn();},ms);this.timers.add(t);return t;}
 async api(path,body,method='POST',options={}){if(this.stopped)throw Error('连接已关闭');const data=await this.service.request(path,body,method,options);if(this.stopped){if((this.role==='host'&&path==='rooms'||this.roomFirst&&path==='rooms/join')&&method==='POST'&&/^[a-f0-9]{64}$/.test(data?.id||'')){this.roomId=data.id;this.releaseRoom();}throw Error('连接已关闭');}return data;}
 async setup(){if(!this.Peer)throw Error('当前浏览器不支持WebRTC');this.pc=new this.Peer({iceServers:this.iceServers});this.pc.onconnectionstatechange=()=>{if(this.stopped)return;const s=this.pc.connectionState;if(s==='failed'||s==='closed'||s==='disconnected')this.fail('P2P连接中断，请重新建房并加入');};if(this.role==='host'){this.bind(this.pc.createDataChannel('control',{ordered:true}));this.bind(this.pc.createDataChannel('frames',{ordered:false,maxRetransmits:0}));}else this.pc.ondatachannel=e=>this.bind(e.channel);}
 bind(ch){if(!['control','frames'].includes(ch.label)){ch.close();return;}this[ch.label]=ch;ch.onopen=()=>{if(this.control?.readyState==='open'&&this.frames?.readyState==='open'&&!this.connected){this.connected=true;this.status='probing';this.lastSeen=this.lastControlSeen=performance.now();this.sendHello();this.tick();this.emit();}};ch.onclose=()=>{if(!this.stopped)this.fail('数据通道已关闭，请重新连接');};ch.onerror=()=>this.fail('数据通道发生错误');ch.onmessage=e=>this.receive(e.data,ch.label);}
 async description(){if(this.pc.iceGatheringState!=='complete')await new Promise(resolve=>{const done=()=>{clearTimeout(t);this.pc?.removeEventListener('icegatheringstatechange',change);resolve();},change=()=>{if(this.pc.iceGatheringState==='complete')done();},t=setTimeout(done,6500);this.pc.addEventListener('icegatheringstatechange',change);});return this.pc.localDescription?.toJSON();}
 async create(){try{this.status='signaling';this.emit();await this.setup();await this.pc.setLocalDescription(await this.pc.createOffer());const offer=await this.description();const permit=this.service.authorizeRoster?await this.service.authorizeRoster():null,rosterFields=permit?.fields||await this.service.rosterFields?.()||{};const r=await this.api('rooms',{...rosterFields,requestId:this.id,hero:this.hero,offer,version:NET_VERSION,policy:this.policy},'POST',{registryPermit:permit});this.roomId=/^[a-f0-9]{64}$/.test(r?.id||'')?r.id:'';if(!compatibleRoom(r,{role:this.role,hero:this.hero}))throw Error('房间可玩名单不一致');this.code=r.code;this.status='waiting';this.emit();this.deadline=performance.now()+120000;this.poll();}catch(e){if(!this.stopped)this.fail(e.message);}}
 async join(code){try{if(!/^\d{6}$/.test(code))throw Error('请输入六位数字房间号');this.code=code;this.status='signaling';this.emit();const permit=this.service.authorizeRoster?await this.service.authorizeRoster():null,rosterFields=permit?.fields||await this.service.rosterFields?.()||{};const r=await this.api('rooms/join',{...rosterFields,code:this.code,version:NET_VERSION,hero:this.hero},'POST',{registryPermit:permit});if(r.version!==NET_VERSION||!compatibleRoom(r,{role:this.role,hero:this.hero})||this.roomFirst&&!isCasualPolicy(r.policy))throw Error('双方版本不一致，请刷新到同一版本');this.roomId=r.id;this.policy=r.policy;await this.setup();await this.pc.setRemoteDescription(r.offer);await this.pc.setLocalDescription(await this.pc.createAnswer());const answer=await this.description();await this.api('rooms/'+this.roomId+'/answer',{answer,version:NET_VERSION});this.status='connecting';this.emit();this.later(()=>{if(!this.connected)this.fail('直连超时；当前网络可能需要TURN中继，尚未配置');},20000);}catch(e){if(!this.stopped)this.fail(e.message);}}
 async poll(){if(this.stopped||this.connected)return;if(performance.now()>this.deadline){this.fail('等待加入超时，请重新建房');return;}try{const r=await this.api('rooms/'+this.roomId,null,'GET');if(r.answer){await this.pc.setRemoteDescription(r.answer);this.status='connecting';this.emit();this.later(()=>{if(!this.connected)this.fail('直连超时；请重试或换网络，尚未配置TURN');},20000);return;}if(performance.now()>this.deadline)throw Error('等待加入超时，请重新建房');this.pollAttempt=(this.pollAttempt||0)+1;this.later(()=>this.poll(),Math.min(6000,1000*2**Math.min(this.pollAttempt,3)));}catch(e){if(!this.stopped)this.fail(e.message);}}
 sendHello(){return this.controlSend({type:'hello',version:NET_VERSION,compatibility:GAME_COMPATIBILITY,hero:this.hero,policy:this.policy,available:this.available,...(this.roomFirst?{selectionMode:'room-first-v1',foreground:this.foreground}:{})});}
 controlSend(v){if(this.control?.readyState!=='open'||this.control.bufferedAmount>262144)return false;this.control.send(JSON.stringify(v));return true;}
 fastSend(v){if(this.frames?.readyState!=='open'||this.frames.bufferedAmount>131072)return false;this.frames.send(JSON.stringify(v));return true;}
 receive(raw,channel){if(this.stopped||typeof raw!=='string'||raw.length>65536)return;let m;try{m=JSON.parse(raw);}catch{return;}if(!m||typeof m.type!=='string')return;const now=performance.now();this.lastSeen=now;
  if(channel==='control'&&['hello','quality','availability','foreground','selection','prepare','prepared','start','reject'].includes(m.type))this.lastControlSeen=now;
  if(m.type==='hello'&&channel==='control'){if(m.version!==NET_VERSION||!compatibleGame(m.compatibility)||!isActiveHero(m.hero)||JSON.stringify(m.policy)!==JSON.stringify(this.policy)||this.roomFirst&&(m.selectionMode!=='room-first-v1'||!isCasualPolicy(m.policy))){this.fail('双方版本、英雄或房间规则不一致');return;}this.peerCompatibility=m.compatibility;this.peerVersion=m.version;this.peerHero=m.hero;this.peerAvailable=m.available!==false;this.peerForeground=m.foreground!==false;this.emit();return;}
  if(m.type==='ping'&&channel==='frames'){if(Number.isSafeInteger(m.id))this.fastSend({type:'pong',id:m.id});return;}
  if(m.type==='pong'&&channel==='frames'){this.probes.pong(m.id,now);return;}
  if(m.type==='quality'&&channel==='control'){if(!validQuality(m.q,this.roomFirst?3000:1200))return;this.peerQuality=m.q;this.peerQualityAt=now;return;}
  if(m.type==='availability'&&channel==='control'&&typeof m.value==='boolean'){this.peerAvailable=m.value;if(!m.value){if(this.pendingEpoch||this.fighting)this.orientationHold=true;this.peerReady=false;if(this.role==='host')this.pendingEpoch=null;}this.emit();return;}
  if(m.type==='foreground'&&channel==='control'&&this.roomFirst&&typeof m.value==='boolean'){this.peerForeground=m.value;if(!m.value){this.peerReady=false;if(this.pendingEpoch||this.fighting)this.orientationHold=true;if(this.role==='host')this.pendingEpoch=null;}this.emit();return;}
  if(m.type==='selection'&&channel==='control'&&this.draft&&this.peerVersion===NET_VERSION){this.draft.receive(m);return;}
  if(m.type==='ready'&&channel==='control'&&!this.roomFirst){this.peerReady=m.value===true&&this.peerAvailable;this.emit();return;}
  if(m.type==='prepare'&&channel==='control'&&this.role==='guest'&&(!this.draft||m.selectionEpoch===this.draft.epoch)){this.acceptPrepare(m);return;}
  if(m.type==='prepared'&&channel==='control'&&this.role==='host'&&m.epoch===this.pendingEpoch&&m.matchId===this.match?.id&&(!this.draft||m.selectionEpoch===this.draft.epoch)){this.commitStart(m);return;}
  if(m.type==='start'&&channel==='control'&&this.role==='guest'&&m.epoch===this.pendingEpoch&&m.matchId===this.match?.id&&(!this.draft||m.selectionEpoch===this.draft.epoch)&&this.connected){this.verifyStart(m);return;}
  if(m.type==='reject'&&channel==='control'&&(!this.draft||m.selectionEpoch===this.draft.epoch&&m.epoch===this.pendingEpoch)){this.pendingEpoch=null;this.error='开战检查未通过：'+String(m.reason||'请重新准备').slice(0,100);this.emit();return;}
  if(m.type==='game'&&this.peerVersion===NET_VERSION&&compatibleGame(this.peerCompatibility)&&this.fighting&&m.epoch===this.seenEpoch&&m.value&&typeof m.value.type==='string'){if(channel==='frames'||m.value.type==='snapshot'){if(!Number.isSafeInteger(m.seq)||m.seq<=this.lastGameSeq)return;this.lastGameSeq=m.seq;}this.onmessage({...m.value,sender:'p2p-peer'});}
 }
 tick(){if(this.stopped||!this.connected)return;const now=performance.now();if(this.roomFirst?now-this.lastControlSeen>10000:now-this.lastSeen>4000){this.fail(this.roomFirst?'可靠连接超过10秒未响应':'对方超过4秒未响应，比赛已暂停');return;}if(!this.peerVersion)this.sendHello();if(this.roomFirst){if(this.control?.bufferedAmount>262144){this.congestedAt??=now;if(now-this.congestedAt>6000){this.fail('可靠连接持续拥塞');return;}}else this.congestedAt=null;}this.fastSend({type:'ping',id:this.probes.sent(now)});const q=this.probes.summary(now);this.controlSend({type:'quality',q:{...q,last:undefined}});if(!this.gate().ok&&this.ready){this.ready=false;this.controlSend({type:'ready',value:false});}this.draft?.tick();this.emit();this.later(()=>this.tick(),350);}
 gate(){if(this.roomFirst){if(!isCasualPolicy(this.policy))return {ok:false,reason:'房间规则不一致'};if(!this.connected||this.control?.readyState!=='open'||this.frames?.readyState!=='open'||this.peerVersion!==NET_VERSION||!compatibleGame(this.peerCompatibility))return {ok:false,reason:'等待双方连接与版本校验'};if(this.control.bufferedAmount>262144)return {ok:false,reason:'可靠连接暂时拥塞'};if(performance.now()-this.lastControlSeen>10000)return {ok:false,reason:'可靠连接超过10秒未响应'};if(!this.foreground||!this.peerForeground)return {ok:false,reason:'返回游戏后继续'};if(!this.available||!this.peerAvailable)return {ok:false,reason:'等待双方横屏'};if(['selecting','fighting'].includes(this.draft.phase)&&!this.draft.materialsReady())return {ok:false,reason:'等待双方素材就绪'};return {ok:true,reason:'已连接，选择英雄'};}if(!this.available)return {ok:false,reason:'请横屏后重新准备'};if(!this.peerAvailable)return {ok:false,reason:'等待对方恢复横屏并重新准备'};const now=performance.now(),q=this.probes.summary(now);if(!this.connected||this.peerVersion!==NET_VERSION||!compatibleGame(this.peerCompatibility))return {ok:false,reason:'等待双方连接与版本校验'};const own=qualityDecision(q,this.policy,q.last===null?Infinity:now-q.last);if(!own.ok)return own;const peer=qualityDecision(this.peerQuality,this.policy,now-this.peerQualityAt);return peer.ok?own:{ok:false,reason:'对方：'+peer.reason};}
 // Only the host can cancel preparation. A guest keeps the epoch so an already
 // committed start can be reconciled as paused instead of stranding one peer in the lobby.
 setAvailable(value){value=!!value;if(this.available===value)return;this.available=value;if(!value){if(this.pendingEpoch||this.fighting)this.orientationHold=true;this.ready=false;if(this.role==='host')this.pendingEpoch=null;}this.controlSend({type:'availability',value});if(!value)this.controlSend({type:'ready',value:false});this.emit();}
 setForeground(value){value=!!value;this.foreground=value;if(!value){if(this.pendingEpoch||this.fighting)this.orientationHold=true;this.ready=false;if(this.role==='host')this.pendingEpoch=null;}this.controlSend({type:'foreground',value});this.emit();}
 setReady(value=true){if(this.draft)return value?this.draft.lock():false;if(value&&!this.gate().ok)return false;this.ready=value;if(value)this.orientationHold=false;this.pendingEpoch=null;this.controlSend({type:'ready',value});this.emit();return true;}
 start(){if(this.draft&&(this.draft.phase!=='selecting'||!this.draft.entered||!this.draft.peerEntered||!this.draft.locked||!this.draft.peerLocked))return false;if(this.role!=='host'||!this.ready||!this.peerReady||!this.gate().ok||this.pendingEpoch)return false;const epoch=crypto.randomUUID();this.pendingEpoch=epoch;this.prepareMatch(epoch);this.later(()=>{if(this.pendingEpoch===epoch){this.pendingEpoch=null;this.error='开战确认超时，可重试同一场比赛';this.emit();}},this.roomFirst?60000:20000);return true;}
 async prepareMatch(epoch){try{this.matchRequest??=matchRequestId();const match=await this.service.createMatch(this.roomId,this.matchRequest,this.draft?.epoch);if(this.stopped||this.pendingEpoch!==epoch)return;if(!compatibleMatch(match)||this.draft&&(match.selectionEpoch!==this.draft.epoch||match.players?.[0]?.hero!==this.hero||match.players?.[1]?.hero!==this.peerHero))throw Error('比赛可玩名单不一致');this.match=match;if(!['awaiting_ready','in_progress'].includes(match.status))throw Error('上一局尚未完成或比赛已过期');await this.service.ready(match.id);if(this.stopped||this.pendingEpoch!==epoch)return;this.controlSend({type:'prepare',epoch,matchId:match.id,...(this.draft?{selectionEpoch:this.draft.epoch}:{})});this.emit();}catch(e){this.startFault(e,epoch);}}
 async acceptPrepare(m){const epoch=m.epoch;if(!this.ready||!this.peerReady||!this.gate().ok||typeof epoch!=='string'||!/^([a-f0-9]{64})$/.test(m.matchId||'')){this.controlSend({type:'reject',reason:'双方尚未准备好',epoch:m.epoch,...(this.draft?{selectionEpoch:this.draft.epoch}:{})});return;}try{this.pendingEpoch=epoch;const match=await this.service.getMatch(m.matchId);if(this.stopped||this.pendingEpoch!==epoch)return;if(!compatibleMatch(match)||this.draft&&match.selectionEpoch!==this.draft.epoch||match.roomId!==this.roomId||match.version!==NET_VERSION||match.players?.[0]?.hero!==this.peerHero||match.players?.[1]?.hero!==this.hero)throw Error('比赛与房间英雄不一致');this.match=await this.service.ready(match.id);if(this.match.status!=='in_progress')throw Error('服务器尚未确认双方开战');if(this.stopped||this.pendingEpoch!==epoch||!this.ready||!this.gate().ok)return;this.controlSend({type:'prepared',epoch,matchId:match.id,...(this.draft?{selectionEpoch:this.draft.epoch}:{})});}catch(e){this.controlSend({type:'reject',reason:e.message,epoch:m.epoch,...(this.draft?{selectionEpoch:this.draft.epoch}:{})});this.startFault(e,epoch);}}
 async commitStart(m){try{const match=await this.service.getMatch(m.matchId);if(this.stopped||this.pendingEpoch!==m.epoch)return;if(!compatibleMatch(match)||this.draft&&match.selectionEpoch!==this.draft.epoch||match.roomId!==this.roomId||match.version!==NET_VERSION||match.players?.[0]?.hero!==this.hero||match.players?.[1]?.hero!==this.peerHero||match.status!=='in_progress'||!this.ready||!this.peerReady||!this.gate().ok)throw Error('开战条件已变化，请重新准备');this.match=match;this.pendingEpoch=null;this.controlSend({type:'start',epoch:m.epoch,matchId:match.id,...(this.draft?{selectionEpoch:this.draft.epoch}:{})});this.begin(m.epoch);}catch(e){this.startFault(e,m.epoch);}}
 async verifyStart(m){try{const match=await this.service.getMatch(m.matchId);if(this.stopped||this.pendingEpoch!==m.epoch)return;const orientationPause=this.orientationHold||!this.available||!this.peerAvailable||!this.foreground||!this.peerForeground;if(!compatibleMatch(match)||this.draft&&match.selectionEpoch!==this.draft.epoch||match.version!==NET_VERSION||match.roomId!==this.roomId||match.players?.[0]?.hero!==this.peerHero||match.players?.[1]?.hero!==this.hero||match.status!=='in_progress'||(!orientationPause&&(!this.ready||!this.gate().ok)))throw Error('服务器未确认开战');this.match=match;this.pendingEpoch=null;this.begin(m.epoch);}catch(e){this.startFault(e,m.epoch);}}
 startFault(e,epoch){if(this.stopped||this.pendingEpoch!==epoch)return;this.pendingEpoch=null;this.error='战绩服务：'+e.message;this.emit();}
 begin(epoch){if(!validHeroPair([this.hero,this.peerHero])){this.fail('英雄尚未开放');return;}const pauseForOrientation=this.orientationHold||!this.available||!this.peerAvailable||!this.foreground||!this.peerForeground;this.orientationHold=false;this.draft?.started();this.seenEpoch=this.match?.id||epoch;this.sentTerminal=false;this.sequence=0;this.lastGameSeq=-1;this.fighting=true;this.ready=false;this.peerReady=false;this.error='';this.onstart({match:this.match,service:this.service,pauseForOrientation,picks:this.role==='host'?[this.hero,this.peerHero]:[this.peerHero,this.hero]});this.emit();}
 sendGame(value){const packet={type:'game',epoch:this.seenEpoch,seq:++this.sequence,value};if(value.type==='snapshot'&&value.snapshot?.phase==='matchEnd'){if(this.sentTerminal)return true;const sent=this.controlSend(packet);if(sent)this.sentTerminal=true;return sent;}return value.type==='snapshot'?this.fastSend(packet):this.controlSend(packet);}
 returnToLobby(){this.orientationHold=false;this.match=null;this.matchRequest=null;this.fighting=false;this.ready=false;this.peerReady=false;this.pendingEpoch=null;this.emit();}
 info(){const now=performance.now();return {role:this.role,code:this.code,roomId:this.roomId,matchId:this.match?.id||null,status:this.status,error:this.error,connected:this.connected,ready:this.ready,peerReady:this.peerReady,available:this.available,peerAvailable:this.peerAvailable,version:this.peerVersion,hero:this.peerHero,policy:this.policy,quality:this.probes.summary(now),peerQuality:this.peerQuality,gate:this.gate(),fighting:this.fighting,transport:'WebRTC DataChannel',...(this.draft?{selection:this.draft.info(),networkHint:qualityHint(this.probes.summary(now),now-(this.probes.summary(now).last??-Infinity))}:{})};}
 fail(reason){if(this.stopped)return;this.draft?.cancel();this.error=reason;this.status='failed';this.connected=false;this.ready=false;this.peerReady=false;this.fighting=false;this.emit();this.onfault(reason);this.releaseRoom();this.shutdown();}
 shutdown(){this.stopped=true;for(const t of this.timers)clearTimeout(t);this.timers.clear();this.abort.abort();this.control?.close();this.frames?.close();this.pc?.close();}
 releaseRoom(){if(this.roomId&&(this.role==='host'||this.roomFirst)&&!this.roomReleased){this.roomReleased=true;this.service.request('rooms/'+this.roomId,null,'DELETE',{keepalive:true}).catch(()=>{});}}
 close(){this.draft?.cancel();this.releaseRoom();this.shutdown();}
}
