const controlTypes=['stun','root','hex','fear','taunt'];
const actionReasons=['control','input_cancel','movement','action'];
const controlState=e=>{const s=e.enableHPLifecycle();s.controls??=[];s.actionRevisions??=[Object.fromEntries(actionReasons.map(k=>[k,0])),Object.fromEntries(actionReasons.map(k=>[k,0]))];return s;};
const controlActor=(e,f)=>{if(!f||![0,1].includes(f.i)||e.fighters[f.i]!==f)throw Error('Invalid control actor');};
const controlEnabled=(e,f,c)=>c.life>1e-8&&(c.pierces||!e.property(f,'debuffImmune'));
export const PackControl={
 apply(e,f,{owner,key,type,duration,pierces=false,dispel='strong'}){controlActor(e,f);if(![0,1].includes(owner)||typeof key!=='string'||!key||key.length>128||!controlTypes.includes(type)||!Number.isFinite(duration)||duration<=0||typeof pierces!=='boolean'||!['basic','strong','none'].includes(dispel))throw Error('Invalid source control');if(f.hp<=0)return null;const s=controlState(e);if(s.controls.length>=64)throw Error('Source control capacity');const admitted=e.control(f,type,duration,pierces,{sourceOnly:true});if(!admitted)return null;const c={id:++e.seq,owner,target:f.i,key,type,life:admitted,duration:admitted,pierces,dispel};s.controls.push(c);return c.id;},
 remaining(e,f,type){let n=f[type]||0;for(const c of e.packCore?.controls||[])if(c.target===f.i&&c.type===type&&controlEnabled(e,f,c))n=Math.max(n,c.life);return n;},
 detach(e,ids,reason='released'){const s=e.packCore;if(!s?.controls)return [];const selected=new Set(ids),records=s.controls.filter(c=>selected.has(c.id)),before=new Map();for(const c of records){const f=e.fighters[c.target];before.set(c.target,e.blocked(f)||this.remaining(e,f,'root')>0);}s.controls=s.controls.filter(c=>!selected.has(c.id));for(const [i,hard]of before){const f=e.fighters[i];if(hard&&!e.blocked(f)&&this.remaining(e,f,'root')<=0){f.ccGrace=1;f.ccChain=0;}}return records.map(c=>({...c,reason}));},
 announce(e,c){e.log('control_source_end',c.target,{controlId:c.id,owner:c.owner,key:c.key,reason:c.reason});e.packCombat.controlEnded(e,c);},
 release(e,id,reason='released'){const records=this.detach(e,[id],reason);for(const c of records)this.announce(e,c);return records.length>0;},
 advance(e,f,dt){for(const c of [...e.packCore?.controls||[]])if(c.target===f.i){const root=c.type==='root'&&this.remaining(e,f,'root')>0;c.life=Math.max(0,c.life-dt);if(c.life<=1e-8){this.release(e,c.id,'expired');if(root&&this.remaining(e,f,'root')<=0&&!e.blocked(f)){f.ccGrace=1;f.ccChain=0;}}}},
 dispel(e,f,tier){for(const c of [...e.packCore?.controls||[]])if(c.target===f.i&&(c.dispel==='basic'||tier==='strong'&&c.dispel==='strong'))this.release(e,c.id,'dispelled');},
 cleanup(e){for(const c of [...e.packCore?.controls||[]])if(e.fighters[c.target].hp<=0)this.release(e,c.id,'target_dead');},
 invalidate(e,f,reason){if(!e.packCore)return;controlActor(e,f);if(!actionReasons.includes(reason))throw Error('Invalid action reason');const s=controlState(e);s.actionRevisions[f.i][reason]++;},
 token(e,f,reasons=actionReasons){controlActor(e,f);if(!Array.isArray(reasons)||!reasons.length||reasons.some(k=>!actionReasons.includes(k))||new Set(reasons).size!==reasons.length)throw Error('Invalid action cancellation policy');const s=controlState(e);return {actor:f.i,revisions:Object.fromEntries(reasons.map(k=>[k,s.actionRevisions[f.i][k]]))};},
 valid(e,token){return !!token&&[0,1].includes(token.actor)&&token.revisions&&Object.keys(token.revisions).length>0&&Object.entries(token.revisions).every(([key,n])=>actionReasons.includes(key)&&Number.isSafeInteger(n)&&n>=0&&n===(e.packCore?.actionRevisions?.[token.actor]?.[key]||0));},
 validate(g){const s=g.packCore;if(!s||s.controls===undefined&&s.actionRevisions===undefined)return true;try{if(!Array.isArray(s.controls)||s.controls.length>64||!Array.isArray(s.actionRevisions)||s.actionRevisions.length!==2||!s.actionRevisions.every(v=>Object.keys(v).length===4&&actionReasons.every(k=>Number.isSafeInteger(v[k])&&v[k]>=0)))return false;const ids=new Set();return s.controls.every(c=>{if(ids.has(c.id))return false;ids.add(c.id);return Number.isSafeInteger(c.id)&&c.id>0&&c.id<=g.packClock?.seq&&[0,1].includes(c.owner)&&[0,1].includes(c.target)&&typeof c.key==='string'&&c.key.length>0&&c.key.length<=128&&controlTypes.includes(c.type)&&Number.isFinite(c.life)&&c.life>=0&&c.life<=c.duration+1e-8&&Number.isFinite(c.duration)&&c.duration>0&&c.duration<=1.5&&typeof c.pierces==='boolean'&&['basic','strong','none'].includes(c.dispel);});}catch{return false;}},
};
