import {checkActorRef,validActorRef,sameActorRef} from './actor-ref.js';
import {mitigateActorAmount} from './actor-damage.js';
import {arenaArmorFactor,packStatusEffective} from './pack-services.js';
import {PackHP} from './pack-hp.js';
const key=s=>typeof s==='string'&&/^[a-z][a-z0-9_-]{0,127}$/.test(s)&&!['constructor','prototype','__proto__'].includes(s);
const number=(n,min=0,max=1e6)=>Number.isFinite(n)&&n>=min&&n<=max;
const copy=x=>JSON.parse(JSON.stringify(x));
const stack=new WeakMap();
const fields=['id','namespace','abilityId','hp','hitsToKill','armor','magicResistance','damage','damageType','attackInterval','attackRange','moveSpeed','windup','warmup','attackableDuringWarmup','persistOnOwnerDeath','reflectTargeted','invulnerable','debuffImmune','groupDeath'];
const flagsOK=f=>f&&typeof f==='object'&&!Array.isArray(f)&&Object.keys(f).every(k=>['basic','noProc','noCleave','noReflect','reflected','allowDeadSource','landed'].includes(k)&&typeof f[k]==='boolean');
export const PackUnits={
 templates(input=[]){if(!Array.isArray(input)||input.length>64)throw Error('Invalid unit templates');const result=new Map();for(const spec of input){if(!spec||Object.keys(spec).some(k=>!fields.includes(k))||!key(spec.id)||!key(spec.namespace)||!key(spec.abilityId)||result.has(spec.id))throw Error('Invalid unit template identity');const t={hp:1,hitsToKill:0,armor:0,magicResistance:0,damage:0,damageType:'physical',attackInterval:1,attackRange:100,moveSpeed:0,windup:.1,warmup:0,attackableDuringWarmup:true,persistOnOwnerDeath:false,reflectTargeted:false,invulnerable:false,debuffImmune:false,groupDeath:false,...spec};if(!number(t.hp,1,100000)||!Number.isSafeInteger(t.hitsToKill)||t.hitsToKill<0||t.hitsToKill>100||!number(t.armor,-100,100)||!number(t.magicResistance,0,1)||!number(t.damage,0,10000)||!number(t.attackInterval,.05,60)||!number(t.attackRange,0,1200)||!number(t.moveSpeed,0,1200)||!number(t.windup,0,10)||!number(t.warmup,0,60)||!['physical','magical','pure'].includes(t.damageType)||['attackableDuringWarmup','persistOnOwnerDeath','reflectTargeted','invulnerable','debuffImmune','groupDeath'].some(k=>typeof t[k]!=='boolean'))throw Error('Invalid unit template values');result.set(t.id,Object.freeze(t));}return result;},
 world(e){const core=e.enableHPLifecycle();return core.units??={version:1,epoch:e.actorEpoch,records:[],deaths:[],jobs:[],deathSeq:0};},
 ref(e,actor){const w=this.world(e);if(e.fighters[actor?.i]===actor)return {kind:'fighter',id:actor.i,epoch:w.epoch,life:e.packCore.life[actor.i]};if(w.records.includes(actor))return copy(actor.ref);throw Error('Actor is not owned by this Engine');},
 resolve(e,ref,{dead=false}={}){checkActorRef(ref);const w=e.packCore?.units;if(!w||ref.epoch!==w.epoch)return null;if(ref.kind==='fighter'){const f=e.fighters[ref.id];return e.packCore.life[ref.id]===ref.life&&(dead||f.hp>0)?f:null;}const u=w.records.find(u=>sameActorRef(u.ref,ref));if(u&&(dead||u.hp>0))return u;return dead?w.deaths.find(d=>sameActorRef(d.victim,ref))?.record??null:null;},
 owner(e,ref){const actor=this.resolve(e,ref,{dead:true});return actor?(ref.kind==='fighter'?ref.id:actor.owner):null;},
 spawn(e,{owner,abilityId,templateId,x,y=0,duration,group=null,groupKillsOwner}={}){const t=e.unitTemplates.get(templateId);groupKillsOwner??=t?.groupDeath;if(!t||groupKillsOwner!==t.groupDeath||abilityId!==t.abilityId||![0,1].includes(owner)||e.fighters[owner].hp<=0||!number(x,45,1155)||!number(y,0,1000)||!number(duration,.001,3600)||group!==null&&!key(group)||typeof groupKillsOwner!=='boolean'||groupKillsOwner&&group===null)throw Error('Invalid unit spawn');const w=this.world(e);if(w.records.length>=16)throw Error('Unit capacity');const id=++e.seq,u={ref:{kind:'unit',id,epoch:w.epoch,life:0},owner,abilityId,templateId,x,y,hp:t.hitsToKill||t.hp,maxHp:t.hitsToKill||t.hp,life:duration,duration,age:0,attackCd:0,controls:[],hits:[],group,groupKillsOwner};w.records.push(u);e.packCombat.actorSpawned(e,copy(u));return copy(u.ref);},
 actors(e,{hostileTo=null,origin=null,radius=1200,alive=true}={}){if(hostileTo!==null)checkActorRef(hostileTo);if(origin!==null&&(!number(origin.x,0,1200)||!number(origin.y,0,1000))||!number(radius,0,2400)||typeof alive!=='boolean')throw Error('Invalid actor query');const w=this.world(e),owner=hostileTo===null?null:this.owner(e,hostileTo);if(hostileTo!==null&&owner===null)return [];const rows=[...e.fighters,...w.records];return rows.filter(a=>(!alive||a.hp>0)&&(owner===null||(e.fighters[a.i]===a?a.i:a.owner)!==owner)&&(!origin||Math.hypot(a.x-origin.x,a.y-origin.y)<=radius)).map(a=>this.ref(e,a)).sort((a,b)=>a.kind.localeCompare(b.kind)||a.id-b.id);},
 profile(e,ref){const a=this.resolve(e,ref);if(!a)return null;if(ref.kind==='unit'){const t=e.unitTemplates.get(a.templateId);return {damage:t.damage,damageType:t.damageType,interval:t.attackInterval,range:t.attackRange,windup:t.windup};}const h=e.hero(a.i);return {damage:(e.property(a,'attack_damage_override')||h.attack)+e.property(a,'attack_bonus'),damageType:'physical',interval:(e.property(a,'attack_interval_override_s')||h.attack_interval_s)*(e.property(a,'attack_interval_multiplier')||1),range:(e.property(a,'attack_range_override')||h.attack_range)+e.property(a,'attack_range_bonus'),windup:.1};},
 queueAttack(e,{source,target,delay=null,persist=false}={}){checkActorRef(source);checkActorRef(target);const s=this.resolve(e,source),t=this.resolve(e,target),p=this.profile(e,source);if(typeof persist!=='boolean'||delay!==null&&!number(delay,0,60))throw Error('Invalid actor attack delay');if(!s||!t||this.owner(e,source)===this.owner(e,target))return null;const w=this.world(e);if(w.jobs.length>=32)throw Error('Actor job capacity');const id=++e.seq,job={id,source:copy(source),target:copy(target),owner:this.owner(e,source),at:e.t+(delay??p.windup),persist,amount:p.damage,damageType:p.damageType,range:p.range,abilityId:source.kind==='unit'?s.abilityId:'actor_basic_attack',flags:{basic:true,noProc:false,noCleave:false,noReflect:false,reflected:false,allowDeadSource:false,landed:true}};w.jobs.push(job);return id;},
 route(e,{source,target,abilityId,range=1200,reflected=false,noReflect=false}={}){checkActorRef(source);checkActorRef(target);if(!key(abilityId)||!number(range,0,2400)||typeof reflected!=='boolean'||typeof noReflect!=='boolean')throw Error('Invalid actor spell route');reflected||=stack.get(e)?.flags.reflected??false;noReflect||=stack.get(e)?.flags.noReflect??false;const s=this.resolve(e,source),t=this.resolve(e,target),result={accepted:false,source:copy(source),target:copy(target),abilityId,reflected,noReflect:noReflect||reflected};if(!s||!t||Math.hypot(s.x-t.x,s.y-t.y)>range+22)return {...result,reason:'unavailable_or_range'};const template=target.kind==='unit'?e.unitTemplates.get(t.templateId):null;if(template?.invulnerable||target.kind==='fighter'&&t.invuln>0)return {...result,reason:'invulnerable'};const counter=target.kind==='fighter'?e.buff(t,'counter'):null;if(!reflected&&!noReflect&&(template?.reflectTargeted||counter?.life>0&&!counter.m.counter_type)){if(counter)t.buffs=t.buffs.filter(b=>b!==counter);return {...result,accepted:true,source:copy(target),target:copy(source),reflected:true,noReflect:true};}return {...result,accepted:true};},
 control(e,{source,target,type,duration,pierces=false,key:controlKey='actor_control'}={}){checkActorRef(source);checkActorRef(target);if(!['stun','root','hex','fear','taunt'].includes(type)||!number(duration,.001,3600)||typeof pierces!=='boolean'||!key(controlKey))throw Error('Invalid actor control');const s=this.resolve(e,source),t=this.resolve(e,target);if(!s||!t)return null;if(target.kind==='fighter')return {id:e.applyControlSource(t,{owner:this.owner(e,source),key:controlKey,type,duration,pierces,sourceActor:copy(source)}),source:copy(source),target:copy(target)};const template=e.unitTemplates.get(t.templateId);if(template.invulnerable||template.debuffImmune&&!pierces)return null;if(t.controls.length>=8)throw Error('Unit control capacity');const c={id:++e.seq,source:copy(source),type,life:duration,duration,key:controlKey};t.controls.push(c);return copy(c);},
 remove(e,ref,reason='removed',killer=null){checkActorRef(ref);if(ref.kind!=='unit'||!['damage','expired','owner_dead','removed','group'].includes(reason))throw Error('Invalid unit removal');if(killer!==null)checkActorRef(killer);const w=e.packCore?.units,u=this.resolve(e,ref,{dead:true});if(!w||!u||!w.records.includes(u))return false;w.records=w.records.filter(v=>v!==u);const event={id:++w.deathSeq,victim:copy(ref),killer:killer&&copy(killer),owner:u.owner,cause:reason,at:e.t,record:{...copy(u),hp:0,life:0}};w.deaths.push(event);if(w.deaths.length>32)w.deaths.shift();w.jobs=w.jobs.filter(j=>!sameActorRef(j.target,ref)&&(!sameActorRef(j.source,ref)||j.persist));e.log('actor_death',u.owner,{actorDeathId:event.id,victim:event.victim,killer:event.killer,cause:reason});e.packCombat.actorDeath(e,copy(event));if(reason==='damage'&&u.group!==null){for(const peer of [...w.records])if(peer.owner===u.owner&&peer.group===u.group)this.remove(e,peer.ref,'group',killer);if(u.groupKillsOwner&&e.fighters[u.owner].hp>0)PackHP.executeGroupDeath(e,e.fighters[u.owner],{source:killer===null?null:this.owner(e,killer),abilityId:u.abilityId,sourceActor:killer,group:u.group});}return true;},
 damage(e,{source,target,amount,damageType,abilityId,attackId=null,kind='spell',flags={}}={}){checkActorRef(source);checkActorRef(target);if(!['spell','attack','cleave','reflection'].includes(kind)||!number(amount)||!['physical','magical','pure'].includes(damageType)||!key(abilityId)||attackId!==null&&(!Number.isSafeInteger(attackId)||attackId<1||attackId>e.seq)||!flagsOK(flags))throw Error('Invalid actor damage');const parent=stack.get(e),policy={basic:false,noProc:false,noCleave:false,noReflect:false,reflected:false,allowDeadSource:false,landed:true,...flags};if(parent)for(const k of ['noProc','noCleave','noReflect','reflected'])policy[k]||=parent.flags[k];if(parent?.depth>=8)throw Error('Actor damage recursion limit');const sourceActor=this.resolve(e,source,{dead:policy.allowDeadSource}),targetActor=this.resolve(e,target),owner=this.owner(e,source),receipt={accepted:false,landed:false,actual:0,deferred:0,source:copy(source),target:copy(target),flags:copy(policy),attackId};if(!sourceActor||!targetActor||owner===null||!policy.landed||kind==='cleave'&&policy.noCleave)return receipt;if(policy.basic&&attackId===null)throw Error('Basic actor damage needs an attack identity');if(source.kind==='fighter'&&target.kind==='fighter'){const result=e.resolveDamage(sourceActor,targetActor,amount,{damage_type:damageType,blockable:policy.basic},{skill:abilityId,attackId,basic:policy.basic,dot:!policy.basic,reflected:policy.reflected,noReflect:policy.noReflect});return {...receipt,...result};}
  if(target.kind==='unit'){const t=e.unitTemplates.get(targetActor.templateId);if(t.invulnerable||targetActor.age<t.warmup&&!t.attackableDuringWarmup||t.hitsToKill&&!policy.basic)return receipt;if(policy.basic){const hitKey=JSON.stringify([source,attackId]);if(targetActor.hits.includes(hitKey))return receipt;targetActor.hits.push(hitKey);if(targetActor.hits.length>32)targetActor.hits.shift();}}
  const event={source:copy(source),targetRef:copy(target),attacker:sourceActor,target:targetActor,sourceOwner:owner,damage:amount,rawDamage:amount,attackId,m:{damage_type:damageType},info:{skill:abilityId,basic:policy.basic,dot:!policy.basic,sourceActor:copy(source),...policy},flags:policy,guard:false};stack.set(e,{flags:policy,depth:(parent?.depth??0)+1});try{
   if(target.kind==='unit'){const t=e.unitTemplates.get(targetActor.templateId);event.damage=t.hitsToKill?1:mitigateActorAmount(amount,{physical:damageType==='physical',physicalReduction:0,magical:damageType==='magical',magicReduction:t.magicResistance})*(damageType==='physical'?arenaArmorFactor(t.armor):1);}
   else{if(targetActor.invuln>0)return receipt;const h=e.hero(target.id);event.damage=mitigateActorAmount(amount,{physical:damageType==='physical',physicalReduction:e.property(targetActor,'physical_reduction'),vulnerability:e.property(targetActor,'vulnerability_physical'),magical:damageType==='magical',magicReduction:Math.max(e.property(targetActor,'magic_reduction'),h.id==='anti_mage'&&e.passivesEnabled(targetActor)?.35:0),blocks:targetActor.buffs.filter(b=>(damageType!=='pure'||b.key==='pudge_meat_shield')&&b.m.block_flat&&b.key!=='tidehunter_shell'&&(!b.m.physical_only||damageType==='physical')).map(b=>({amount:b.m.block_flat,fraction:b.m.block_fraction_cap}))});}
   e.packCombat.beforeActorDamage(e,event);if(!number(event.damage))throw Error('Invalid actor damage hook');const before=targetActor.hp;
   if(target.kind==='fighter'){const debit=PackHP.debit(e,event);receipt.deferred=debit.deferred;receipt.actual=debit.actual;targetActor.receivedDamage+=debit.damage;targetActor.cleanseDamage+=debit.damage;targetActor.lastDamageTime=e.t;e.fighters[owner].damage+=debit.damage;}
   else{targetActor.hp=Math.max(0,targetActor.hp-event.damage);receipt.actual=before-targetActor.hp;}
   receipt.accepted=true;receipt.landed=true;event.damage=receipt.actual;e.packCombat.afterActorDamage(e,event);if(policy.basic&&!policy.noProc)e.packCombat.afterActorAttack(e,event);if(target.kind==='unit'&&targetActor.hp<=0)this.remove(e,target,'damage',source);PackHP.deaths(e);return receipt;
  }finally{if(parent)stack.set(e,parent);else stack.delete(e);}
 },
 cleanup(e){const w=e.packCore?.units;if(!w)return;w.jobs=w.jobs.filter(j=>j.persist||e.fighters[j.owner].hp>0);for(const u of [...w.records])if(e.fighters[u.owner].hp<=0&&!e.unitTemplates.get(u.templateId).persistOnOwnerDeath)this.remove(e,u.ref,'owner_dead');},
 advance(e,dt){const w=e.packCore?.units;if(!w)return;this.cleanup(e);for(const u of [...w.records]){const t=e.unitTemplates.get(u.templateId);u.life=Math.max(0,u.life-dt);u.age+=dt;u.attackCd=Math.max(0,u.attackCd-dt);for(const c of u.controls)c.life=Math.max(0,c.life-dt);u.controls=u.controls.filter(c=>c.life>1e-8);if(u.life<=1e-8){this.remove(e,u.ref,'expired');continue;}if(u.age<t.warmup||u.controls.some(c=>['stun','hex','fear','taunt'].includes(c.type))||t.damage<=0)continue;const candidates=this.actors(e,{hostileTo:u.ref,origin:u,radius:1200}).map(ref=>({ref,a:this.resolve(e,ref)})).sort((a,b)=>Math.hypot(a.a.x-u.x,a.a.y-u.y)-Math.hypot(b.a.x-u.x,b.a.y-u.y)||a.ref.kind.localeCompare(b.ref.kind)||a.ref.id-b.ref.id),nearest=candidates[0];if(!nearest)continue;const distance=Math.hypot(nearest.a.x-u.x,nearest.a.y-u.y);if(distance>t.attackRange+22&&!u.controls.some(c=>c.type==='root'))u.x=Math.max(45,Math.min(1155,u.x+Math.sign(nearest.a.x-u.x)*Math.min(t.moveSpeed*dt,Math.max(0,distance-t.attackRange))));else if(distance<=t.attackRange+22&&u.attackCd<=1e-8){this.queueAttack(e,{source:u.ref,target:nearest.ref});u.attackCd=t.attackInterval;}}
  const due=w.jobs.filter(j=>j.at<=e.t+1e-8).sort((a,b)=>a.at-b.at||a.id-b.id);w.jobs=w.jobs.filter(j=>j.at>e.t+1e-8);for(const j of due){const s=this.resolve(e,j.source,{dead:j.persist}),t=this.resolve(e,j.target);if(!s||!t||!j.persist&&e.fighters[j.owner].hp<=0||(j.source.kind==='unit'?s.controls?.some(c=>['stun','hex','fear','taunt'].includes(c.type)):e.blocked(s))||Math.hypot(s.x-t.x,s.y-t.y)>j.range+22)continue;this.damage(e,{...j,source:j.source,target:j.target,attackId:j.id,flags:{...j.flags,allowDeadSource:j.persist}});}this.cleanup(e);
 },
 validate(e,g){const w=g.packCore?.units;if(w===undefined)return true;try{if(w.version!==1||!Number.isSafeInteger(w.epoch)||w.epoch<1||!Number.isSafeInteger(w.deathSeq)||w.deathSeq<0||!Array.isArray(w.records)||w.records.length>16||!Array.isArray(w.deaths)||w.deaths.length>32||!Array.isArray(w.jobs)||w.jobs.length>32)return false;const ids=new Set();for(const u of w.records){const t=e.unitTemplates.get(u.templateId);if(!t||!validActorRef(u.ref)||u.ref.kind!=='unit'||u.ref.epoch!==w.epoch||u.ref.life!==0||u.ref.id>g.packClock.seq||ids.has(u.ref.id)||![0,1].includes(u.owner)||u.abilityId!==t.abilityId||u.maxHp!==(t.hitsToKill||t.hp)||!number(u.hp,Number.EPSILON,u.maxHp)||!number(u.duration,.001,3600)||!number(u.life,Number.EPSILON,u.duration)||!number(u.age,0,u.duration)||Math.abs(u.age+u.life-u.duration)>1e-7||!number(u.attackCd,0,t.attackInterval)||!number(u.x,45,1155)||!number(u.y,0,1000)||!Array.isArray(u.controls)||u.controls.length>8||!Array.isArray(u.hits)||u.hits.length>32||u.hits.some(h=>typeof h!=='string'||h.length>256)||u.group!==null&&!key(u.group)||u.groupKillsOwner!==t.groupDeath||u.groupKillsOwner&&u.group===null)return false;ids.add(u.ref.id);for(const c of u.controls)if(!Number.isSafeInteger(c.id)||c.id<1||c.id>g.packClock.seq||!validActorRef(c.source)||c.source.epoch!==w.epoch||!['stun','root','hex','fear','taunt'].includes(c.type)||!number(c.duration,.001,3600)||!number(c.life,Number.EPSILON,c.duration)||!key(c.key))return false;}
   const jobIds=new Set();for(const j of w.jobs){if(!Number.isSafeInteger(j.id)||j.id<1||j.id>g.packClock.seq||jobIds.has(j.id)||!validActorRef(j.source)||!validActorRef(j.target)||j.source.epoch!==w.epoch||j.target.epoch!==w.epoch||![0,1].includes(j.owner)||!number(j.at,g.t,g.t+60)||typeof j.persist!=='boolean'||!number(j.amount,0,100000)||!number(j.range,0,1200)||!key(j.abilityId)||!['physical','magical','pure'].includes(j.damageType)||!flagsOK(j.flags)||!j.flags.basic)return false;jobIds.add(j.id);}for(const d of w.deaths)if(!Number.isSafeInteger(d.id)||d.id<1||d.id>w.deathSeq||!validActorRef(d.victim)||d.victim.epoch!==w.epoch||d.victim.kind!=='unit'||d.killer!==null&&!validActorRef(d.killer)||![0,1].includes(d.owner)||!['damage','expired','owner_dead','removed','group'].includes(d.cause)||!number(d.at,0,g.t)||!d.record||!sameActorRef(d.record.ref,d.victim)||d.record.hp!==0||d.record.life!==0||!e.unitTemplates.has(d.record.templateId))return false;return true;
  }catch{return false;}}
};
