// Canonical display copy only; never protocol or simulation data.
export const UI_COPY_EN=Object.freeze({
  "code must contain exactly six digits": "Enter a six-digit room code",
  "等待双方素材就绪": "Waiting for both players' images",
  "房间号": "Room code",
  "六位房间号": "Six-digit room code",
  "把房间号发给朋友": "Send this room code to a friend",
  "复制房间号": "Copy room code",
  "房间号已复制": "Room code copied",
  "请选中房间号并手动复制": "Select the room code and copy it manually",
  "等待对手加入…": "Waiting for your opponent…",
  "竞技场背景加载失败": "Arena background unavailable",
  "正在准备竞技场素材…": "Preparing arena images…",
  "战斗精灵加载失败": "Fighter images unavailable",
  "等待双方横屏与素材就绪": "Waiting for both players' landscape view and images",

  "网络连接暂不可用，请稍后重试": "Connection temporarily unavailable. Retry.",
  "版本信息暂不可用，请稍后重试": "Version information unavailable. Retry.",
  "当前版本与对战服务不兼容，请稍后重新检查": "This version is unavailable. Check again.",
  "版本检查已更新，请重试": "Version check changed. Retry.",
  "正在检查版本…": "Checking version…",
  "发现新版本，请更新后进入对战": "A new version is available.",
  "新版本将在退出对局后更新": "Update after leaving the match.",
  "重新检查": "Check again",
  "更新并重新加载": "Update and reload",

  "选择英雄": "Choose your hero",
  "连接房间": "Connecting to room",
  "连接正常": "Connection stable",
  "网络检测中": "Measuring connection",
  "网络数据暂未更新": "Network data not refreshed yet",
  "网络波动，操作可能延迟": "Network varies; input may be delayed",
  "可靠连接超过10秒未响应": "Reliable connection unresponsive for 10 seconds",
  "可靠连接持续拥塞": "Reliable connection remains congested",
  "可靠连接暂时拥塞": "Reliable connection is congested",
  "返回游戏后继续": "Return to the game to continue",
  "等待双方横屏": "Waiting for both players in landscape",
  "已连接，选择英雄": "Connected; choose your hero",
  "房间规则不一致": "Room policy mismatch",
  "房间选人状态不一致": "Room selection state mismatch",
  "选人服务：": "Hero selection service: ",
  "未操作时使用默认英雄水晶室女；倒计时结束自动锁定": "Default: Crystal Maiden. Your current hero locks when time runs out.",
  "自己 · 选择中": "You · choosing",
  "对方 · 选择中": "Opponent · choosing",
  "已锁定": "Locked",
  "等待双方进入选人": "Waiting for both players to choose",
  "准备开始": "Ready to start",
  "已锁定，等待对方": "Locked; waiting for opponent",
  "正在锁定…": "Locking hero…",
  "建立房间": "Reserve room",
  "连接对手": "Connect to opponent",
  "进入选人": "Choose heroes",
  "分享房间号，等待对方": "Share your room code; waiting for opponent",
  "正在校验双方版本": "Checking both versions",
  "正在连接…": "Connecting…",
  "双方同意再战，等待战绩确认": "Both want a rematch; waiting for result confirmation",
  "已同意再战，等待对方": "Rematch accepted; waiting for opponent",
  "对方想再战": "Opponent wants a rematch",
  "同房再战，无需重新加入": "Rematch in this room; no need to rejoin",
  "已同意再战": "Rematch accepted",
  "再战": "Rematch",
  "重试": "Retry",
  "取消": "Cancel",
  "准备开战…": "Starting match…",
  "版本不一致": "Version mismatch",
  "反制": "Countered",
  "守卫被摧毁": "Ward destroyed",
  "强驱散": "Strong dispel",
  "暂无法施法": "Cannot cast now",
  "治疗守卫": "Healing Ward",
  "法术反制": "Counterspell",
  "破防": "Guard break",
  "训练重置": "Practice reset",
  "闪避": "Dodged",
  "闪避反击": "Dodge counter",
  "后端英雄注册表版本不兼容": "Backend hero registry version is incompatible",
  "后端英雄身份与冻结清单不一致": "Backend hero identities differ from the frozen registry",
  "后端英雄注册表不完整": "Backend hero registry is incomplete",
  "后端可玩名单不一致": "Backend playable roster mismatch",
  "构建版本与可玩名单不匹配": "Build version does not match the playable roster",
  "操作说明": "How to play",
  "英雄档案": "Hero archive",
  "战绩": "Records",
  "音乐 / 音量": "Audio",
  "音乐与音量": "Audio settings",
  "音效 开": "SFX on",
  "音效 关": "SFX off",
  "全屏或添加到主屏幕": "Fullscreen or add to Home Screen",
  "⛶ 全屏 / 主屏幕": "⛶ Fullscreen / Home Screen",
  "等待对手": "Waiting for an opponent",
  "进入房间后确认英雄": "Confirm heroes after joining",
  "我的英雄": "My hero",
  "电脑对手": "CPU opponent",
  "一人一英雄，一战定胜负": "Pick a hero. Win the duel.",
  "玩法": "Game modes",
  "对战": "PvP",
  "与真人较量": "Play against a person",
  "人机": "PvE",
  "与电脑练习": "Practice against the CPU",
  "选择我的英雄": "Choose my hero",
  "选择电脑英雄": "Choose CPU hero",
  "创建或加入都使用此英雄": "Use this hero to create or join",
  "点击左右人物卡切换玩家": "Select either player card to change their hero",
  "未发布 · 四技能尚未全部验收 · 暂停适配": "Unreleased · Four-skill acceptance incomplete · Adaptation paused",
  "未发布 · 暂停适配": "Unreleased · Paused",
  "未发布": "Unreleased",
  "选择": "Choose ",
  "已选": "Selected",
  "创建或加入房间，都会使用你选中的英雄": "Your selected hero is used when creating or joining a room",
  "双方可以选择相同英雄 · 被动自动生效，无需按键": "Both players may pick the same hero · Passives work automatically",
  "移动 · W 跳跃 · F 攻击 · Q E R T 技能": "Move · W Jump · F Attack · Q E R T Skills",
  "移动 · ↑ 跳跃 · J 攻击 · U I O P 技能": "Move · ↑ Jump · J Attack · U I O P Skills",
  "后方向防御 · 后下蹲防 · F 攻击": "Hold back to guard · Down-back to crouch guard · F Attack",
  "创建 / 加入房间": "Create / join room",
  "进入竞技场": "Enter arena",
  "非官方 Dota 同人游戏 · 四槽竞技场适配 · 无装备、无登录、无付费数值": "Unofficial Dota fan game · Four-slot arena adaptation · No items, login or paid stats",
  "官网数据与格斗改编说明": "Data sources and arena adaptation",
  "关闭": "Close",
  "方向、攻击、四个技能": "Movement, attack and four skills",
  "天辉": "Radiant",
  "夜魇": "Dire",
  "移动": "Move",
  "跳跃": "Jump",
  "下蹲": "Crouch",
  "攻击 / 按住连击": "Attack / hold for repeated attacks",
  "四个技能": "Four skills",
  "准备好了": "Ready to play",
  "后方向始终是远离对手的一侧：地面按后方向会后退兼防御，后下方向为原地蹲防；换边后立即跟随双方位置判断。正下和前下只下蹲，不防御。上或斜上起跳，跳跃保留起跳时的水平惯性。": "Back always means away from your opponent. On the ground, hold back to retreat and guard, or down-back to crouch guard in place. This changes immediately when players swap sides. Down and down-forward only crouch. Up or diagonal-up jumps, preserving horizontal momentum at takeoff.",
  "不区分高、低段格挡；只在地面、防守方向正确且未攻击、施法、蓄力或处于硬直时防御。可格挡命中减少80%伤害，守势耗尽会破防；持续伤害和标注不可格挡的技能不受此减伤。没有独立重击、冲刺或格挡按钮。": "There are no high/low guard categories. Guard requires being grounded, facing the correct defensive direction, and not attacking, casting, charging or in hitstun. Blockable hits deal 80% less damage; an empty guard meter causes a guard break. Damage over time and unblockable skills ignore this reduction. There are no separate heavy attack, dash or guard buttons.",
  "手机横屏：左手拖动摇杆，右手一个攻击键和四个技能。被动自动生效；引导技能按住，蓄力技能按住后松开。指向地面技能默认瞄准对手施法时的位置。标准手柄：左摇杆 / 十字键移动、后方向防御，向上或 A 跳跃，X 攻击；肩键和扳机对应四个技能。摇杆回到中立后才能再次上推跳跃。": "On a phone in landscape, use the left stick and the attack/four-skill buttons on the right. Passives work automatically; hold channeled skills, and hold then release charged skills. Ground-targeted skills aim at the opponent’s position at cast time. Standard gamepad: left stick/D-pad moves, back guards, up or A jumps, X attacks, and shoulder buttons/triggers use the four skills. Return the stick to neutral before another upward jump.",
  "联网房间双方使用自己的 P1 键位或触控。桌面同屏可用两套键位或两个手柄。同浏览器双窗口仅支持当前设备、当前浏览器；跨设备使用 P2P，双方连接检查通过并准备后开战。": "Each online player uses P1 keys or touch controls. Shared-screen desktop play supports two key sets or two gamepads. Two-window mode works only on this device in the same browser. Use P2P across devices; both players must pass connection checks and ready up before starting.",
  "被动": "Passive",
  "被": "P",
  "官网满级冷却": "Max-level cooldown",
  "法力消耗": "Mana cost",
  "见说明": "See description",
  "每秒伤害": "Damage per second",
  "单次基础伤害": "Base hit damage",
  "无直接伤害": "No direct damage",
  "暴击": "Critical hit",
  "普攻附加伤害": "Attack bonus damage",
  "触发伤害": "Trigger damage",
  "每次守卫伤害": "Damage per ward attack",
  "总持续伤害": "Total damage over time",
  "每次爆炸伤害": "Damage per explosion",
  "初始伤害": "Initial damage",
  "满蓄力伤害": "Fully charged damage",
  "普攻额外伤害": "Extra attack damage",
  "全场伤害": "Arena-wide damage",
  "官网伤害基值": "Official base damage",
  "官网持续秒数": "Official duration (s)",
  "伤害、冷却和耗蓝采用官网满级基础技能。二维射程、格挡、生命与连招规则为本作改编。": "Damage, cooldown and mana use the official max-level base skill values. Two-dimensional range, guarding, health and combo rules are arena adaptations.",
  "查看官方数值与来源": "Official values and sources",
  "官网 ·": "Official site ·",
  "官方技能数据快照来源": "Official skill snapshot source",
  "同样的英雄，二维格斗规则": "Familiar heroes, 2D fighting rules",
  "20位英雄和80个基础技能来自原交互原型。技能名称、主动 / 被动分类、伤害类型、伤害基值、冷却、耗蓝和持续时间以2026年9月30日读取的 Dota 2 官方数据为准。官网动态数据没有补丁标签，不能视作完整7.41f客户端复刻。": "The original prototype supplied 20 heroes and 80 base skills. Skill names, active/passive categories, damage types, base damage, cooldowns, mana and durations use the official Dota 2 snapshot read on September 30, 2026. The live website data has no patch label and is not a complete recreation of the 7.41f client.",
  "本作是独立同人2D格斗改编：角色生命与法力、移动速度和普攻使用竞技场配置；1个Dota距离单位映射0.55竞技场单位；加上跳跃、普攻、后方向防御、99秒回合与三局两胜。连续硬控最长1.5秒，脱控后有1秒控制保护。": "This independent fan-made 2D fighter uses arena settings for health, mana, movement and basic attacks. One Dota distance unit maps to 0.55 arena units. It adds jumping, basic attacks, back-direction guarding, 99-second rounds and best-of-three matches. Continuous hard control is capped at 1.5 seconds, followed by 1 second of control protection.",
  "保留主要技能机制与引导打断、弹体、充能、开关、被动和公式伤害；地图没有小兵、树林或多人目标，不使用装备、天赋、神杖和命石系统。灵魂、墙体绑定和二维随机范围有明确格斗适配。各技能详情可查看本作实际参数与说明。": "Core skill mechanics include channel interruption, projectiles, charges, toggles, passives and formula-based damage. The arena has no creeps, trees or multiple targets, and no items, talents, Scepter or facet systems. Souls, wall binding and random 2D areas have explicit arena adaptations. Skill details describe the game’s actual parameters and behavior.",
  "背景音乐为《Dota 2 Reborn D+B Remix》，收录于《The Dota 2 Remixes EP》，作者 Valve Studio Orchestra。这是混音版。人物图像与技能图标原始素材属于 Valve；额外2D角色与场景为AI生成同人美术。此作品与 Valve、Dota 2 或拳皇官方没有关联，无商用授权声明。": "Music: Dota 2 Reborn D+B Remix, from The Dota 2 Remixes EP, by Valve Studio Orchestra. This is a remix. Original hero images and skill icons belong to Valve; additional 2D characters and environments are AI-generated fan art. This work is unaffiliated with Valve, Dota 2 or The King of Fighters and makes no claim of commercial authorization.",
  "游戏本身不要求账号。私有托管页面可能需要拥有者的站点访问身份；下载的离线HTML可以直接双击使用同屏模式。": "The game requires no account. A privately hosted page may require the owner’s site-access identity. Open the downloaded offline HTML directly for shared-screen play.",
  "知道了": "Got it",
  "DOTA双人格斗竞技场": "DOTA two-player fighting arena",
  "无限练习": "Unlimited practice",
  "人机对决": "CPU duel",
  "WebRTC直连": "Direct WebRTC",
  "双窗口真实同步": "Two-window synchronization",
  "同屏真人对战": "Shared-screen PvP",
  "音效": "SFX",
  "全屏": "Fullscreen",
  "暂停": "Pause",
  "拖动摇杆：左右移动，上推跳跃，后推防御、后下蹲防": "Stick: left/right to move, up to jump, back to guard, down-back to crouch guard",
  "移动 / 跳跃 / 后防": "Move / jump / guard",
  "普通攻击": "Basic attack",
  "攻击": "Attack",
  "按住连击": "Hold to attack",
  "（被动，自动生效）": " (passive, automatic)",
  "窗口失去焦点，已自动暂停": "Window lost focus; automatically paused",
  "切回此窗口后继续战斗": "Return to this window to continue",
  "当前回合已冻结，双方状态保留": "Round paused; both players’ states preserved",
  "继续对战": "Resume duel",
  "重置训练": "Reset practice",
  "退出并重新选人": "Quit to hero selection",
  "对局结束 · 三局两胜": "Match over · Best of three",
  "获胜": "wins",
  "回合与保存详情，可滚动": "Round and save details; scrollable",
  "重试保存": "Retry save",
  "再战一场": "Rematch",
  "返回选人": "Hero selection",
  "等待对方恢复横屏": "Waiting for opponent to return to landscape",
  "等待另一位玩家恢复连接": "Waiting for the other player to reconnect",
  "已向房主请求再战": "Rematch requested from the host",
  "音效已开启": "SFX enabled",
  "音效已关闭": "SFX disabled",
  "双窗口模式需要同源网站与可用的本机存储；离线文件支持同屏双人": "Two-window mode needs the same website origin and local storage. Offline files support shared-screen play.",
  "双窗口真实对战": "Two-window PvP",
  "在同一个浏览器中打开两份本网站，拖成两个独立窗口。没有游戏账号、没有模拟对手。两个窗口要使用相同的网站地址。键盘只控制当前聚焦的窗口；两人同时用键盘请选同屏双人。房号10分钟有效，每分钟最多10次加入尝试；异常关闭窗口后席位最多约20秒释放；它仅用于本机协调，不是强身份认证。": "Open this website twice in the same browser and place the tabs in separate windows. No account or simulated opponent is used. Both windows must use the same address. Keyboard controls affect the focused window; choose shared-screen play for simultaneous keyboard use. Room codes last 10 minutes, with up to 10 join attempts per minute. An unexpectedly closed seat is released in about 20 seconds at most. This is local coordination, not strong identity authentication.",
  "在同一个浏览器中打开两份本网站，拖成两个独立窗口。没有游戏账号、没有模拟对手。两个窗口要使用相同的网站地址。键盘只控制当前聚焦的窗口；两人同时用键盘请选同屏双人。房间号10分钟有效，每分钟最多10次加入尝试；异常关闭窗口后席位最多约20秒释放；它仅用于本机协调，不是强身份认证。": "Open this website twice in the same browser and place the tabs in separate windows. No account or simulated opponent is used. Both windows must use the same address. Keyboard controls affect the focused window; choose shared-screen play for simultaneous keyboard use. Room codes last 10 minutes, with up to 10 join attempts per minute. An unexpectedly closed seat is released in about 20 seconds at most. This is local coordination, not strong identity authentication.",
  "创建房间": "Create room",
  "或者输入朋友窗口显示的六位房号": "Or enter the six-digit room code from your friend’s window",
  "或者输入朋友窗口显示的六位房间号": "Or enter the six-digit room code from your friend’s window",
  "加入房间": "Join room",
  "仅同一浏览器的两个窗口，不支持不同电脑。双方在自己的窗口使用 P1 键位；触控使用各自一侧。": "Only two windows in the same browser; separate computers are unsupported here. Each player uses P1 keys in their window, or their own touch controls.",
  "对方窗口失去连接，已返回房间": "The other window disconnected; returned to the room",
  "双方游戏版本或可玩英雄名单不一致，请刷新": "Game versions or playable rosters differ; refresh both pages",
  "房间已有两位玩家": "Room already has two players",
  "另一位玩家离开了房间": "The other player left the room",
  "英雄尚未开放": "Hero is not released",
  "两位玩家已连接": "Both players connected",
  "等待另一位玩家": "Waiting for another player",
  "在本浏览器另一窗口输入上面的房号": "Enter this room code in another window of this browser",
  "在本浏览器另一窗口输入上面的房间号": "Enter this room code in another window of this browser",
  "双方都使用自己窗口的 P1 键位。请把两个窗口并排显示，避免后台标签页限速。": "Use P1 keys in each player’s window. Keep both windows visible side by side to avoid background tab throttling.",
  "双方开战": "Start duel",
  "等待房主开始": "Waiting for the host to start",
  "离开房间": "Leave room",
  "等待另一位玩家连接": "Waiting for the other player to connect",
  "对方暂停了比赛": "Opponent paused the match",
  "双方状态已保留": "Both players’ states preserved",
  "继续": "Continue",
  "开启": "On",
  "开关": "Toggle",
  "已装填": "Armed",
  "平局，再战一回合": "Draw; play another round",
  "毒×": "Poison ×",
  "破被动": "Break",
  "眩晕": "Stun",
  "妖术": "Hex",
  "禁锢": "Root",
  "沉默": "Silence",
  "缴械": "Disarm",
  "减速": "Slow",
  "恐惧": "Fear",
  "嘲讽": "Taunt",
  "控制保护": "Control protection",
  "引导中": "Channeling",
  "龙形态": "Dragon form",
  "黑夜": "Night",
  "音乐已关闭": "Music disabled",
  "官方音乐文件尚未接入": "Official music file unavailable",
  "点击播放音乐": "Click to play music",
  "正在播放…": "Starting playback…",
  "官方原声 · 循环播放": "Official soundtrack · Looping",
  "音乐缓冲中…": "Music buffering…",
  "音乐已暂停，点击播放继续": "Music paused; click Play to resume",
  "音乐已停止": "Music stopped",
  "点击播放以开启音乐": "Click Play to enable music",
  "音乐暂不可用": "Music unavailable",
  "音乐加载失败，请检查网络后重试。": "Music failed to load. Check your connection and retry.",
  "音乐播放失败，请重试。": "Music playback failed. Please retry.",
  "点播放以开启音乐。": "Click Play to enable music.",
  "已添加，可从主屏幕打开 DOTA PK": "Added; open DOTA PK from the Home Screen",
  "退出全屏": "Exit fullscreen",
  "已在主屏幕模式": "Running from Home Screen",
  "全屏与主屏幕游玩": "Fullscreen and Home Screen play",
  "Safari 普通标签页不能由游戏强制隐藏地址栏和标签栏。添加到主屏幕后，请从新图标打开独立画面。": "The game cannot force Safari’s address and tab bars to hide in a normal tab. Add it to your Home Screen and open the new icon for a standalone view.",
  "在 Safari 点“分享”按钮。": "In Safari, tap Share.",
  "选择“添加到主屏幕”；若有“作为网页 App 打开”，保持开启。": "Choose Add to Home Screen. Keep Open as Web App enabled if shown.",
  "点“添加”，再从主屏幕的 DOTA PK 图标进入并横屏。": "Tap Add, then open DOTA PK from the Home Screen and rotate to landscape.",
  "联网对战仍需要网络。主屏幕模式由浏览器支持决定，不是修改 Safari 设置。": "Online play still needs a connection. Home Screen mode depends on browser support; it does not change Safari settings.",
  "添加 DOTA PK": "Add DOTA PK",
  "返回游戏": "Return to game",
  "未能添加，请通过浏览器菜单添加到主屏幕": "Could not add the app; use the browser menu to add it to the Home Screen",
  "画面已适配当前缩放，确认后继续": "View adjusted to the current zoom; confirm to continue",
  "已恢复横屏，准备好后继续": "Landscape restored; continue when ready",
  "屏幕方向已变化，准备好后继续": "Orientation changed; continue when ready",
  "背景音乐": "Background music",
  "音乐音量": "Music volume",
  "游戏音效": "Game sound effects",
  "音效音量": "SFX volume",
  "播放音乐": "Play music",
  "暂停音乐": "Pause music",
  "。菜单与对局连续播放同一首混音。": ". The same remix continues between the menu and matches.",
  "音乐开启后循环播放。切到后台会暂停，返回后可在这里继续。": "Music loops while enabled. It pauses in the background; return here to resume.",
  "本地对局": "Local match",
  "对战记录": "Match history",
  "对战与人机分开记录。此列表保留本浏览器最近200局；只有“战绩已保存”表示服务器已接收。中止或有争议的比赛不计胜负。": "PvP and PvE records are separate. This browser keeps the latest 200 matches. Only “Record saved” means the server received it. Aborted or disputed matches do not count as wins or losses.",
  "秒 ·": "s ·",
  "尚无已结束的比赛。": "No completed matches yet.",
  "未知英雄": "Unknown hero",
  "P2P信令需要托管网址；离线文件可同屏对战": "P2P signaling needs a hosted URL; offline files support shared-screen play",
  "输入房间号": "Enter room code",
  "六位数字房间号": "Six-digit room code",
  "请输入六位数字房间号": "Enter a six-digit room code",
  "连接已暂停": "Connection paused",
  "重新连接": "Reconnect",
  "P2P 房间": "P2P room",
  "准备": "Ready",
  "房间最多等待2分钟。断线后重新建房；不会恢复未完成的旧回合。探测丢包为DataChannel应用层超时比例。": "Rooms wait up to 2 minutes. Create a new room after disconnection; unfinished rounds are not restored. Probe loss is the application-level DataChannel timeout rate.",
  "正在建立…": "Creating…",
  "等待房主规则": "Waiting for host policy",
  "尚未收到": "Not received yet",
  "本端 ": "Local: ",
  "对端 ": "Peer: ",
  "自己 ": "You: ",
  "对方 ": "Opponent: ",
  "已准备": "Ready",
  "未准备": "Not ready",
  "取消准备": "Unready",
  "等待战绩确认；保存失败时请先重试": "Wait for record confirmation; retry first if saving failed",
  "候选后端注册表已核对": "Candidate backend registry verified",
  "候选后端注册表不可用，新名单未获批准": "Candidate registry unavailable; new roster not authorized",
  "候选后端：": "Candidate backend: ",
  "请横屏游玩": "Play in landscape",
  "横转手机，准备开战": "Rotate your phone to play",
  "左手摇杆，右手攻击与技能。": "Left stick, right attack and skills.",
  "横屏后即可选人和进入竞技场。": "Choose heroes and enter the arena in landscape.",
  "尝试全屏": "Try fullscreen",
  "若无法自动旋转，请手动横转设备。Safari 标签页的地址栏由浏览器管理。": "If rotation fails, rotate the device manually. Safari manages the address bar in browser tabs.",
  "添加到主屏幕，使用独立画面": "Add to Home Screen for a standalone view",
  "在 Safari 点“分享”。": "In Safari, tap Share.",
  "选择“添加到主屏幕”，保持“作为网页 App 打开”（若显示）。": "Choose Add to Home Screen and keep Open as Web App enabled if shown.",
  "添加后，从主屏幕的 DOTA PK 图标重新打开。": "After adding, reopen using the DOTA PK Home Screen icon.",
  "DOTA PK · 1V1 竞技场": "DOTA PK · 1V1 Arena",
  "已在主屏幕独立模式中游玩": "Already playing in Home Screen standalone mode",
  "已进入全屏；请手动横转设备。": "Fullscreen entered; rotate the device manually.",
  "当前浏览器不支持网页全屏；可添加到主屏幕，以独立模式打开。": "This browser does not support web fullscreen; add the app to Home Screen for standalone play.",
  "浏览器未进入全屏；可添加到主屏幕游玩。": "Fullscreen was not entered; you can add the app to Home Screen.",
  "未能进入全屏，仍可横屏游玩。": "Could not enter fullscreen; landscape play remains available.",
  "尚未确认RTT规则": "RTT policy not confirmed",
  "检测数据无效": "Invalid probe data",
  "正在采集连接质量": "Measuring connection quality",
  "检测结果已过期": "Probe results expired",
  "RTT不符合开战规则": "RTT does not meet the start policy",
  "延迟抖动过大": "Jitter is too high",
  "探测丢包过多": "Probe loss is too high",
  "连接质量合格": "Connection quality passed",
  "请横屏后重新准备": "Rotate to landscape and ready up again",
  "等待对方恢复横屏并重新准备": "Waiting for opponent to return to landscape and ready up",
  "等待双方连接与版本校验": "Waiting for connection and version verification",
  "对方：": "Opponent: ",
  "连接已关闭": "Connection closed",
  "当前浏览器不支持WebRTC": "WebRTC is unsupported in this browser",
  "P2P连接中断，请重新建房并加入": "P2P disconnected; create and join a new room",
  "数据通道已关闭，请重新连接": "Data channel closed; reconnect",
  "数据通道发生错误": "Data channel error",
  "房间可玩名单不一致": "Room playable roster mismatch",
  "请输入六位数字口令": "Enter a six-digit room code",
  "双方版本不一致，请刷新到同一版本": "Versions differ; refresh both pages to the same version",
  "直连超时；当前网络可能需要TURN中继，尚未配置": "Direct connection timed out; this network may need a TURN relay, which is not configured",
  "直连超时；请重试或换网络，尚未配置TURN": "Direct connection timed out; retry or change networks. TURN is not configured",
  "等待加入超时，请重新建房": "Join wait timed out; create a new room",
  "双方版本、英雄或房间规则不一致": "Versions, heroes or room policies differ",
  "开战检查未通过：": "Start checks failed: ",
  "请重新准备": "Ready up again",
  "对方超过4秒未响应，比赛已暂停": "Opponent has not responded for over 4 seconds; match paused",
  "开战确认超时，可重试同一场比赛": "Start confirmation timed out; retry the same match",
  "比赛可玩名单不一致": "Match playable roster mismatch",
  "上一局尚未完成或比赛已过期": "Previous match unfinished or match expired",
  "双方尚未准备好": "Both players must be ready",
  "比赛与房间英雄不一致": "Match and room heroes differ",
  "服务器尚未确认双方开战": "Server has not confirmed both players’ start",
  "开战条件已变化，请重新准备": "Start conditions changed; ready up again",
  "服务器未确认开战": "Server has not confirmed the start",
  "战绩服务：": "Record service: ",
  "连接已中断，请重新建房": "Disconnected; create a new room",
  "战绩已保存 · 双方一致": "Record saved · Both reports agree",
  "战绩已保存 · 客户端上报": "Record saved · Client reported",
  "已提交，等待对方确认": "Submitted; waiting for opponent confirmation",
  "双方战果不一致，未计胜负": "Reports disagree; no win or loss counted",
  "比赛已中止，未计胜负": "Match aborted; no win or loss counted",
  "比赛进行中": "Match in progress",
  "等待双方确认开战": "Waiting for both players to confirm start",
  "等待房主保存战绩": "Waiting for host to save the record",
  "正在保存战绩…": "Saving record…",
  "已保存本机，尚未同步服务器": "Saved locally; not synced to server",
  "尚未保存到服务器，可重试": "Not saved to server; retry available",
  "尚未保存到服务器": "Not saved to server",
  "战绩服务不可用，本局仅保留本机记录：": "Record service unavailable; this match is stored only locally: ",
  "战绩服务暂不可用": "Record service temporarily unavailable",
  "战绩服务没有返回有效数据": "Record service returned invalid data",
  "战绩会话无效": "Invalid record session",
  "注册表核对已更新，请重试": "Registry check updated; retry",
  "英雄名单核对已变化，请重试": "Roster verification changed; retry",
  "请求英雄名单与核对凭据不一致": "Requested roster differs from authorization",
  "不能加入自己创建的窗口": "Cannot join your own window",
  "加入尝试过多，请一分钟后重试": "Too many join attempts; retry in one minute",
  "房号碰撞，请重试": "Room code collision; retry",
  "房间号碰撞，请重试": "Room code collision; retry",
  "无法生成房号，请重试": "Could not generate room code; retry",
  "无法生成房间号，请重试": "Could not generate room code; retry",
  "无法读取本机房号注册表": "Could not read local room registry",
  "无法读取本机房间号注册表": "Could not read local room registry",
  "本机房号注册表被占用，请关闭旧版本窗口": "Local room registry is in use; close old-version windows",
  "本机房间号注册表被占用，请关闭旧版本窗口": "Local room registry is in use; close old-version windows",
  "本机房号预约失败，请重试": "Local room reservation failed; retry",
  "本机房间号预约失败，请重试": "Local room reservation failed; retry",
  "本机房间不存在或口令已过期": "Local room does not exist or room code expired",
  "本机房间不存在或房间号已过期": "Local room does not exist or room code expired",
  "本机房间过多，请关闭旧房间或稍后重试": "Too many local rooms; close old rooms or retry later",
  "本浏览器无法安全预约本机房间，请使用同屏对战": "This browser cannot safely reserve local rooms; use shared-screen play",
  "请输入六位数字房号": "Enter a six-digit room code",
  "控制法师": "Control mage",
  "反击战士": "Counterattack fighter",
  "远程消耗": "Ranged harassment",
  "机动刺客": "Mobile assassin",
  "远程压制": "Ranged pressure",
  "爆发法师": "Burst mage",
  "控制爆发": "Control and burst",
  "距离爆发": "Range-based burst",
  "位移法刺": "Blinking spell assassin",
  "持续压制": "Sustained pressure",
  "近战水域追击": "Melee water pursuit",
  "近战 · 追击": "Melee · Pursuit",
  "远程 · 换位": "Ranged · Position swap",
  "近战 · 潮汐控制": "Melee · Tidal control",
  "远程 · 冰霜控制": "Ranged · Frost control",
  "远程 · 消耗续航": "Ranged · Harassment and sustain",
  "远程 · 持续伤害": "Ranged · Damage over time",
  "近战 · 变身": "Melee · Transformation",
  "远程 · 范围法术": "Ranged · Area spells",
  "近战 · 治疗护盾": "Melee · Healing and protection",
  "远程 · 血量爆发": "Ranged · Health-based burst",
  "近战 · 夜战": "Melee · Night combat",
  "远程 · 冰火控制": "Ranged · Ice and fire control",
  "近战 · 持续输出": "Melee · Sustained damage",
  "近战 · 缠绕恢复": "Melee · Root and recovery",
  "近战 · 多重施法": "Melee · Multicast",
  "近战 · 冲锋控制": "Melee · Charge and control",
  "远程 · 法术爆发": "Ranged · Spell burst",
  "近战 · 火焰机动": "Melee · Fire mobility",
  "近战 · 区域控制": "Melee · Area control",
  "近战 · 位移爆发": "Melee · Mobility and burst",
  "近战 · 治疗连击": "Melee · Healing and combos",
  "远程 · 双枪爆发": "Ranged · Dual-gun burst"
});

// Recognized backend/browser faults are localized only at the display boundary.
export const SERVICE_COPY_ZH=Object.freeze({
  "invalid session": "会话无效",
  "session expired": "会话已过期",
  "room code capacity exhausted": "房间号容量已满，请稍后重试",
  "room unavailable": "房间不存在、已关闭或已过期",
  "rate limit exceeded": "操作过于频繁，请稍后重试",
  "not a participant": "你不是此比赛的参与者",
  "origin not allowed": "当前网站来源不被允许",
  "database unavailable": "战绩服务暂不可用",
  "route not found": "服务地址不存在",
  "application/json required": "请求格式无效",
  "body too large": "请求内容过大",
  "not found": "记录不存在",
  "already exists": "记录已存在",
  "version mismatch": "双方版本不一致，请刷新",
  "too many rounds": "回合数量无效",
  "invalid round sequence": "回合顺序无效",
  "score does not match rounds": "比分与回合不一致",
  "invalid winner": "获胜方无效",
  "aborted match cannot award a win": "中止比赛不能计胜负",
  "invalid abort reason": "中止原因无效",
  "invalid outcome": "战果无效",
  "invalid room": "房间请求无效",
  "requestId reused with different body": "同一请求编号不能用于不同内容",
  "code must contain exactly six digits": "请输入六位数字房间号",
  "roster mismatch": "房间可玩名单不一致",
  "cannot join your own room": "不能加入自己创建的房间",
  "room full": "房间已有两位玩家",
  "hero already locked": "英雄已锁定",
  "invalid answer": "连接应答无效",
  "room expired": "房间已过期",
  "answer already locked": "连接应答已锁定",
  "invalid requestId": "请求编号无效",
  "room not ready": "房间尚未准备好",
  "room session expired": "房间会话已过期",
  "previous match still active or pending": "上一局仍在进行或等待确认",
  "submission already locked": "战果上报已锁定",
  "match does not accept results": "此比赛不能接收战果",
  "invalid pve match": "人机比赛请求无效",
  "invalid AI difficulty": "电脑难度无效",
  "requestId reused": "请求编号已使用",
  "unknown or inactive gameplay roster": "英雄名单不存在或未开放",
  "game version and roster mismatch": "游戏版本与英雄名单不匹配",
  "hero is not playable in this roster": "此英雄不在当前可玩名单中",
  "Failed to fetch": "网络请求失败，请重试",
  "fetch failed": "网络请求失败，请重试",
  "The operation was aborted due to timeout": "请求超时，请重试",
  "This operation was aborted": "请求已取消"
});
