import test from 'node:test';import assert from 'node:assert/strict';
import {createPackServices} from '../../../src/pack-services.js';
import {Engine} from '../../../src/engine.js';import {runtimeHeroes} from '../../../src/runtime-heroes.js';import {CORE4_PACKS} from '../../../src/hero-packs/index.js';import {ACTIVE_ROSTER} from '../../../src/hero-registry.js';
import {PACKS,ENGINE_PACKS,PRIORITY_IDS} from '../../../src/hero-packs/r91/index.js';
import {api,R91Combat} from '../../../src/hero-packs/r91/runtime.js';import {validateAim} from '../../../src/hero-packs/r91/targeting.js';
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-6,`${a} != ${b}`);
const heroes=[...runtimeHeroes.filter(h=>!PACKS.some(p=>p.definition.registryNumericId===h.registryNumericId)),...PACKS.map(p=>p.definition)];
const roster={...ACTIVE_ROSTER,heroIds:[...new Set([...ACTIVE_ROSTER.heroIds,...PACKS.map(p=>p.definition.registryNumericId)])]};
// Explicit isolated diagnostic: stripping Bristle's gate only exposes its known block defect.
// Not exported or usable by UI; no success here grants the blocked hero complete acceptance.
const bristleDiagnostic=()=>({...PACKS.find(p=>p.definition.registryNumericId===97),contract:{...PACKS.find(p=>p.definition.registryNumericId===97).contract,requiresCapabilities:[]}});
export function arena(id=99,side=0,opponent=0,{diagnostic=false}={}){const ps=[...CORE4_PACKS,...ENGINE_PACKS,...(diagnostic?[bristleDiagnostic()]:[])],pair=side?[opponent,id]:[id,opponent];const e=new Engine(heroes,pair,{seed:197,simulationRoster:roster,heroPacks:ps}).start();const f=e.fighters[side],t=e.fighters[1-side];f.x=side?600:400;t.x=500;return {e,f,t,opts:{seed:197,simulationRoster:roster,heroPacks:ps},pair};}
export function run(e,seconds){const end=e.t+seconds;let n=0;while(e.t<end-1e-8&&e.phase==='fight'){e.step();assert(++n<20000);}}
test('all35 identities, selections, innate omissions and immutable unlock gates preserved',()=>{assert.equal(PACKS.length,35);assert.deepEqual(PACKS.map(p=>p.definition.registryNumericId),Array.from({length:36},(_,i)=>91+i).filter(x=>x!==100));for(const p of PACKS){assert.equal(p.systemId,'r91');assert.equal(p.sharedSystem,R91Combat);assert(Object.isFrozen(p.definition));assert.equal(p.definition.activeUnlock,false);assert.equal(p.definition.runtimeReady,false);assert.deepEqual(p.contract.selectedAbilityIds,p.definition.abilities.map(a=>a.valveAbilityId));assert(p.contract.automaticInnateIds.every(x=>!p.contract.omittedAbilityIds.includes(x)));}assert.deepEqual(ENGINE_PACKS.map(p=>p.definition.registryNumericId),[94,99,104,106,117,121,124]);});
for(const p of PACKS.filter(p=>p.contract.requiresCapabilities.length))test(`real Engine capability gate rejects ${p.definition.registryNumericId} before init`,()=>assert.throws(()=>new Engine(heroes,[p.definition.registryNumericId,0],{heroPacks:[...CORE4_PACKS,p],simulationRoster:roster}),/Missing public pack capability/));
for(const id of [94,99])for(const side of [0,1])for(let slot=0;slot<4;slot++)test(`real Engine ${id} side${side} slot${slot}: committed input or passive gray refusal`,()=>{const {e,f}=arena(id,side),a=e.ability(side,slot),mp=f.mp;e.setInput(side,{['s'+slot]:true});e.step();if(a.mvp.passive){assert.equal(f.casts,0);near(f.mp,mp);assert.equal(f.cd[slot],0);}else{assert.equal(f.casts,1);near(f.mp,mp-a.mvp.mana);run(e,.7);assert(e.logs.some(l=>l.type==='activate'&&l.skill===a.id));}});
for(const side of [0,1]){
 test(`Seal side${side} refuses new hostile status under immunity, buffs remain usable`,()=>{const {e,f,t}=arena(99,side,94);e.addBuff(t,'harness_immune',{debuffImmune:true},2);assert(e.cast(side,2));run(e,.2);assert.equal(api.status(e,t,'seal'),undefined);assert(!e.isSilenced(t));assert(e.cast(t.i,3));assert(t.packModules.r91.data.stampede);});
 test(`Seal side${side} ongoing immunity suppresses silence+amp without deletion, expiry keeps advancing`,()=>{const {e,f,t}=arena(99,side,94);e.cast(side,2);run(e,.2);const s=api.status(e,t,'seal');assert(s&&s.hostile&&!s.pierces);let hp=t.hp;api.damageResult(e,f.i,t,100,{type:'magical',abilityId:'audit'});near(hp-t.hp,135);e.addBuff(t,'harness_immune',{debuffImmune:true},1);assert(!e.isSilenced(t));hp=t.hp;api.damageResult(e,f.i,t,100,{type:'magical',abilityId:'audit'});near(hp-t.hp,100);assert.equal(api.status(e,t,'seal'),s);const life=s.life;run(e,1.1);assert(s.life<life);assert(e.isSilenced(t));hp=t.hp;api.damageResult(e,f.i,t,100,{type:'magical',abilityId:'audit'});near(hp-t.hp,135);run(e,5);assert(!e.isSilenced(t));});
 test(`Centaur side${side} self Stampede accepts enemy invulnerability and produces actual movement speed`,()=>{const {e,f,t}=arena(94,side);t.invuln=2;const base=e.packCombat.moveMultiplier(e,f);assert(e.cast(side,3));const fast=e.packCombat.moveMultiplier(e,f);assert(fast>base);near(e.hero(side).move_speed*fast,330);f.recovery=0;const x=f.x;e.setInput(side,side?{left:true}:{right:true});run(e,.1);assert(Math.abs(f.x-x)>30);});
 test(`Centaur side${side} self disarm survives debuff immunity and short stun cancels windup persistently`,()=>{const {e,f,t}=arena(94,side);e.addBuff(f,'harness_immune',{debuffImmune:true},1);e.cast(side,0);assert(e.packCombat.disarmed(e,f));assert(!e.attack(side));const hp=t.hp;e.control(f,'stun',.1,true);run(e,.8);near(t.hp,hp);assert(!e.packCombat.disarmed(e,f));});
 test(`Centaur side${side} Double Edge goes through the real nonlethal damage pipeline`,()=>{const {e,f,t}=arena(94,side);f.hp=10;const hp=t.hp;e.cast(side,1);run(e,.4);near(hp-t.hp,451.65);near(f.hp,1);assert(e.logs.some(l=>l.type==='hit'&&l.skill==='centaur_double_edge'));});
 test(`Bristle diagnostic side${side}: Goo armor and slow are suppressed then resume`,()=>{const {e,f,t}=arena(97,side,94,{diagnostic:true});e.cast(side,0);run(e,.7);assert(api.status(e,t,'goo')?.hostile);const normal=e.packCombat.moveMultiplier(e,t);e.addBuff(t,'harness_immune',{debuffImmune:true},1);assert(e.packCombat.moveMultiplier(e,t)>normal);let hp=t.hp;api.damageResult(e,f.i,t,100,{type:'physical',abilityId:'audit'});near(hp-t.hp,100);run(e,1.1);hp=t.hp;api.damageResult(e,f.i,t,100,{type:'physical',abilityId:'audit'});near(hp-t.hp,100*(1+.39/1.39));});
}
test('Centaur Retaliate depends on landed basic attack even if actual debit is zero',()=>{const {e,f,t}=arena(94);e.addBuff(f,'harness_full_reduction',{physical_reduction:1},1);const hp=t.hp;e.basicHit(t,f,{id:++e.seq,damage:30,m:{damage_type:'physical',blockable:false}});near(f.hp,f.maxHp);near(hp-t.hp,80.385);const after=t.hp;api.damageResult(e,t.i,f,30,{type:'pure',abilityId:'audit',reflected:true});near(t.hp,after);});
test('Centaur missed/invulnerable received attack cannot retaliate',()=>{const {e,f,t}=arena(94);f.invuln=1;const hp=t.hp;e.basicHit(t,f,{id:++e.seq,damage:30,m:{damage_type:'physical'}});near(t.hp,hp);});
test('Skywrath barrier uses actual magic debit and never creates a copied HP authority',()=>{const {e,f,t}=arena(99,0,100);t.pack.borrowed=2;t.hp=600;api.damageResult(e,0,t,200,{type:'magical',abilityId:'skywrath_mage_arcane_bolt'});assert.equal(f.packModules.r91.data.barriers.length,0);near(t.hp,800);assert(!('hp'in f.packModules.r91.data));});
test('Seal amplifier precedes the existing Abaddon shield exactly once',()=>{const {e,f,t}=arena(99,0,100);e.cast(1,1);run(e,.6);e.cast(0,2);run(e,.2);const hp=t.hp,r=api.damageResult(e,0,t,200,{type:'magical',abilityId:'audit'});near(r.actual,60);near(hp-t.hp,60);});
test('Skywrath reflection preserves caster profile and never grants reflected Scion stacks',()=>{for(const slot of [0,2]){const {e,f,t}=arena(99,0,5);e.cast(1,2);run(e,.1);e.cast(0,slot);run(e,1);if(slot===0){assert(f.hp<f.maxHp);assert.equal(f.packModules.r91.data.barriers.length,0);}else {assert(e.isSilenced(f));assert(!e.isSilenced(t));}}});
test('Mystic Flare ticks20 times at a fixed area and stops hitting an escaped target',()=>{const {e,f,t}=arena(99);const hp=t.hp;e.cast(0,3);run(e,2.2);near(hp-t.hp,1600);const z=arena(99);z.e.cast(0,3);run(z.e,.5);z.t.x=1000;const escaped=z.t.hp;run(z.e,2);near(z.t.hp,escaped);});
test('Bristle diagnostic exposes missing block bypass; capability remains declared',()=>{const {e,f,t}=arena(97,0,94,{diagnostic:true});e.addBuff(t,'harness_block',{block_flat:20,block_fraction_cap:1},1);const hp=t.hp;e.cast(0,1);run(e,.1);near(hp-t.hp,65);assert(PACKS.find(p=>p.definition.registryNumericId===97).contract.requiresCapabilities.includes('damage-block-bypass'));});
test('pure admission on actual Engine fighters: priority self skills ignore enemy invulnerability, Kisses min range rejects',()=>{const {e,f,t}=arena(94);t.invuln=2;for(const [rid,slot]of [[94,3],[102,1],[109,3]]){const a=PACKS.find(p=>p.definition.registryNumericId===rid).definition.abilities[slot];assert(validateAim(e,f,a).ok);}const a=PACKS.find(p=>p.definition.registryNumericId===118).definition.abilities[3],before=e.snapshot();t.x=f.x+150;const state=e.snapshot();assert.equal(validateAim(e,f,a).reason,'minimum_range');assert.deepEqual(e.snapshot(),state);assert(validateAim(e,f,a,{aim:f.x+400}).ok);assert(!validateAim(e,f,a,{aim:NaN}).ok);});
for(const [rid,slot]of [[94,0],[94,3],[99,0],[99,2],[99,3]])test(`real Engine deterministic restore ${rid}/${slot}`,()=>{const {e,opts,pair}=arena(rid);e.cast(0,slot);run(e,.12);const s=e.snapshot();assert(R91Combat.validateSnapshot(e,s));const b=new Engine(heroes,pair,opts).restoreSimulation(s);for(let i=0;i<100;i++){e.step();b.step();assert.deepEqual(e.snapshot(),b.snapshot());}});
test('strict own snapshot validator rejects forged copied profiles and payload values',()=>{const cases=[{id:99,slot:0,age:.2,mutations:[s=>s.packModules.r91.entities[0].data.damage=9999,s=>s.packModules.r91.entities[0].data.abilityId='centaur_hoof_stomp',s=>s.packModules.r91.entities[0].data.extra=true]},{id:94,slot:0,age:.1,mutations:[s=>s.packModules.r91.jobs[0].kind='quill',s=>s.packModules.r91.jobs[0].data={damage:9999},s=>s.packModules.r91.jobs[0].id=0]},{id:99,slot:2,age:.2,mutations:[s=>s.fighters[1].packModules.r91.statuses[0].hostile=false,s=>s.fighters[1].packModules.r91.statuses[0].pierces=true,s=>s.fighters[1].packModules.r91.statuses[0].values.magicAmp=9]}];for(const c of cases){const {e,opts,pair}=arena(c.id);e.cast(0,c.slot);run(e,c.age);for(const mutate of c.mutations){const s=e.snapshot();mutate(s);assert.throws(()=>new Engine(heroes,pair,opts).restoreSimulation(s),/Invalid simulation snapshot/);}}const {e,opts,pair}=arena(99);e.cast(0,0);const s=e.snapshot();s.fighters[0].cast.m.mana=0;assert.throws(()=>new Engine(heroes,pair,opts).restoreSimulation(s));});
test('pause, hitstop and round reset use the Engine simulation clock',()=>{const {e,f}=arena(99);e.cast(0,0);run(e,.2);const snap=e.snapshot();e.paused=true;e.step();assert.equal(e.t,snap.t);assert.deepEqual(e.packModules,snap.packModules);e.paused=false;e.hitstop=1;e.step();assert.equal(e.t,snap.t);assert.deepEqual(e.packModules,snap.packModules);e.resetRound();assert.equal(e.packModules.r91.entities.length,0);assert.equal(e.fighters[0].packModules.r91.data.barriers.length,0);});
test('mirror picks initialize/tick the shared system once and produce valid snapshots',()=>{const {e}=arena(99,0,99);e.cast(0,0);e.cast(1,0);run(e,.2);assert.equal(e.packModules.r91.entities.length,2);assert(R91Combat.validateSnapshot(e,e.snapshot()));});
test('reflected Seal and Goo retain separate origin/owner and pass strict restore',()=>{for(const [id,slot]of [[99,2],[97,0]]){const {e,f,t,opts,pair}=arena(id,0,5,{diagnostic:id===97});e.cast(1,2);run(e,.1);e.cast(0,slot);run(e,1);const s=api.status(e,f,id===99?'seal':'goo');assert(s);assert.equal(s.owner,1);assert.equal(s.origin,0);assert(R91Combat.validateSnapshot(e,e.snapshot()));const b=new Engine(heroes,pair,opts).restoreSimulation(e.snapshot());run(e,.2);run(b,.2);assert.deepEqual(e.snapshot(),b.snapshot());}});
test('pierces debuff immunity does not permit new delivery to invulnerable fighter',()=>{const {e,t}=arena(99);t.invuln=1;assert.equal(api.applyStatus(e,t,{key:'seal',owner:0,duration:1,values:{silence:true},pierces:true}),null);assert.equal(api.applyPositiveStatus(e,t,{key:'buff',owner:1,duration:1,values:{attack:1}}),null);});

test('invalid point/self options cannot bypass enemy range or spend resources',()=>{const {e,f,t}=arena(99);t.x=1155;const before=e.snapshot();assert.equal(e.cast(0,2,{self:true}),false);assert.deepEqual(e.snapshot(),before);assert.equal(e.cast(0,3,{aim:NaN}),false);assert.deepEqual(e.snapshot(),before);});
test('hostile periodic callbacks discard suppressed ticks without catch-up',()=>{const {e,f,t}=arena(99);const s=api.applyStatus(e,t,{key:'seal',owner:0,duration:2,values:{},interval:.1});s.hostile=true;s.polarity='hostile';s.origin=0;let count=0,enabled=0;e.addBuff(t,'harness_immune',{debuffImmune:true},1);for(let i=0;i<10;i++)api.advanceStatuses(e,t,.05,(_s,ok)=>{count++;if(ok)enabled++;});assert.equal(count,5);assert.equal(enabled,0);t.buffs=[];for(let i=0;i<2;i++)api.advanceStatuses(e,t,.05,(_s,ok)=>{count++;if(ok)enabled++;});assert.equal(count,6);assert.equal(enabled,1);});
test('Stampede does not consume its one contact on an invulnerable target',()=>{const {e,f,t}=arena(94);t.x=f.x+30;t.invuln=.5;const hp=t.hp;e.cast(0,3);run(e,.3);near(t.hp,hp);assert.equal(f.packModules.r91.data.stampede.hit.length,0);run(e,.3);near(hp-t.hp,303.3);assert.deepEqual(f.packModules.r91.data.stampede.hit,[1]);});
// The following are explicit typed-status integration fixtures, not Oracle hero acceptance.
function typedArena(){const service=createPackServices('statusprobe'),original=PACKS.find(p=>p.definition.registryNumericId===94),fixture={...original,definition:{...original.definition,packKey:'statusprobe'},systemId:'statusprobe',sharedSystem:{namespace:'statusprobe',init(e){service.world(e);for(const f of e.fighters)service.fighter(e,f);},cast(){return false;},activate(){throw Error('no fixture skills');},tick(e,dt){for(const f of e.fighters)service.advanceStatuses(e,f,dt);},validateSnapshot(_e,s){return service.validateSnapshot(s);}}};const hs=heroes.map(h=>h.registryNumericId===94?fixture.definition:h),opts={seed:197,simulationRoster:roster,heroPacks:[...CORE4_PACKS,...ENGINE_PACKS.filter(p=>p.definition.registryNumericId!==94),fixture]},e=new Engine(hs,[99,94],opts).start();e.fighters[0].x=400;e.fighters[1].x=500;return {e,service,hs,opts};}
test('ABI2.1 typed positive namespace immunity suppresses R91 Seal across systems',()=>{const {e,service}=typedArena(),[f,t]=e.fighters;e.cast(0,2);run(e,.2);assert(e.isSilenced(t));const s=service.applyPositiveStatus(e,t,{key:'immune',owner:1,duration:1,values:{debuffImmune:true},dispel:'none'});assert.equal(s.hostile,false);assert.equal(s.polarity,'positive');assert.equal(s.pierces,false);assert.equal(e.property(t,'debuffImmune'),1);assert(!e.isSilenced(t));const hp=t.hp;api.damageResult(e,0,t,100,{type:'magical',abilityId:'audit'});near(hp-t.hp,100);run(e,1.1);assert(e.isSilenced(t));});
test('ABI2.1 mixed components serialize separately, suppress and dispel by polarity',()=>{const {e,service}=typedArena(),t=e.fighters[1];const parts=service.applyMixedStatus(e,t,{key:'edict_fixture',owner:0,duration:3,positive:{values:{magicShield:1},dispel:'basic'},negative:{values:{disarm:true},dispel:'basic'}});for(const s of [parts.positive,parts.negative]){assert.equal(s.polarity,'mixed');assert.equal(s.group,'edict_fixture');assert.equal(s.owner,0);}assert.equal(parts.positive.hostile,false);assert.equal(parts.negative.hostile,true);service.applyPositiveStatus(e,t,{key:'immune',owner:1,duration:1,values:{debuffImmune:true},dispel:'none'});assert(service.hasValue(e,t,'magicShield'));assert(!service.hasValue(e,t,'disarm'));service.dispel(e,t,'basic',{hostile:false});assert(!service.hasValue(e,t,'magicShield'));assert(service.status(e,t,'edict_fixture_hostile'));run(e,1.1);assert(service.hasValue(e,t,'disarm'));service.dispel(e,t,'basic');assert(!service.hasValue(e,t,'disarm'));});
test('ABI2.1 typed positive/mixed statuses roundtrip with immunity and no catch-up',()=>{const {e,service,hs,opts}=typedArena(),t=e.fighters[1];service.applyMixedStatus(e,t,{key:'pair_fixture',owner:0,duration:2,positive:{values:{gain:2},dispel:'strong',interval:.2},negative:{values:{loss:3},dispel:'basic',interval:.2}});service.applyPositiveStatus(e,t,{key:'immune',owner:1,duration:.5,values:{debuffImmune:true},dispel:'none'});const s=e.snapshot(),b=new Engine(hs,[99,94],opts).restoreSimulation(s);for(let i=0;i<80;i++){e.step();b.step();assert.deepEqual(e.snapshot(),b.snapshot());}});
test('ABI2.1 positive status applies under immunity; mixed negative half alone is rejected',()=>{const {e,service}=typedArena(),t=e.fighters[1];e.addBuff(t,'harness_immune',{debuffImmune:true},1);const parts=service.applyMixedStatus(e,t,{key:'pair_fixture',owner:0,duration:2,positive:{values:{gain:2},dispel:'basic'},negative:{values:{loss:3},dispel:'basic'}});assert(parts.positive);assert.equal(parts.negative,null);assert.equal(service.value(e,t,'gain'),2);assert.equal(service.value(e,t,'loss'),0);});
