// Five expected missing-capability failures at frozen c84ca0d ABI2.4. Deferred HP is now provided and tested separately.
// Real Engine probes; injected test HP/positions are explicitly harness initial state.
import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../../src/engine.js';import {runtimeHeroes} from '../../../src/runtime-heroes.js';import {CORE4_PACKS} from '../../../src/hero-packs/index.js';import {ACTIVE_ROSTER} from '../../../src/hero-registry.js';import {PACKS,ENGINE_PACKS} from '../../../src/hero-packs/r91/index.js';import {createPackServices} from '../../../src/pack-services.js';
const api=createPackServices('r91_probe'),h=[...runtimeHeroes.filter(h=>!PACKS.some(p=>p.definition.registryNumericId===h.registryNumericId)),...PACKS.map(p=>p.definition)],roster={...ACTIVE_ROSTER,heroIds:[...ACTIVE_ROSTER.heroIds,94,97,99]};
const arena=()=>new Engine(h,[94,99],{heroPacks:[...CORE4_PACKS,...ENGINE_PACKS],simulationRoster:roster}).start();
test('REQUIRED forced-orders: Duel timed mutual attacks and expiry restoration',()=>{const e=arena();assert.equal(typeof api.forceOrder,'function','no public forced-order authority in frozen ABI');const token=api.forceOrder(e,{actor:0,kind:'attack',target:1,duration:5,blockManualMove:true,blockManualAttack:true});assert(token);});
test('REQUIRED swept-motion: Skewer short stun invalidates collision/damage token',()=>{const e=arena();assert.equal(typeof api.startMotion,'function','e.move is endpoint clamping, not swept motion');const token=api.startMotion(e,{owner:0,actor:0,destinationX:600,speed:495,abilityId:'magnataur_skewer',cancelOnInterrupt:true});e.control(e.fighters[0],'stun',.1);assert.equal(api.motionActive(e,token),false);});
test('REQUIRED attackable-units: Phoenix egg receives10 landed hero attacks, exactly one owner death',()=>{const e=arena();assert.equal(typeof api.spawnUnit,'function','effect-only spawn cannot create an attackable egg');const egg=api.spawnUnit(e,{owner:0,kind:'egg',x:320,attackCountHP:10,life:6});assert.notEqual(egg.targetId,0);assert.notEqual(egg.targetId,1);});
test('REQUIRED cross-system-positive-dispel: remove a legacy enemy buff without removing negative Seal',()=>{const e=arena();assert.equal(typeof e.dispelStatusesByPolarity,'function','ABI2.1 api.dispel is namespace-local; no global public polarity dispatcher for foreign/legacy buffs');});
test('REQUIRED damage-block-bypass: Quill must deal85, not65, through flat20 block',()=>{const p=PACKS.find(p=>p.definition.registryNumericId===97),diagnostic={...p,contract:{...p.contract,requiresCapabilities:[]}};const e=new Engine(h,[97,94],{heroPacks:[...CORE4_PACKS,...ENGINE_PACKS,diagnostic],simulationRoster:roster}).start(),[f,t]=e.fighters;f.x=400;t.x=500;e.addBuff(t,'harness_block',{block_flat:20,block_fraction_cap:1},1);const hp=t.hp;e.cast(0,1);assert.equal(hp-t.hp,85,'gated diagnostic demonstrates existing flat-block semantic mismatch');});
