import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../../src/engine.js';import {runtimeHeroes} from '../../../src/runtime-heroes.js';import {CORE4_PACKS} from '../../../src/hero-packs/index.js';import {ACTIVE_ROSTER} from '../../../src/hero-registry.js';import {PACKS,ENGINE_PACKS} from '../../../src/hero-packs/r91/index.js';import {api,R91Combat} from '../../../src/hero-packs/r91/runtime.js';
const IDS=[104,106,117,121,124],near=(a,b)=>assert(Math.abs(a-b)<1e-5,`${a} != ${b}`);
const hs=[...runtimeHeroes.filter(h=>!PACKS.some(p=>p.definition.registryNumericId===h.registryNumericId)),...PACKS.map(p=>p.definition)],opts={seed:197,simulationRoster:{...ACTIVE_ROSTER,heroIds:[...new Set([...ACTIVE_ROSTER.heroIds,...ENGINE_PACKS.map(p=>p.definition.registryNumericId)])]},heroPacks:[...CORE4_PACKS,...ENGINE_PACKS]};
function arena(id,side=0,other=0){const pair=side?[other,id]:[id,other],e=new Engine(hs,pair,opts).start(),f=e.fighters[side],t=e.fighters[1-side];f.x=side?800:400;t.x=side?700:500;return {e,f,t,pair};}
function run(e,seconds){const end=e.t+seconds;let count=0;while(e.t<end-1e-8&&e.phase==='fight'){e.step();assert(count++<20000);}}
function input(e,i,slot){e.setInput(i,{['s'+slot]:true});const at=e.t;let n=0;do{e.step();assert(n++<100);}while(e.t===at&&e.phase==='fight');e.setInput(i,{});}
for(const id of IDS)for(const side of [0,1])for(let slot=0;slot<4;slot++)test(`V5 input→step ${id} side${side} slot${slot+1}`,()=>{const {e,f,t}=arena(id,side);if(id===106&&slot===3)f.x=side?1100:100;const a=e.ability(side,slot),mp=f.mp;input(e,side,slot);if(a.mvp.passive){assert.equal(f.casts,0);near(f.mp,mp);assert.equal(f.cd[slot],0);}else{assert.equal(f.casts,1);near(f.mp,mp-a.mvp.mana);run(e,.7);assert(e.logs.some(l=>l.type==='activate'&&l.skill===a.id));}assert(R91Combat.validateSnapshot(e,e.snapshot()));});
for(const side of [0,1]){
 test(`Ember Chains side${side} full275, dispel, immunity suppresses without catchup`,()=>{const {e,f,t}=arena(104,side);const hp=t.hp;input(e,side,0);run(e,3);near(hp-t.hp,275);const z=arena(104,side);input(z.e,side,0);run(z.e,.25);z.e.addBuff(z.t,'harness_immune',{debuffImmune:true},1);const before=z.t.hp;run(z.e,.8);near(z.t.hp,before);run(z.e,2.5);assert(z.t.hp<before);assert(z.t.hp>z.t.maxHp-275);const w=arena(104,side);input(w.e,side,0);run(w.e,.3);w.e.dispel(w.t,'basic');const clean=w.t.hp;run(w.e,3);near(w.t.hp,clean);});
 test(`Ember Sleight side${side} real invulnerability and one ability slash`,()=>{const {e,f,t}=arena(104,side);const hp=t.hp;input(e,side,1);assert(f.invuln>0);const own=f.hp;api.damageResult(e,t.i,f,100,{type:'pure',abilityId:'fixture'});near(f.hp,own);run(e,.5);near(hp-t.hp,e.hero(side).attack+160);assert.equal(e.logs.filter(l=>l.type==='hit'&&l.skill==='ember_spirit_sleight_of_fist').length,1);});
 test(`Ember FlameGuard side${side} actual post-mitigation70% shield and exhaustion stops aura`,()=>{const {e,f,t}=arena(104,side);input(e,side,2);const st=api.status(e,f,'x_flame_'+side);e.addBuff(f,'harness_mr',{magic_reduction:.5},1);const r=api.damageResult(e,t.i,f,200,{type:'magical',abilityId:'fixture'});near(r.actual,30);near(st.values.amount,230);api.damageResult(e,t.i,f,1000,{type:'magical',abilityId:'fixture'});assert.equal(api.status(e,f,'x_flame_'+side),undefined);const hp=t.hp;run(e,.5);near(t.hp,hp);});
 test(`Underlord side${side} fixed gate min distance, control/input cancellation and successful teleport`,()=>{const z=arena(106,side);const before=z.e.snapshot();assert.equal(z.e.cast(side,3,{aim:z.f.x+100}),false);assert.deepEqual(z.e.snapshot(),before);z.f.x=side?1100:100;input(z.e,side,3);run(z.e,.2);z.e.control(z.f,'stun',.1);run(z.e,4);near(z.f.x,side?1100:100);const w=arena(106,side);w.f.x=side?1100:100;input(w.e,side,3);run(w.e,3.6);near(w.f.x,side?45:1155);});
 test(`Void side${side} physical shield never consumes magical damage and counts conversion hit`,()=>{const {e,f,t}=arena(117,side,100);t.pack.borrowed=2;t.hp=600;input(e,side,2);run(e,.1);const sh=api.status(e,f,'x_pulse_'+side);near(sh.values.amount,210);const r=api.damageResult(e,t.i,f,100,{type:'magical',abilityId:'fixture'});near(r.actual,100);near(sh.values.amount,210);near(api.damageResult(e,t.i,f,100,{type:'physical',abilityId:'fixture'}).actual,0);near(sh.values.amount,110);});
 test(`Dawn side${side} Luminosity fourth landed crit heals exact attackId receipt`,()=>{const {e,f,t}=arena(121,side);f.hp=2000;for(let i=0;i<3;i++)e.basicHit(f,t,{id:++e.seq,damage:100,m:{damage_type:'physical',blockable:false}});const hp=t.hp,own=f.hp;e.basicHit(f,t,{id:++e.seq,damage:100,m:{damage_type:'physical',blockable:false}});near(hp-t.hp,200);near(f.hp-own,100);assert.equal(f.packModules.r91.data.extra.luminosity,0);});
 test(`Muerta side${side} Veil physical immunity precedes shields and converts real basic attacks`,()=>{const {e,f,t}=arena(124,side);input(e,side,3);run(e,.6);assert(api.hasValue(e,f,'physicalImmune'));near(api.damageResult(e,t.i,f,100,{type:'physical',abilityId:'fixture'}).actual,0);near(api.damageResult(e,t.i,f,100,{type:'magical',abilityId:'fixture'}).actual,100);const m={damage_type:'physical'},base=e.hero(side).attack,modified=e.packCombat.attack(e,f,t,base,m);near(modified,2*base);assert.equal(m.damage_type,'magical');run(e,8.1);assert(!api.hasValue(e,f,'physicalImmune'));});
}
test('Ember Remnant three charges exhaust and restore serially, source death cancels teleport',()=>{const {e,f,t}=arena(104);for(let i=0;i<3;i++){assert(e.cast(0,3,{aim:500+i*10}));run(e,.6);}const c=f.packModules.r91.data.extra.charges[0];assert.equal(c.count,0);f.cd[3]=0;f.recovery=0;const snap=e.snapshot();assert.equal(e.cast(0,3),false);assert.deepEqual(e.snapshot(),snap);run(e,34);assert.equal(c.count,1);const z=arena(104);z.e.cast(0,3,{aim:700});api.damageResult(z.e,1,z.f,10000,{type:'pure',abilityId:'fixture'});z.e.step();assert(!z.e.packModules.r91.jobs.some(j=>j.owner===0));near(z.f.x,400);});
test('Underlord Firestorm has6 waves and nonstacking burn; Pit retriggers only after3.6',()=>{const {e,f,t}=arena(106);input(e,0,0);run(e,6.7);assert.equal(e.logs.filter(l=>l.type==='hit'&&l.skill==='abyssal_underlord_firestorm'&&Math.abs(l.damage-105)<.001).length,6);assert(api.status(e,t,'x_fireburn_0'));const w=arena(106);input(w.e,0,1);run(w.e,7.8);assert.equal(w.e.logs.filter(l=>l.type==='hit'&&l.skill==='abyssal_underlord_pit_of_malice').length,3);});
test('Underlord aura reduces only base attack and grants once at authoritative death dispatch',()=>{const {e,f,t}=arena(106);const m={damage_type:'physical'},base=e.hero(1).attack;near(e.packCombat.attack(e,t,f,base+40,m),base*.68+40);api.damageResult(e,0,t,1e4,{type:'pure',abilityId:'fixture'});e.step();near(api.value(e,f,'bonusDamage'),45);e.step();near(api.value(e,f,'bonusDamage'),45);});
test('Void remnant waits for legal target then pulls via Engine clamp, one activation',()=>{const {e,f,t}=arena(117);t.x=600;assert(e.cast(0,0,{aim:550}));run(e,.3);const hp=t.hp;near(t.hp,hp);run(e,.3);near(hp-t.hp,240);assert(t.x<600);run(e,1);near(hp-t.hp,240);});
test('Void phase has no damage before exit and never resets existing longer invulnerability',()=>{const {e,f,t}=arena(117);assert(e.cast(0,1,{aim:f.x}));run(e,.4);f.invuln=3;const hp=t.hp;run(e,1.1);near(hp-t.hp,345);assert(f.invuln>1.5);});
test('Void Astral has two charges and only exit hit, mark suppresses under immunity',()=>{const {e,f,t}=arena(117);t.x=650;input(e,0,3);run(e,.25);const c=f.packModules.r91.data.extra.charges[0];assert.equal(c.count,1);assert(api.status(e,t,'x_voidmark_0'));e.addBuff(t,'harness_immune',{debuffImmune:true},2);const hp=t.hp;run(e,1.5);near(t.hp,hp);assert(!api.status(e,t,'x_voidmark_0'));const z=arena(117);z.t.x=500;z.e.cast(0,3,{aim:850});run(z.e,.3);near(z.t.hp,z.t.maxHp);});
test('Dawn Starbreaker exactly3 slams and short control invalidates future slams',()=>{const {e,f,t}=arena(121);input(e,0,0);run(e,1.4);assert.equal(e.logs.filter(l=>l.type==='hit'&&l.skill==='dawnbreaker_fire_wreath').length,3);const z=arena(121);input(z.e,0,0);run(z.e,.15);z.e.control(z.f,'stun',.1);run(z.e,1.5);near(z.t.hp,z.t.maxHp);});
test('Dawn Hammer has outgoing/return hits and true fire-trail ticks; Solar heals/pulses/lands',()=>{const {e,f,t}=arena(121);input(e,0,1);run(e,6.5);const hits=e.logs.filter(l=>l.type==='hit'&&l.skill==='dawnbreaker_celestial_hammer');assert.equal(hits.filter(h=>h.damage===140).length,2);assert(hits.some(h=>h.damage===25));const z=arena(121);z.f.hp=2000;input(z.e,0,3);run(z.e,3);near(z.f.hp,2285);near(z.t.maxHp-z.t.hp,400);});
test('Dawn guard actual>0 does not count landed; converted fourth attack heals0',()=>{const {e,f,t}=arena(121,0,100);f.hp=2000;for(let i=0;i<3;i++)e.basicHit(f,t,{id:++e.seq,damage:20,m:{damage_type:'physical',blockable:false}});t.pack.borrowed=2;t.hp=600;const hp=f.hp;e.basicHit(f,t,{id:++e.seq,damage:100,m:{damage_type:'physical',blockable:false}});near(f.hp,hp);assert.equal(f.packModules.r91.data.extra.luminosity,0);const z=arena(121);z.e.setInput(1,{right:true});z.e.basicHit(z.f,z.t,{id:++z.e.seq,damage:100,m:{damage_type:'physical',blockable:true}});assert.equal(z.f.packModules.r91.data.extra.luminosity,0);});
test('Muerta direct shot reflects once and Calling has actual orbital contacts/immune suppression',()=>{const {e,f,t}=arena(124,0,5);e.cast(1,2);run(e,.1);input(e,0,0);run(e,1);assert(f.hp<f.maxHp);near(t.hp,t.maxHp);const z=arena(124);input(z.e,0,1);run(z.e,1);assert(z.t.hp<z.t.maxHp);z.e.addBuff(z.t,'harness_immune',{debuffImmune:true},1);assert(!z.e.isSilenced(z.t));near(z.e.packCombat.moveMultiplier(z.e,z.t),1);});
test('Muerta Gunslinger is toggleable, seeded, no recursive secondary proc and break-safe',()=>{const {e,f,t}=arena(124);e.seed=1;const hp=t.hp;e.basicHit(f,t,{id:++e.seq,damage:100,m:{damage_type:'physical',blockable:false}});near(hp-t.hp,100+e.hero(0).attack);input(e,0,2);run(e,.3);assert.equal(f.packModules.r91.data.extra.gunslinger,false);e.seed=1;const before=t.hp;e.basicHit(f,t,{id:++e.seq,damage:100,m:{damage_type:'physical',blockable:false}});near(before-t.hp,100);});
for(const [id,slot,age]of [[104,0,.5],[104,2,.4],[104,3,.4],[106,0,1],[106,3,1],[117,0,.2],[117,1,.4],[117,3,.4],[121,0,.4],[121,1,1],[121,3,.5],[124,1,.5],[124,3,.5]])test(`V5 restore pending ${id}/${slot}`,()=>{const {e,f,pair}=arena(id);if(id===106&&slot===3)f.x=100;input(e,0,slot);run(e,age);const snap=e.snapshot();assert(R91Combat.validateSnapshot(e,snap));const b=new Engine(hs,pair,opts).restoreSimulation(snap);for(let i=0;i<240;i++){e.step();b.step();assert.deepEqual(e.snapshot(),b.snapshot());}});
test('V5 snapshot rejects changed damage/status owner/opcode/charge count and finite-but-invalid values',()=>{for(const [id,slot,mutate]of [[104,2,s=>s.fighters[0].packModules.r91.statuses[0].values.amount=9999],[104,3,s=>s.fighters[0].packModules.r91.data.extra.charges[0].count=99],[121,1,s=>s.packModules.r91.jobs[0].data.op='solar_land'],[124,1,s=>s.packModules.r91.entities[0].data.mode='storm'],[106,0,s=>s.packModules.r91.entities[0].data.face=99]]){const {e,pair}=arena(id);input(e,0,slot);run(e,.6);const snap=e.snapshot();mutate(snap);assert.throws(()=>new Engine(hs,pair,opts).restoreSimulation(snap));}});
test('V5 actual damage receipts never enter persistent fighter/world state',()=>{const {e,f,t}=arena(121);e.basicHit(f,t,{id:++e.seq,damage:100,m:{damage_type:'physical'}});assert(!Object.hasOwn(f.packModules.r91.data.extra,'lastAttack'));assert(!JSON.stringify(e.packModules).includes('actual'));});
test('V5 passive break suppresses Underlord aura, Dawn stack gain and Muerta bonus shot',()=>{for(const id of [106,121,124]){const {e,f,t}=arena(id,0,45);f.pack.statuses.push({key:'viper_strike',owner:1,life:6,values:{},dispel:'none',pierces:true});assert(!e.passivesEnabled(f));if(id===106){const base=e.hero(1).attack;near(e.packCombat.attack(e,t,f,base,{damage_type:'physical'}),base);}else{e.seed=1;const hp=t.hp;e.basicHit(f,t,{id:++e.seq,damage:100,m:{damage_type:'physical',blockable:false}});near(hp-t.hp,100);if(id===121)assert.equal(f.packModules.r91.data.extra.luminosity,0);}}});
test('V5 own channels cancel on short control, movement, new cast and input_cancel',()=>{for(const cancel of [(e,f)=>e.control(f,'stun',.1),(e,f)=>e.setInput(f.i,{right:true}),(e,f)=>{f.recovery=0;e.cast(f.i,0,{aim:f.x});},(e,f)=>e.cancelInput(f.i)]){const {e,f}=arena(106);f.x=100;input(e,0,3);run(e,.2);cancel(e,f);run(e,4);assert(f.x<800);assert(!f.packModules.r91.data.extra.channel);}});
test('V5 Solar cannot be canceled after launch but manual input before launch prevents all later land effects',()=>{const {e,f,t}=arena(121);input(e,0,3);run(e,.3);e.cancelInput(0);const hp=t.hp;run(e,3);near(t.hp,hp);const z=arena(121);z.e.cast(0,3,{aim:500});run(z.e,1.9);assert(z.f.packModules.r91.data.extra.channel?.flight);z.e.cancelInput(0);run(z.e,1);assert(z.e.logs.some(l=>l.type==='hit'&&l.skill==='dawnbreaker_solar_guardian'&&Math.abs(l.damage-190)<.01));});
test('V5 physical/magical shields are positive and independently dispellable during immunity',()=>{for(const [id,slot,key]of [[104,2,'x_flame_0'],[117,2,'x_pulse_0']]){const {e,f}=arena(id);e.addBuff(f,'harness_immune',{debuffImmune:true},5);input(e,0,slot);run(e,.1);assert(api.effective(e,f,key));api.dispel(e,f,'basic');assert(api.status(e,f,key));api.dispel(e,f,'basic',{hostile:false});assert(!api.status(e,f,key));}});
test('V5 snapshots reject foreign channel ownership and revision rollback',()=>{const {e,pair}=arena(106);const s=e.snapshot();s.fighters[1].packModules.r91.data.extra.channel={kind:'solar',startX:500,until:2.5,flight:false};assert.throws(()=>new Engine(hs,pair,opts).restoreSimulation(s));});
