// All positions, HP/counters and foreign status injections below are explicit harness fixtures.
import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../../../src/engine.js';import {runtimeHeroes} from '../../../src/runtime-heroes.js';import {HERO_PACKS} from '../../../src/pack-runtime.js';import {PACKS,ENGINE_PACKS} from '../../../src/hero-packs/r91/index.js';import {api,R91Combat} from '../../../src/hero-packs/r91/runtime.js';import {createPackServices,PACK_ABI_VERSION,PACK_CAPABILITIES} from '../../../src/pack-services.js';import {ACTIVE_ROSTER} from '../../../src/hero-registry.js';
const hs=[...runtimeHeroes.filter(h=>!PACKS.some(p=>p.definition.registryNumericId===h.registryNumericId)),...PACKS.map(p=>p.definition)];
const foreign=createPackServices('v6_fixture');
function arena(id=99,side=0,other=0,{foreignFixture=false,diagnostic=false}={}){let lock=false;const events=[];const fixture={namespace:'v6_fixture',init(e){foreign.world(e);e.fighters.forEach(f=>foreign.fighter(e,f));},silenced(){return lock;},dispel(e,f,tier){foreign.dispel(e,f,tier);},tick(e,dt){e.fighters.forEach(f=>foreign.advanceStatuses(e,f,dt));},death(e,ev){events.push(ev);},cast(){return false;},activate(){return true;}};
const base=HERO_PACKS.filter(p=>p.systemId!=='r91'),ps=[...base,...ENGINE_PACKS];if(foreignFixture){const p=base.find(p=>p.definition.registryNumericId===25);ps.push({...p,definition:{...(hs.find(h=>h.registryNumericId===other)||runtimeHeroes[other]),registryNumericId:other},contract:{},systemId:'v6_fixture',sharedSystem:fixture});}
if(diagnostic){const p=PACKS.find(p=>p.definition.registryNumericId===97);ps.push({...p,contract:{...p.contract,requiresCapabilities:[]}});}
const pair=side?[other,id]:[id,other],opts={seed:197,heroPacks:ps,simulationRoster:{...ACTIVE_ROSTER,heroIds:hs.map(h=>h.registryNumericId??runtimeHeroes.indexOf(h))}},e=new Engine(hs,pair,opts).start(),f=e.fighters[side],t=e.fighters[1-side];f.x=side?600:400;t.x=500;return {e,f,t,opts,pair,events,setLock(v){lock=v;}};}
const near=(a,b)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`),run=(e,s)=>{const end=e.t+s;let i=0;while(e.t<end-1e-8&&e.phase==='fight'){e.step();assert(++i<10000);}};
test('V6 exact frozen ABI2.4 provides five newly used shared contracts',()=>{assert.equal(PACK_ABI_VERSION,'duel-pack-2.4-targeting');for(const k of ['deferred-hp','death-events','source-controls','action-cancellation','cross-pack-status-query','targeted-spell-routing'])assert(PACK_CAPABILITIES.includes(k));});
for(const side of [0,1]){
 for(const [id,slot] of [[94,1],[99,0],[99,1],[99,2],[124,0],[97,0]])test(`V6 shared route ${id}/${slot} side${side} consumes one counter and preserves origin`,()=>{const {e,f,t}=arena(id,side,5,{diagnostic:id===97});e.addBuff(t,'counter',{},5);e.addBuff(f,'counter',{},5);assert(e.cast(side,slot));run(e,1.2);assert(!e.buff(t,'counter'));assert(e.buff(f,'counter'));assert.equal(e.logs.filter(x=>x.type==='spell_reflected').length,1);near(t.hp,t.maxHp);if(id===99&&slot===2){assert(api.status(e,f,'seal'));assert.equal(api.status(e,f,'seal').origin,side);}else if(id===97)assert(api.status(e,f,'goo'));else assert(f.hp<f.maxHp);assert(R91Combat.validateSnapshot(e,e.snapshot()));});
 for(const [id,slot]of [[99,0],[99,2],[124,0]])test(`V6 route ${id}/${slot} side${side} counter consumed even if reflected destination invulnerable`,()=>{const {e,f,t}=arena(id,side,5);e.addBuff(t,'counter',{},5);assert(e.cast(side,slot));f.invuln=3;run(e,1);assert(!e.buff(t,'counter'));near(f.hp,f.maxHp);near(t.hp,t.maxHp);assert(!api.status(e,f,'seal'));assert(!api.status(e,f,'x_deadslow_'+side));});
 test(`V6 no-cost target admission side${side} never consumes counter or commits action`,()=>{const {e,f,t}=arena(99,side,5);e.addBuff(t,'counter',{},5);t.invuln=2;const before=e.snapshot();assert.equal(e.cast(side,0),false);assert.deepEqual(e.snapshot(),before);});
 test(`V6 immediate delivery rechecks Seal range side${side}`,()=>{const {e,f,t}=arena(99,side,5);e.addBuff(t,'counter',{},5);assert(e.cast(side,2));f.x=45;t.x=1155;run(e,.2);assert(e.buff(t,'counter'));assert(!api.status(e,t,'seal'));assert(!api.status(e,f,'seal'));});
 for(const [id,slot]of [[104,3],[106,3],[117,1],[117,3],[121,3]])test(`V6 source-root mobility admission ${id}/${slot} side${side}`,()=>{const {e,f,t}=arena(id,side);if(id===106)f.x=side?1100:100;const cid=e.applyControlSource(f,{owner:t.i,key:'harness_other_root',type:'root',duration:1,dispel:'basic'});assert(cid);assert.equal(f.root,0);assert(e.controlRemaining(f,'root')>0);const before=e.snapshot();assert.equal(e.cast(side,slot),false);assert.deepEqual(e.snapshot(),before);e.addBuff(f,'harness_immune',{debuffImmune:true},2);assert(e.cast(side,slot));});
 test(`V6 channels use cross-pack effective silence but ignore author action locks side${side}`,()=>{const z=arena(106,side,0,{foreignFixture:true});z.f.x=side?1100:100;assert(z.e.cast(side,3));z.setLock(true);run(z.e,3.6);near(z.f.x,side?45:1155);const w=arena(106,side,0,{foreignFixture:true});w.f.x=side?1100:100;assert(w.e.cast(side,3));foreign.applyStatus(w.e,w.f,{key:'foreign_silence',owner:w.t.i,duration:.1,values:{silence:true}});run(w.e,.05);foreign.dispel(w.e,w.f);run(w.e,4);near(w.f.x,side?1100:100);assert(!w.f.packModules.r91.data.extra.channel);});
 test(`V6 source stun release preserves unrelated raw timer side${side}`,()=>{const {e,f,t}=arena(94,side);assert(e.cast(side,0));run(e,.6);const control=e.packCore.controls.find(c=>c.key==='r91:centaur_hoof_stomp');assert(control);t.root=.8;assert(e.releaseControlSource(control.id,'harness_release'));near(e.controlRemaining(t,'root'),.8);near(e.controlRemaining(t,'stun'),0);});
 test(`V6 basic dispel clears Chains root only, preserving independent strong control side${side}`,()=>{const {e,f,t}=arena(104,side);assert(e.cast(side,0));const root=e.packCore.controls.find(c=>c.key==='r91:ember_spirit_searing_chains');assert(root);t.stun=.2;e.dispel(t,'basic');assert(!e.packCore.controls.some(c=>c.id===root.id));near(t.stun,.2);assert(!api.status(e,t,'x_chains_'+side));});
 test(`V6 Atrophy reward waits for core deferred death/cause and is delivered once side${side}`,()=>{const {e,f,t,events}=arena(106,side,0,{foreignFixture:true});t.hp=100;const ledger=api.beginDeferredHP(e,t,{owner:f.i,abilityId:'harness_promise',duration:.2});const r=api.damageResult(e,f.i,t,200,{type:'pure',abilityId:'abyssal_underlord_firestorm'});near(r.actual,0);near(t.hp,100);near(api.value(e,f,'bonusDamage'),0);e.packCombat.endStep(e);near(api.value(e,f,'bonusDamage'),0);run(e,.3);near(t.hp,0);near(api.value(e,f,'bonusDamage'),45);assert.equal(events.length,1);assert.equal(events[0].cause.kind,'deferred');assert.equal(events[0].cause.ledgerId,ledger);assert.equal(events[0].cause.source,f.i);e.packCombat.death(e,events[0]);near(api.value(e,f,'bonusDamage'),45);});
}
test('V6 direct committed casts invalidate prior tokens once; passive/refused casts never commit',()=>{for(const [id,slot]of [[94,0],[99,2],[104,2],[106,0],[117,2],[121,0],[124,2]]){const {e,f}=arena(id);const token=e.actionToken(f,['action']);assert(e.cast(0,slot));assert(!e.actionTokenValid(token));assert.equal(e.packCore.actionRevisions[0].action,token.revisions.action+1);}const z=arena(106);const snap=z.e.snapshot();assert.equal(z.e.cast(0,2),false);assert.deepEqual(z.e.snapshot(),snap);});
test('V6 same-frame released short control cancels Stomp and Gate persistently',()=>{for(const id of [94,106]){const {e,f,t}=arena(id);if(id===106)f.x=100;assert(e.cast(0,id===94?0:3));const cid=e.applyControlSource(f,{owner:1,key:'harness_short',type:'stun',duration:.01});assert(cid);e.releaseControlSource(cid,'harness_same_frame_release');const hp=t.hp;run(e,4);near(t.hp,hp);if(id===106)near(f.x,100);}});
test('V6 input cancellation and new actions cannot resurrect old channels after snapshot restore',()=>{for(const cancel of [(e)=>e.cancelInput(0),(e)=>e.setInput(0,{jump:true}),(e,f)=>{f.recovery=0;assert(e.cast(0,0,{aim:f.x}));}]){const {e,f,opts,pair}=arena(106);f.x=100;assert(e.cast(0,3));run(e,.1);cancel(e,f);e.setInput(0,{});const restored=new Engine(hs,pair,opts).restoreSimulation(e.snapshot());run(e,4);run(restored,4);assert.deepEqual(e.snapshot(),restored.snapshot());assert(f.x<800);}});
test('V6 physical counter is never consumed by spells; AoE/self buffs never route',()=>{const z=arena(124,0,5);z.e.addBuff(z.t,'counter',{counter_type:'basic_physical'},5);assert(z.e.cast(0,0));run(z.e,1);near(z.t.maxHp-z.t.hp,325*.65);assert(z.e.buff(z.t,'counter'));assert.equal(z.e.logs.filter(x=>x.type==='spell_reflected').length,0);for(const [id,slot]of [[94,3],[99,3],[104,2],[117,2]]){const {e,f,t}=arena(id,0,5);e.addBuff(t,'counter',{},5);assert(e.cast(0,slot));run(e,1);assert(e.buff(t,'counter'));assert.equal(e.logs.filter(x=>x.type==='spell_reflected').length,0);}});
test('V6 target invulnerable at projectile delivery keeps its counter and receives no components',()=>{for(const [id,slot]of [[99,0],[99,1],[124,0]]){const {e,f,t}=arena(id,0,5);e.addBuff(t,'counter',{},5);assert(e.cast(0,slot));t.invuln=3;run(e,1);assert(e.buff(t,'counter'));near(t.hp,t.maxHp);assert.equal(t.packModules.r91.statuses.length,0);}});
test('V6 real R91 periodic chain stops after Tidehunter dispels exact live status',()=>{const {e,f,t}=arena(104,0,19);assert(e.cast(0,0));run(e,.2);api.damageResult(e,0,t,430,{type:'pure',abilityId:'harness_prethreshold'});const hp=t.hp;run(e,1);near(hp-t.hp,25);assert(!api.status(e,t,'x_chains_0'));});
test('V6 strict restore rejects forged source-control ownership and deleted cancellation token',()=>{const {e,opts,pair}=arena(94);e.cast(0,0);let s=e.snapshot();delete s.packModules.r91.jobs[0].actionToken;assert.throws(()=>new Engine(hs,pair,opts).restoreSimulation(s));run(e,.6);s=e.snapshot();const c=s.packCore.controls.find(c=>c.key.startsWith('r91:'));assert(c);c.owner=1;assert.throws(()=>new Engine(hs,pair,opts).restoreSimulation(s));});
test('V6 deferral receipt stays zero for Luminosity, settlement never invents a second basic proc',()=>{const {e,f,t}=arena(121);f.hp=2000;for(let i=0;i<3;i++)e.basicHit(f,t,{id:++e.seq,damage:10,m:{damage_type:'physical',blockable:false}});api.beginDeferredHP(e,t,{owner:1,abilityId:'harness_promise',duration:.3});e.basicHit(f,t,{id:++e.seq,damage:100,m:{damage_type:'physical',blockable:false}});near(f.hp,2000);assert.equal(f.packModules.r91.data.extra.luminosity,0);run(e,.4);near(f.hp,2000);assert.equal(f.packModules.r91.data.extra.luminosity,0);});
test('V6 periodic status clock forgery rejects atomically; source control and core clocks replay exactly',()=>{const {e,f,t,opts,pair}=arena(104);e.cast(0,0);run(e,.1);const snap=e.snapshot();for(const mutate of [s=>s.elapsed+=.2,s=>s.tick=.2,s=>s.life-=.2]){const bad=structuredClone(snap);mutate(bad.fighters[1].packModules.r91.statuses[0]);assert.throws(()=>new Engine(hs,pair,opts).restoreSimulation(bad));assert.deepEqual(e.snapshot(),snap);}const b=new Engine(hs,pair,opts).restoreSimulation(snap);for(let i=0;i<160;i++){e.step();b.step();assert.deepEqual(e.snapshot(),b.snapshot());}});
