import fs from 'node:fs';import assert from 'node:assert/strict';import {freshPage,viewport,navigate,delay} from './browser-cdp.mjs';
const p=await freshPage(),report={kind:'Actual isolated headless Chrome renderer; CDP emulated mobile/touch, not physical phone or heard audio',checks:[]};
try{await viewport(p,390,844);await navigate(p,'http://127.0.0.1:4175/?qa=1');await p.screenshot('01-portrait-entry');const initial=await p.evaluate('({gate:!document.querySelector("#orientation-gate").hidden,inert:document.querySelector("#app").inert,engine:!!DUEL.engine})');assert(initial.gate&&initial.inert&&!initial.engine);report.checks.push({portraitEntry:initial});
await viewport(p,844,390);await delay(350);await p.click('[data-playmode="pve"]');await p.screenshot('02-landscape-selection');await p.click('[data-action="start"]');await delay(2700);await p.screenshot('03-landscape-battle');
const battle=await p.evaluate('({sides:[...document.querySelectorAll("[data-side]")].map(e=>e.dataset.side),skills:document.querySelectorAll("[data-skill]").length,arrows:document.querySelectorAll("[data-direction]").length,iframe:document.querySelectorAll("iframe").length,canvas:document.querySelector("canvas").getBoundingClientRect().toJSON(),phase:DUEL.engine.phase,audio:DUEL.musicStatus})');assert.deepEqual(battle.sides,['0']);assert.equal(battle.skills,4);assert.equal(battle.arrows,0);assert.equal(battle.iframe,0);assert.equal(battle.canvas.width,844);assert.equal(battle.canvas.height,390);report.checks.push({battle});
const stick=await p.rect('[data-stick="0"]'),attack=await p.rect('.attack-main');const x=stick.x+stick.width/2,y=stick.y+stick.height/2;const point=(id,x,y)=>({id,x,y,radiusX:8,radiusY:8,force:1});const touch=(type,touchPoints)=>p.send('Input.dispatchTouchEvent',{type,touchPoints});const x0=await p.evaluate('DUEL.engine.fighters[0].x');await touch('touchStart',[point(1,x,y)]);await touch('touchMove',[point(1,x+60,y)]);await delay(250);await touch('touchStart',[point(1,x+60,y),point(2,attack.x+attack.width/2,attack.y+attack.height/2)]);await delay(250);const held=await p.evaluate('({x:DUEL.engine.fighters[0].x,input:DUEL.engine.input[0],cap:document.querySelector(".stick-cap").style.transform})');assert(held.x>x0);assert(held.input.right&&held.input.attack);await p.screenshot('04-multitouch-held');await touch('touchEnd',[]);await delay(100);const released=await p.evaluate('({input:DUEL.engine.input[0],cap:document.querySelector(".stick-cap").style.transform})');assert(!Object.values(released.input).some(Boolean));report.checks.push({touch:{x0,held,released}});
await viewport(p,390,844);await delay(300);const before=await p.evaluate('({time:DUEL.engine.time,hp:DUEL.engine.fighters.map(f=>f.hp),paused:DUEL.engine.paused})');await delay(2000);const after=await p.evaluate('({time:DUEL.engine.time,hp:DUEL.engine.fighters.map(f=>f.hp),paused:DUEL.engine.paused})');assert.deepEqual(after,before);assert(after.paused);await p.screenshot('05-portrait-battle-paused');report.checks.push({portraitFreeze:{before,after}});
await viewport(p,844,390);await delay(200);await p.click('[data-action="resume"]');
for(const [w,h]of [[667,375],[740,360],[915,412],[844,390]]){await viewport(p,w,h);await delay(200);const boxes=await p.evaluate('({viewport:[innerWidth,innerHeight],arena:document.querySelector("canvas").getBoundingClientRect().toJSON(),controls:[...document.querySelectorAll(".joystick,.action-cluster,.battle-tools")].map(e=>({class:e.className,...e.getBoundingClientRect().toJSON()}))})');assert.equal(boxes.arena.width,w);assert.equal(boxes.arena.height,h);for(const b of boxes.controls){assert(b.x>=0&&b.y>=0&&b.right<=w&&b.bottom<=h,JSON.stringify(b));}report.checks.push({size:boxes});await p.screenshot('size-'+w+'x'+h);}
report.errors=p.events.filter(e=>e.method==='Runtime.exceptionThrown');assert.equal(report.errors.length,0);report.audioAtEnd=await p.evaluate('DUEL.musicStatus');fs.writeFileSync('qa/browser-evidence/mobile-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify({passed:report.checks.length,audio:report.audioAtEnd}));}
catch(e){report.failure=String(e);report.errors=p.events.filter(e=>e.method==='Runtime.exceptionThrown');fs.writeFileSync('qa/browser-evidence/mobile-report.json',JSON.stringify(report,null,2));await p.screenshot('failure');console.error(e);process.exitCode=1;}finally{p.close();}
