// Controlled real Engine fixtures, not natural browser or official-client acceptance.
import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../src/engine.js';import {runtimeHeroes} from '../src/runtime-heroes.js';import {CohortCombat} from '../src/cohort-combat.js';
const near=(actual,expected,tolerance=1e-5)=>assert(Math.abs(actual-expected)<=tolerance,`${actual} != ${expected}`);
function setup(id,side=0){const picks=side?[1,id]:[id,1],e=new Engine(runtimeHeroes,picks,{seed:334});e.start();const f=e.fighters[side],t=e.fighters[1-side];f.x=side?650:450;t.x=side?450:650;f.dir=side?-1:1;t.hp=t.maxHp=50000;return {e,f,t};}
function seconds(e,amount){const end=e.t+amount;let n=0;while(e.t<end-1e-8&&e.phase==='fight'){e.step();assert(n++<20000,'bounded simulation');}}
const broken=f=>f.pack.statuses.push({key:'viper_strike',owner:1-f.i,life:6,duration:6,elapsed:0,tick:0,values:{},dispel:'none'});
for(const id of [25,31,45,100])for(const side of [0,1])for(let slot=0;slot<4;slot++)test(`core4 ${id} P${side+1} slot${slot+1}: actual cast cost/CD/passive contract`,()=>{
 const {e,f,t}=setup(id,side);t.x=f.x+f.dir*90;const a=e.ability(side,slot),before=f.mp;if(a.mvp.passive){assert.equal(e.cast(side,slot),false);assert.equal(f.mp,before);assert.equal(f.casts,0);return;}assert(e.cast(side,slot));assert.equal(f.mp,before-(a.valveAbilityId===5218?0:a.mvp.mana));if(a.valveAbilityId!==5218)near(f.cd[slot],a.mvp.cooldown_s);seconds(e,.5);assert(f.casts>=1);assert([f.hp,t.hp,f.mp,...f.cd].every(Number.isFinite));
});
for(const id of [25,31,45,100])test(`core4 ${id}: death, silence, mana, serialization and round reset`,()=>{
 const {e,f}=setup(id);const slot=id===45?1:0;f.silence=1;assert(!e.cast(0,slot));f.silence=0;f.mp=0;assert(!e.cast(0,slot));f.mp=1200;f.hp=0;assert(!e.cast(0,slot));f.hp=f.maxHp;assert(e.cast(0,slot));seconds(e,.4);assert.deepEqual(JSON.parse(JSON.stringify(e.snapshot())),e.snapshot());e.resetRound();assert(e.fighters.every(v=>v.pack.statuses.length===0&&v.pack.poison.length===0));assert(e.packState.areas.length===0&&e.packState.links.length===0&&e.packState.storms.length===0);
});
test('Razor plasma has exactly one outward and return contact; range scales each hit and no extra generic hit',()=>{
 const {e,f,t}=setup(25);t.x=f.x+300;const hp=t.hp;assert(e.cast(0,0));seconds(e,2.3);const contacts=e.logs.filter(l=>l.type==='plasma_contact');assert.deepEqual(contacts.map(l=>l.phase),['out','back']);near(hp-t.hp,2*(50+135*300/385));assert.equal(e.packState.rings.length,0);
});
test('Razor plasma outside maximum radius misses both phases',()=>{const {e,f,t}=setup(25);t.x=f.x+450;const hp=t.hp;e.cast(0,0);seconds(e,2.3);assert.equal(t.hp,hp);});
test('Razor static link transfers equal attack damage, breaks at440, retains18s then expires',()=>{
 const {e,f,t}=setup(25);assert(e.cast(0,1));seconds(e,2.3);const link=e.packState.links[0];assert(link.amount>47&&link.amount<49);near(CohortCombat.attack(e,f,t,85,{}),85+link.amount);near(CohortCombat.attack(e,t,f,100,{}),100-link.amount);t.x=f.x+450;seconds(e,.1);assert(!link.draining);const saved=link.amount;seconds(e,17);near(link.amount,saved);seconds(e,1.2);assert.equal(e.packState.links.length,0);
});
test('Razor link out of range spends no mana; death stops draining',()=>{const {e,f,t}=setup(25);t.x=f.x+350;const mp=f.mp;assert(!e.cast(0,1));assert.equal(f.mp,mp);t.x=f.x+100;e.cast(0,1);seconds(e,.4);t.hp=0;e.step();assert(e.packState.links.every(l=>!l.draining));});
test('Razor surge targeted spell always triggers once per2.5s and reflected damage cannot reflect again',()=>{
 const {e,f,t}=setup(25);const hp=t.hp;CohortCombat.targeted(e,t,f,'test_target');near(hp-t.hp,170);CohortCombat.targeted(e,t,f,'test_target');near(hp-t.hp,170);f.pack.surgeCD=0;e.hit(t,f,100,{damage_type:'pure'},{basic:true,reflected:true});near(hp-t.hp,170);broken(f);CohortCombat.targeted(e,t,f,'test_target');near(hp-t.hp,170);
});
test('Razor surge attack proc uses seeded chance boundary; no DOT proc',()=>{for(const random of [.199,.2]){const {e,f,t}=setup(25);e.random=()=>random;const hp=t.hp;e.hit(t,f,10,{damage_type:'pure'},{basic:true});near(hp-t.hp,random<.2?170:0);}const {e,f,t}=setup(25);e.random=()=>0;const hp=t.hp;e.hit(t,f,10,{damage_type:'pure'},{dot:true});assert.equal(t.hp,hp);});
test('Razor storms stack as independent instances and each hit progressively reduces armor',()=>{const {e,f,t}=setup(25);e.cast(0,3);seconds(e,.51);near(50000-t.hp,90);assert.equal(t.pack.statuses.find(s=>s.key.startsWith('storm_armor')).values.armor,-1);f.cd[3]=0;f.recovery=0;e.cast(0,3);assert.equal(e.packState.storms.length,2);seconds(e,.51);assert(50000-t.hp>270);assert.equal(t.pack.statuses.filter(s=>s.key.startsWith('storm_armor')).length,2);});
test('Viper toggle pays20 per real projectile attack; successful impact adds poison and separate Predator damage',()=>{const {e,f,t}=setup(45);t.hp=t.maxHp/2;assert(e.cast(0,0));const mp=f.mp,hp=t.hp;assert(e.attack(0));near(f.mp,mp-20);seconds(e,.5);assert(t.pack.poison.length===1);assert(e.logs.some(l=>l.skill==='viper_predator'&&l.type==='hit'));assert(hp-t.hp>80);f.recovery=0;assert(e.cast(0,0));assert(!f.pack.poisonOn);});
test('Viper poison caps6, replaces oldest and uses independent expiry; basic dispel clears all',()=>{const {e,f,t}=setup(45);for(let n=0;n<8;n++)CohortCombat.afterAttack(e,f,t,{m:{corePoison:true}},true);assert.equal(t.pack.poison.length,6);t.pack.poison[0].life=.1;seconds(e,.15);assert.equal(t.pack.poison.length,5);e.dispel(t,'basic');assert.equal(t.pack.poison.length,0);});
test('Viper poison magic resistance reduction affects spell damage separately from physical damage',()=>{const {e,f,t}=setup(45);for(let n=0;n<3;n++)CohortCombat.afterAttack(e,f,t,{m:{corePoison:true}},true);const hp=t.hp;e.hit(f,t,100,{damage_type:'magical'},{dot:true});near(hp-t.hp,130);const next=t.hp;e.hit(f,t,100,{damage_type:'physical'},{dot:true});near(next-t.hp,100);});
test('Viper toxin projectile arrives before area begins, ramp resets on exit and overlapping areas do not stack',()=>{const run=duplicate=>{const {e,f,t}=setup(45);e.cast(0,1);seconds(e,.21);assert.equal(e.packState.areas.length,0);seconds(e,.3);const area=e.packState.areas[0];assert(area);if(duplicate)e.packState.areas.push({...area,id:999});const hp=t.hp;seconds(e,2);const damage=hp-t.hp;assert(t.pack.toxinExposure>2);t.x=1100;seconds(e,.1);near(t.pack.toxinExposure,0);t.x=area.x;seconds(e,.1);assert(t.pack.toxinExposure<.12);return damage;};near(run(false),run(true));});
test('Viper skin gives25percent magic resistance and reflection is bounded, range filtered and break gated',()=>{const {e,f,t}=setup(45);let hp=f.hp;e.hit(t,f,100,{damage_type:'magical'},{dot:true});near(hp-f.hp,75);assert(t.pack.statuses.some(s=>s.key==='skin'));t.pack.statuses=[];e.hit(t,f,100,{damage_type:'pure'},{reflected:true});assert(!t.pack.statuses.length);broken(f);hp=f.hp;e.hit(t,f,100,{damage_type:'magical'},{basic:true});near(hp-f.hp,100);assert(!t.pack.statuses.length);f.pack.statuses=[];t.x=1155;f.x=45;e.hit(t,f,10,{damage_type:'pure'},{basic:true});assert(!t.pack.statuses.length);});
test('Viper strike uses a projectile, applies undispellable6s break and linearly fading slow; no extra charges',()=>{const {e,f,t}=setup(45);e.cast(0,3);assert(!t.pack.statuses.length);seconds(e,.5);const s=t.pack.statuses.find(s=>s.key==='viper_strike');assert(s);assert(CohortCombat.broken(t));assert.equal(f.charges[3],0);e.dispel(t,'strong');assert(CohortCombat.broken(t));const first=CohortCombat.moveMultiplier(e,t);seconds(e,3);assert(CohortCombat.moveMultiplier(e,t)>first);seconds(e,3.5);assert(!CohortCombat.broken(t));});
test('Viper strike can be jumped in2D and cannot apply through invulnerability',()=>{for(const jump of [true,false]){const {e,f,t}=setup(45);e.cast(0,3);if(jump){t.y=350;t.vy=300;}else t.invuln=1;seconds(e,.6);assert(!CohortCombat.broken(t));}});
test('Abaddon coil self-cost is40percent of320, enemy projectile damage and down+self healing are distinct',()=>{
 const {e,f,t}=setup(100);const hp=f.hp,thp=t.hp;e.cast(0,0);seconds(e,.7);near(hp-f.hp,128);near(thp-t.hp,320);f.cd[0]=0;f.recovery=0;f.hp=1000;e.setInput(0,{down:true});e.cast(0,0);seconds(e,.3);near(f.hp,1192);
});
test('Abaddon coil cannot self-kill; active Borrowed Time converts self cost',()=>{const {e,f}=setup(100);f.hp=20;f.cd[3]=65;e.cast(0,0,{self:true});seconds(e,.3);near(f.hp,321);f.hp=1000;f.cd[0]=0;f.cd[3]=0;f.recovery=0;e.cast(0,3);e.cast(0,0,{self:true});seconds(e,.3);near(f.hp,1448);});
test('Abaddon shield absorbs all three damage types and explodes for full210 on depletion',()=>{for(const damage_type of ['physical','magical','pure']){const {e,f,t}=setup(100);t.x=f.x+100;e.cast(0,1);seconds(e,.31);const hp=f.hp,thp=t.hp;e.hit(t,f,150,{damage_type},{dot:true});near(f.hp,hp);near(f.pack.shield.amount,60);e.hit(t,f,100,{damage_type},{dot:true});near(hp-f.hp,40);assert.equal(f.pack.shield,null);near(thp-t.hp,210);}});
test('Abaddon shield expiration and replacement each burst once, dead owner does not emit new attack',()=>{const {e,f,t}=setup(100);t.x=f.x+100;e.cast(0,1);seconds(e,.4);f.cd[1]=0;f.recovery=0;const hp=t.hp;e.cast(0,1);seconds(e,.4);near(hp-t.hp,210);seconds(e,12);near(hp-t.hp,420);e.cast(0,1);seconds(e,.4);f.hp=0;e.step();assert.equal(f.pack.shield,null);assert.equal(e.phase,'roundEnd');});
test('Abaddon curse is applied by attack, grants40 attack speed versus cursed target and45DPS',()=>{const {e,f,t}=setup(100);t.x=f.x+80;const hp=t.hp;e.basicHit(f,t,{damage:100,m:{damage_type:'physical'},id:1});assert(t.pack.statuses.some(s=>s.key==='curse'));near(CohortCombat.attackInterval(e,f,t,.7),.5);seconds(e,1);assert(hp-t.hp>=145);e.dispel(t,'basic');assert(!t.pack.statuses.some(s=>s.key==='curse'));});
test('Abaddon withering uses level18 33.5percent reduction only below40percent, lasting5s',()=>{const {e,f,t}=setup(100);t.hp=t.maxHp*.3;e.hit(f,t,1,{damage_type:'pure'},{dot:true});const before=t.hp;e.heal(t,100);near(t.hp-before,66.5);t.hp=t.maxHp*.5;const high=t.hp;e.heal(t,100);near(t.hp-high,100);seconds(e,5.1);t.hp=100;const low=t.hp;e.heal(t,100);near(t.hp-low,100);});
test('Borrowed Time manual control exception, silence auto exception and break auto suppression',()=>{
 for(const control of ['stun','hex','fear','taunt']){const {e,f}=setup(100);f[control]=1;assert(e.cast(0,3));assert.equal(f[control],control==='taunt'?1:0,'Axe taunt remains explicitly undispellable');}
 const {e,f,t}=setup(100);f.silence=1;assert(!e.cast(0,3));f.hp=450;e.hit(t,f,100,{damage_type:'pure'},{dot:true});assert(f.pack.borrowed>0);assert.equal(f.hp,350);
 const other=setup(100);broken(other.f);other.f.hp=450;other.e.hit(other.t,other.f,100,{damage_type:'pure'},{dot:true});assert.equal(other.f.pack.borrowed,0);other.f.silence=0;assert(other.e.cast(0,3));
});
test('Borrowed Time does not resurrect a lethal hit from above threshold; shield lets converted damage through',()=>{const a=setup(100);a.f.hp=450;a.e.hit(a.t,a.f,500,{damage_type:'pure'},{dot:true});assert.equal(a.f.hp,0);assert.equal(a.f.pack.borrowed,0);const {e,f,t}=setup(100);f.hp=1000;e.cast(0,1);seconds(e,.4);e.cast(0,3);const before=f.hp;e.hit(t,f,200,{damage_type:'pure'},{dot:true});near(f.hp-before,200);near(f.pack.shield.amount,210);seconds(e,6.1);assert.equal(f.pack.borrowed,0);});
test('Slardar sprint gives34percent speed,100percent slow resistance2.5s then fades; preserves a live channel on cast',()=>{const {e,f}=setup(31);f.slowPct=.5;f.slow=10;f.channel={slot:1,m:{},life:1};assert(e.cast(0,0));assert(f.channel);f.channel=null;near(CohortCombat.moveMultiplier(e,f),2.68);seconds(e,5);assert(CohortCombat.moveMultiplier(e,f)<2.68);seconds(e,5.1);assert.equal(f.pack.sprint,null);});
test('Slardar crush creates water, physical300 damage, stun then delayed slow and automatic level18 water bonuses',()=>{const {e,f,t}=setup(31);t.x=f.x+100;f.hp-=100;const hp=t.hp;e.cast(0,1);seconds(e,.27);near(hp-t.hp,300);assert(t.stun>0);assert(e.packState.areas.some(a=>a.type==='water'));seconds(e,.55);assert(f.pack.water);near(CohortCombat.attack(e,f,t,100,{}),122.2);assert(f.hp>f.maxHp-100);const before=f.hp;e.hit(t,f,100,{damage_type:'physical'},{dot:true});near(before-f.hp,100*(1-.324/1.324));seconds(e,.4);assert(CohortCombat.moveMultiplier(e,t)<1);f.x=1100;seconds(e,.1);assert(!f.pack.water);near(CohortCombat.attack(e,f,t,100,{}),100);});
test('Slardar every fourth landed attack bashes once and break stops accumulation',()=>{const {e,f,t}=setup(31);t.x=f.x+80;const hp=t.hp;for(let n=0;n<3;n++)e.basicHit(f,t,{damage:10,m:{damage_type:'physical'},id:n});near(hp-t.hp,30);e.basicHit(f,t,{damage:10,m:{damage_type:'physical'},id:4});near(hp-t.hp,240);assert(t.stun>0);assert.equal(f.pack.bashCount,0);broken(f);for(let n=0;n<4;n++)e.basicHit(f,t,{damage:10,m:{damage_type:'physical'},id:n});assert.equal(f.pack.bashCount,0);});
test('Slardar Haze armor and reveal are separate; moving target leaves water trails and basic dispel removes mark',()=>{const {e,f,t}=setup(31);e.cast(0,3);seconds(e,.32);assert(t.pack.revealed);const before=t.hp;e.hit(f,t,100,{damage_type:'physical'},{dot:true});near(before-t.hp,100*(1+1.2/2.2));t.x+=100;seconds(e,.2);assert(e.packState.areas.some(a=>a.type==='water'&&Math.abs(a.x-t.x)<1));e.dispel(t,'basic');seconds(e,.05);assert(!t.pack.revealed);assert(!t.pack.statuses.some(s=>s.key==='haze'));});
test('break suppresses old Juggernaut Blade Dance and Anti-Mage resistance through shared pipeline',()=>{const e=new Engine(runtimeHeroes,[45,0]);e.start();e.random=()=>0;const jug=e.fighters[1];assert.equal(e.bladeDance(jug,100),200);broken(jug);assert.equal(e.bladeDance(jug,100),100);const b=new Engine(runtimeHeroes,[45,5]);b.start();const [v,am]=b.fighters;let hp=am.hp;b.hit(v,am,100,{damage_type:'magical'},{dot:true});near(hp-am.hp,65);broken(am);hp=am.hp;b.hit(v,am,100,{damage_type:'magical'},{dot:true});near(hp-am.hp,100);});

test('shield bursts before a lethal remainder and only once',()=>{const {e,f,t}=setup(100);f.cd[3]=65;e.cast(0,1);seconds(e,.4);f.hp=250;const hp=t.hp;e.hit(t,f,1000,{damage_type:'pure'},{dot:true});assert.equal(f.hp,0);near(hp-t.hp,210);e.step();near(hp-t.hp,210);assert.equal(f.pack.shield,null);});
test('moving target crossing an expanding plasma ring is hit only once on that phase',()=>{const {e,f,t}=setup(25);t.x=f.x+350;e.cast(0,0);seconds(e,.5);assert.equal(e.logs.filter(l=>l.type==='plasma_contact').length,0);t.x=f.x+100;seconds(e,.05);assert.equal(e.logs.filter(l=>l.type==='plasma_contact'&&l.phase==='out').length,1);seconds(e,.4);assert.equal(e.logs.filter(l=>l.type==='plasma_contact'&&l.phase==='out').length,1);});
