import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../src/engine.js';import {runtimeHeroes} from '../src/runtime-heroes.js';import {CohortCombat} from '../src/cohort-combat.js';
const near=(a,b)=>assert(Math.abs(a-b)<1e-6,`${a} != ${b}`);
function ticks(e,n){for(let i=0;i<n;i++)e.step();}
function setup(id,side){const e=new Engine(runtimeHeroes,side?[0,id]:[id,0],{seed:810}).start(),a=e.fighters[side],t=e.fighters[1-side];a.x=600;t.x=side?400:800;return {e,a,t};}
for(const side of [0,1])test(`Razor P${side+1} link allows every moving attack recovery frame independent of animation`,()=>{
 const runs=[];for(const attack of [false,true]){const {e,a,t}=setup(25,side);assert(e.cast(side,1));ticks(e,40);t.invuln=1;assert(e.packState.links.some(l=>l.draining));const before=a.x,logs=e.logs.length;e.setInput(side,{left:!side,right:!!side,attack});ticks(e,36);assert(!e.logs.slice(logs).some(l=>l.type==='hit'||l.type==='block'));assert(e.packState.links.some(l=>l.draining));runs.push(Math.abs(a.x-before));}near(runs[0],156);near(runs[1],runs[0]);
});
for(const side of [0,1])test(`Razor P${side+1} movement exception requires live link and attack recovery, never cast or hurt recovery`,()=>{
 const {e,a,t}=setup(25,side);e.cast(side,1);ticks(e,40);assert(e.attack(side));a.animation='walk';assert(CohortCombat.movingAttack(e,a));e.packState.links[0].draining=false;assert(!CohortCombat.movingAttack(e,a));e.packState.links[0].draining=true;
 e.hit(t,a,1,{damage_type:'pure',hitstun_s:.16,blockable:false},{skill:'test_hit'});assert(!CohortCombat.movingAttack(e,a));a.recovery=0;a.attackCd=0;e.attack(side);e.control(a,'stun',.1);assert(!CohortCombat.movingAttack(e,a));ticks(e,30);a.recovery=0;e.cast(side,0);assert(!CohortCombat.movingAttack(e,a));
});
for(const side of [0,1])test(`Crush is retained but move and attack slow are suppressed during real Blade Fury P${2-side}`,()=>{
 const {e,a,t}=setup(31,side);t.x=a.x+(side?-100:100);assert(e.cast(side,1));ticks(e,80);const status=t.pack.statuses.find(s=>s.key==='crush');assert(status);near(CohortCombat.moveMultiplier(e,t),.65);assert(CohortCombat.attackInterval(e,t,a,.7)>.7);assert(e.cast(t.i,0));ticks(e,30);assert.equal(e.property(t,'debuffImmune'),1);assert(t.pack.statuses.includes(status));assert.equal(status.pierces,false);near(CohortCombat.moveMultiplier(e,t),1);near(CohortCombat.attackInterval(e,t,a,.7),.7);
});
for(const side of [0,1])for(const pierces of [false,true])test(`Generic persistent debuff P${2-side}, pierces=${pierces}: immunity suppression and timed recovery`,()=>{
 const {e,a,t}=setup(31,side);t.pack.statuses.push({key:'future_slow',owner:a.i,life:8,duration:8,elapsed:0,tick:0,values:{moveSlow:.4,attackSlow:30},dispel:'strong',pierces});near(CohortCombat.moveMultiplier(e,t),.6);const slowed=.7*100/70;near(CohortCombat.attackInterval(e,t,a,.7),slowed);e.addBuff(t,'temporary_immunity',{debuffImmune:true},.2);near(CohortCombat.moveMultiplier(e,t),pierces?.6:1);near(CohortCombat.attackInterval(e,t,a,.7),pierces?slowed:.7);ticks(e,15);assert.equal(e.property(t,'debuffImmune'),0);assert(t.pack.statuses.some(s=>s.key==='future_slow'));near(CohortCombat.moveMultiplier(e,t),.6);near(CohortCombat.attackInterval(e,t,a,.7),slowed);
});
for(const side of [0,1])test(`Viper Strike retains piercing move and attack slow through immunity P${2-side}`,()=>{const {e,a,t}=setup(45,side);assert(e.cast(side,3));ticks(e,35);const s=t.pack.statuses.find(s=>s.key==='viper_strike');assert(s);assert.equal(s.pierces,true);e.addBuff(t,'temporary_immunity',{debuffImmune:true},1);assert(CohortCombat.moveMultiplier(e,t)<1);assert(CohortCombat.attackInterval(e,t,a,.7)>.7);});
for(const side of [0,1])for(const layers of [1,6])test(`Viper arena magic multiplier matches Anti-Mage35percent resistance P${2-side}, ${layers} real poison layers`,()=>{const e=new Engine(runtimeHeroes,side?[5,45]:[45,5],{seed:271}).start(),a=e.fighters[side],t=e.fighters[1-side];a.x=side?600:500;t.x=side?500:600;assert(e.cast(side,0));for(let i=0;i<layers;i++){a.attackCd=a.recovery=0;assert(e.attack(side));for(let n=0;t.pack.poison.length<i+1&&n<100;n++)e.step();assert.equal(t.pack.poison.length,i+1);}const hp=t.hp;e.hit(a,t,100,{damage_type:'magical',blockable:false},{dot:true});near(hp-t.hp,65*(1+.1*layers));});
