import fs from 'node:fs';import vm from 'node:vm';import {NET_VERSION} from '../src/net-version.js';
import test from 'node:test';import assert from 'node:assert/strict';import {MatchAPI} from '../src/match-api.js';
test('isolated room-selection preview4196 routes only to candidate18086 without changing hosted routing',()=>{const descriptor=Object.getOwnPropertyDescriptor(globalThis,'location');try{Object.defineProperty(globalThis,'location',{value:{hostname:'127.0.0.1',port:'4196'},configurable:true});assert.equal(new MatchAPI().base,'http://127.0.0.1:18086/api/v1');Object.defineProperty(globalThis,'location',{value:{hostname:'dotapk.lol',port:'4196'},configurable:true});assert.equal(new MatchAPI().base,'https://api.dotapk.lol/api/v1');}finally{if(descriptor)Object.defineProperty(globalThis,'location',descriptor);else delete globalThis.location;}});
test('hosted frontend uses HTTPS Go API and localhost keeps QA endpoint',()=>{const descriptor=Object.getOwnPropertyDescriptor(globalThis,'location');try{for(const hostname of ['dotapk.lol','frontend-example.example.workers.dev']){Object.defineProperty(globalThis,'location',{value:{hostname},configurable:true});assert.equal(new MatchAPI().base,'https://api.dotapk.lol/api/v1');}for(const hostname of ['127.0.0.1','localhost']){Object.defineProperty(globalThis,'location',{value:{hostname},configurable:true});assert.equal(new MatchAPI().base,'http://127.0.0.1:18082/api/v1');}assert.equal(new MatchAPI({base:'/custom'}).base,'/custom');}finally{if(descriptor)Object.defineProperty(globalThis,'location',descriptor);else delete globalThis.location;}});

test('published HTML boots one complete fingerprinted package and entry metadata bypasses stale caches',()=>{
 const root=new URL('../dist/client/',import.meta.url),manifest=JSON.parse(fs.readFileSync(new URL('build-manifest.json',root),'utf8')),html=fs.readFileSync(new URL('index.html',root),'utf8');
 assert.equal(manifest.gameVersion,NET_VERSION);assert.match(manifest.entry.script,/^src\/app\.duel-[a-f0-9]{20}\.js$/);assert.match(manifest.entry.style,/^src\/style\.duel-[a-f0-9]{20}\.css$/);
 assert(html.includes('src="'+manifest.entry.script+'"'));assert(html.includes('data-source="'+manifest.entry.style+'"'));assert.match(html,/<script id="startup-app" defer src=/);assert(!html.includes('rel="stylesheet"'));assert(!html.includes('src="src/app.js"'));
 const bundle=fs.readFileSync(new URL(manifest.entry.script,root),'utf8');assert(bundle.includes(NET_VERSION));assert(!bundle.includes('I18N_QA'));new vm.Script(bundle);assert(fs.statSync(new URL(manifest.entry.style,root)).size>1000);
 const headers=fs.readFileSync(new URL('_headers',root),'utf8');for(const path of ['/','/index.html','/build-manifest.json'])assert(headers.includes(path+'\n  Cache-Control: no-store'));
});
