import {idbFixture} from './idb-fixture.mjs';
// Browser-independent app integration. This mock validates wiring and protocol,
// not rendered layout, WebAudio, real touch, real gamepads or browser permissions.
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const root=new URL('../',import.meta.url);const read=f=>fs.readFileSync(new URL(f,root),'utf8');
const source=['audio-score.js','audio-map.js','audio-synth.js','audio.js','official-music.js','mobile.js','music.js','net-quality.js','net-version.js','match-api.js','local-rooms.js','p2p.js'].map(f=>fs.readFileSync(new URL('../src/'+f,import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/export (const|class|function) /g,'$1 ')).join('\n')+'\n'+read('src/data.js').replaceAll('export const ','const ')+'\n'+read('src/engine.js').replaceAll('export const ','const ').replaceAll('export class ','class ')+'\n'+read('src/app.js').replace(/^import .*;\n/gm,'');
class Node{constructor(tag='div',attrs={}){this.tagName=tag.toUpperCase();this.attrs=attrs;this.dataset=Object.fromEntries(Object.entries(attrs).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase()),v]));this.style={};this.children=[];this._text='';this.value='';this.className=attrs.class||'';this.classList={add:()=>{},remove:()=>{},toggle:()=>{}};this.listeners={};}
 set innerHTML(html){this.children=[];parse(html,this);this._html=html;}get innerHTML(){return this._html||'';}set textContent(v){this._text=String(v);}get textContent(){return this._text+this.children.map(x=>x.textContent).join('');}appendChild(n){n.parent=this;this.children.push(n);return n;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);}querySelectorAll(sel){const out=[];const matches=n=>{if(sel.startsWith('#'))return n.attrs.id===sel.slice(1);if(sel.startsWith('.'))return (n.className||'').split(' ').includes(sel.slice(1));if(sel.startsWith('[')){const m=sel.match(/^\[([^\]^=]+)(\^=|=)?["']?([^"'\]]*)["']?\]$/);return m&&m[1]in n.attrs&&(!m[2]||(m[2]==='='?n.attrs[m[1]]===m[3]:n.attrs[m[1]].startsWith(m[3])));}return n.tagName===sel.toUpperCase();};const visit=n=>{for(const c of n.children){if(matches(c))out.push(c);visit(c);}};visit(this);return out;}querySelector(s){return this.querySelectorAll(s)[0]||null;}addEventListener(k,fn){(this.listeners[k]??=[]).push(fn);}setPointerCapture(){}focus(){}click(){this.onclick?.({stopPropagation(){}});}getContext(){return new Proxy({createLinearGradient:()=>({addColorStop(){}})},{get(t,k){return t[k]||(()=>{});},set(t,k,v){t[k]=v;return true;}});}}
function parse(html,root){let stack=[root];const re=/<\/([\w-]+)>|<([\w-]+)([^>]*?)>|([^<]+)/g;let m;while((m=re.exec(html))){if(m[1]){if(stack.length>1)stack.pop();}else if(m[2]){let attrs={},a;const ar=/([^\s=]+)(?:="([^"]*)"|='([^']*)'|=([^\s>]+))?/g;while((a=ar.exec(m[3])))attrs[a[1]]=a[2]??a[3]??a[4]??'';const n=new Node(m[2],attrs);stack.at(-1).appendChild(n);if(!['img','br','input','meta','link','hr'].includes(m[2]))stack.push(n);}else stack.at(-1)._text+=m[4];}}
const indexedDB=idbFixture(),channels=new Map();const clearChannels=channels.clear.bind(channels);channels.clear=()=>{clearChannels();indexedDB.clear();};class BC{constructor(name){this.name=name;(channels.get(name)||channels.set(name,new Set()).get(name)).add(this);}postMessage(data){for(const c of channels.get(this.name)||[])if(c!==this)queueMicrotask(()=>c.onmessage?.({data:structuredClone(data)}));}close(){channels.get(this.name)?.delete(this);}}
function app(qa=false,fetcher=null){const doc=new Node('document');doc.appendChild(new Node('main',{id:'app'}));doc.appendChild(new Node('div',{id:'toast'}));doc.appendChild(new Node('section',{id:'orientation-gate'}));doc.createElement=t=>new Node(t);doc.addEventListener=Node.prototype.addEventListener.bind(doc);doc.documentElement=new Node('html');doc.body=doc;const events={},frames=[];let now=0;const ctx={indexedDB,crypto:globalThis.crypto,document:doc,console,Audio:class{constructor(){this.paused=true;}addEventListener(){}play(){this.paused=false;return Promise.resolve();}pause(){this.paused=true;}load(){}},structuredClone,Map,Math,Date,JSON,Promise,Image:class{constructor(){this.complete=true;this.naturalWidth=1024;}},fetch:fetcher|| (async()=>({ok:true,json:async()=>JSON.parse(read('assets/atlas.json'))})),navigator:{getGamepads:()=>[]},location:{protocol:'https:',search:qa?'?qa=1':''},localStorage:{getItem:()=>null,setItem(){}},performance:{now:()=>now},requestAnimationFrame:cb=>frames.push(cb),setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},BroadcastChannel:BC,addEventListener:(k,fn)=>(events[k]??=[]).push(fn)};ctx.window=ctx;vm.createContext(ctx);vm.runInContext(source,ctx,{timeout:2000});return {ctx,doc,events,get duel(){return ctx.DUEL;},tick(n=1){for(let i=0;i<n;i++){now+=1000/60;const cbs=frames.splice(0);cbs.forEach(f=>f(now));}},key(code,down=true){for(const f of events[down?'keydown':'keyup']||[])f({code,preventDefault(){},target:{}});},button(action){const n=doc.querySelector(`[data-action="${action}"]`);assert(n,action+' button exists');n.click();},mode(mode){doc.querySelector(`[data-mode="${mode}"]`).click();}};}
const flush=async()=>{for(let i=0;i<100;i++)await Promise.resolve();};
test('selection contains20real hero choices, two public modes, PVP connection options and all portraits',()=>{const a=app();assert.equal(a.doc.querySelectorAll('[data-hero]').length,20);assert.equal(a.doc.querySelectorAll('[data-playmode]').length,2);assert.equal(a.doc.querySelectorAll('[data-mode]').length,3);assert.equal(a.doc.querySelector('[data-mode="training"]'),null);assert(a.doc.textContent.includes('一人一英雄'));});
test('app start renders all8skills and both keyboard sets independently move fighters',async()=>{let a=app();a.button('start');await flush();a.tick(150);assert.equal(a.doc.querySelectorAll('[data-skill]').length,8);const e=a.duel.engine;let x=e.fighters.map(f=>f.x);a.key('KeyD');a.key('ArrowLeft');a.tick(20);a.key('KeyD',false);a.key('ArrowLeft',false);assert(e.fighters[0].x>x[0]);assert(e.fighters[1].x<x[1]);assert.equal(a.doc.querySelector('#clock').textContent,'99');});
test('pause,help,close,rematch and quit correctly wire actual controls',()=>{const a=app();a.button('start');a.tick(150);a.button('pause');assert(a.duel.engine.paused);a.button('resume');assert(!a.duel.engine.paused);a.key('Escape');assert(a.duel.engine.paused);a.button('quit');assert.equal(a.duel.state.screen,'select');a.duel.start({mode:'training'});a.tick(150);assert.equal(a.duel.engine.mode,'training');a.button('pause');a.button('reset');assert.equal(a.duel.engine.phase,'fight');assert(!a.duel.engine.paused);});
test('window blur releases held inputs and pauses local game',()=>{let a=app();a.button('start');a.tick(150);a.key('KeyD');a.tick(10);for(const f of a.events.blur)f();assert(a.duel.engine.paused);a.button('resume');const x=a.duel.engine.fighters[0].x;a.tick(20);assert.equal(a.duel.engine.fighters[0].x,x);});
test('skill archive buttons resolve all20×4records without runtime errors',()=>{const a=app();for(let h=0;h<20;h++){a.duel.state.picks[0]=h;a.duel.state.picking=0;a.duel.selection();a.button('codex');assert(a.doc.textContent.includes(a.duel.heroes[h].name));for(let s=0;s<4;s++){a.doc.querySelector(`[data-slot="${s}"]`).click();assert(a.doc.textContent.includes(a.duel.heroes[h].abilities[s].name));}a.button('close');}});
test('real app room protocol joins two VM instances,transfers bothinputs,pause,rematch,leave',async()=>{channels.clear();const host=app(),guest=app();host.mode('room');guest.mode('room');host.button('start');host.button('roomCreate');await flush();const code=host.duel.room.code;guest.button('start');guest.doc.querySelector('#roomInput').value=code;guest.button('roomJoin');await flush();assert(host.duel.room.connected);assert(guest.duel.room.connected);host.button('roomStart');await flush();assert.equal(host.duel.state.screen,'battle');assert.equal(guest.duel.state.screen,'battle');host.tick(150);await flush();guest.tick(1);await flush();assert(guest.duel.snapshot);let old=host.duel.engine.fighters[1].x;guest.key('KeyA');guest.tick(3);await flush();host.tick(20);await flush();assert(host.duel.engine.fighters[1].x<old,'guest P1keys control authoritativeP2');guest.key('KeyA',false);guest.tick(3);await flush();guest.button('pause');await flush();assert(host.duel.engine.paused);guest.button('resume');await flush();assert(!host.duel.engine.paused);host.button('pause');host.button('quit');await flush();assert.equal(guest.duel.room.connected,false);assert.equal(host.duel.state.screen,'select');});
test('third room client is rejected without replacing theconnected opponent',async()=>{channels.clear();const a=app(),b=app(),c=app();for(const x of[a,b,c]){x.mode('room');x.button('start');}a.button('roomCreate');await flush();const code=a.duel.room.code;for(const x of[b,c]){x.doc.querySelector('#roomInput').value=code;x.button('roomJoin');await flush();}assert(a.duel.room.connected);assert(b.duel.room.connected);assert.equal(c.duel.room,null);});

test('sub-frame keyboard and pointer taps survive until a simulation step',()=>{const a=app();a.button('start');a.tick(150);a.key('KeyW');a.key('KeyW',false);a.tick(2);assert(a.duel.engine.fighters[0].y>0,'brief keyboard jump delivered');a.tick(100);const b=a.doc.querySelector('[data-input="attack"]');for(const fn of b.listeners.pointerdown)fn({type:'pointerdown',pointerId:1,preventDefault(){}});for(const fn of b.listeners.pointerup)fn({type:'pointerup',pointerId:1});a.tick(2);assert(a.duel.engine.fighters[0].attackCd>0,'brief pointer attack delivered');});
test('blur cancels queued taps before resume',()=>{const a=app();a.button('start');a.tick(150);a.key('KeyW');a.key('KeyW',false);for(const fn of a.events.blur)fn();a.button('resume');a.tick(1);assert.equal(a.duel.engine.fighters[0].y,0);});
test('guest quick tap survives both network and host-frame sampling and labels show local keys',async()=>{channels.clear();const h=app(),g=app();for(const a of[h,g]){a.mode('room');a.button('start');}h.button('roomCreate');await flush();g.doc.querySelector('#roomInput').value=h.duel.room.code;g.button('roomJoin');await flush();h.button('roomStart');await flush();h.tick(150);await flush();g.tick(3);await flush();g.key('KeyW');g.key('KeyW',false);g.tick(3);await flush();g.tick(3);await flush();h.tick(2);assert(h.duel.engine.fighters[1].y>0,'release packet must not erase unconsumed press');const own=g.doc.querySelector('[data-side="1"]');assert.equal(g.doc.querySelectorAll('[data-side]').length,1);assert(own.querySelector('[data-input="attack"]'));assert(own.querySelector('[data-stick="1"]'));assert(own.textContent.includes('Q'));assert(!own.textContent.includes('U'));});

test('opt-in real-browser metrics starts on an empty sample without stopping animation',()=>{const a=app(true);a.button('start');a.tick(180);assert(a.duel.engine.frame>0);assert(a.doc.textContent.includes('samples'));});
test('portrait resize cancels queued input and pauses battle',()=>{const a=app();a.button('start');a.tick(150);a.key('KeyW');a.ctx.innerWidth=390;a.ctx.innerHeight=844;for(const fn of a.events.resize)fn();assert(a.duel.engine.paused);assert.equal(a.doc.querySelector('[data-action="resume"]'),null);a.tick(120);assert(a.duel.engine.paused);a.ctx.innerWidth=844;a.ctx.innerHeight=390;for(const fn of a.events.resize)fn();a.button('resume');a.tick(2);assert.equal(a.duel.engine.fighters[0].y,0);});

test('queued tap survives hitstop and cancels on pointercancel',()=>{const a=app();a.button('start');a.tick(150);a.duel.engine.hitstop=.05;a.key('KeyW');a.key('KeyW',false);a.tick(10);assert(a.duel.engine.fighters[0].y>0);a.tick(100);const b=a.doc.querySelector('[data-input="attack"]');for(const fn of b.listeners.pointerdown)fn({type:'pointerdown',pointerId:8,preventDefault(){}});for(const fn of b.listeners.pointercancel)fn({type:'pointercancel',pointerId:8});a.tick(2);assert.equal(a.duel.engine.fighters[0].attackCd,0);});

test('only PVP and PVE are public modes; human and connection selections launch the matching game',()=>{const a=app();a.doc.querySelector('[data-playmode="pve"]').click();assert.equal(a.duel.state.mode,'cpu');assert.equal(a.doc.querySelectorAll('[data-playmode]').length,2);assert.equal(a.doc.querySelectorAll('[data-mode]').length,0);a.button('start');assert.equal(a.duel.engine.mode,'cpu');a.button('pause');a.button('quit');a.doc.querySelector('[data-playmode="pvp"]').click();assert.equal(a.duel.state.mode,'local');a.button('start');assert.equal(a.duel.engine.mode,'local');});

test('portrait on first entry never creates a local or CPU match, including direct app start',()=>{const a=app();a.ctx.innerWidth=390;a.ctx.innerHeight=844;for(const fn of a.events.resize)fn();a.doc.querySelector('[data-playmode="pve"]').click();a.button('start');assert.equal(a.duel.engine,null);assert.equal(a.duel.start({mode:'cpu'}),null);a.tick(600);assert.equal(a.duel.engine,null);});
test('guest joins with their selected hero, not the default P2 card',async()=>{channels.clear();const h=app(),g=app();for(const a of[h,g]){a.mode('room');}g.doc.querySelector('[data-hero="8"]').click();assert.equal(g.duel.state.myHero,8);h.button('start');h.button('roomCreate');await flush();g.button('start');g.doc.querySelector('#roomInput').value=h.duel.room.code;g.button('roomJoin');await flush();assert.equal(h.duel.state.picks[1],8);assert.equal(g.duel.state.picks[1],8);});
test('end-of-match result stays reachable after Escape with rematch and save retry intact',()=>{const a=app();a.button('start');const e=a.duel.engine;for(let round=0;round<2;round++){e.start();e.fighters[1].hp=0;e.step();e.phaseTime=0;e.step();}a.tick(10);assert.equal(e.phase,'matchEnd');assert(a.doc.querySelector('[data-action="rematch"]'));a.key('Escape');a.tick(10);assert(a.doc.querySelector('[data-action="rematch"]'));assert(a.doc.querySelector('[data-action="retryRecord"]'));a.button('rematch');assert.equal(a.duel.engine.round,1);assert.equal(a.duel.engine.score[0],0);assert.equal(a.doc.querySelectorAll('[data-side]').length,2);});
test('PVE has only local radial actions and passive skill input never enters keyboard state',()=>{const a=app();a.doc.querySelector('[data-playmode="pve"]').click();a.button('start');a.tick(150);assert.equal(a.doc.querySelectorAll('[data-side]').length,1);assert.equal(a.doc.querySelectorAll('[data-skill]').length,4);assert(a.doc.querySelector('.attack-main'));const e=a.duel.engine,slot=a.duel.heroes[0].abilities.findIndex(x=>x.mvp.passive);a.key(['KeyQ','KeyE','KeyR','KeyT'][slot]);a.tick(1);assert(!e.input[0]['s'+slot]);});
test('result actions remain outside details scrolling and failed-save retry disappears after a successful retry',async()=>{
 let fail=true,submits=0;const match={id:'d'.repeat(64),status:'in_progress',trust:'client_reported'};
 const a=app(false,async url=>{if(String(url).includes('atlas.json'))return {ok:true,json:async()=>JSON.parse(read('assets/atlas.json'))};if(String(url).endsWith('/sessions'))return {ok:true,json:async()=>({playerId:'a'.repeat(64),token:'b'.repeat(64)})};if(String(url).endsWith('/results')){submits++;return {ok:!fail,status:fail?503:200,json:async()=>fail?{error:'offline test'}:{...match,status:'recorded'}};}return {ok:true,json:async()=>match};});
 a.ctx.innerWidth=667;a.ctx.innerHeight=250;for(const f of a.events.resize)f();a.duel.start({mode:'cpu'});await flush();const e=a.duel.engine;for(let round=0;round<2;round++){e.start();e.fighters[1].hp=0;e.step();e.phaseTime=0;e.step();}a.tick(10);await flush();
 const panel=a.doc.querySelector('.result-panel'),details=panel.querySelector('.result-details'),footer=panel.querySelector('.result-footer');assert.equal(details.querySelector('[data-action="rematch"]'),null);assert.equal(details.querySelector('[data-action="quit"]'),null);assert(footer.querySelector('[data-action="rematch"]'));assert(footer.querySelector('[data-action="quit"]'));assert.equal(footer.parent,panel);
 const retry=footer.querySelector('[data-action="retryRecord"]');assert.equal(retry.hidden,false);assert.equal(retry.disabled,false);assert.equal(a.duel.record.status,'error');fail=false;a.button('retryRecord');await flush();assert.equal(a.duel.record.status,'recorded');assert.equal(submits,2);assert.equal(retry.hidden,true);assert.equal(retry.disabled,true);assert(a.doc.querySelector('#record-summary').textContent.includes('已保存'));
 a.button('quit');assert.equal(a.duel.state.screen,'select');
});
test('unsupported fullscreen opens actionable install guidance instead of promising hidden Safari tabs',async()=>{const a=app();a.button('fullscreen');await flush();assert(a.doc.textContent.includes('Safari 普通标签页不能由游戏强制隐藏'));assert(a.doc.textContent.includes('添加到主屏幕'));assert(a.doc.querySelector('.install-panel'));a.button('close');assert.equal(a.duel.state.screen,'select');});
