import test from 'node:test';import assert from 'node:assert/strict';
import {Engine} from '../src/engine.js';import {heroes} from '../src/data.js';import {World} from './integrity-harness.mjs';
const tick=(e,n=1)=>{for(let i=0;i<n;i++)e.step();};
const setup=()=>{const e=new Engine(heroes,[0,3],{mode:'training'});e.start();return e;};
const key=code=>({code,target:{},preventDefault(){}});
const pad=(x,y,pressed=[])=>({index:0,axes:[x,y],buttons:Array.from({length:16},(_,n)=>({pressed:pressed.includes(n)}))});

test('all eight physical directions plus neutral have distinct authoritative states',()=>{for(const [n,input]of [[1,{down:true,left:true}],[2,{down:true}],[3,{down:true,right:true}],[4,{left:true}],[5,{}],[6,{right:true}],[7,{jump:true,left:true}],[8,{jump:true}],[9,{jump:true,right:true}]]){const e=setup();e.setInput(0,input);tick(e);assert.equal(e.fighters[0].direction,n);assert.equal(e.fighters[0].crouching,n<4);}});
test('forward, backward and vertical jumps retain launch velocity after key release without diagonal speed gain',()=>{for(const swapped of [false,true])for(const dx of [-1,0,1]){const e=setup(),f=e.fighters[0];f.x=swapped?800:400;e.fighters[1].x=swapped?200:1000;const dir=swapped?-1:1;e.setInput(0,{jump:true,left:dx<0,right:dx>0});tick(e);assert.equal(f.jumpKind,dx===0?'neutral':dx*dir>0?'forward':'back');assert.equal(f.airVx,dx*heroes[0].move_speed);e.setInput(0,{});const start=f.x;tick(e,12);assert(Math.abs(f.x-start-dx*heroes[0].move_speed*.2)<.01);assert(f.y>0);}});
test('holding jump never jumps again on landing; a fresh press does',()=>{const e=setup(),f=e.fighters[0];e.setInput(0,{jump:true});tick(e,70);assert.equal(f.y,0);assert.equal(f.vy,0);tick(e,10);assert.equal(f.y,0);e.setInput(0,{});tick(e);e.setInput(0,{jump:true});tick(e,2);assert(f.y>0);});
test('only back-down crouch guards; down and forward-down crouch without defense',()=>{for(const swapped of [false,true])for(const dx of [-1,0,1]){const e=setup(),f=e.fighters[0];f.x=swapped?800:400;e.fighters[1].x=swapped?200:1000;const x=f.x,back=swapped?1:-1;e.setInput(0,{down:true,left:dx<0,right:dx>0});tick(e,8);assert.equal(f.x,x);assert.equal(f.crouching,true);assert.equal(!!f.guard,dx===back);const hp=f.hp;e.hit(e.fighters[1],f,100,{blockable:true},{basic:true});assert.equal(hp-f.hp,dx===back?20:100);}const e=setup();e.setInput(0,{guard:true});tick(e);assert.equal(e.fighters[0].guard,false,'legacy guard command cannot bypass direction');});
test('opposing directional keys cancel, and recovery/root prevent jump exploits',()=>{const e=setup(),f=e.fighters[0],x=f.x;e.setInput(0,{left:true,right:true,jump:true,down:true});tick(e);assert.equal(f.direction,5);assert.equal(f.x,x);assert.equal(f.vy,0);e.setInput(0,{});tick(e);f.recovery=.5;e.setInput(0,{jump:true});tick(e);assert.equal(f.vy,0);f.recovery=0;f.root=1;e.setInput(0,{});tick(e);e.setInput(0,{jump:true});tick(e);assert.equal(f.vy,0);});
test('keyboard diagonals and lower directions stay isolated across both players',()=>{const w=new World(),t=w.tab();t.DUEL.start({mode:'local'});for(const k of ['KeyW','KeyD','ArrowDown','ArrowLeft'])t.events.keydown(key(k));let i=t.__audit.getInput();assert(i[0].jump&&i[0].right);assert(!i[0].down);assert(i[1].down&&i[1].left);assert(!i[1].jump);t.events.keyup(key('KeyD'));assert.equal(t.__audit.getInput()[0].right,false);assert(t.__audit.getInput()[1].left);t.events.blur();assert(!Object.values(t.__audit.getInput()[0]).some(Boolean));assert(!Object.values(t.__audit.getInput()[1]).some(Boolean));});
test('gamepad vertical axis supports diagonals and only rearms directional jump at neutral',()=>{const w=new World(),t=w.tab();t.DUEL.start({mode:'local'});t.setPads([pad(.8,-.8)]);t.__audit.gamepads();assert(t.__audit.getInput()[0].jump&&t.__audit.getInput()[0].right);t.setPads([pad(.8,0)]);t.__audit.gamepads();t.setPads([pad(.8,-.8)]);t.__audit.gamepads();assert.equal(t.__audit.getInput()[0].jump,false);t.setPads([pad(0,0)]);t.__audit.gamepads();t.setPads([pad(-.8,-.8)]);t.__audit.gamepads();assert(t.__audit.getInput()[0].jump&&t.__audit.getInput()[0].left);t.setPads([pad(-.8,.8)]);t.__audit.gamepads();assert(t.__audit.getInput()[0].down&&t.__audit.getInput()[0].left);});
test('releasing or disconnecting a pad cannot erase held keyboard input',()=>{const w=new World(),t=w.tab();t.DUEL.start({mode:'local'});t.events.keydown(key('KeyD'));t.setPads([pad(0,0,[2])]);t.__audit.gamepads();assert(t.__audit.getInput()[0].right&&t.__audit.getInput()[0].attack);t.setPads([]);t.__audit.gamepads();assert(t.__audit.getInput()[0].right);assert.equal(t.__audit.getInput()[0].attack,false);});
test('room authoritative inputs preserve new down plus diagonal jump flags',()=>{const w=new World(),{host,guest}=w.pair();host.__audit.action('roomStart');w.flush();guest.__audit.sendRoom({type:'input',input:{down:true,left:true}});w.flush();assert(host.__audit.getGuestInput().down);host.DUEL.engine.start();w.now=17;host.__audit.loop(w.now);assert(host.DUEL.engine.fighters[1].crouching);guest.__audit.sendRoom({type:'input',input:{jump:true,right:true}});w.flush();w.now=34;host.__audit.loop(w.now);assert(host.DUEL.engine.fighters[1].vy>0);});

test('held gamepad input stays released through blur and resume until the controller returns to neutral',()=>{const w=new World(),t=w.tab();t.DUEL.start({mode:'local'});t.setPads([pad(.8,-.8)]);t.__audit.gamepads();t.events.blur();t.__audit.action('resume');t.__audit.gamepads();assert(!Object.values(t.__audit.getInput()[0]).some(Boolean));t.setPads([pad(0,0)]);t.__audit.gamepads();t.setPads([pad(.8,-.8)]);t.__audit.gamepads();assert(t.__audit.getInput()[0].jump&&t.__audit.getInput()[0].right);});
