import {inRealmChannel} from './vm-channel.mjs';
import {bundleApp} from '../scripts/bundle-app.mjs';
import {CASUAL_PVP_POLICY} from '../src/net-quality.js';
import {registryFixture} from './registry-fixture.mjs';
import {idbFixture} from './idb-fixture.mjs';
// Browser-independent app integration. This mock validates wiring and protocol,
// not rendered layout, WebAudio, real touch, real gamepads or browser permissions.
import test from 'node:test';import assert from 'node:assert/strict';import vm from 'node:vm';import fs from 'node:fs';
const root=new URL('../',import.meta.url);const read=f=>fs.readFileSync(new URL(f,root),'utf8');
const source=(await bundleApp({append:'window.I18N_QA={get session(){return p2pSession;},skillDialog,p2pDialog,pause,result,updateHUD,renderP2PLobby,toast,audioDialog,recordsDialog,installDialog,manual,about};'})).code;
class Node{constructor(tag='div',attrs={}){this.nodeType=1;this.tagName=tag.toUpperCase();this.attrs=attrs;this.dataset=Object.fromEntries(Object.entries(attrs).filter(([k])=>k.startsWith('data-')).map(([k,v])=>[k.slice(5).replace(/-([a-z])/g,(_,x)=>x.toUpperCase()),v]));this.style={};this.children=[];this.value='';this.disabled='disabled'in attrs;this.hidden='hidden'in attrs;this.className=attrs.class||'';this.classList={add:()=>{},remove:()=>{},toggle:()=>{}};this.listeners={};}
 set innerHTML(html){this.children=[];parse(html,this);this._html=html;}get innerHTML(){return this._html||'';}get childNodes(){return this.children;}set textContent(v){this.children=[];this.appendChild(new TextNode(String(v)));}get textContent(){return this.children.map(x=>x.textContent).join('');}appendChild(n){n.parent=this;this.children.push(n);return n;}remove(){if(this.parent)this.parent.children=this.parent.children.filter(x=>x!==this);}querySelectorAll(sel){const out=[];const matches=n=>{if(sel.startsWith('#'))return n.attrs.id===sel.slice(1);if(sel.startsWith('.'))return (n.className||'').split(' ').includes(sel.slice(1));if(sel.startsWith('[')){const m=sel.match(/^\[([^\]^=]+)(\^=|=)?["']?([^"'\]]*)["']?\]$/);return m&&m[1]in n.attrs&&(!m[2]||(m[2]==='='?n.attrs[m[1]]===m[3]:n.attrs[m[1]].startsWith(m[3])));}return n.tagName===sel.toUpperCase();};const visit=n=>{for(const c of n.children){if(c.nodeType===1&&matches(c))out.push(c);if(c.children)visit(c);}};visit(this);return out;}querySelector(s){return this.querySelectorAll(s)[0]||null;}addEventListener(k,fn){(this.listeners[k]??=[]).push(fn);}setAttribute(k,v){this.attrs[k]=v;}getAttribute(k){return this.attrs[k]??null;}hasAttribute(k){return k in this.attrs;}setPointerCapture(){}focus(){let root=this;while(root.parent)root=root.parent;root.activeElement=this;for(const f of this.listeners.focus||[])f({});}select(){}click(){this.onclick?.({stopPropagation(){}});}getContext(){this.canvasText=[];return new Proxy({fillText:text=>this.canvasText.push(text),strokeText:text=>this.canvasText.push(text),createLinearGradient:()=>({addColorStop(){}})},{get(t,k){return t[k]||(()=>{});},set(t,k,v){t[k]=v;return true;}});}}
class TextNode{constructor(value){this.nodeType=3;this.nodeValue=value;}get textContent(){return this.nodeValue;}set textContent(v){this.nodeValue=String(v);}}
const decode=s=>s.replace(/&(?:amp|lt|gt|quot|#39);/g,k=>({'&amp;':'&','&lt;':'<','&gt;':'>','&quot;':'"','&#39;':"'"}[k]));
function parse(html,root){let stack=[root];const re=/<\/([\w-]+)>|<([\w-]+)([^>]*?)>|([^<]+)/g;let m;while((m=re.exec(html))){if(m[1]){if(stack.length>1)stack.pop();}else if(m[2]){let attrs={},a;const ar=/([^\s=]+)(?:="([^"]*)"|='([^']*)'|=([^\s>]+))?/g;while((a=ar.exec(m[3])))attrs[a[1]]=a[2]??a[3]??a[4]??'';const n=new Node(m[2],attrs);stack.at(-1).appendChild(n);if(!['img','br','input','meta','link','hr'].includes(m[2]))stack.push(n);}else stack.at(-1).appendChild(new TextNode(decode(m[4])));}}
const indexedDB=idbFixture(),channels=new Map();const clearChannels=channels.clear.bind(channels);channels.clear=()=>{clearChannels();indexedDB.clear();};class BC{constructor(name){this.name=name;(channels.get(name)||channels.set(name,new Set()).get(name)).add(this);}postMessage(data){for(const c of channels.get(this.name)||[])if(c!==this)queueMicrotask(()=>c.onmessage?.({data:structuredClone(data)}));}close(){channels.get(this.name)?.delete(this);}}
function app({fetcher=null,storedLanguage=null,cookieLanguage=null,blockedCookies=false,blockedStorage=false}={}){const saved=new Map(storedLanguage?[['dota-duel-language',storedLanguage]]:[]);const doc=new Node('document');const cookies=new Map(cookieLanguage?[['dota-duel-language',cookieLanguage]]:[]);Object.defineProperty(doc,'cookie',{get(){if(blockedCookies)throw Error('cookies blocked');return [...cookies].map(([k,v])=>k+'='+v).join('; ');},set(value){if(blockedCookies)throw Error('cookies blocked');const [k,v]=value.split(';')[0].split('=');cookies.set(k,v);doc.lastCookieWrite=value;}});doc.appendChild(new Node('main',{id:'app'}));doc.appendChild(new Node('div',{id:'toast'}));parse(read('index.html').match(/<section id="orientation-gate"[\s\S]*?<\/section>/)[0],doc);doc.createElement=t=>new Node(t);doc.addEventListener=Node.prototype.addEventListener.bind(doc);doc.documentElement=new Node('html');doc.body=doc;const events={},frames=[];let now=0;const ctx={indexedDB,crypto:globalThis.crypto,document:doc,console,Audio:class{constructor(){this.paused=true;}addEventListener(){}play(){this.paused=false;return Promise.resolve();}pause(){this.paused=true;}load(){}},structuredClone,Map,Math,Date,Promise,Image:class{constructor(){this.complete=true;this.naturalWidth=1024;}},fetch:fetcher|| (async()=>({ok:true,json:async()=>JSON.parse(read('assets/atlas.json'))})),navigator:{getGamepads:()=>[]},location:{protocol:'https:',search:''},localStorage:{getItem(k){if(blockedStorage)throw Error('storage blocked');return saved.get(k)??null;},setItem(k,v){if(blockedStorage)throw Error('storage blocked');saved.set(k,v);},removeItem(k){if(blockedStorage)throw Error('storage blocked');saved.delete(k);}},performance:{now:()=>now},requestAnimationFrame:cb=>frames.push(cb),setTimeout:()=>1,clearTimeout(){},setInterval:()=>1,clearInterval(){},BroadcastChannel:BC,addEventListener:(k,fn)=>(events[k]??=[]).push(fn)};ctx.window=ctx;ctx.BroadcastChannel=inRealmChannel(BC,ctx);vm.createContext(ctx);vm.runInContext(source,ctx,{timeout:4000});return {ctx,doc,events,saved,cookies,get duel(){return ctx.DUEL;},tick(n=1){for(let i=0;i<n;i++){now+=1000/60;const cbs=frames.splice(0);cbs.forEach(f=>f(now));}},key(code,down=true){for(const f of events[down?'keydown':'keyup']||[])f({code,preventDefault(){},target:{}});},button(action){const n=doc.querySelector(`[data-action="${action}"]`);assert(n,action+' button exists');n.click();},mode(mode){ctx.DUEL.state.mode=mode;ctx.DUEL.selection();}};}
const flush=async()=>{for(let i=0;i<100;i++)await Promise.resolve();};
// Exercise the home control when available; controller calls below validate display state, not extra UI controls.
const toggle=(a,lang)=>{const button=a.doc.querySelector('.nav')?.querySelector(`[data-language="${lang}"]`);if(button)button.click();else a.duel.language.setLanguage(lang);};
const dispatch=(node,type,details={})=>{const e={preventDefault(){},...details};for(const fn of node.listeners[type]||[])fn(e);};
const englishOnly=root=>{const missing=[];const visit=n=>{if(n.nodeType===3&&/[\u3400-\u9fff]/.test(n.nodeValue))missing.push(n.nodeValue);if(n.nodeType===1){if(n.hasAttribute('data-language-switch'))return;for(const k of ['aria-label','title','alt','placeholder']){const v=n.getAttribute(k);if(v&&/[\u3400-\u9fff]/.test(v))missing.push(k+': '+v);}}for(const child of n.childNodes||[])visit(child);};visit(root);assert.deepEqual(missing,[],'untranslated visible copy: '+JSON.stringify(missing));};

test('homepage setting defaults Chinese, persists English and preserves the room-first invitation nodes',()=>{const a=app();assert.equal(a.duel.language.current,'zh');assert.equal(a.doc.querySelectorAll('[data-hero]').length,0);assert.equal(a.doc.querySelectorAll('[data-invite-digit]').length,6);const input=a.doc.querySelector('[data-invite-digit="0"]');input.value='0';const form=a.doc.querySelector('#p2p-entry-form');toggle(a,'en');assert.equal(a.cookies.get('dota-duel-language'),'en');assert.equal(a.saved.get('dota-duel-language'),undefined);assert.equal(a.doc.documentElement.getAttribute('lang'),'en');assert.equal(a.doc.querySelector('#p2p-entry-form'),form);assert.equal(input.value,'0');englishOnly(a.doc.querySelector('#app'));toggle(a,'zh');assert.equal(a.doc.querySelector('#p2p-entry-form'),form);const b=app({storedLanguage:'en'});assert.equal(b.duel.language.current,'en');englishOnly(b.doc.querySelector('#app'));});

test('language setting exists only on home; rooms, dialogs, battle and results inherit saved preference',()=>{const a=app({storedLanguage:'en'});assert.equal(a.doc.querySelectorAll('[data-language-switch]').length,1);assert.equal(a.doc.querySelector('.nav').querySelectorAll('[data-language]').length,2);assert.equal(a.doc.querySelector('#orientation-gate').querySelectorAll('[data-language]').length,0);a.ctx.I18N_QA.p2pDialog();assert.equal(a.doc.querySelector('.panel').querySelectorAll('[data-language]').length,0);englishOnly(a.doc.querySelector('.panel'));for(const dialog of ['manual','audioDialog','recordsDialog','installDialog']){a.ctx.I18N_QA[dialog]();assert.equal(a.doc.querySelector('.panel').querySelectorAll('[data-language]').length,0);englishOnly(a.doc.querySelector('.panel'));a.button('close');}a.duel.start({mode:'local'});assert.equal(a.doc.querySelectorAll('[data-language]').length,0);englishOnly(a.doc.querySelector('#app'));a.ctx.I18N_QA.pause();assert.equal(a.doc.querySelector('.panel').querySelectorAll('[data-language]').length,0);englishOnly(a.doc.querySelector('.panel'));const g=a.duel.engine.snapshot();g.score=[2,1];g.history=[{winner:0},{winner:1},{winner:0}];a.ctx.I18N_QA.result(g,true);assert.equal(a.doc.querySelectorAll('[data-language]').length,0);englishOnly(a.doc.querySelector('.result-panel'));a.duel.selection();assert.equal(a.duel.language.current,'en');assert.equal(a.doc.querySelectorAll('[data-language-switch]').length,1);const b=app({cookieLanguage:a.cookies.get('dota-duel-language')});assert.equal(b.duel.language.current,'en');englishOnly(b.doc.querySelector('#app'));});

test('six digits retain leading zeroes and auto-submit exactly once; invalid edits and language changes preserve partial nodes',async()=>{const calls=[];let a;const fetcher=async(url,opts={})=>{url=String(url);const body=opts.body?JSON.parse(opts.body):null;calls.push({url,body});const data=url.includes('atlas.json')?JSON.parse(read('assets/atlas.json')):url.endsWith('/registry')?registryFixture():url.endsWith('/sessions')?{playerId:'b'.repeat(64),token:'c'.repeat(64)}:url.endsWith('/rooms/join')?{id:'d'.repeat(64),code:body.code,version:a.duel.compatibility.gameVersion,rosterId:a.duel.roster.rosterId,registryVersion:a.duel.compatibility.registryVersion,players:[{id:'a'.repeat(64),hero:1},{id:'b'.repeat(64),hero:1}],policy:CASUAL_PVP_POLICY,offer:{type:'offer',sdp:'v=0'}}:{};return {ok:true,json:async()=>data};};a=app({fetcher});a.ctx.RTCPeerConnection=SignalPeer;a.ctx.AbortController=AbortController;const digits=a.doc.querySelectorAll('[data-invite-digit]'),form=a.doc.querySelector('#p2p-entry-form');assert.equal(form.querySelector('[type="submit"]'),null);dispatch(digits[1],'paste',{clipboardData:{getData:()=> '123x45'}});toggle(a,'en');assert.equal(a.doc.querySelector('#p2p-entry-error').textContent,'Enter a six-digit invite code');dispatch(digits[0],'paste',{clipboardData:{getData:()=> '00123'}});const active=a.doc.activeElement;toggle(a,'zh');toggle(a,'en');assert.equal(a.doc.activeElement,active);assert.equal(a.doc.querySelector('#p2p-entry-form'),form);assert.equal(digits.map(d=>d.value).join(''),'00123');digits[5].value='4';dispatch(digits[5],'input');assert(digits.every(d=>d.disabled));dispatch(form,'submit');dispatch(form,'submit');await flush();assert.equal(a.duel.network.status,'connecting');assert.equal(calls.filter(c=>c.url.endsWith('/rooms/join')).length,1);assert.equal(calls.find(c=>c.url.endsWith('/rooms/join')).body.code,'001234');assert.equal(a.duel.language.current,'en');englishOnly(a.doc.querySelector('.room-flow'));a.ctx.I18N_QA.session.fail('P2P连接中断，请重新建房并加入');a.button('p2pRetry');assert.equal(a.doc.querySelectorAll('#p2p-entry-form').length,1);assert.equal(a.doc.querySelectorAll('[data-invite-digit]').length,6);assert.equal(a.doc.querySelectorAll('.overlay').length,0);assert.equal(a.duel.network,undefined);});

test('all 22 released hero archives and 88 actual arena descriptions are bilingual',()=>{const a=app();a.mode('cpu');toggle(a,'en');assert.equal(a.duel.roster.heroIds.length,22);assert.equal(a.doc.querySelectorAll('[data-hero]').filter(b=>b.disabled).length,24);for(const id of a.duel.roster.heroIds){for(let slot=0;slot<4;slot++){a.ctx.I18N_QA.skillDialog(id,slot);englishOnly(a.doc.querySelector('.panel'));assert.equal(a.doc.querySelectorAll('[data-slot]').length,4);}}toggle(a,'zh');assert(a.doc.querySelector('.panel').textContent.includes('多重施法'));assert(a.doc.querySelector('.panel').textContent.includes('竞技概率解释待独立审查'));});

test('manual, about, audio, install and history dialogs switch existing nodes and translate labels',()=>{const a=app();for(const name of ['manual','about','audioDialog','installDialog','recordsDialog']){a.ctx.I18N_QA[name]();const panel=a.doc.querySelector('.panel');toggle(a,'en');assert.equal(a.doc.querySelector('.panel'),panel);englishOnly(panel);toggle(a,'zh');assert.equal(a.doc.querySelector('.panel'),panel);}a.saved.set('dota-duel-history',JSON.stringify([{mode:'pvp',registryVersion:'duel-heroes-127-v1',heroes:[1,3],result:{score:[2,1]},status:'confirmed',durationMs:3000,version:'test',startedAt:0}]));a.ctx.I18N_QA.recordsDialog();toggle(a,'en');assert(a.doc.textContent.includes('Record saved'));assert(a.doc.textContent.includes('CRYSTAL MAIDEN'));englishOnly(a.doc.querySelector('.panel'));toggle(a,'zh');assert(a.doc.textContent.includes('战绩已保存'));});

test('running battle, pause and results keep engine/snapshot/inputs untouched across language changes',()=>{const a=app();a.duel.start({mode:'local'});const e=a.duel.engine,canvas=a.doc.querySelector('#arena'),snapshot=JSON.stringify(e.snapshot()),hud=a.doc.querySelector('.hud');toggle(a,'en');assert.equal(a.duel.engine,e);assert.equal(a.doc.querySelector('#arena'),canvas);assert.equal(a.doc.querySelector('.hud'),hud);assert.equal(JSON.stringify(e.snapshot()),snapshot);englishOnly(a.doc.querySelector('#app'));a.ctx.I18N_QA.pause('窗口失去焦点，已自动暂停');const paused=JSON.stringify(e.snapshot()),panel=a.doc.querySelector('.panel');toggle(a,'zh');toggle(a,'en');assert.equal(a.doc.querySelector('.panel'),panel);assert.equal(JSON.stringify(e.snapshot()),paused);englishOnly(panel);const g=e.snapshot();g.score=[2,1];g.history=[{winner:0},{winner:1},{winner:0}];a.ctx.I18N_QA.result(g,true);const result=a.doc.querySelector('.result-panel');assert(result.textContent.includes('wins'));assert(result.textContent.includes('3 rounds'));englishOnly(result);toggle(a,'zh');assert.equal(a.doc.querySelector('.result-panel'),result);assert(result.textContent.includes('获胜'));toggle(a,'en');assert(result.textContent.includes('wins'));assert.equal(a.duel.engine,e);});

class SignalPeer{constructor(){this.iceGatheringState='complete';}createDataChannel(label){return {label,readyState:'connecting',close(){},send(){}};}async createOffer(){return {type:'offer',sdp:'v=0\r\n'};}async createAnswer(){return {type:'answer',sdp:'v=0\r\n'};}async setLocalDescription(x){this.localDescription={toJSON:()=>x};}async setRemoteDescription(){}close(){}}

test('waiting P2P room, exact policy and canonical error survive bilingual live updates without API reentry',async()=>{const calls=[];let a;const fetcher=async(url,opts={})=>{url=String(url);calls.push({url,method:opts.method||'GET',body:opts.body?JSON.parse(opts.body):null});let data;if(url.includes('atlas.json'))data=JSON.parse(read('assets/atlas.json'));else if(url.endsWith('/registry'))data=registryFixture();else if(url.endsWith('/sessions'))data={playerId:'a'.repeat(64),token:'b'.repeat(64)};else if(url.endsWith('/rooms')){const b=JSON.parse(opts.body);data={id:'d'.repeat(64),code:'001234',registryVersion:a.duel.compatibility.registryVersion,rosterId:a.duel.roster.rosterId,version:a.duel.compatibility.gameVersion,players:[{id:'a'.repeat(64),hero:b.hero},{id:'',hero:0}],policy:b.policy};}else data={};return {ok:true,json:async()=>data};};a=app({fetcher});a.ctx.RTCPeerConnection=SignalPeer;a.ctx.AbortController=AbortController;a.ctx.I18N_QA.p2pDialog();a.button('p2pCreate');await flush();assert.equal(a.duel.network.status,'waiting');assert.equal(a.duel.network.code,'001234');const r=a.duel.room,network=JSON.stringify(a.duel.network),callCount=calls.length;toggle(a,'en');englishOnly(a.doc.querySelector('.room-flow'));assert.equal(a.duel.room,r);assert.equal(JSON.stringify(a.duel.network),network);assert.equal(calls.length,callCount);assert.equal(a.doc.querySelector('#p2p-live').textContent,'Measuring connection');assert.equal(JSON.stringify(a.duel.network.policy),JSON.stringify(CASUAL_PVP_POLICY));const p=a.ctx.I18N_QA.session;p.error='对方：延迟抖动过大';p.emit();assert.equal(a.doc.querySelector('#p2p-status').textContent,'Opponent: Jitter is too high');assert.equal(p.error,'对方：延迟抖动过大');p.error='';p.emit();toggle(a,'zh');assert.equal(a.duel.room,r);assert.equal(JSON.stringify(a.duel.network),network);assert.equal(calls.filter(c=>c.url.endsWith('/rooms')&&c.method==='POST').length,1);a.button('quit');await flush();assert.equal(calls.filter(c=>c.method==='DELETE').length,1);});

test('canonical fault and dynamic toast can switch repeatedly while source errors and room state stay intact',()=>{const a=app();const text='战绩服务：room full';a.ctx.I18N_QA.toast(text);const el=a.doc.querySelector('#toast');assert.equal(el.textContent,'战绩服务：房间已有两位玩家');toggle(a,'en');assert.equal(el.textContent,'Record service: room full');a.ctx.I18N_QA.toast('对方：检测结果已过期');assert.equal(el.textContent,'Opponent: Probe results expired');toggle(a,'zh');assert.equal(el.textContent,'对方：检测结果已过期');toggle(a,'en');assert.equal(el.textContent,'Opponent: Probe results expired');assert.equal(a.duel.room,null);assert.equal(text,'战绩服务：room full');});

test('canvas combat text changes language while the canonical effect/snapshot remains identical',()=>{const a=app();a.duel.start({mode:'local'});const e=a.duel.engine;e.effects.push({type:'text',text:'破防!',x:200,y:100,life:1,maxLife:1,color:'#fff'});const snapshot=JSON.stringify(e.snapshot());a.duel.render();const canvas=a.doc.querySelector('#arena');assert(canvas.canvasText.some(t=>t==='破防!'));canvas.canvasText.length=0;toggle(a,'en');a.duel.render();assert(canvas.canvasText.some(t=>t==='Guard break!'));assert.equal(JSON.stringify(e.snapshot()),snapshot);assert.equal(e.effects.at(-1).text,'破防!');toggle(a,'zh');canvas.canvasText.length=0;a.duel.render();assert(canvas.canvasText.some(t=>t==='破防!'));});

test('English host and Chinese guest join the same room with unchanged canonical request fields',async()=>{let h,g,room;const calls=[];const fetcher=role=>async(url,opts={})=>{url=String(url);const body=opts.body?JSON.parse(opts.body):null;calls.push({role,url,method:opts.method||'GET',body});let data;if(url.includes('atlas.json'))data=JSON.parse(read('assets/atlas.json'));else if(url.endsWith('/registry'))data=registryFixture();else if(url.endsWith('/sessions'))data={playerId:(role==='host'?'a':'b').repeat(64),token:'c'.repeat(64)};else if(url.endsWith('/rooms')){room={id:'d'.repeat(64),code:'001234',registryVersion:h.duel.compatibility.registryVersion,rosterId:h.duel.roster.rosterId,version:h.duel.compatibility.gameVersion,players:[{id:'a'.repeat(64),hero:body.hero},{id:'',hero:0}],policy:body.policy,offer:body.offer};data=structuredClone(room);}else if(url.endsWith('/rooms/join')){room.players[1]={id:'b'.repeat(64),hero:body.hero};data=structuredClone(room);}else data=structuredClone(room||{});return {ok:true,json:async()=>data};};
 h=app({fetcher:fetcher('host'),storedLanguage:'en'});g=app({fetcher:fetcher('guest')});for(const a of [h,g]){a.ctx.RTCPeerConnection=SignalPeer;a.ctx.AbortController=AbortController;}h.ctx.I18N_QA.p2pDialog();h.button('p2pCreate');await flush();assert.equal(h.duel.network.status,'waiting');g.ctx.I18N_QA.p2pDialog();const digits=g.doc.querySelectorAll('[data-invite-digit]');dispatch(digits[0],'paste',{clipboardData:{getData:()=>h.duel.network.code}});await flush();assert.equal(g.duel.network.status,'connecting');assert.equal(g.duel.network.roomId,h.duel.network.roomId);assert.equal(h.duel.language.current,'en');assert.equal(g.duel.language.current,'zh');assert.equal(JSON.stringify(h.duel.network.policy),JSON.stringify(g.duel.network.policy));assert.equal(JSON.stringify(h.duel.compatibility),JSON.stringify(g.duel.compatibility));
 const join=calls.find(c=>c.url.endsWith('/rooms/join'));assert.deepEqual(Object.keys(join.body).sort(),['code','hero','rosterId','version']);assert.equal(join.body.hero,1);assert.equal(join.body.code,'001234');assert.equal(join.body.version,h.duel.compatibility.gameVersion);englishOnly(h.doc.querySelector('.room-flow'));assert(g.doc.querySelector('.room-flow').textContent.includes('等待双方连接与版本校验'));const before=calls.length;toggle(g,'en');toggle(h,'zh');assert.equal(calls.length,before);assert.equal(g.duel.network.roomId,h.duel.network.roomId);h.button('quit');g.button('quit');await flush();assert.equal(calls.filter(c=>c.method==='DELETE').length,2);
});


test('one language cookie overrides legacy storage, migrates old choices and survives unavailable storage',()=>{
 const preferred=app({cookieLanguage:'zh',storedLanguage:'en'});assert.equal(preferred.duel.language.current,'zh');
 const migrated=app({storedLanguage:'en'});assert.equal(migrated.duel.language.current,'en');assert.equal(migrated.cookies.get('dota-duel-language'),'en');assert.equal(migrated.saved.has('dota-duel-language'),false);
 assert.match(migrated.doc.lastCookieWrite,/Path=\/; Max-Age=31536000; SameSite=Lax; Secure$/);
 const cookieOnly=app({cookieLanguage:'en',blockedStorage:true});assert.equal(cookieOnly.duel.language.current,'en');toggle(cookieOnly,'zh');assert.equal(cookieOnly.cookies.get('dota-duel-language'),'zh');
 const fallback=app({storedLanguage:'en',blockedCookies:true});assert.equal(fallback.duel.language.current,'en');toggle(fallback,'zh');assert.equal(fallback.saved.get('dota-duel-language'),'zh');
 const unavailable=app({blockedCookies:true,blockedStorage:true});assert.equal(unavailable.duel.language.current,'zh');toggle(unavailable,'en');assert.equal(unavailable.duel.language.current,'en');
 const invalid=app({cookieLanguage:'fr'});assert.equal(invalid.duel.language.current,'zh');toggle(invalid,'en');assert.equal(invalid.cookies.get('dota-duel-language'),'en');assert.equal(invalid.doc.querySelectorAll('[data-language-switch]').length,1);
});
