import test from 'node:test';import assert from 'node:assert/strict';
import {secureRoomCode,LocalRoomRegistry} from '../src/local-rooms.js';import {idbFixture} from './idb-fixture.mjs';
const random=(values)=>{let id=0;return {getRandomValues(a){a[0]=values.length>1?values.shift():values[0];return a;},randomUUID:()=>`reservation-${++id}`};};
test('six digit generator rejects biased tail and preserves leading zeros',()=>{assert.equal(secureRoomCode(random([4294967295,4294000000,7])),'000007');assert.throws(()=>secureRoomCode(random([4294967295])),/无法生成/);});
test('atomic concurrent reservations retry collisions and concurrent claims allow exactly one guest',async()=>{const indexedDB=idbFixture(),rng=random([123,123,456]),a=new LocalRoomRegistry({indexedDB,random:rng}),b=new LocalRoomRegistry({indexedDB,random:rng});const rooms=await Promise.all([a.reserve('a'),b.reserve('b')]);assert.deepEqual(rooms.map(x=>x.code),['000123','000456']);const claims=await Promise.allSettled([a.claim(rooms[0].code,'g1'),b.claim(rooms[0].code,'g2')]);assert.equal(claims.filter(x=>x.status==='fulfilled').length,1);assert.equal(await b.verifyGuest(rooms[0].code,rooms[0].id,'g1'),true);});
test('collision retry is bounded and unavailable IndexedDB fails closed',async()=>{const a=new LocalRoomRegistry({indexedDB:idbFixture(),random:random([9])});await a.reserve('a');await assert.rejects(a.reserve('b'),/碰撞/);await assert.rejects(new LocalRoomRegistry({indexedDB:null}).reserve('a'),/无法安全预约/);});
test('invitation TTL permits fresh reservation while old channel identity cannot claim or delete it',async()=>{let now=100;const a=new LocalRoomRegistry({indexedDB:idbFixture(),random:random([9]),now:()=>now});const old=await a.reserve('a');now+=600000;await assert.rejects(a.claim(old.code,'g'),/过期/);const fresh=await a.reserve('b');assert.notEqual(fresh.id,old.id);assert.equal(await a.release(old.code,old.id,'a'),false);assert.equal((await a.claim(fresh.code,'g')).id,fresh.id);assert.equal(await a.verifyGuest(fresh.code,old.id,'g'),false);});
test('guest lease expires, renewal extends and old guest cannot evict replacement',async()=>{let now=100;const a=new LocalRoomRegistry({indexedDB:idbFixture(),random:random([9]),now:()=>now}),r=await a.reserve('h');await a.claim(r.code,'g');now+=19000;await a.renew(r.code,r.id,'g');now+=19000;await assert.rejects(a.claim(r.code,'third'),/已有两位/);now+=1001;await a.claim(r.code,'third');assert.equal(await a.release(r.code,r.id,'g'),false);assert.equal(await a.verifyGuest(r.code,r.id,'third'),true);await a.release(r.code,r.id,'third');assert.equal(await a.verifyGuest(r.code,r.id,'third'),false);});
test('failed joins count toward shared per-origin rolling quota and reset after one minute',async()=>{let now=100;const db=idbFixture(),a=new LocalRoomRegistry({indexedDB:db,now:()=>now}),b=new LocalRoomRegistry({indexedDB:db,now:()=>now});for(let i=0;i<10;i++)await assert.rejects((i%2?a:b).claim('bad','g'),/六位/);await assert.rejects(a.claim('000000','g'),/一分钟/);now+=60000;await assert.rejects(b.claim('000000','g'),/不存在/);});
