import test from 'node:test';import assert from 'node:assert/strict';
import {MatchAPI,MatchRecord,resultPayload} from '../src/match-api.js';import {NET_VERSION} from '../src/net-version.js';
const game={history:[{winner:0,remaining:70.1234},{winner:-1,remaining:0},{winner:0,remaining:40.3214}],score:[2,0]};
const storage=()=>{const m=new Map();return {getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v)};};
test('concurrent calls create one anonymous session and use its bearer, never the six-digit code',async()=>{const calls=[];const a=new MatchAPI({base:'/api/v1',fetcher:async(url,opt)=>{calls.push({url,...opt});return {ok:true,json:async()=>url.endsWith('/sessions')?{playerId:'a'.repeat(64),token:'b'.repeat(64)}:{id:'c'.repeat(64),status:'in_progress'}};}});await Promise.all([a.createPVE(0,1,'request-one-123456'),a.createPVE(2,3,'request-two-123456')]);assert.equal(calls.filter(c=>c.url.endsWith('/sessions')).length,1);assert(calls.slice(1).every(c=>c.headers.Authorization==='Bearer '+'b'.repeat(64)));const body=JSON.parse(calls[1].body);assert.deepEqual(Object.keys(body).sort(),['aiDifficulty','hero','opponentHero','requestId','version']);assert.equal(body.version,NET_VERSION);});
test('result payload derives exact score from authoritative rounds, clamps/rounds ms and classifies aborts',()=>{assert.deepEqual(resultPayload(game),{version:NET_VERSION,outcome:'completed',rounds:[{number:1,winner:0,remainingMs:70123},{number:2,winner:-1,remainingMs:0},{number:3,winner:0,remainingMs:40321}],score:[2,0],winner:0,reason:''});const aborted=resultPayload({history:[{winner:1,remaining:23.8}]},'disconnect');assert.equal(aborted.outcome,'aborted');assert.equal(aborted.winner,-1);assert.equal(aborted.reason,'disconnect');assert.deepEqual(aborted.score,[0,1]);});
test('reports submit once, retry the identical immutable payload and only confirmed receipts claim saved',async()=>{let attempts=0,first;const store=storage(),service={async submit(id,payload){attempts++;if(!first)first=JSON.stringify(payload);assert.equal(JSON.stringify(payload),first);if(attempts===1)throw Error('offline');return {id,status:'confirmed',trust:'peer_agreement',reported:[true,true]};}};const r=new MatchRecord({mode:'pvp',transport:'p2p',heroes:[0,1],match:{id:'c'.repeat(64)},service,storage:store});await r.finish(game);assert.equal(r.status,'error');assert.equal(JSON.parse(store.getItem('dota-duel-history'))[0].status,'error');await r.submit();assert.equal(r.status,'confirmed');await r.finish({history:[]},'left');assert.equal(attempts,2);assert.equal(JSON.parse(store.getItem('dota-duel-history')).length,1);});
test('a pending report remains unconfirmed until server polling resolves disputed or timed out',async()=>{let scheduled;const r=new MatchRecord({mode:'pvp',transport:'p2p',heroes:[0,1],match:{id:'c'.repeat(64)},service:{async submit(){return {id:'c'.repeat(64),status:'pending'};},async getMatch(){return {id:'c'.repeat(64),status:'aborted',reason:'result_timeout'};}},storage:storage(),schedule:fn=>scheduled=fn});await r.finish(game);assert.equal(r.status,'pending');await scheduled();assert.equal(r.status,'aborted');});
test('PVE record waits for match creation before final submission and freezes the selected heroes',async()=>{let ready,submitted=0;const chosen=[0,1],r=new MatchRecord({mode:'pve',transport:'cpu',heroes:chosen,service:{createPVE:()=>new Promise(resolve=>ready=resolve),async submit(){submitted++;return {id:'c'.repeat(64),status:'recorded',trust:'client_reported'};}},storage:storage()});r.beginPVE();await Promise.resolve();const finished=r.finish(game);chosen[0]=19;assert.equal(submitted,0);ready({id:'c'.repeat(64),status:'in_progress'});await finished;assert.equal(submitted,1);assert.equal(r.status,'recorded');assert.deepEqual(r.view().heroes,[0,1]);assert.equal(r.view().mode,'pve');});
test('local PVP and unavailable PVE are recorded locally without claiming a server write',async()=>{const a=new MatchRecord({mode:'pvp',transport:'local',heroes:[0,1],storage:storage()});await a.finish(game);assert.equal(a.status,'local');assert.equal(a.view().matchId,null);const b=new MatchRecord({mode:'pve',transport:'cpu',heroes:[0,1],service:{async createPVE(){throw Error('unavailable');}},storage:storage()});b.beginPVE();await b.finish(game);assert.equal(b.status,'local');assert.match(b.error,/仅保留本机/);});

test('two tabs sharing one server match produce one history entry and a late pending response cannot downgrade confirmation',()=>{const store=storage(),match={id:'c'.repeat(64)},a=new MatchRecord({mode:'pvp',transport:'p2p',heroes:[0,1],match,storage:store}),b=new MatchRecord({mode:'pvp',transport:'p2p',heroes:[0,1],match,storage:store});a.payload=b.payload=resultPayload(game);a.status='confirmed';a.emit();b.status='pending';b.emit();const rows=JSON.parse(store.getItem('dota-duel-history'));assert.equal(rows.length,1);assert.equal(rows[0].status,'confirmed');});

test('local PVP uses strict local endpoint body and one reporter for both human slots',async()=>{const calls=[],api=new MatchAPI({base:'/api/v1',fetcher:async(url,opt)=>{calls.push({url,...opt});return {ok:true,json:async()=>url.endsWith('/sessions')?{playerId:'a'.repeat(64),token:'b'.repeat(64)}:{id:'c'.repeat(64),status:'in_progress'}};}});await api.createLocal(0,3,'broadcastchannel','request-local-123456');const body=JSON.parse(calls[1].body);assert.equal(calls[1].url,'/api/v1/matches/local');assert.deepEqual(body,{requestId:'request-local-123456',version:NET_VERSION,hero:0,opponentHero:3,transport:'broadcastchannel'});});
test('BC observer mirrors only its host epoch and never creates, submits, polls, or writes history',async()=>{const forbidden=()=>{throw Error('observer must not write');},service={createLocal:forbidden,submit:forbidden,getMatch:forbidden},r=new MatchRecord({mode:'pvp',transport:'broadcastchannel',heroes:[0,3],observer:true,localId:'epoch',service,storage:{setItem:forbidden},schedule:forbidden});await r.beginLocal();await r.finish(game);await r.submit();const host={localId:'epoch',version:NET_VERSION,mode:'pvp',transport:'broadcastchannel',heroes:[0,3],matchId:'c'.repeat(64),status:'recorded',trust:'client_reported',participantKinds:['local_slot','local_slot'],reporterPlayerId:'a'.repeat(64)};assert.equal(r.observeHost({...host,localId:'old-epoch'}),false);assert.equal(r.observeHost({...host,heroes:[0,4]}),false);assert.equal(r.observeHost(host),true);assert.equal(r.observeHost({...host,status:'in_progress'}),false);await r.finish(game);assert.equal(r.status,'recorded');assert.deepEqual(r.view().participantKinds,['local_slot','local_slot']);assert.equal(r.view().reporterPlayerId,host.reporterPlayerId);assert.equal(r.payload,null);});
test('local and BC creator store one receipt per match, rematch gets a new request ID, aborted stays aborted',async()=>{for(const transport of ['local','broadcastchannel']){const calls=[],store=storage(),service={async createLocal(a,b,t,id){calls.push({a,b,t,id});return {id:'c'.repeat(64),status:'in_progress'};},async submit(id,payload){calls.push({id,payload});return {id,status:payload.outcome==='aborted'?'aborted':'recorded',transport,trust:'client_reported',participantKinds:['local_slot','local_slot'],reporterPlayerId:'a'.repeat(64)};}};const r=new MatchRecord({mode:'pvp',transport,heroes:[0,3],service,storage:store});r.beginLocal();await Promise.all([r.finish(game),r.finish(game)]);assert.equal(calls.length,2);assert.equal(r.status,'recorded');assert.equal(JSON.parse(store.getItem('dota-duel-history')).length,1);const next=new MatchRecord({mode:'pvp',transport,heroes:[0,3],service,storage:storage()});await next.beginLocal();await next.finish({history:[]},'disconnect');assert.notEqual(next.localId,r.localId);assert.equal(next.status,'aborted');assert.equal(calls[3].payload.winner,-1);}});


test('failed creation retains payload and manual retry reuses its original request ID',async()=>{let attempts=0,ids=[],reported;const service={async createLocal(a,b,t,id){ids.push(id);if(++attempts===1)throw Error('offline');return {id:'c'.repeat(64),status:'in_progress'};},async submit(id,payload){reported=payload;return {id,status:'recorded'};}};const r=new MatchRecord({mode:'pvp',transport:'local',heroes:[0,3],service,storage:storage()});await r.beginLocal();await r.finish(game);const frozen=JSON.stringify(r.payload);assert.equal(r.status,'local');assert.equal(attempts,1);await r.submit();assert.equal(r.status,'recorded');assert.deepEqual(ids,[r.localId,r.localId]);assert.equal(JSON.stringify(reported),frozen);});
