import test from 'node:test';import assert from 'node:assert/strict';import {VirtualStick,arenaViewport,controlSlots,portraitViewport,toggleGameFullscreen} from '../src/mobile.js';import {World} from './integrity-harness.mjs';
test('joystick deadzone, eight sectors and clamped visual cap',()=>{const s=new VirtualStick();assert.deepEqual(s.update(8,0,50).input,{});for(const [x,y,k]of [[50,0,'right'],[50,50,'down'],[0,50,'down'],[-50,50,'left'],[-50,0,'left'],[-50,-50,'up'],[0,-50,'up'],[50,-50,'right']]){const v=s.update(x,y,50);assert(v.input[k]);assert(Math.hypot(v.x,v.y)<=50.0001);}assert.deepEqual(s.update(0,0,50).input,{});});
test('angular hysteresis prevents sector flapping and jumps need neutral rearm',()=>{const s=new VirtualStick();s.update(50,0,50);assert(!s.update(50,23,50).input.down);assert(s.update(50,35,50).input.down);assert(s.update(0,-50,50).input.jump);s.update(50,0,50);assert.equal(s.update(0,-50,50).input.jump,false);s.update(0,0,50);assert(s.update(0,-50,50).input.jump);});
test('only local seat is shown except explicit desktop local versus',()=>{assert.deepEqual(controlSlots('cpu',null),[0]);assert.deepEqual(controlSlots('p2p',{player:1}),[1]);assert.deepEqual(controlSlots('room',{player:0}),[0]);assert.deepEqual(controlSlots('local',null),[0,1]);assert.deepEqual(controlSlots('local',null,true),[0]);});
test('phone aspect ratios and safe areas preserve full canvas and reserve floor above controls',()=>{for(const [w,h] of [[667,375],[740,360],[844,390],[915,412],[1366,768]]){const v=arenaViewport(w,h,{left:44,right:44,bottom:21},154);assert.equal(v.width,w);assert.equal(v.height,h);assert(v.x>=44);assert(v.x+1280*v.scale<=w-44+.01);assert(v.ground<=h-21-154-12+.01);assert(v.scale>0);}assert(portraitViewport({innerWidth:390,innerHeight:844}));assert(!portraitViewport({innerWidth:844,innerHeight:390}));});
test('fullscreen absent, denied and orientation-lock denied all degrade with feedback',async()=>{const messages=[];assert.equal((await toggleGameFullscreen({documentElement:{}},{},m=>messages.push(m))).reason,'unsupported');assert.equal((await toggleGameFullscreen({documentElement:{requestFullscreen:()=>Promise.reject(Error())}},{},m=>messages.push(m))).reason,'denied');const doc={documentElement:{requestFullscreen:async()=>doc.fullscreenElement={}}};assert((await toggleGameFullscreen(doc,{orientation:{lock:()=>Promise.reject(Error())}},m=>messages.push(m))).fullscreen);assert.equal(messages.length,3);});
const event=(id,x=50,y=50,type='pointermove')=>({pointerId:id,clientX:x,clientY:y,type,preventDefault(){}});
function fixture(t){const cap={style:{}},pad={dataset:{stick:'0'},handlers:{},classList:{add(){},remove(){}},querySelector:()=>cap,getBoundingClientRect:()=>({left:0,top:0,width:100,height:100}),setPointerCapture(){},addEventListener(k,f){this.handlers[k]=f;}},button={dataset:{playerinput:'0',input:'attack'},handlers:{},classList:{add(){},remove(){}},setPointerCapture(){},addEventListener(k,f){this.handlers[k]=f;}};t.nodes.get('#app').querySelectorAll=q=>q==='[data-stick]'?[pad]:q==='[data-input]'?[button]:[];t.__audit.bindTouch();return {pad,button,cap};}
test('drag pointer capture remains directional outside base, independent attack finger, second stick finger ignored',()=>{const t=new World().tab();t.DUEL.start({mode:'cpu'});const {pad,button,cap}=fixture(t);pad.handlers.pointerdown(event(1));pad.handlers.pointermove(event(1,200,50));assert(t.__audit.getInput()[0].right);assert.match(cap.style.transform,/31px/);button.handlers.pointerdown(event(2));assert(t.__audit.getInput()[0].attack);pad.handlers.pointerdown(event(3,0,50));pad.handlers.pointermove(event(3,0,50));assert(t.__audit.getInput()[0].right);button.handlers.pointerup(event(2,0,0,'pointerup'));assert(t.__audit.getInput()[0].right);assert.equal(t.__audit.getInput()[0].attack,false);pad.handlers.pointerup(event(1,200,50,'pointerup'));assert(!Object.values(t.__audit.getInput()[0]).some(Boolean));assert.equal(cap.style.transform,'translate(0px,0px)');});
test('pointer cancellation, capture loss and blur reset visual cap and logical input',()=>{for(const kind of ['pointercancel','lostpointercapture','blur']){const t=new World().tab();t.DUEL.start({mode:'local'});const {pad,cap}=fixture(t);pad.handlers.pointerdown(event(1,80,10));if(kind==='blur')t.events.blur();else pad.handlers[kind](event(1,80,10,kind));assert(!Object.values(t.__audit.getInput()[0]).some(Boolean));assert.equal(cap.style.transform,'translate(0px,0px)');}});
test('remote portrait state prevents the other player from resuming behind the rotate gate',()=>{const w=new World(),{host,guest}=w.pair();host.__audit.action('roomStart');w.flush();guest.resize(390,844);w.flush();assert(host.DUEL.engine.paused);assert(host.DUEL.room.peerPortrait);host.__audit.action('resume');assert(host.DUEL.engine.paused);guest.resize(844,390);w.flush();assert.equal(host.DUEL.room.peerPortrait,false);host.__audit.action('resume');w.flush();assert.equal(host.DUEL.engine.paused,false);});
test('WebRTC session creation uses my selected hero for both host and guest roles',()=>{for(const role of ['host','guest']){const t=new World().tab();t.DUEL.state.myHero=8;t.DUEL.state.picks=[8,3];const session=t.__audit.newP2P(role,null);assert.equal(session.hero,8);assert.equal(t.DUEL.state.picks[role==='host'?0:1],8);}});
test('closing a dialog while the peer is portrait retains an accessible quit path',()=>{const w=new World(),{host,guest}=w.pair();host.__audit.action('roomStart');w.flush();guest.resize(390,844);w.flush();host.__audit.action('music');host.__audit.close();assert(host.DUEL.engine.paused);assert.match(host.__audit.getModal().innerHTML,/等待对方恢复横屏/);assert.match(host.__audit.getModal().innerHTML,/data-action="quit"/);});
