import test from 'node:test';import assert from 'node:assert/strict';import {LocalMusic} from '../src/music.js';
class AudioStub{constructor(src){this.src=src;this.paused=true;this.currentTime=0;}async play(){this.paused=false;this.onplay?.();}pause(){this.paused=true;this.onpause?.();}removeAttribute(){}load(){}}
function harness(){const stored=new Map(),revoked=[];let clock=0;const m=new LocalMusic({storage:{getItem:k=>stored.get(k),setItem:(k,v)=>stored.set(k,v)},AudioClass:AudioStub,now:()=>clock,schedule:()=>0,cancel:()=>{},urls:{createObjectURL:()=> 'blob:local-only',revokeObjectURL:x=>revoked.push(x)}});return {m,stored,revoked,advance:ms=>clock+=ms};}
test('local BGM uses only blob source, loops, and preferences survive independently of SFX',async()=>{const {m,stored}=harness();m.loadFile({name:'owned.wav',type:'audio/wav',size:500});await Promise.resolve();assert(m.track.loop);assert.equal(m.track.src,'blob:local-only');assert(!m.status().playing);m.track.currentTime=.2;m.observe();assert(m.status().playing);m.configure({musicVolume:.2,sfxVolume:.8,sfxEnabled:false});assert.equal(m.track.volume,.2);assert(m.settings.musicEnabled);assert(!m.settings.sfxEnabled);assert.equal(JSON.parse(stored.get('dota-duel-audio')).sfxVolume,.8);});
test('music respects mute, page lifecycle, resume and object URL cleanup',async()=>{const {m,revoked}=harness();m.loadFile({name:'a.mp3',type:'audio/mpeg',size:1});m.lifecycle({hidden:true});assert(m.track.paused);m.lifecycle({hidden:false});assert(!m.track.paused);m.configure({musicEnabled:false});m.lifecycle({pageAway:true});m.lifecycle({pageAway:false});assert(m.track.paused);m.clear();assert.deepEqual(revoked,['blob:local-only']);assert.equal(m.status().name,'');});
test('invalid or oversized music is rejected without replacing the current track',()=>{const {m}=harness();assert.throws(()=>m.loadFile({name:'x.exe',type:'',size:2}));assert.throws(()=>m.loadFile({name:'x.mp3',type:'audio/mpeg',size:130*1024*1024}));assert.equal(m.track,null);});
test('autoplay rejection is visible and can be retried by user gesture',async()=>{const {m}=harness();m.AudioClass=class extends AudioStub{async play(){throw {name:'NotAllowedError'};}};m.loadFile({name:'x.wav',type:'audio/wav',size:2});await Promise.resolve();assert.match(m.status().error,/点击播放/);});
test('switching local tracks pauses and detaches the old audio and revokes each URL once',()=>{const {m,revoked}=harness();m.loadFile({name:'one.wav',type:'audio/wav',size:1});const first=m.track;m.loadFile({name:'two.wav',type:'audio/wav',size:1});assert(first.paused);assert.equal(first.onplay,null);assert.equal(first.onerror,null);assert.notEqual(first,m.track);assert.equal(m.status().name,'two.wav');assert.equal(revoked.length,1);m.clear();m.clear();assert.equal(revoked.length,2);});
test('paused=false, playing event and resolved play promise are not playback without clock progress',async()=>{const {m,advance}=harness();m.loadFile({name:'valid.wav',type:'audio/wav',size:50});m.track.onplaying();await Promise.resolve();assert(!m.status().playing);assert.equal(m.status().diagnostics.playResult,'resolved');advance(12001);m.observe();assert.equal(m.status().state,'stalled');assert.match(m.status().error,/未取得进展/);assert(m.track.paused);m.clear();});
test('actual progress and clock wrap confirm playback; lifecycle resume requires fresh progress',async()=>{const {m,advance}=harness();m.loadFile({name:'valid.wav',type:'audio/wav',size:50});await Promise.resolve();m.track.currentTime=1.9;m.observe();assert(m.status().playing);advance(250);m.track.currentTime=.15;m.observe();assert.equal(m.status().diagnostics.loopCount,1);m.lifecycle({hidden:true});assert(!m.status().playing);m.lifecycle({hidden:false});assert(!m.status().playing);advance(250);m.track.currentTime=.4;m.observe();assert(m.status().playing);m.clear();});
test('pending play requests are coalesced and timed out; late completion cannot erase failure',async()=>{const {m,advance}=harness();let resolve,calls=0;m.AudioClass=class extends AudioStub{play(){calls++;this.paused=false;return new Promise(r=>resolve=r);}};m.loadFile({name:'a.wav',type:'audio/wav',size:10});m.sync();m.configure({musicVolume:.8});assert.equal(calls,1);advance(12001);m.observe();resolve();await Promise.resolve();assert.equal(m.status().state,'stalled');assert(!m.status().playing);assert.equal(m.status().diagnostics.playResult,'timeout');m.clear();});
test('decode errors and unsupported play rejection cannot claim playing; retry starts a new load',async()=>{const {m}=harness();m.loadFile({name:'invalid.wav',type:'audio/wav',size:50});m.track.error={code:4,message:'bad format'};m.track.onerror();await Promise.resolve();assert.equal(m.status().state,'error');assert.match(m.status().error,/无法解码/);assert(!m.status().playing);m.clear();m.AudioClass=class extends AudioStub{async play(){throw {name:'NotSupportedError'};}};m.loadFile({name:'invalid.wav',type:'audio/wav',size:50});await Promise.resolve();assert.equal(m.status().state,'error');assert.match(m.status().error,/无法解码/);m.clear();});
test('replacement ignores stale promise rejection and reports teardown/revocation',async()=>{const {m}=harness();let reject;m.AudioClass=class extends AudioStub{play(){this.paused=false;return new Promise((_,r)=>reject=r);}};m.loadFile({name:'old.wav',type:'audio/wav',size:50});const oldReject=reject;m.AudioClass=AudioStub;m.loadFile({name:'new.wav',type:'audio/wav',size:60});oldReject({name:'NotAllowedError'});await Promise.resolve();assert.equal(m.status().error,'');assert.equal(m.status().name,'new.wav');assert.deepEqual(m.status().diagnostics.lastRelease,{paused:true,sourceRemoved:true,handlersRemoved:true,loadReset:true,urlRevoked:true});m.clear();assert.equal(m.status().diagnostics.released,2);});
