import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import {createHash} from 'node:crypto';
import {OfficialAlbumPlayer,OFFICIAL_ALBUM} from '../src/official-music.js';
function setup(track=OFFICIAL_ALBUM){const events={},a={paused:true,currentTime:0,duration:90,plays:0,loads:0,addEventListener(n,f){events[n]=f;},play(){this.paused=false;this.plays++;return Promise.resolve();},pause(){this.paused=true;},load(){this.loads++;},removeAttribute(){}};let factories=0;const p=new OfficialAlbumPlayer({document:{hidden:false},track,audioFactory:()=>{factories++;return a;}});return {p,a,events,get factories(){return factories;}};}
test('file music waits for a gesture, uses a single looping audio element and clamps volume',async()=>{const x=setup();x.p.configure(true,.35);assert.equal(x.factories,0);x.p.unlock();await Promise.resolve();assert.equal(x.factories,1);assert(x.a.loop);assert.equal(x.a.volume,.35);assert(x.p.status().playing);x.p.setVolume(2);assert.equal(x.a.volume,1);x.p.setVolume(-1);assert.equal(x.a.volume,0);await x.p.play();assert.equal(x.factories,1);});
test('Reborn remix continues through menu, battle and rematch without reloading or resetting playback',async()=>{const {p,a}=setup();p.configure(true);await p.play();a.currentTime=41;const plays=a.plays;for(const scene of ['battle','menu','battle'])p.setScene(scene);await Promise.resolve();assert.equal(a.src,OFFICIAL_ALBUM.scenes.battle);assert.equal(a.loads,0);assert.equal(a.plays,plays);assert.equal(a.currentTime,41);assert.equal(p.status().name,'Dota 2 Reborn D+B Remix');assert(p.status().playing);});
test('disable, background and pagehide pause; returning never resumes without action',async()=>{const {p,a}=setup();p.configure(true);await p.play();p.lifecycle({hidden:true});assert(a.paused);p.lifecycle({hidden:false});assert(a.paused);await p.play();p.lifecycle({pageAway:true});assert(a.paused);p.lifecycle({pageAway:false});assert(a.paused);p.configure(false);assert.equal(p.state,'disabled');});
test('autoplay rejection and audio errors report failure rather than playing',async()=>{const {p,a,events}=setup();p.configure(true);a.play=()=>Promise.reject(Object.assign(Error(),{name:'NotAllowedError'}));assert.equal(await p.play(),false);assert.equal(p.state,'blocked');assert(!p.status().playing);events.error();assert.equal(p.state,'error');assert(p.error);});
test('a late successful play cannot resume after stop',async()=>{const {p,a}=setup();let resolve;a.play=()=>new Promise(r=>resolve=r);p.configure(true);const pending=p.play();p.stop();resolve();await pending;assert(a.paused);assert(!p.status().playing);});
test('missing file manifest remains an explicit unavailable state',async()=>{const {p}=setup({title:'missing',src:null});p.configure(true);assert.equal(await p.play(),false);assert.equal(p.state,'missing');assert(!p.status().available);});
test('official MP3s exactly match provenance manifest and contain actual audio payload',()=>{const root=new URL('../',import.meta.url),manifest=JSON.parse(fs.readFileSync(new URL('assets/music/source-manifest.json',root)));assert.equal(manifest.tracks.length,2);for(const track of manifest.tracks){const bytes=fs.readFileSync(new URL(track.file,root));assert.equal(bytes.length,track.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),track.sha256);assert(bytes.length>900000);}});
test('runtime has no video player, reserved rail or user import; music and SFX controls remain independent',()=>{const read=f=>fs.readFileSync(new URL('../'+f,import.meta.url),'utf8'),source=read('src/app.js')+read('src/official-music.js')+read('index.html')+read('src/style.css');assert.doesNotMatch(source,/youtube|bandcamp|iframe|official-rail|type="file"/i);assert.match(source,/id="music-volume"/);assert.match(source,/id="sfx-volume"/);assert.match(source,/internalMusic:false/);});

test('built-in Reborn remix is the exact user-selected file and both scenes select it',()=>{const root=new URL('../',import.meta.url),m=JSON.parse(fs.readFileSync(new URL('assets/music/reborn-source.json',root))),bytes=fs.readFileSync(new URL(m.file,root));assert.equal(bytes.length,9133967);assert.equal(createHash('sha256').update(bytes).digest('hex'),'e19fc6ebc70965227f7e1f4bb30e69367033fdc97f6c9ca09ea53470643eae85');assert.equal(OFFICIAL_ALBUM.src,m.file);assert.equal(OFFICIAL_ALBUM.scenes.menu,m.file);assert.equal(OFFICIAL_ALBUM.scenes.battle,m.file);assert.equal(OFFICIAL_ALBUM.artist,'Valve Studio Orchestra');assert(OFFICIAL_ALBUM.title.includes('Remix'));});

test('player and about text identify the selected remix without stale TI4 credits or missing links',()=>{const s=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');assert.doesNotMatch(s,/TI4|Chance Thomas|OFFICIAL_ALBUM\.sourcePage/);assert.match(s,/Dota 2 Reborn D\+B Remix/);assert.match(s,/这是混音版/);});
