import test from 'node:test';import assert from 'node:assert/strict';
import {compatibleRoom,compatibleMatch} from '../src/compatibility.js';
import {ACTIVE_ROSTER,REGISTRY_VERSION,heroRegistry,isActiveHero} from '../src/hero-registry.js';
import {NET_VERSION} from '../src/net-version.js';import {AUTO_PVP_POLICY} from '../src/net-quality.js';
import {PeerSession} from '../src/p2p.js';import {MatchAPI} from '../src/match-api.js';import {registryFixture} from './registry-fixture.mjs';
const room=()=>({id:'d'.repeat(64),code:'001234',rosterId:ACTIVE_ROSTER.rosterId,registryVersion:REGISTRY_VERSION,version:NET_VERSION,players:[{id:'a'.repeat(64),hero:1},{id:'',hero:0}],policy:{...AUTO_PVP_POLICY},offer:{type:'offer',sdp:'v=0\r\n'},closed:false});
test('real Go empty guest seat is valid only for host room admission; not for a match or guest join',()=>{const r=room();assert(compatibleRoom(r,{role:'host',hero:1}));assert(!compatibleRoom(r,{role:'guest',hero:3}));assert(!compatibleMatch(r));assert(!isActiveHero(0));});
test('room identity and own hero remain exact and cannot fall back to legacy or missing fields',()=>{for(const key of ['rosterId','registryVersion','version']){for(const value of [undefined,'old'])assert(!compatibleRoom({...room(),[key]:value},{role:'host',hero:1}),key);}assert(!compatibleRoom(room(),{role:'host',hero:3}));assert(!compatibleRoom(room(),{role:'unknown',hero:1}));});
test('empty-seat exception never admits an occupied excluded hero or malformed guest/host',()=>{for(const row of heroRegistry.rows().filter(x=>!isActiveHero(x.registryNumericId))){const r=room();r.players[1]={id:'b'.repeat(64),hero:row.registryNumericId};assert(!compatibleRoom(r,{role:'host',hero:1}),String(row.registryNumericId));}for(const player of [{id:'',hero:3},{id:'',hero:null},{hero:0},{id:'x',hero:3}]){const r=room();r.players[1]=player;assert(!compatibleRoom(r,{role:'host',hero:1}));}const r=room();r.players[0]={id:'',hero:0};assert(!compatibleRoom(r,{role:'host',hero:1}));assert(!compatibleRoom({...room(),players:[]},{role:'host',hero:1}));});
class SignalPeer{constructor(){this.iceGatheringState='complete';}createDataChannel(label){return {label,readyState:'connecting',close(){}};}async createOffer(){return {type:'offer',sdp:'v=0\r\n'};}async createAnswer(){return {type:'answer',sdp:'v=0\r\n'};}async setLocalDescription(x){this.localDescription={toJSON:()=>x};}async setRemoteDescription(){}close(){}}
function setup(role,response){const calls=[],service=new MatchAPI({fetcher:async(url,opts)=>{const path=new URL(url).pathname,body=opts.body?JSON.parse(opts.body):null;calls.push({path,method:opts.method,body});let value=path.endsWith('/registry')?registryFixture():path.endsWith('/sessions')?{playerId:(role==='host'?'a':'b').repeat(64),token:'c'.repeat(64)}:path.endsWith('/rooms')||path.endsWith('/rooms/join')?response:{ok:true};return {ok:true,json:async()=>value};}});const p=new PeerSession({role,hero:role==='host'?1:3,policy:role==='host'?{...AUTO_PVP_POLICY}:null,service,Peer:SignalPeer});p.later=()=>{};return {p,calls};}
const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
test('actual PeerSession and MatchAPI accept Go room creation, retain six digits and release once on close',async()=>{const {p,calls}=setup('host',room());try{await p.create();assert.equal(p.status,'waiting');assert.equal(p.code,'001234');assert.equal(p.roomId,'d'.repeat(64));const posted=calls.find(x=>x.path.endsWith('/rooms')&&x.method==='POST');assert.equal(posted.body.rosterId,ACTIVE_ROSTER.rosterId);assert.equal(posted.body.version,NET_VERSION);assert.deepEqual(posted.body.policy,AUTO_PVP_POLICY);}finally{p.close();p.close();await flush();}assert.equal(calls.filter(x=>x.method==='DELETE').length,1);assert(!calls.some(x=>x.path.includes('/matches')));});
test('occupied active guest accepts exact identity and own hero on actual join path',async()=>{const r=room();r.players[1]={id:'b'.repeat(64),hero:3};assert(compatibleRoom(r,{role:'guest',hero:3}));assert(compatibleMatch(r));const {p,calls}=setup('guest',r);try{await p.join(r.code);assert.equal(p.status,'connecting');assert.equal(p.roomId,r.id);assert.equal(p.code,r.code);assert(calls.some(x=>x.path.endsWith('/answer')));}finally{p.close();}const wrong=structuredClone(r);wrong.players[1].hero=4;assert(!compatibleRoom(wrong,{role:'guest',hero:3}));});
test('rejected allocated host room is released exactly once; match validator remains strict',async()=>{const r=room();r.players[1]={id:'b'.repeat(64),hero:0};const {p,calls}=setup('host',r);await p.create();await flush();assert.equal(p.status,'failed');assert.equal(p.error,'房间可玩名单不一致');assert(p.stopped);p.close();await flush();assert.equal(calls.filter(x=>x.method==='DELETE').length,1);assert(!compatibleMatch(r));});
