import {GAME_COMPATIBILITY} from '../src/compatibility.js';
import test from 'node:test';import assert from 'node:assert/strict';import {PeerSession} from '../src/p2p.js';import {NET_VERSION} from '../src/net-version.js';import {DEFAULT_NET_POLICY} from '../src/net-quality.js';
const policy={...DEFAULT_NET_POLICY,direction:'above',rttMs:100};
test('default signaling fetch retains browser receiver, uses server-issued bearer and closes by room id',async()=>{const original=globalThis.fetch,calls=[];globalThis.fetch=async function(url,opts){assert.equal(this,globalThis);calls.push({url,method:opts.method,auth:opts.headers.Authorization});return {ok:true,json:async()=>url.endsWith('/sessions')?{playerId:'a'.repeat(64),token:'b'.repeat(64),expires:Date.now()+86400000}:{ok:true}};};try{const p=new PeerSession({role:'host',hero:0,policy});await p.api('rooms',{});p.roomId='c'.repeat(64);p.releaseRoom();await flush();assert.deepEqual(calls.map(c=>c.method),['POST','POST','DELETE']);assert.equal(calls[1].auth,'Bearer '+'b'.repeat(64));assert.equal(calls[2].url,'https://api.dotapk.lol/api/v1/rooms/'+'c'.repeat(64));p.close();}finally{globalThis.fetch=original;}});
function matchServer(){const ready=[false,false],roomId='d'.repeat(64),match={id:'e'.repeat(64),roomId,version:NET_VERSION,players:[{hero:13},{hero:13}],status:'awaiting_ready'};return {roomId,match,service(role){return {async createMatch(){return {...match};},async ready(){ready[role==='host'?0:1]=true;if(ready.every(Boolean))match.status='in_progress';return {...match};},async getMatch(){return {...match};},async request(){return {ok:true};}};}};}
function connected(role,onstart=()=>{},server=matchServer()){const p=new PeerSession({role,hero:13,policy,onstart,service:server.service(role)});p.roomId=server.roomId;p.connected=true;p.status='probing';p.peerVersion=NET_VERSION;p.peerCompatibility=GAME_COMPATIBILITY;p.peerHero=13;const now=performance.now();p.probes.rows=Array.from({length:30},(_,i)=>({id:i,sent:now-10000+i*320,rtt:20,received:now-9980+i*320}));p.probes.rows[29].received=now;p.peerQuality={...p.probes.summary(now)};p.peerQualityAt=now;p.control={readyState:'open',bufferedAmount:0,send(){},close(){}};p.frames={...p.control};return p;}
const flush=async()=>{for(let i=0;i<60;i++)await Promise.resolve();};
test('start requires both ready, a fresh two-way window and peer handshake; valid pair commits same match epoch',async()=>{const starts=[],server=matchServer();const h=connected('host',x=>starts.push(['h',x]),server),g=connected('guest',x=>starts.push(['g',x]),server);h.control.send=raw=>queueMicrotask(()=>g.receive(raw,'control'));g.control.send=raw=>queueMicrotask(()=>h.receive(raw,'control'));assert(!h.start());h.setReady();await flush();assert(!h.start());g.setReady();await flush();assert(h.start());await flush();assert.equal(starts.length,2);assert.equal(h.seenEpoch,g.seenEpoch);assert.equal(h.seenEpoch,server.match.id,'game epoch is the server match id');assert(h.fighting&&g.fighting);h.shutdown();g.shutdown();});
test('stale peer metrics, high RTT and unconfirmed policy prevent ready/start',()=>{const p=connected('host');p.peerQualityAt=-10000;assert(!p.setReady());p.peerQualityAt=performance.now();p.peerQuality.p95=200;assert(!p.setReady());p.peerQuality.p95=20;p.policy={...policy,direction:null};assert(!p.setReady());p.shutdown();});
test('quality degradation invalidates prior readiness and cannot use a stale prepared reply',()=>{const p=connected('host');p.setReady();p.peerReady=true;assert(p.start());const epoch=p.pendingEpoch;p.peerQuality.p95=300;p.receive(JSON.stringify({type:'prepared',epoch}),'control');assert(!p.fighting);p.shutdown();});
test('version mismatch fails closed and disconnect releases transport state',()=>{let reason;const p=connected('guest');p.onfault=x=>reason=x;p.receive(JSON.stringify({type:'hello',version:'old',hero:13,policy}),'control');assert(p.stopped);assert(!p.connected);assert.match(reason,/版本/);});
test('old match packets and out-of-order frames cannot overwrite current state',()=>{const p=connected('guest'),seen=[];p.fighting=true;p.seenEpoch='new';p.onmessage=m=>seen.push(m);for(const [epoch,seq] of [['old',20],['new',4],['new',3],['new',4],['new',5]])p.receive(JSON.stringify({type:'game',epoch,seq,value:{type:'snapshot'}}),'frames');assert.equal(seen.length,2);p.shutdown();});
test('overloaded channel drops obsolete frames and reconnect lobby clears ready flags',()=>{const p=connected('host');p.frames.bufferedAmount=200000;assert(!p.sendGame({type:'snapshot',snapshot:{}}));assert(p.sendGame({type:'input',input:{attack:true}}));p.ready=p.peerReady=p.fighting=true;p.returnToLobby();assert(!p.ready&&!p.peerReady&&!p.fighting);p.shutdown();});
test('signaling polling backs off, has a hard deadline and stops after answer',async()=>{const p=new PeerSession({role:'host',hero:0,policy});p.code='000123';p.roomId='d'.repeat(64);p.deadline=performance.now()+120000;const delays=[];p.api=async()=>({answer:null});p.later=(f,ms)=>delays.push(ms);for(let i=0;i<5;i++)await p.poll();assert.deepEqual(delays,[2000,4000,6000,6000,6000]);let deleted=0;p.service.request=async(path,body,method)=>{assert.equal(method,'DELETE');deleted++;return {};};p.pc={async setRemoteDescription(){},close(){}};p.api=async()=>({answer:{type:'answer'}});await p.poll();assert.equal(deleted,0,'successful signaling must retain the room for match records');assert.equal(p.status,'connecting');p.close();await flush();assert.equal(deleted,1);const expired=new PeerSession({role:'host',hero:0,policy});expired.deadline=-1;let reads=0;expired.api=async()=>{reads++;};await expired.poll();assert.equal(reads,0);assert(expired.stopped);});
test('a reconnect creates fresh credentials and never restores old epoch or readiness',()=>{const old=connected('host');old.ready=old.peerReady=old.fighting=true;old.seenEpoch='old';old.fail('closed');const fresh=new PeerSession({role:'host',hero:0,policy});assert.notEqual(old.token,fresh.token);assert.notEqual(old.id,fresh.id);assert(!fresh.ready&&!fresh.peerReady&&!fresh.fighting);assert.equal(fresh.seenEpoch,'');assert(old.stopped);fresh.close();});

test('canonical final snapshot uses reliable control exactly once per match, while ordinary frames remain fast',()=>{const p=connected('host'),control=[],frames=[];p.control.send=v=>control.push(JSON.parse(v));p.frames={...p.control,send:v=>frames.push(JSON.parse(v))};p.sendGame({type:'snapshot',snapshot:{phase:'fight'}});p.sendGame({type:'snapshot',snapshot:{phase:'matchEnd',history:[]}});p.sendGame({type:'snapshot',snapshot:{phase:'matchEnd',history:[]}});assert.equal(frames.length,1);assert.equal(control.length,1);assert.equal(control[0].value.snapshot.phase,'matchEnd');p.shutdown();});

test('late unreliable frames cannot overwrite a reliable terminal snapshot',()=>{const p=connected('guest'),states=[];p.fighting=true;p.seenEpoch='match';p.onmessage=m=>states.push(m.snapshot.phase);for(const [channel,seq,phase]of [['frames',8,'fight'],['control',10,'matchEnd'],['frames',9,'fight']])p.receive(JSON.stringify({type:'game',epoch:'match',seq,value:{type:'snapshot',snapshot:{phase}}}),channel);assert.deepEqual(states,['fight','matchEnd']);p.shutdown();});

// Scheduling tests use fake transport/service replies; these are not browser/WebRTC acceptance.
function readyPair(starts=[]){
 const server=matchServer(),h=connected('host',x=>starts.push(['host',x]),server),g=connected('guest',x=>starts.push(['guest',x]),server);
 h.control.send=raw=>queueMicrotask(()=>g.receive(raw,'control'));g.control.send=raw=>queueMicrotask(()=>h.receive(raw,'control'));
 h.setReady();g.setReady();return {h,g,server};
}
test('portrait in the ready lobby withdraws readiness; landscape does not ready or start automatically',async()=>{
 const starts=[],{h,g}=readyPair(starts);try{await flush();g.setAvailable(false);await flush();assert.equal(g.ready,false);assert.equal(h.peerReady,false);assert.equal(h.peerAvailable,false);assert.equal(h.start(),false);assert.equal(g.setReady(),false);
 g.setAvailable(true);await flush();assert.equal(g.ready,false);assert.equal(h.peerReady,false);assert.equal(h.start(),false);assert.equal(starts.length,0);
 assert(g.setReady());await flush();assert(h.start());await flush();assert.equal(starts.length,2);assert(starts.every(([,x])=>!x.pauseForOrientation));}finally{h.shutdown();g.shutdown();}
});
test('stale ready packets cannot override a portrait peer, and frames cannot change availability',()=>{
 const h=connected('host');try{h.receive(JSON.stringify({type:'availability',value:false}),'frames');assert(h.peerAvailable);h.receive(JSON.stringify({type:'availability',value:false}),'control');h.receive(JSON.stringify({type:'ready',value:true}),'control');assert.equal(h.peerReady,false);assert.equal(h.gate().ok,false);h.receive(JSON.stringify({type:'availability',value:'true'}),'control');assert.equal(h.peerAvailable,false);}finally{h.shutdown();}
});
for(const rotatingRole of ['host','guest'])test(`${rotatingRole} rotation cancels an in-flight host preparation before commit`,async()=>{
 const starts=[],{h,g}=readyPair(starts);let release;
 try{await flush();const get=h.service.createMatch;h.service.createMatch=()=>new Promise(resolve=>{release=async()=>resolve(await get());});assert(h.start());(rotatingRole==='host'?h:g).setAvailable(false);await flush();assert.equal(h.pendingEpoch,null);await release();await flush();assert.equal(starts.length,0);assert.equal(h.fighting,false);assert.equal(g.fighting,false);(rotatingRole==='host'?h:g).setAvailable(true);await flush();assert.equal(starts.length,0);assert.equal(h.start(),false);}finally{h.shutdown();g.shutdown();}
});
for(const restoreBeforeReply of [false,true])test(`guest rotation during committed-start verification enters a paused match (restored=${restoreBeforeReply})`,async()=>{
 const starts=[],{h,g,server}=readyPair(starts);let release,reads=0;const get=g.service.getMatch;
 g.service.getMatch=async()=>{const result=await get();if(++reads===2)return new Promise(resolve=>{release=()=>resolve(result);});return result;};
 try{await flush();assert(h.start());await flush();assert.equal(h.fighting,true);assert.equal(g.fighting,false);assert.equal(typeof release,'function');g.setAvailable(false);await flush();assert.equal(h.peerAvailable,false);assert.equal(g.ready,false);if(restoreBeforeReply){g.setAvailable(true);await flush();assert.equal(g.ready,false);assert.equal(g.fighting,false);}release();await flush();assert.equal(g.fighting,true);assert.equal(g.seenEpoch,server.match.id);const guestStart=starts.find(([role])=>role==='guest')[1];assert.equal(guestStart.pauseForOrientation,true);assert.equal(guestStart.match.id,server.match.id);}finally{h.shutdown();g.shutdown();}
});
test('portrait advertised in the connection hello blocks lobby readiness',()=>{
 const h=connected('host');try{h.receive(JSON.stringify({type:'hello',version:NET_VERSION,compatibility:GAME_COMPATIBILITY,hero:13,policy,available:false}),'control');assert.equal(h.info().peerAvailable,false);assert.equal(h.setReady(),false);}finally{h.shutdown();}
});

test('a room allocated after host cancellation is released once without reviving the session',async()=>{let resolveRoom;const calls=[],id='d'.repeat(64);const service={request(path,body,method){calls.push({path,method});return path==='rooms'?new Promise(r=>resolveRoom=r):Promise.resolve({ok:true});}};const p=new PeerSession({role:'host',hero:0,policy,service});const pending=p.api('rooms',{});p.close();resolveRoom({id,code:'000012'});await assert.rejects(pending,/连接已关闭/);await flush();assert(p.stopped);assert(!p.ready&&!p.peerReady);assert.equal(p.code,'');assert.deepEqual(calls,[{path:'rooms',method:'POST'},{path:'rooms/'+id,method:'DELETE'}]);p.close();assert.equal(calls.length,2);});
