import test from 'node:test';import assert from 'node:assert/strict';
import {MatchAPI} from '../src/match-api.js';import {ACTIVE_ROSTER} from '../src/hero-registry.js';import {registryFixture} from './registry-fixture.mjs';
// Released IDs 1 and 3 reach registry authorization; paused IDs fail earlier.
const response=data=>({ok:true,json:async()=>data});
const wrong=()=>({...registryFixture(),registrySha256:'wrong'});
function apiFixture(){let available='offline',calls=[];const api=new MatchAPI({base:'/api/v1',fetcher:async(url,options)=>{calls.push({url,options});if(url.endsWith('/registry')){if(available==='offline')throw Error('offline');return response(available==='bad'?wrong():registryFixture());}return response(url.endsWith('/sessions')?{playerId:'a'.repeat(64),token:'b'.repeat(64)}:{id:'c'.repeat(64),status:'in_progress'});}});return {api,calls,set:v=>available=v};}
for(const failure of ['offline','bad'])test(`registry ${failure} clears failed cache and next ordinary create revalidates without reload`,async()=>{const {api,calls,set}=apiFixture();set(failure);await assert.rejects(()=>api.createPVE(1,3,'same-request'));assert.equal(api.registryTask,null);assert.equal(calls.length,1);set('good');await api.createPVE(1,3,'same-request');assert.equal(api.registryStatus.status,'verified');assert.deepEqual(JSON.parse(calls.find(c=>c.url.endsWith('/matches/pve')).options.body).rosterId,ACTIVE_ROSTER.rosterId);assert.equal(calls.filter(c=>c.url.endsWith('/registry')).length,2);});
test('continuous registry mismatch is retried but never downgraded or allowed to create a session or match',async()=>{const {api,calls,set}=apiFixture();set('bad');for(let i=0;i<3;i++){await assert.rejects(()=>api.createLocal(1,3,'local','same-request'));assert.equal(api.registryStatus.status,'incompatible');}assert.equal(calls.length,3);assert(calls.every(c=>c.url.endsWith('/registry')));});
test('verified registry stays cached and concurrent callers share one in-flight check',async()=>{let calls=0,release;const api=new MatchAPI({fetcher:()=>{calls++;return new Promise(resolve=>release=()=>resolve(response(registryFixture())));}});const a=api.loadRegistry(),b=api.loadRegistry();await Promise.resolve();assert.equal(calls,1);release();assert.equal((await a).status,'verified');assert.equal((await b).status,'verified');await api.loadRegistry();await api.rosterFields();assert.equal(calls,1);});
for(const oldResult of ['good','bad','offline'])test(`explicit refresh supersedes an older ${oldResult} request without stale publication`,async()=>{const pending=[];const api=new MatchAPI({fetcher:()=>new Promise((resolve,reject)=>pending.push({resolve,reject}))});const old=api.loadRegistry();const oldOutcome=old.then(value=>({value}),error=>({error}));await Promise.resolve();const fresh=api.loadRegistry({refresh:true});await Promise.resolve();pending[1].resolve(response(registryFixture()));await fresh;const cached=api.registryTask;if(oldResult==='offline')pending[0].reject(Error('offline'));else pending[0].resolve(response(oldResult==='good'?registryFixture():wrong()));assert((await oldOutcome).error,'superseded caller must not proceed with stale validation');assert.equal(api.registryStatus.status,'verified');assert.equal(api.registryTask,cached);await api.loadRegistry();assert.equal(pending.length,2);});
test('a late old success cannot bypass a failed newer binding check',async()=>{const pending=[];const api=new MatchAPI({fetcher:()=>new Promise(resolve=>pending.push(resolve))});const old=api.rosterFields();const oldOutcome=old.then(value=>({value}),error=>({error}));await Promise.resolve();const fresh=api.loadRegistry({refresh:true});await Promise.resolve();pending[1](response(wrong()));await assert.rejects(()=>fresh);pending[0](response(registryFixture()));assert((await oldOutcome).error);assert.equal(api.registryStatus.status,'incompatible');assert.equal(api.registryTask,null);});
test('an older failure finishing first cannot clear a newer pending check',async()=>{const pending=[];const api=new MatchAPI({fetcher:()=>new Promise((resolve,reject)=>pending.push({resolve,reject}))});const old=api.loadRegistry();const oldOutcome=old.catch(error=>error);await Promise.resolve();const fresh=api.loadRegistry({refresh:true});await Promise.resolve();const task=api.registryTask;pending[0].reject(Error('offline'));assert(await oldOutcome instanceof Error);assert.equal(api.registryTask,task);const shared=api.loadRegistry();pending[1].resolve(response(registryFixture()));assert.equal((await fresh).status,'verified');assert.equal((await shared).status,'verified');assert.equal(pending.length,2);});
