// One Node process: emitted-only module graph, cold imports and focused wiring smoke.
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import assert from 'node:assert/strict';import {pathToFileURL,fileURLToPath} from 'node:url';
import {createHash} from 'node:crypto';import {build} from 'esbuild';
const root=path.resolve(fileURLToPath(new URL('../',import.meta.url))),out=path.join(root,'../release22-validation');
fs.mkdirSync(out,{recursive:true});
const emitted=path.join(root,'dist/client'),cold=fs.mkdtempSync(path.join(os.tmpdir(),'dotapk-heros22-cold-'));
fs.cpSync(path.join(emitted,'src'),path.join(cold,'src'),{recursive:true});
fs.copyFileSync(path.join(emitted,'build-manifest.json'),path.join(cold,'build-manifest.json'));
fs.writeFileSync(path.join(cold,'package.json'),'\u007b"type":"module"\u007d\n');
const manifest=JSON.parse(fs.readFileSync(path.join(cold,'build-manifest.json'),'utf8'));
const graph=await build({absWorkingDir:cold,entryPoints:['src/app.js'],bundle:true,metafile:true,write:false,format:'esm',platform:'browser',target:'es2022',logLevel:'silent'});
const inputs=Object.keys(graph.metafile.inputs),edges=Object.values(graph.metafile.inputs).flatMap(row=>row.imports);
assert(inputs.includes('src/hero-legacy-phase-rules.js'));assert(inputs.includes('src/released-hero-rules.js'));assert(inputs.includes('src/released-roster.js'));
assert(edges.every(row=>!row.external),'no package or Source fallback');
for(const input of inputs)assert(path.resolve(cold,input).startsWith(cold+path.sep));
const from=file=>import(pathToFileURL(path.join(cold,file)).href);
const {Engine}=await from('src/engine.js'),{runtimeHeroes}=await from('src/runtime-heroes.js');
const {ACTIVE_ROSTER}=await from('src/hero-registry.js');
const {createReleasedHeroRegistry}=await from('src/released-hero-rules.js');
const {createRemoteSnapshotValidator}=await from('src/remote-snapshot.js');
const {GAME_COMPATIBILITY}=await from('src/compatibility.js');
const registry=createReleasedHeroRegistry(),sealed=registry.seal();
assert.equal(manifest.gameVersion,GAME_COMPATIBILITY.gameVersion);
assert.equal(manifest.roster.rosterId,ACTIVE_ROSTER.rosterId);assert.deepEqual(manifest.roster.heroIds,ACTIVE_ROSTER.heroIds);
assert.equal(manifest.rulesHash,sealed.rulesHash);
const originalManifest=JSON.parse(fs.readFileSync(path.join(root,'../release-scope-accepted127-2026-10-06/sealed-manifest132.json'),'utf8'));
assert.deepEqual(sealed.manifest,originalManifest,'all code/schema/parameters/hooks unchanged from accepted127 baseline');
const e=new Engine(runtimeHeroes,[50,9],{seed:0,simulationRoster:ACTIVE_ROSTER,heroRuleRegistry:registry}).start();
e.setInput(0,{left:true});e.step();assert(createRemoteSnapshotValidator(runtimeHeroes,{roster:ACTIVE_ROSTER,heroRuleRegistry:registry})(e.snapshot()));
const sha=p=>createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const report={result:'PASS emitted-only cold import and module graph',coldRoot:cold,emittedRoot:emitted,gameVersion:manifest.gameVersion,rosterId:ACTIVE_ROSTER.rosterId,heroIds:ACTIVE_ROSTER.heroIds,rulesHash:sealed.rulesHash,wireRulesetHash:GAME_COMPATIBILITY.rulesetHash,registryVersion:GAME_COMPATIBILITY.registryVersion,registrySHA256:GAME_COMPATIBILITY.registrySha256,graphModules:inputs.length,graphEdges:edges.length,externalEdges:0,sourceFallback:false,identical132Manifest:true,inputs:inputs.map(p=>({path:p,sha256:sha(path.join(cold,p))})),snapshotValidated:true,oneNodeProcess:true,realBrowser:false};
fs.writeFileSync(path.join(out,'cold-import.json'),JSON.stringify(report,null,2)+'\n');
fs.writeFileSync(path.join(out,'cold-metafile.json'),JSON.stringify(graph.metafile,null,2)+'\n');
process.env.RELEASE22_ROOT=cold;process.env.RELEASE22_REPORT=path.join(out,'emitted-mechanism-smoke.json');
await import('./release22-mechanism-smoke.mjs');
console.log(JSON.stringify({result:report.result,gameVersion:report.gameVersion,modules:inputs.length,edges:edges.length,externalEdges:0,coldRoot:cold}));
