import test from 'node:test';
import assert from 'node:assert/strict';
import {PeerSession} from '../src/p2p.js';
import {CASUAL_PVP_POLICY,ProbeWindow,qualityHint} from '../src/net-quality.js';
import {GAME_COMPATIBILITY} from '../src/compatibility.js';
import {ACTIVE_ROSTER,REGISTRY_VERSION} from '../src/hero-registry.js';
import {NET_VERSION} from '../src/net-version.js';

// Deterministic transport/server contract tests; not browser or SQL acceptance.
const flush=async()=>{for(let i=0;i<100;i++)await Promise.resolve();};
function pair({enter=true}={}){
 let now=0,count=0;const starts=[],calls=[],ready=[false,false];
 let room={id:'a'.repeat(64),version:NET_VERSION,rosterId:ACTIVE_ROSTER.rosterId,registryVersion:REGISTRY_VERSION,players:[{id:'b'.repeat(64),hero:1},{id:'c'.repeat(64),hero:1}],policy:CASUAL_PVP_POLICY};let match;
 const service=seat=>({async request(path,body,method){calls.push({seat,path,body,method});if(method==='DELETE')return {ok:true};if(path.endsWith('/selection')){if(body.action==='begin'){assert.equal(seat,0);if(match)assert(['confirmed','disputed','aborted'].includes(match.status));room.selection={epoch:body.epoch,previousEpoch:body.previousEpoch,previousMatchId:body.previousMatchId,locked:[false,false]};room.players.forEach(p=>p.hero=1);}else{assert.equal(body.epoch,room.selection.epoch);room.players[seat].hero=body.hero;room.selection.locked[seat]=true;}}return structuredClone(room);},async createMatch(id,requestId,selectionEpoch){calls.push({seat,path:'matches',selectionEpoch,requestId});assert(room.selection.locked.every(Boolean));assert.equal(selectionEpoch,room.selection.epoch);if(match?.selectionEpoch===selectionEpoch)return structuredClone(match);count++;ready.fill(false);match={id:String(count).repeat(64),roomId:id,version:NET_VERSION,rosterId:ACTIVE_ROSTER.rosterId,registryVersion:REGISTRY_VERSION,selectionEpoch,players:structuredClone(room.players),status:'awaiting_ready'};return structuredClone(match);},async ready(){ready[seat]=true;if(ready.every(Boolean))match.status='in_progress';return structuredClone(match);},async getMatch(){return structuredClone(match);}});
 const make=(role,seat)=>{const p=new PeerSession({role,hero:1,policy:{...CASUAL_PVP_POLICY},roomFirst:true,service:service(seat),onstart:m=>starts.push({role,...m})});p.connected=true;p.peerVersion=NET_VERSION;p.peerCompatibility=GAME_COMPATIBILITY;p.peerHero=1;p.roomId=room.id;p.lastControlSeen=performance.now();p.later=()=>{};p.control={readyState:'open',bufferedAmount:0,close(){}};p.frames={readyState:'open',bufferedAmount:0,send(){},close(){}};p.draft.now=()=>now;// This protocol-only fixture models already-decoded current images.
 p.onstate=()=>{p.draft.setMaterials(true);if(enter)p.draft.enter();};return p;};
 const h=make('host',0),g=make('guest',1);
 h.control.send=v=>queueMicrotask(()=>g.receive(v,'control'));g.control.send=v=>queueMicrotask(()=>h.receive(v,'control'));
 return {h,g,starts,calls,get room(){return room;},get match(){return match;},terminal(){match.status='confirmed';h.draft.finish();g.draft.finish();},async tick(ms=0){now+=ms;h.draft.tick();g.draft.tick();await flush();},close(){h.shutdown();g.shutdown();}};
}
test('native channels and exact hello permit selection without a probe sample; ordinary jitter is only a hint',()=>{const p=pair();try{assert(p.h.gate().ok);assert.equal(qualityHint(p.h.probes.summary(performance.now())),'网络检测中');p.h.peerQuality={samples:3,received:2,median:450,p95:900,jitter:500,loss:33};assert(p.h.gate().ok);assert.equal(qualityHint(p.h.peerQuality),'网络波动，操作可能延迟');p.h.control.readyState='closed';assert(!p.h.gate().ok);}finally{p.close();}});
test('countdown starts only after both selection UIs acknowledge entry; timeout uses default legal heroes and backend ready',async()=>{const p=pair({enter:false});try{await p.tick();assert.equal(p.h.draft.phase,'selecting');assert.equal(p.g.draft.phase,'selecting');await p.tick(25000);assert.equal(p.h.draft.deadline,null);p.h.draft.enter();p.g.draft.enter();await flush();await p.tick();assert.equal(p.h.draft.remaining,20000);await p.tick(19999);assert.equal(p.starts.length,0);await p.tick(1);await p.tick();assert.equal(p.starts.length,2);assert.deepEqual(p.match.players.map(x=>x.hero),[1,1]);assert.equal(p.match.status,'in_progress');assert.equal(p.h.seenEpoch,p.g.seenEpoch);}finally{p.close();}});
test('both explicit locks start early once and snapshot the chosen heroes in immutable server match players',async()=>{const p=pair();try{await p.tick();await p.tick();assert(p.h.draft.choose(3));assert(p.g.draft.choose(8));await flush();await Promise.all([p.h.setReady(),p.g.setReady()]);await flush();await p.tick(1000);assert.equal(p.starts.length,2);assert.deepEqual(p.match.players.map(x=>x.hero),[3,8]);assert.equal(p.calls.filter(c=>c.path==='matches').length,1);assert(!p.h.draft.choose(4));}finally{p.close();}});
test('timeout/manual lock race deduplicates each authenticated lock and rejects old epoch previews',async()=>{const p=pair();try{await p.tick();await p.tick();const epoch=p.h.draft.epoch;p.h.draft.receive({action:'pick',epoch:'old',hero:8,revision:999});assert.equal(p.h.peerHero,1);const lock=p.g.setReady();await p.tick(20000);await lock;await p.tick();assert.equal(p.calls.filter(c=>c.body?.action==='lock'&&c.seat===1).length,1);assert.equal(p.starts.length,2);p.h.receive(JSON.stringify({type:'selection',action:'locked',epoch:'old',hero:8}),'control');assert.equal(p.h.peerHero,1);assert.equal(p.match.selectionEpoch,epoch);}finally{p.close();}});
test('background pauses remaining time, restores the same clock, and latency warning never resets it',async()=>{const p=pair();try{await p.tick();await p.tick();await p.tick(5000);p.g.setForeground(false);await flush();await p.tick();const left=p.h.draft.remaining;assert.equal(left,15000);await p.tick(45000);assert.equal(p.h.draft.remaining,left);p.g.setForeground(true);await flush();await p.tick();assert.equal(p.h.draft.remaining,left);p.h.peerQuality={p95:1000,jitter:500,loss:40};await p.tick(1000);assert.equal(p.h.draft.remaining,14000);}finally{p.close();}});
test('same-room rematch waits for both consent and terminal result, creates a fresh selection/match epoch, and ignores old preparation',async()=>{const p=pair();try{await p.tick();await p.tick();await Promise.all([p.h.setReady(),p.g.setReady()]);await p.tick();const old=structuredClone(p.match),oldEpoch=p.h.draft.epoch;p.h.draft.finish();p.g.draft.finish();p.h.draft.requestRematch();await p.tick();assert.equal(p.h.draft.epoch,oldEpoch);p.g.draft.requestRematch();await flush();await p.tick();assert.equal(p.h.draft.epoch,oldEpoch,'in_progress previous match blocks new draft');p.terminal();await p.tick(2000);await p.tick();assert.notEqual(p.h.draft.epoch,oldEpoch);assert.equal(p.h.roomId,old.roomId);p.h.draft.choose(4);p.g.draft.choose(8);await flush();p.g.receive(JSON.stringify({type:'prepare',epoch:'late',selectionEpoch:oldEpoch,matchId:old.id}),'control');assert.equal(p.g.pendingEpoch,null);await Promise.all([p.h.setReady(),p.g.setReady()]);await p.tick();assert.notEqual(p.match.id,old.id);assert.deepEqual(old.players.map(x=>x.hero),[1,1]);assert.deepEqual(p.match.players.map(x=>x.hero),[4,8]);assert.equal(p.starts.length,4);}finally{p.close();}});
test('casual probes retain a short rolling window and show missing samples instead of synthetic zero RTT',()=>{const p=new ProbeWindow({window:12,timeoutMs:3000});const id=p.sent(0);assert.equal(p.summary(1).median,null);assert.equal(qualityHint(p.summary(1)),'网络检测中');assert(p.pong(id,1800));assert.equal(p.summary(1801).median,1800);for(let i=1;i<20;i++){const n=p.sent(i*350);p.pong(n,i*350+50);}assert.equal(p.summary(10000).samples,12);assert(!p.pong(id,2200));});
test('controlled frame loss and long probe RTT do not veto reliable selection, while control failure does',async()=>{const p=pair();try{p.h.probes.rows=[{id:1,sent:performance.now()-2000,rtt:900,received:performance.now()-1100},{id:2,sent:performance.now()-4000,rtt:null,received:null}];p.h.peerQuality={samples:2,received:1,median:900,p95:900,jitter:650,loss:50};p.h.frames.send=()=>{};assert(p.h.gate().ok);await p.tick();await p.tick();assert.equal(p.h.draft.phase,'selecting');p.h.lastControlSeen=performance.now()-10001;assert(!p.h.gate().ok);p.h.tick();assert(p.h.stopped);assert.equal(p.h.draft.phase,'failed');}finally{p.close();}});
test('severe control backlog blocks preparation and sustained six-second congestion releases the room',()=>{const p=pair();try{p.h.control.bufferedAmount=262145;assert(!p.h.gate().ok);p.h.congestedAt=performance.now()-6001;p.h.tick();assert(p.h.stopped);assert.equal(p.h.error,'可靠连接持续拥塞');assert.equal(p.calls.filter(x=>x.method==='DELETE').length,1);}finally{p.close();}});

// Explicit injected stale/duplicate messages; this is not a natural device/network reproduction.
test('material proof requires current epoch and both heroes; stale availability cannot reopen the gate',async()=>{const p=pair();try{await p.tick();await p.tick();const epoch=p.h.draft.epoch;p.g.onstate=()=>p.g.draft.enter();p.g.draft.setMaterials(false);await flush();assert(!p.h.gate().ok);assert(!p.g.gate().ok);const proof=structuredClone(p.g.draft.materials);p.h.receive(JSON.stringify({type:'availability',value:true}),'control');assert(!p.h.gate().ok,'bare availability is insufficient');for(const fields of [{epoch:'00000000-0000-4000-8000-000000000000'},{hero:82},{peerHero:82},{revision:proof.revision}]){p.h.receive(JSON.stringify({type:'selection',action:'materials',...proof,...fields,ready:true}),'control');assert(!p.h.gate().ok);}await p.tick(45000);assert.equal(p.starts.length,0);assert.equal(p.calls.filter(c=>c.path==='matches').length,0);p.g.draft.setMaterials(true);await flush();assert(p.h.gate().ok);await Promise.all([p.h.setReady(),p.g.setReady()]);await p.tick();assert.equal(p.starts.length,2);assert.equal(p.h.seenEpoch,p.g.seenEpoch);const count=p.starts.length;for(let i=0;i<3;i++)p.h.receive(JSON.stringify({type:'selection',action:'materials',...p.g.draft.materials}),'control');await p.tick();assert.equal(p.starts.length,count);assert.equal(p.match.selectionEpoch,epoch);}finally{p.close();}});
test('changing either hero invalidates both proofs until the exact new pair has decoded',async()=>{const p=pair();try{await p.tick();await p.tick();p.g.onstate=()=>p.g.draft.enter();const old=structuredClone(p.g.draft.materials);assert(p.g.draft.choose(8));await flush();assert(!p.h.gate().ok);assert(!p.g.gate().ok);p.h.receive(JSON.stringify({type:'selection',action:'materials',...old,revision:old.revision+100}),'control');assert(!p.h.gate().ok);p.g.draft.setMaterials(true);await flush();assert(p.h.gate().ok);assert(p.g.gate().ok);assert.equal(p.g.draft.materials.hero,8);assert.equal(p.g.draft.materials.peerHero,1);assert(p.h.draft.choose(3));await flush();assert(!p.h.gate().ok);p.g.draft.setMaterials(true);await flush();assert(p.h.gate().ok);assert(p.g.gate().ok);}finally{p.close();}});
test('cancelled selection ignores late material proof; rematch resets epoch and prevents old ready/start replay',async()=>{const p=pair();try{await p.tick();await p.tick();await Promise.all([p.h.setReady(),p.g.setReady()]);await p.tick();const oldProof=structuredClone(p.g.draft.materials),oldMatch=structuredClone(p.match);p.terminal();p.h.draft.requestRematch();p.g.draft.requestRematch();await flush();p.g.onstate=()=>p.g.draft.enter();await p.tick(2000);await p.tick();assert.notEqual(p.h.draft.epoch,oldProof.epoch);assert(!p.h.gate().ok);p.h.receive(JSON.stringify({type:'selection',action:'materials',...oldProof,revision:999}),'control');assert(!p.h.gate().ok);p.g.receive(JSON.stringify({type:'start',epoch:'old-start',selectionEpoch:oldProof.epoch,matchId:oldMatch.id}),'control');await flush();assert.equal(p.starts.length,2);p.g.draft.setMaterials(true);await flush();await Promise.all([p.h.setReady(),p.g.setReady()]);await p.tick();assert.equal(p.starts.length,4);assert.equal(p.h.seenEpoch,p.g.seenEpoch);p.g.close();p.g.receive(JSON.stringify({type:'selection',action:'materials',...p.h.draft.materials}),'control');assert(p.g.stopped);assert.equal(p.g.draft.phase,'failed');assert.equal(p.g.draft.peerMaterials,null);}finally{p.close();}});
