import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import fs from 'node:fs';import worker from '../worker/index.js';import {adapter} from '../scripts/sqlite-d1.mjs';
function app(){const db=new DatabaseSync(':memory:');for(const f of fs.readdirSync(new URL('../drizzle/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())db.exec(fs.readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));return {db,call:async(path,method='GET',body,who='host'.repeat(16),origin='https://duel.test')=>{const r=await worker.fetch(new Request('https://duel.test/api/p2p/'+path,{method,headers:{Authorization:'Bearer '+who,'Content-Type':'application/json',Origin:origin},...(body?{body:JSON.stringify(body)}:{})}),{DB:adapter(db)});return {status:r.status,data:await r.json()};}};}
const offer={type:'offer',sdp:'v=0\r\ntest'},answer={type:'answer',sdp:'v=0\r\nanswer'},body={offer,version:'v1',policy:{direction:'above',rttMs:100}};
test('signaling exchanges only SDP, protects host reads and atomically rejects a third player',async()=>{const a=app();const created=await a.call('rooms','POST',body);assert.equal(created.status,201);const path='rooms/'+created.data.code;assert.equal((await a.call(path)).data.version,'v1');const results=await Promise.all(['guest1','guest2'].map(t=>a.call(path+'/answer','POST',{answer,version:'v1'},t.repeat(12))));assert.deepEqual(results.map(x=>x.status).sort(),[200,409]);assert.equal((await a.call(path+'/answer','GET',null,'intruder'.repeat(8))).status,403);assert.deepEqual((await a.call(path+'/answer')).data.answer,answer);assert.equal((await a.call(path,'GET',null,'third'.repeat(16))).status,409);assert.equal(a.db.prepare('SELECT COUNT(*) n FROM p2p_rooms').get().n,1);a.db.close();});
test('room expiry, version mismatch, origin checks, invalid input and host deletion fail safely',async()=>{const a=app();assert.equal((await a.call('rooms','POST',body,undefined,'https://other.test')).status,403);assert.equal((await a.call('rooms','POST',{...body,offer:{}})).status,400);const c=await a.call('rooms','POST',body),p='rooms/'+c.data.code;assert.equal((await a.call(p+'/answer','POST',{answer,version:'v0'},'guest'.repeat(16))).status,409);assert.equal((await a.call(p,'DELETE',null,'guest'.repeat(16))).status,403);a.db.prepare('UPDATE p2p_rooms SET expires=0').run();assert.equal((await a.call(p)).status,404);const n=await a.call('rooms','POST',body);assert.equal(a.db.prepare('SELECT COUNT(*) n FROM p2p_rooms').get().n,1);assert.equal((await a.call('rooms/'+n.data.code,'DELETE')).status,200);a.db.close();});
test('missing platform DB gives a clear recoverable 503',async()=>{const r=await worker.fetch(new Request('https://duel.test/api/p2p/health'),{});assert.equal(r.status,503);});
test('claimed answer is immutable, exact retry is idempotent and raw tokens never enter DB or responses',async()=>{const a=app(),c=await a.call('rooms','POST',body),p='rooms/'+c.data.code,g='guest'.repeat(16);assert.match(c.data.code,/^[ABCDEFGHJKLMNPQRSTUVWXYZ23456789]{10}$/);assert.equal((await a.call(p+'/answer','POST',{answer,version:'v1'},g)).status,200);assert.equal((await a.call(p+'/answer','POST',{answer,version:'v1'},g)).status,200);assert.equal((await a.call(p+'/answer','POST',{answer:{...answer,sdp:'v=0\r\nchanged'},version:'v1'},g)).status,409);const row=a.db.prepare('SELECT * FROM p2p_rooms').get();assert.equal(row.answer,JSON.stringify(answer));assert(!JSON.stringify(row).includes(g));assert.equal(row.guest_hash.length,64);assert(!JSON.stringify((await a.call(p+'/answer')).data).includes('hash'));a.db.close();});
test('expiry is physically cleaned on room read, including exact TTL boundary',async()=>{const a=app(),c=await a.call('rooms','POST',body);a.db.prepare('UPDATE p2p_rooms SET expires=?').run(Date.now());assert.equal((await a.call('rooms/'+c.data.code)).status,404);assert.equal(a.db.prepare('SELECT COUNT(*) n FROM p2p_rooms').get().n,0);a.db.close();});
test('shared rate budget bounds creation and guessing even with rotated bearer tokens',async()=>{const a=app();for(let i=0;i<6;i++)assert.equal((await a.call('rooms','POST',body,String(i).repeat(40))).status,201);assert.equal((await a.call('rooms','POST',body)).status,429);a.db.prepare('DELETE FROM p2p_limits').run();for(let i=0;i<120;i++)assert.equal((await a.call('rooms/AAAAAAAAAA','GET',null,String(i).padStart(40,'x'))).status,404);assert.equal((await a.call('rooms/AAAAAAAAAA')).status,429);assert.equal(a.db.prepare('SELECT COUNT(*) n FROM p2p_limits').get().n,1);a.db.close();});
test('unknown-length streaming payload is canceled after byte cap',async()=>{const a=app();let canceled=false;const stream=new ReadableStream({pull(c){c.enqueue(new Uint8Array(16000));},cancel(){canceled=true;}});const r=await worker.fetch(new Request('https://duel.test/api/p2p/rooms',{method:'POST',headers:{Authorization:'Bearer '+'host'.repeat(16)},body:stream,duplex:'half'}),{DB:adapter(a.db)});assert.equal(r.status,413);assert(canceled);assert.equal(a.db.prepare('SELECT COUNT(*) n FROM p2p_rooms').get().n,0);a.db.close();});
test('room capacity is enforced by conditional insertion',async()=>{const a=app();for(let i=0;i<100;i++)a.db.prepare('INSERT INTO p2p_rooms (code,host_hash,offer,version,policy,created,expires) VALUES (?,?,?,?,?,?,?)').run(String(i),'h','{}','v','{}',Date.now(),Date.now()+600000);assert.equal((await a.call('rooms','POST',body)).status,429);assert.equal(a.db.prepare('SELECT COUNT(*) n FROM p2p_rooms').get().n,100);a.db.close();});
