// Controlled DOM/stream/clock fixtures. These are not browser pixels or iOS tests.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';import{createHash}from'node:crypto';
const html=fs.readFileSync('index.html','utf8'),code=html.match(/<script id="startup-bootstrap">([\s\S]*?)<\/script>/)[1];
const sha=b=>createHash('sha256').update(b).digest('hex');
function payload(text='window.FIGHTER_TEXT="水晶室女";'){const bytes=Buffer.from(text),bodies=[],parts=[];for(let i=0;i<bytes.length;i+=13){const body=bytes.subarray(i,i+13);bodies.push(body);parts.push({src:'/part'+parts.length,bytes:body.length,sha256:sha(body)});}return {config:{bytes:bytes.length,sha256:sha(bytes),parts},bodies,bytes};}
function fixture({fetcher,cookie='',storage=null,offline=false,online=true}={}){
 const nodes={},appended=[],frames=[],timers=new Map(),events={},requests=[],urls=new Map();let now=0,reloads=0,next=0;
 function node(tag='div',id=''){return{tagName:tag.toUpperCase(),id,hidden:id==='startup-retry'||id==='startup-pause',attrs:{},textContent:'',setAttribute(k,v){this.attrs[k]=v;},removeAttribute(k){delete this[k];delete this.attrs[k];},remove(){this.removed=true;if(nodes[this.id]===this)delete nodes[this.id];}};}
 for(const id of ['startup-loading','startup-progress','startup-status','startup-hint','startup-retry','startup-pause','startup-style'])nodes[id]=node(id==='startup-style'?(offline?'style':'link'):'div',id);
 nodes['startup-style'].href='src/style.css';const root=nodes['startup-loading'];const document={cookie,getElementById:id=>nodes[id],createElement:tag=>node(tag),body:{appendChild(n){appended.push(n);if(n.id)nodes[n.id]=n;return n;}}};
 const ctx={document,navigator:{onLine:online},crypto:globalThis.crypto,AbortController,Uint8Array,Blob,Array,Promise,Date:class extends Date{static now(){return now;}},URL:{createObjectURL(blob){const id='blob:test/'+urls.size;urls.set(id,blob);return id;},revokeObjectURL(id){urls.delete(id);}},localStorage:{getItem:()=>storage},location:{reload(){reloads++;}},fetch:async(url,opts)=>{requests.push({url,signal:opts.signal,cache:opts.cache});return fetcher(url,opts,requests.length);},addEventListener(k,f){(events[k]??=[]).push(f);},removeEventListener(k,f){events[k]=(events[k]||[]).filter(x=>x!==f);},requestAnimationFrame:f=>frames.push(f),setTimeout(f,ms){timers.set(++next,{f,at:now+ms});return next;},clearTimeout:id=>timers.delete(id)};
 ctx.window=ctx;const realmWindow=vm.runInNewContext(code+'\nwindow;',ctx);
 return{ctx,nodes,root,appended,requests,urls,boot:ctx.DOTA_STARTUP,get reloads(){return reloads;},frame(){frames.splice(0).forEach(f=>f());},advance(ms){now+=ms;const due=[...timers].filter(([,v])=>v.at<=now);for(const[id,t]of due){timers.delete(id);t.f();}},emit(k,e){(events[k]||[]).forEach(f=>f({...e,target:e.target===ctx?realmWindow:e.target}));}};
}
const flush=async()=>{for(let i=0;i<6;i++)await new Promise(resolve=>setImmediate(resolve));};
async function toScript(f){for(let i=0;i<40&&!f.appended.some(n=>n.tagName==='SCRIPT');i++){await flush();f.frame();}assert(f.appended.some(n=>n.tagName==='SCRIPT'));return f.appended.find(n=>n.tagName==='SCRIPT');}
const stream=body=>new Response(new ReadableStream({start(c){c.enqueue(body.subarray(0,2));c.enqueue(body.subarray(2));c.close();}}),{headers:{'content-length':'2','content-encoding':'gzip'}});
test('inline loading precedes stylesheet and app; progress has no invented task percentages',()=>{const order=['id="startup-critical"','id="startup-loading"','id="startup-bootstrap"','id="startup-style"','id="app"','id="startup-app"'].map(s=>html.indexOf(s));assert(order.every((p,i)=>p>=0&&(!i||p>order[i-1])));assert.match(html,/<progress[^>]+max="100"[^>]*><\/progress>/);assert.doesNotMatch(code,/45000|Math\.random|setInterval/);assert.doesNotMatch(fs.readFileSync('src/style.css','utf8'),/@import/);});
test('no fixed45s failure; idle hint keeps the request active, then90s idle pauses rather than fails',async()=>{const p=payload(),f=fixture({fetcher:()=>new Promise(()=>{})});f.boot.start(p.config);await flush();f.advance(46000);assert.equal(f.boot.info().phase,'downloading');assert.equal(f.nodes['startup-retry'].hidden,false);assert.equal(f.requests[0].signal.aborted,false);assert(f.nodes['startup-hint'].textContent.includes('仍在继续'));f.advance(44000);assert.equal(f.boot.info().phase,'paused');assert.equal(f.requests[0].signal.aborted,true);assert.equal(f.reloads,0);});
test('decoded streamed bytes use pinned build size, not compressed Content-Length;100 only after UI+styles',async()=>{const p=payload();let controller;const f=fixture({fetcher:(url)=>url==='/part0'?Promise.resolve(new Response(new ReadableStream({start(c){controller=c;}}),{headers:{'content-length':'1'}})):stream(p.bodies[+url.slice(5)])});f.boot.stylesReady();f.boot.start(p.config);await flush();controller.enqueue(p.bodies[0].subarray(0,4));await flush();assert.equal(f.boot.info().received,4);assert.equal(f.nodes['startup-progress'].value,4/p.bytes.length*100);f.advance(50000);assert.equal(f.boot.info().phase,'downloading');controller.enqueue(p.bodies[0].subarray(4));controller.close();const s=await toScript(f);assert.equal(f.boot.info().phase,'initializing');assert.equal(f.nodes['startup-progress'].value,undefined);assert.equal(await f.urls.get(s.src).text(),p.bytes.toString());f.boot.appReady();assert.equal(f.nodes['startup-progress'].value,100);f.frame();f.frame();assert(f.root.removed);assert.equal(f.urls.size,0);});
test('true interrupted body retains completed parts; retry immediately responds and fetches only missing parts',async()=>{const p=payload();let broken=true;const f=fixture({fetcher:url=>{const i=+url.slice(5);if(i===1&&broken)return new Response(new ReadableStream({start(c){c.enqueue(p.bodies[i].subarray(0,2));c.error(Error('fixture interrupted'));}}));return stream(p.bodies[i]);}});f.boot.stylesReady();f.boot.start(p.config);for(let i=0;i<25&&f.boot.info().phase!=='failed';i++)await flush();assert.equal(f.boot.info().phase,'failed');assert.equal(f.boot.info().retainedParts,1);assert.equal(f.reloads,0);broken=false;f.nodes['startup-retry'].onclick();assert.equal(f.boot.info().phase,'downloading');assert.equal(f.nodes['startup-retry'].hidden,true);assert(f.nodes['startup-hint'].textContent.includes('正在重试'));await toScript(f);assert.equal(f.requests.filter(x=>x.url==='/part0').length,1);assert.equal(f.requests.filter(x=>x.url==='/part1').length,2);f.boot.appReady();assert.equal(f.boot.info().phase,'ready');});
test('cancel/retry aborts old fetch and ignores its late success without duplicate evaluation',async()=>{const p=payload();let release;const f=fixture({fetcher:(url,opts,n)=>n===1?new Promise(resolve=>release=resolve):stream(p.bodies[+url.slice(5)])});f.boot.start(p.config);await flush();f.advance(13000);f.nodes['startup-retry'].onclick();assert(f.requests[0].signal.aborted);release(stream(Buffer.from('stale-invalid')));await toScript(f);assert.equal(f.appended.filter(n=>n.tagName==='SCRIPT').length,1);assert.equal(f.boot.info().phase,'initializing');});
test('pause is interactive, cancels in-flight work and continues from completed fragments',async()=>{const p=payload();let block=true;const f=fixture({fetcher:url=>+url.slice(5)===1&&block?new Promise(()=>{}):stream(p.bodies[+url.slice(5)])});f.boot.start(p.config);for(let i=0;i<20&&f.requests.length<2;i++)await flush();f.nodes['startup-pause'].onclick();assert.equal(f.boot.info().phase,'paused');assert(f.requests[1].signal.aborted);assert.equal(f.nodes['startup-retry'].textContent,'继续加载');block=false;f.nodes['startup-retry'].onclick();await toScript(f);assert.equal(f.requests.filter(x=>x.url==='/part0').length,1);});
for(const kind of ['HTTP','truncated','digest'])test(kind+' error is real and explicit; no silent retry or auto reload',async()=>{const p=payload(),body=kind==='truncated'?p.bodies[0].subarray(0,2):Buffer.alloc(p.bodies[0].length);const f=fixture({fetcher:()=>kind==='HTTP'?new Response('error',{status:503}):stream(body)});f.boot.start(p.config);for(let i=0;i<20&&f.boot.info().phase!=='failed';i++)await flush();assert.equal(f.boot.info().phase,'failed');assert.equal(f.nodes['startup-retry'].hidden,false);assert.equal(f.requests.length,1);assert.equal(f.reloads,0);assert.equal(f.boot.info().retainedParts,0);});
test('active ongoing byte progress is not failed or paused by elapsed startup duration',async()=>{const p=payload();let controller;const f=fixture({fetcher:()=>new Response(new ReadableStream({start(c){controller=c;}}))});f.boot.start(p.config);await flush();for(let i=0;i<4;i++){f.advance(11000);controller.enqueue(p.bodies[0].subarray(i,i+1));await flush();}assert.equal(f.boot.info().phase,'downloading');assert.equal(f.requests[0].signal.aborted,false);assert.equal(f.nodes['startup-hint'].textContent,'');});
test('stylesheet-only failure after app init retries CSS without reload or another app evaluation',async()=>{const f=fixture();f.boot.appReady();f.boot.fail('styles');f.nodes['startup-retry'].onclick();assert.equal(f.reloads,0);const link=f.appended.find(n=>n.tagName==='LINK');assert(link);link.onload();f.frame();f.frame();assert(f.root.removed);});
test('late stylesheet success removes overlay after UI-ready without failure timer',()=>{const f=fixture();f.boot.appReady();f.advance(50000);assert.equal(f.boot.info().phase,'styles');f.boot.stylesReady();f.frame();f.frame();assert(f.root.removed);assert.equal(f.reloads,0);});
test('initialization failure offers immediate explicit reopen once; no double evaluation',async()=>{const p=payload(),f=fixture({fetcher:url=>stream(p.bodies[+url.slice(5)])});f.boot.start(p.config);const s=await toScript(f);s.onerror();assert.equal(f.nodes['startup-retry'].textContent,'重新打开');f.nodes['startup-retry'].onclick();f.nodes['startup-retry'].onclick();assert.equal(f.reloads,1);assert.equal(f.appended.filter(n=>n.tagName==='SCRIPT').length,1);});
test('active room/battle retry never reloads',()=>{for(const state of [{screen:'battle',room:null},{screen:'select',room:{code:'000123'}}]){const f=fixture();f.ctx.DUEL={state};f.boot.fail('initialization');f.nodes['startup-retry'].onclick();assert.equal(f.reloads,0);}});
test('offline failure is distinct; preferences and offline inline success remain intact',()=>{const f=fixture({online:false,cookie:'dota-duel-language=en',storage:'zh'});f.boot.fail('download');assert.match(f.nodes['startup-status'].textContent,/offline/);assert.equal(f.boot.info().language,'en');const off=fixture({offline:true,storage:'en'});off.boot.appReady();off.frame();off.frame();assert(off.root.removed);assert.equal(off.requests.length,0);});
test('safe areas and first app hook remain independent from registry/material requests',()=>{const critical=html.match(/<style id="startup-critical">([\s\S]*?)<\/style>/)[1];for(const side of ['top','right','bottom','left'])assert(critical.includes('safe-area-inset-'+side));const app=fs.readFileSync('src/app.js','utf8');assert.match(app,/\nselection\(\);\nwindow\.DOTA_STARTUP\?\.appReady\(\);/);assert.match(app,/let releasedHeroRules;/);assert.doesNotMatch(app,/const releasedHeroRules=HEROS22_BUILD/);});
test('built fragments reconstruct one parseable exact compact entry, pinned SHA and all refs exist',()=>{const manifest=JSON.parse(fs.readFileSync('dist/client/build-manifest.json'));const joined=Buffer.concat(manifest.startup.parts.map(p=>{const b=fs.readFileSync('dist/client/'+p.src);assert.equal(b.length,p.bytes);assert.equal(sha(b),p.sha256);return b;}));assert.equal(joined.length,manifest.startup.bytes);assert.equal(sha(joined),manifest.startup.sha256);assert(joined.equals(fs.readFileSync('dist/client/'+manifest.entry.script)));new vm.Script(joined.toString());const built=fs.readFileSync('dist/client/index.html','utf8');assert.doesNotMatch(built,/<script[^>]+src=/);assert.match(built,/id="startup-config"/);assert.match(built,/id="startup-launch"/);assert.equal(manifest.gameVersion,'duel-64714553cccdaf8cc362');});

test('actual whole-app HTTP stream keeps five verified checkpoints after controlled interruption and resumes missing parts',async()=>{
 const manifest=JSON.parse(fs.readFileSync('dist/client/build-manifest.json')),calls=[],config=manifest.startup;let breakOnce=true;
 const f=fixture({fetcher:async(url,opts)=>{calls.push(url);const response=await fetch('http://127.0.0.1:4196/'+url,{signal:opts.signal});assert.equal(response.status,200);const upstream=response.body.getReader();let received=0;return new Response(new ReadableStream({async pull(c){try{const next=await upstream.read();await new Promise(resolve=>setTimeout(resolve,2));received+=next.value?.byteLength||0;if(url===config.src&&breakOnce&&received>config.parts.slice(0,5).reduce((n,p)=>n+p.bytes,0)+65536){breakOnce=false;await upstream.cancel();c.error(Error('controlled HTTP interruption, not natural network'));return;}if(next.done)c.close();else c.enqueue(next.value);}catch(e){c.error(e);}},cancel(){return upstream.cancel();}}),{headers:response.headers});}});
 f.boot.stylesReady();f.boot.start(config);for(let i=0;i<2000&&f.boot.info().phase!=='failed';i++)await new Promise(resolve=>setTimeout(resolve,2));
 assert.equal(f.boot.info().phase,'failed');assert.equal(f.boot.info().retainedParts,5);f.nodes['startup-retry'].onclick();let script;for(let i=0;i<3000&&!script;i++){await new Promise(resolve=>setTimeout(resolve,2));f.frame();script=f.appended.find(n=>n.tagName==='SCRIPT');}assert(script);const actual=Buffer.from(await f.urls.get(script.src).arrayBuffer());assert.equal(sha(actual),config.sha256);assert.equal(calls.length,1+config.parts.length-5);assert.equal(calls[0],config.src);assert.equal(calls.filter(x=>x===config.src).length,1);assert.equal(calls.filter(x=>x===config.parts[0].src).length,0);assert.equal(calls.filter(x=>x===config.parts[5].src).length,1);f.boot.appReady();assert.equal(f.boot.info().phase,'ready');
});
test('arrayBuffer-only fallback counts completed decoded content without inventing stream progress',async()=>{const p=payload(),f=fixture({fetcher:url=>({ok:true,arrayBuffer:async()=>Uint8Array.from(p.bodies[+url.slice(5)]).buffer})});f.boot.start(p.config);await toScript(f);assert.equal(f.boot.info().received,p.bytes.length);assert.equal(f.boot.info().phase,'initializing');});
test('source/offline initialization exception before configured download is explicit',()=>{const f=fixture({offline:true});f.emit('error',{target:f.ctx});assert.equal(f.boot.info().phase,'failed');assert.equal(f.nodes['startup-retry'].textContent,'重新打开');});
test('corrupt cached part is explicitly revalidated on retry; verified parts remain reusable',async()=>{const p=payload();let bad=true;const f=fixture({fetcher:url=>stream(bad?Buffer.alloc(p.bodies[0].length):p.bodies[+url.slice(5)])});f.boot.start(p.config);for(let i=0;i<20&&f.boot.info().phase!=='failed';i++)await flush();bad=false;f.nodes['startup-retry'].onclick();await toScript(f);assert.equal(f.requests[0].cache,'default');assert.equal(f.requests[1].cache,'reload');});

test('normal cold/warm stream uses one full app request and verifies checkpoints across UTF8 byte boundaries',async()=>{const p=payload();p.config.src='/app.js';const f=fixture({fetcher:url=>{assert.equal(url,'/app.js');return stream(p.bytes);}});f.boot.stylesReady();f.boot.start(p.config);const script=await toScript(f);assert.equal(f.requests.length,1);assert.equal(await f.urls.get(script.src).text(),p.bytes.toString());f.boot.appReady();assert.equal(f.boot.info().received,p.bytes.length);assert.equal(f.boot.info().phase,'ready');});
test('whole download EOF/error preserves complete checkpoints and retry uses only fragment URLs',async()=>{const p=payload();p.config.src='/app.js';const f=fixture({fetcher:url=>url==='/app.js'?stream(p.bytes.subarray(0,p.bodies[0].length+3)):stream(p.bodies[+url.slice(5)])});f.boot.start(p.config);for(let i=0;i<20&&f.boot.info().phase!=='failed';i++)await flush();assert.equal(f.boot.info().retainedParts,1);f.nodes['startup-retry'].onclick();await toScript(f);assert.equal(f.requests.filter(r=>r.url==='/app.js').length,1);assert.equal(f.requests.filter(r=>r.url==='/part0').length,0);});
