// Native-resource event/source fixtures, not browser cache, navigation or pixel measurements.
import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const html=fs.readFileSync('index.html','utf8'),code=html.match(/<script id="startup-bootstrap">([\s\S]*?)<\/script>/)[1];
function fixture({cookie='',storage=null,offline=false,online=true,blocked=false}={}){
 const nodes={},frames=[],timers=new Map(),events={},appended=[];let now=0,next=0,reloads=0;const mainURL='https://dotapk.lol/src/app.fixture.js';
 function node(tag='div',id=''){return {tagName:tag.toUpperCase(),id,hidden:id==='startup-retry',attrs:{},textContent:'',setAttribute(k,v){this.attrs[k]=v;},removeAttribute(k){delete this[k];delete this.attrs[k];},remove(){this.removed=true;if(nodes[this.id]===this)delete nodes[this.id];}};}
 for(const id of ['startup-loading','startup-progress','startup-status','startup-hint','startup-retry','startup-style','startup-app'])nodes[id]=node(id==='startup-style'?(offline?'style':'link'):id==='startup-app'?'script':'div',id);
 nodes['startup-style'].href='https://dotapk.lol/src/style.fixture.css';nodes['startup-app'].src=mainURL;const root=nodes['startup-loading'];
 const document={get cookie(){if(blocked)throw Error('cookie unavailable');return cookie;},getElementById:id=>nodes[id],createElement:tag=>node(tag),body:{appendChild(n){appended.push(n);if(n.id)nodes[n.id]=n;return n;}}};
 const ctx={document,navigator:{onLine:online},Date:class extends Date{static now(){return now;}},localStorage:{getItem(){if(blocked)throw Error('storage unavailable');return storage;}},location:{reload(){reloads++;}},fetch(){throw Error('loader must not fetch app');},Blob:class{constructor(){throw Error('loader must not allocate app blob');}},addEventListener(k,f){(events[k]??=[]).push(f);},removeEventListener(k,f){events[k]=(events[k]||[]).filter(x=>x!==f);},requestAnimationFrame:f=>frames.push(f),setTimeout(f,ms){timers.set(++next,{f,at:now+ms});return next;},clearTimeout:id=>timers.delete(id)};
 Object.defineProperty(ctx,'crypto',{get(){throw Error('loader must not require crypto');}});ctx.window=ctx;const realm=vm.runInNewContext(code+'\nwindow;',ctx);
 return {ctx,nodes,root,frames,timers,events,appended,boot:ctx.DOTA_STARTUP,get reloads(){return reloads;},frame(){frames.splice(0).forEach(f=>f());},advance(ms){now+=ms;for(const[id,t]of [...timers])if(t.at<=now){timers.delete(id);t.f();}},emit(k,e={}){(events[k]||[]).forEach(f=>f({...e,target:e.target===ctx?realm:e.target}));}};
}
test('HTML exposes lightweight feedback before native stylesheet and stable module script',()=>{const order=['id="startup-critical"','id="startup-loading"','id="startup-bootstrap"','id="startup-style"','id="app"','id="startup-app"'].map(s=>html.indexOf(s));assert(order.every((p,i)=>p>=0&&(!i||p>order[i-1])));assert.match(html,/<script id="startup-app" type="module" src="src\/app.js"/);assert.doesNotMatch(html,/startup-config|startup-launch|startup-pause/);assert(Buffer.byteLength(code)<8500);});
test('feedback is observational: no fetch, hashing, bytes, Blob, module injection or synthetic percentage',()=>{assert.doesNotMatch(code,/fetch\(|digest\(|crypto|Blob|createObjectURL|AbortController|arrayBuffer|createElement\('script'\)|45000|Math\.random|\.src=/);assert.match(html,/<progress[^>]+max="100"[^>]*><\/progress>/);});
for(const first of ['styles','app'])test('cold native completion '+first+' first: handoff requires styles and actual appReady',()=>{const f=fixture();if(first==='styles')f.boot.stylesReady(f.nodes['startup-style']);else f.boot.appReady();assert.equal(f.nodes['startup-progress'].value,undefined);assert(!f.root.removed);if(first==='styles')f.boot.appReady();else f.boot.stylesReady(f.nodes['startup-style']);assert.equal(f.boot.info().phase,'ready');assert.equal(f.nodes['startup-progress'].value,100);f.frame();f.frame();assert(f.root.removed);assert.equal(f.appended.length,0);assert.equal(f.reloads,0);});
test('cached completion event fixture uses same stable URL with no loader I/O or added module evaluation',()=>{for(let i=0;i<2;i++){const f=fixture();assert.equal(f.boot.info().source,'https://dotapk.lol/src/app.fixture.js');f.boot.stylesReady(f.nodes['startup-style']);f.boot.appReady();f.boot.moduleLoaded(f.nodes['startup-app']);f.frame();f.frame();assert(f.root.removed);assert.equal(f.appended.filter(n=>n.tagName==='SCRIPT').length,0);assert.equal(f.timers.size,0);}});
test('slow download admits uncertainty;90s wait exposes recovery without auto-refresh and can still complete',()=>{const f=fixture();f.advance(12000);assert.equal(f.boot.info().phase,'loading');assert.equal(f.nodes['startup-retry'].hidden,false);assert.match(f.nodes['startup-hint'].textContent,/尚未就绪/);assert.doesNotMatch(f.nodes['startup-hint'].textContent,/仍在继续/);assert.equal(f.timers.size,1);f.advance(180000);assert.equal(f.boot.info().phase,'waiting');assert.equal(f.boot.info().waitExpired,true);assert.match(f.nodes['startup-hint'].textContent,/等待较久/);assert.equal(f.reloads,0);f.boot.stylesReady(f.nodes['startup-style']);f.boot.appReady();assert(f.root.removed);});
test('slow load manual cancel/reopen immediately changes state and reloads same document once',()=>{const f=fixture();f.advance(12000);f.nodes['startup-retry'].onclick();assert.equal(f.boot.info().phase,'reopening');assert.match(f.nodes['startup-status'].textContent,/正在重试/);assert.equal(f.nodes['startup-retry'].disabled,true);assert.equal(f.reloads,1);f.nodes['startup-retry'].onclick();f.boot.stylesReady(f.nodes['startup-style']);f.boot.appReady();f.boot.moduleLoaded(f.nodes['startup-app']);assert.equal(f.reloads,1);assert.equal(f.boot.info().phase,'reopening');assert(!f.root.removed);assert.equal(f.appended.length,0);});
test('document cancellation/pagehide ignores late native callbacks and never creates a second module',()=>{const f=fixture();f.emit('pagehide');f.boot.appReady();f.boot.stylesReady(f.nodes['startup-style']);f.boot.fail('module',f.nodes['startup-app']);f.nodes['startup-retry'].onclick();f.advance(100000);assert.equal(f.boot.info().closed,true);assert(!f.root.removed);assert.equal(f.reloads,0);assert.equal(f.appended.length,0);});
for(const reason of ['module','initialization'])test('true '+reason+' failure is explicit and offers one manual reopen',()=>{const f=fixture();f.boot.fail(reason,f.nodes['startup-app']);assert.equal(f.boot.info().phase,'failed');assert.equal(f.nodes['startup-retry'].hidden,false);assert.equal(f.reloads,0);f.nodes['startup-retry'].onclick();f.nodes['startup-retry'].onclick();assert.equal(f.reloads,1);assert.equal(f.appended.length,0);});
test('loaded module missing appReady is initialization failure instead of permanent loading',()=>{const f=fixture();f.boot.moduleLoaded(f.nodes['startup-app']);assert.equal(f.boot.info().phase,'failed');assert.match(f.nodes['startup-status'].textContent,/启动未完成/);});
test('global initialization error/rejection is handled; unrelated image failures are ignored',()=>{for(const event of ['error','unhandledrejection']){const f=fixture();f.emit(event,{target:f.ctx});assert.equal(f.boot.info().phase,'failed');}const f=fixture();f.emit('error',{target:{tagName:'IMG'}});assert.equal(f.boot.info().phase,'loading');});
for(const appReady of [false,true])test('CSS-only retry '+(appReady?'after':'before')+' appReady uses cached script unchanged',()=>{const f=fixture();if(appReady)f.boot.appReady();const old=f.nodes['startup-style'];f.boot.fail('styles',old);f.nodes['startup-retry'].onclick();assert.equal(f.reloads,0);const link=f.appended.find(n=>n.tagName==='LINK');assert(link);assert.equal(link.href,old.href);assert.equal(f.boot.info().source,'https://dotapk.lol/src/app.fixture.js');f.boot.stylesReady(old);assert.equal(f.boot.info().styles,false);link.onload();if(!appReady)f.boot.appReady();f.frame();f.frame();assert(f.root.removed);assert.equal(f.appended.filter(n=>n.tagName==='SCRIPT').length,0);});
test('active battle/room and completed app never force-refresh from loader controls',()=>{for(const state of [{screen:'battle',room:null},{screen:'select',room:{code:'000123'}}]){const f=fixture();f.ctx.DUEL={state};f.boot.fail('module');f.nodes['startup-retry'].onclick();assert.equal(f.reloads,0);}const f=fixture();f.boot.stylesReady();f.boot.appReady();f.nodes['startup-retry'].onclick();f.boot.fail('module');assert.equal(f.reloads,0);assert.equal(f.boot.info().phase,'ready');});
test('offline message and inline offline app preserve cookie/storage language without network requirements',()=>{const f=fixture({online:false,cookie:'dota-duel-language=en',storage:'zh'});f.advance(12000);assert.match(f.nodes['startup-hint'].textContent,/offline/);assert.equal(f.boot.info().language,'en');const off=fixture({offline:true,storage:'en'});off.boot.appReady();off.frame();off.frame();assert(off.root.removed);assert.equal(off.reloads,0);const blocked=fixture({blocked:true});assert.equal(blocked.boot.info().language,'zh');});
test('built release boots one native fingerprinted script and no fragment metadata/files',()=>{const m=JSON.parse(fs.readFileSync('dist/client/build-manifest.json')),built=fs.readFileSync('dist/client/index.html','utf8');assert.equal(m.startup,undefined);assert.equal((built.match(/<script\b[^>]*\bsrc=/g)||[]).length,1);assert(built.includes('src="'+m.entry.script+'"'));assert(built.includes('data-source="'+m.entry.style+'"'));assert.match(built,/<script id="startup-app" defer src=/);assert.doesNotMatch(built,/<link[^>]*rel="stylesheet"/);assert.equal(m.delivery.styles,'inline');assert.doesNotMatch(built,/startup-config|startup-launch|blob:/);assert(!fs.readdirSync('dist/client/src').some(f=>f.startsWith('startup.')));const program=fs.readFileSync('dist/client/'+m.entry.script,'utf8');new vm.Script(program);assert.doesNotMatch(program,/\bimport\s*\(|\bimport\.meta/);assert(program.startsWith('\"use strict\";'));assert(program.includes('window.DOTA_STARTUP.appStarting();'));});

test('actual native evaluation announces initialization; appReady remains required',()=>{const f=fixture();assert.equal(f.boot.info().appStarted,false);f.boot.appStarting();assert.equal(f.boot.info().phase,'initializing');assert.equal(f.boot.info().appStarted,true);assert(!f.root.removed);f.boot.stylesReady();f.boot.appReady();assert(f.root.removed);assert.equal(f.frames.length,0,'ready never depends on throttled animation frames');});
test('inline stylesheet removes network and load-event dependency from the ready boundary',()=>{const f=fixture({offline:true});f.boot.appStarting();f.boot.appReady();assert.equal(f.boot.info().styles,true);assert(f.root.removed);assert.equal(f.appended.length,0);});
test('already loaded stylesheet sheet recovers a lost onload callback',()=>{const f=fixture();f.nodes['startup-style'].sheet={};f.boot.appReady();assert(f.root.removed);assert.equal(f.nodes['startup-style'].media,'all');});
test('BFCache return recovers loading and latches ready callbacks while suspended',()=>{for(const readyDuringFreeze of [false,true]){const f=fixture({offline:true});f.emit('pagehide',{persisted:true});assert.equal(f.boot.info().suspended,true);if(readyDuringFreeze){f.boot.appStarting();f.boot.appReady();assert(!f.root.removed);}f.emit('pageshow',{persisted:true});assert.equal(f.boot.info().closed,false);assert.equal(f.boot.info().suspended,false);if(!readyDuringFreeze){f.boot.appStarting();f.boot.appReady();}assert(f.root.removed);assert.equal(f.boot.info().phase,'ready');assert.equal(f.reloads,0);}});
test('BFCache return keeps true failure explicit and recovers elapsed wait without reload loops',()=>{const f=fixture();f.emit('pagehide',{persisted:true});f.boot.fail('module',f.nodes['startup-app']);f.emit('pageshow',{persisted:true});assert.equal(f.boot.info().phase,'failed');assert.equal(f.nodes['startup-retry'].hidden,false);const slow=fixture();slow.emit('pagehide',{persisted:true});slow.advance(180000);slow.emit('pageshow',{persisted:true});assert.equal(slow.boot.info().phase,'waiting');assert.equal(slow.reloads,0);});
test('manual retry requests one fresh document, preserves other URL state and reuses stable app URL',()=>{const f=fixture();const replacements=[];f.ctx.URL=URL;f.ctx.location={protocol:'https:',href:'https://dotapk.lol/?lang=en#home',replace:v=>replacements.push(v),reload(){throw Error('expected fresh document');}};f.boot.fail('module');f.nodes['startup-retry'].onclick();f.nodes['startup-retry'].onclick();assert.equal(replacements.length,1);const u=new URL(replacements[0]);assert.equal(u.searchParams.get('lang'),'en');assert.equal(u.searchParams.get('_startup_retry'),'0');assert.equal(u.hash,'#home');assert.equal(f.nodes['startup-app'].src,'https://dotapk.lol/src/app.fixture.js');assert.equal(f.appended.length,0);});
test('fingerprinted entries have immutable caches; previous entry is complete and compatible',()=>{const m=JSON.parse(fs.readFileSync('dist/client/build-manifest.json')),headers=fs.readFileSync('dist/client/_headers','utf8');for(const file of [m.entry.script,m.entry.style,...m.delivery.retainedEntries]){assert(headers.includes('/'+file+'\n  Cache-Control: public, max-age=31536000, immutable'));assert(fs.statSync('dist/client/'+file).size>0);}assert([0,2].includes(m.delivery.retainedEntries.length));});

test('repeated BFCache back/return never injects or initializes a second app and ready survives later returns',()=>{const f=fixture({offline:true});f.boot.appStarting();for(let i=0;i<3;i++){f.emit('pagehide',{persisted:true});f.advance(5000);f.emit('pageshow',{persisted:true});assert.equal(f.boot.info().closed,false);assert.equal(f.boot.info().appStarted,true);assert.equal(f.boot.info().app,false);assert(!f.root.removed);}f.boot.appReady();assert(f.root.removed);for(let i=0;i<3;i++){f.emit('pagehide',{persisted:true});f.emit('pageshow',{persisted:true});f.boot.appStarting();f.boot.appReady();assert.equal(f.boot.info().phase,'ready');}assert.equal(f.appended.length,0);assert.equal(f.reloads,0);assert.equal(f.timers.size,0);});
